### ISSUE TITLE
reStart failed after install

### ISSUE THREAD

**Issue by acrozes** [spark-jobserver/spark-jobserver#1006]
I try to test spark-jobserver on Windows

**Used Spark version**
Spark 2.2.0

**Used Spark Job Server version**
0.8.0 or 0.8.1-SNAPSHOT

**Deployed mode**
Spark Standalone Cluster: 1 master, 1 worker, spark-shell is fine (spark-shell.cmd --master spark://192.168.36.1:7077)
```
$ jps
16672 Jps
17712
6320
10900 CoarseGrainedExecutorBackend
13780 sbt-launch.jar
14420 sbt-launch.jar
11704 Master
15528 Worker
11628 SparkSubmit
```
spark-jobserver in "Development mode"

**Actual (wrong) behavior**
On sbt shell, reStart failled with the error:
 job-server-tests[ERROR] java.lang.NoClassDefFoundError: org/apache/spark/SparkContext

```
> reStart
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Processed 16 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 6 ms
[success] created output: C:\spark-jobserver\job-server-extras\target
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Processed 13 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 2 ms
[success] created output: C:\spark-jobserver\job-server-api\target
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Processed 0 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 1 ms
[success] created output: C:\spark-jobserver\job-server-python\target
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Processed 6 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 2 ms
[success] created output: C:\spark-jobserver\job-server-tests\target
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Processed 11 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 2 ms
[success] created output: C:\spark-jobserver\akka-app\target
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Processed 46 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 4 ms
[success] created output: C:\spark-jobserver\job-server\target
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Processed 0 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 0 ms
[success] created output: C:\spark-jobserver\target
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[info] Updating {file:/C:/spark-jobserver/}job-server-api...
[info] Updating {file:/C:/spark-jobserver/}job-server-api...
[info] Updating {file:/C:/spark-jobserver/}akka-app...
[info] Updating {file:/C:/spark-jobserver/}akka-app...
[info] Updating {file:/C:/spark-jobserver/}akka-app...
[info] Updating {file:/C:/spark-jobserver/}akka-app...
[info] Updating {file:/C:/spark-jobserver/}job-server-api...
[info] Updating {file:/C:/spark-jobserver/}job-server-api...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[info] Updating {file:/C:/spark-jobserver/}job-server-tests...
[info] Updating {file:/C:/spark-jobserver/}job-server-python...
[info] Updating {file:/C:/spark-jobserver/}job-server...
[info] Updating {file:/C:/spark-jobserver/}job-server...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * io.netty:netty-all:4.0.33.Final -> 4.0.44.Final
[warn] Run 'evicted' to see detailed eviction warnings
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * io.netty:netty-all:4.0.33.Final -> 4.0.44.Final
[warn] Run 'evicted' to see detailed eviction warnings
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Updating {file:/C:/spark-jobserver/}job-server-extras...
[info] Processed 11 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 2 ms
[success] created output: C:\spark-jobserver\akka-app\target
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Resolving spark.jobserver#job-server_2.11;0.8.0 ...
[info] Processed 13 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 3 ms
[success] created output: C:\spark-jobserver\job-server-api\target
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.3 ...
[info] Processed 13 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 2 ms
[success] created output: C:\spark-jobserver\job-server-api\target
[info] Resolving org.jvnet.mimepull#mimepull;1.9.5 ...
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Resolving org.apache.shiro#shiro-core;1.2.4 ...
[info] Processed 13 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 2 ms
[success] created output: C:\spark-jobserver\job-server-api\target
[warn] Credentials file C:\Users\test\.bintray\.credentials does not exist
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Resolving org.apache#apache;14 ...
[info] Processed 46 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 2 ms
[success] created output: C:\spark-jobserver\job-server\target
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Processed 11 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 0 ms
[success] created output: C:\spark-jobserver\akka-app\target
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Processed 13 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 0 ms
[success] created output: C:\spark-jobserver\job-server-api\target
[info] Application job-server-api not yet started
[info] Application akka-app not yet started
[info] Resolving org.apache.spark#spark-launcher_2.11;2.2.0 ...
[warn] Multiple main classes detected.  Run show discoveredMainClasses to see the list

Multiple main classes detected, select one to run:

 [1] spark.jobserver.LongPiJob
 [2] spark.jobserver.NoOpJob
 [3] spark.jobserver.VeryShortDoubleJob
 [4] spark.jobserver.WordCountExample
[info] Resolving org.apache.spark#spark-unsafe_2.11;2.2.0 ...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * io.netty:netty-all:4.0.33.Final -> 4.0.44.Final
[warn] Run 'evicted' to see detailed eviction warnings
4

[info] Application job-server-python not yet started
[info] Starting application job-server-python in the background ...
job-server-python Starting spark.jobserver.JobServer.main()
[info] Updating {file:/C:/spark-jobserver/}root...
[info] Application job-server-tests not yet started
[info] Starting application job-server-tests in the background ...
job-server-tests Starting spark.jobserver.WordCountExample.main()
[info] Resolving io.spray#spray-http_2.11;1.3.3 ...
[info] Application job-server not yet started
[info] Starting application job-server in the background ...
job-server Starting spark.jobserver.JobServer.main()
[info] Resolving org.typelevel#macro-compat_2.11;1.1.1 ...
job-server-tests[ERROR] java.lang.NoClassDefFoundError: org/apache/spark/SparkContext
job-server-tests[ERROR]         at java.lang.Class.getDeclaredMethods0(Native Method)
job-server-tests[ERROR]         at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
job-server-tests[ERROR]         at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
job-server-tests[ERROR]         at java.lang.Class.getMethod0(Class.java:3018)
job-server-tests[ERROR]         at java.lang.Class.getMethod(Class.java:1784)
job-server-tests[ERROR]         at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
job-server-tests[ERROR]         at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
job-server-tests[ERROR] Caused by: java.lang.ClassNotFoundException: org.apache.spark.SparkContext
job-server-tests[ERROR]         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
job-server-tests[ERROR]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
job-server-tests[ERROR]         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
job-server-tests[ERROR]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[info] Resolving io.spray#spray-client_2.11;1.3.3 ...
[info] Resolving spark.jobserver#job-server-api_2.11;0.8.0 ...
[info] Resolving com.typesafe.slick#slick_2.11;3.1.1 ...
[info] Resolving commons-pool#commons-pool;1.5.4 ...
[info] Application job-server-extras not yet started
[info] Starting application job-server-extras in the background ...
job-server-extras Starting spark.jobserver.JobServer.main()
[info] Resolving spark.jobserver#job-server-extras_2.11;0.8.0 ...
job-server-python[ERROR] Erreur : impossible de trouver ou charger la classe principale spark.jobserver.JobServer
[info] Resolving org.apache#apache;14 ...
job-server-extras[ERROR] log4j:ERROR Could not read configuration file from URL [file:config/log4j-local.properties].
job-server-extras[ERROR] java.io.FileNotFoundException: config\log4j-local.properties (Le chemin d▒acc▒s sp▒cifi▒ est introuvable)
job-server-extras[ERROR]        at java.io.FileInputStream.open0(Native Method)
job-server-extras[ERROR]        at java.io.FileInputStream.open(FileInputStream.java:195)
job-server-extras[ERROR]        at java.io.FileInputStream.<init>(FileInputStream.java:138)
job-server-extras[ERROR]        at java.io.FileInputStream.<init>(FileInputStream.java:93)
job-server-extras[ERROR]        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
job-server-extras[ERROR]        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
job-server-extras[ERROR]        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:557)
job-server-extras[ERROR]        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
job-server-extras[ERROR]        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
job-server-extras[ERROR]        at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:81)
job-server-extras[ERROR]        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:329)
job-server-extras[ERROR]        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:349)
job-server-extras[ERROR]        at spark.jobserver.JobServer$.<init>(JobServer.scala:34)
job-server-extras[ERROR]        at spark.jobserver.JobServer$.<clinit>(JobServer.scala)
job-server-extras[ERROR]        at spark.jobserver.JobServer.main(JobServer.scala)
job-server-extras[ERROR] log4j:ERROR Ignoring configuration file [file:config/log4j-local.properties].
job-server-extras[ERROR] log4j:WARN No appenders could be found for logger (spark.jobserver.JobServer$).
job-server-extras[ERROR] log4j:WARN Please initialize the log4j system properly.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * io.netty:netty-all:4.0.33.Final -> 4.0.44.Final
[warn] Run 'evicted' to see detailed eviction warnings
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
job-server-extras ... finished with exit code 1
job-server ... finished with exit code 1
[info] Processed 13 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 2 ms
[success] created output: C:\spark-jobserver\job-server-api\target
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Processed 46 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 2 ms
[success] created output: C:\spark-jobserver\job-server\target
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Processed 11 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 1 ms
[success] created output: C:\spark-jobserver\akka-app\target
[info] scalastyle using config C:\spark-jobserver\scalastyle-config.xml
[info] Processed 16 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 2 ms
[success] created output: C:\spark-jobserver\job-server-extras\target
[info] Application root not yet started
[trace] Stack trace suppressed: run last root/*:reStart for the full output.
[trace] Stack trace suppressed: run last job-server-api/*:reStart for the full output.
[trace] Stack trace suppressed: run last akka-app/*:reStart for the full output.
[error] (root/*:reStart) No main class detected!
[error] (job-server-api/*:reStart) No main class detected!
[error] (akka-app/*:reStart) No main class detected!
[error] Total time: 652 s, completed 17 janv. 2018 19:32:34
> reStatus
[info] Application job-server-extras is currently NOT running
[info] Application job-server-python is currently NOT running
[info] Application root is currently NOT running
[info] Application akka-app is currently NOT running
[info] Application job-server-api is currently NOT running
[info] Application job-server is currently NOT running
[info] Application job-server-tests is currently NOT running
[success] Total time: 3 s, completed 17 janv. 2018 19:37:20
>

```
Am I miss something ? 
Thank you

**Comment by noorul** [comment]
You need to use job-server-extras/reStart

See the example in https://github.com/spark-jobserver/spark-jobserver#development-mode
