### ISSUE TITLE
Slick driver 

### ISSUE THREAD

**Issue by addmeaning** [spark-jobserver/spark-jobserver#1011]
I am not sure if it is spark-jobserver or slick driver issue.
According to [Slick supported databases](http://slick.lightbend.com/doc/3.2.1/supported-databases.html) insertOrUpdate method only compatible with MySQL db.

**Used Spark version**
2.2.0

**Used Spark Job Server version**
(Released version, git branch or docker image version)
0.8.0 (from this image: https://hub.docker.com/r/tcjennings/spark-jobserver/)

**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
Spark Standalone.

**Actual (wrong) behavior**
While being configured to use Postgresql backend slick driver uses InserOrUpdate function (logs below)

sjs-configuration:
```
spark{
...
      slick-profile = "slick.driver.PostgresDriver"
      jdbc-driver = org.postgresql.Driver
...
}
```

**Slick driver version**
3.1.1

**Logs**

```
[2018-01-25 12:09:57,619] INFO  k.jobserver.io.JobDAOActor [] [akka://JobServer/user/dao-manager] - Starting actor spark.jobserver.io.JobDAOActor
[2018-01-25 12:09:57,619] ERROR ka.actor.OneForOneStrategy [] [akka://JobServer/user/dao-manager] - ERROR: syntax error at or near "merge"
  Position: 1
org.postgresql.util.PSQLException: ERROR: syntax error at or near "merge"
  Position: 1
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction$$anonfun$nativeUpsert$1.apply(JdbcActionComponent.scala:560)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction$$anonfun$nativeUpsert$1.apply(JdbcActionComponent.scala:557)
	at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:347)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:407)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:498)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.nativeUpsert(JdbcActionComponent.scala:557)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.f$1(JdbcActionComponent.scala:540)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.run(JdbcActionComponent.scala:553)
	at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:32)
	at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:29)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by valan4ik** [comment]
Closing due to inactivity + currently we use slick version `3.3.3` already.
Please reopen if the issue appears again.
