### ISSUE TITLE
start SJS throw NoSuchMethodError: spark.jobserver.util.SparkJobUtils$.getContextDeletionTimeout(Lcom/typesafe/config/Config;)I

### ISSUE THREAD

**Issue by YuanGunGun** [spark-jobserver/spark-jobserver#1018]
**Used Spark version**
1.6.1
**Used Spark Job Server version**
v0.7.0
**Deployed mode**
yarn-client
**Actual (wrong) behavior**
run server_start.sh
**Steps to reproduce**
1、server_package.sh
2、server_start.sh
**Logs**

```
[2018-02-05 17:32:32,966] INFO  ka.event.slf4j.Slf4jLogger [] [] - Slf4jLogger started
[2018-02-05 17:32:33,033] INFO  Remoting [] [Remoting] - Starting remoting
[2018-02-05 17:32:33,204] INFO  Remoting [] [Remoting] - Remoting started; listening on addresses :[akka.tcp://JobServer@127.0.0.1:43002]
[2018-02-05 17:32:33,225] INFO  Cluster(akka://JobServer) [] [Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:43002] - Starting up...
[2018-02-05 17:32:33,267] INFO  Cluster(akka://JobServer) [] [Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:43002] - Registered cluster JMX MBean [akka:type=Cluster]
[2018-02-05 17:32:33,268] INFO  Cluster(akka://JobServer) [] [Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:43002] - Started up successfully
[2018-02-05 17:32:33,292] INFO  Cluster(akka://JobServer) [] [Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:43002] - No seed-nodes configured, manual cluster join required
[2018-02-05 17:32:34,046] INFO  ark.jobserver.io.JobSqlDAO [] [] - rootDir is /tmp/spark-jobserver/sqldao/data
[2018-02-05 17:32:34,052] INFO  ark.jobserver.io.JobSqlDAO [] [] - DBCP disabled
[2018-02-05 17:32:34,082] INFO  ternal.util.VersionPrinter [] [] - Flyway 3.2.1 by Boxfuse
[2018-02-05 17:32:34,343] INFO  dbsupport.DbSupportFactory [] [] - Database: jdbc:mysql://x.x.x.x:3306/jobserver?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false (MySQL 5.5)
[2018-02-05 17:32:34,499] INFO  nternal.command.DbValidate [] [] - Validated 2 migrations (execution time 00:00.064s)
[2018-02-05 17:32:34,532] INFO  internal.command.DbMigrate [] [] - Current version of schema `jobserver`: 0.7.1
[2018-02-05 17:32:34,533] INFO  internal.command.DbMigrate [] [] - Schema `jobserver` is up to date. No migration necessary.
[2018-02-05 17:32:34,542] INFO  k.jobserver.io.JobDAOActor [] [akka://JobServer/user/dao-manager] - Starting actor spark.jobserver.io.JobDAOActor
[2018-02-05 17:32:34,544] INFO  jobserver.DataManagerActor [] [akka://JobServer/user/data-manager] - Starting actor spark.jobserver.DataManagerActor
[2018-02-05 17:32:34,546] INFO  rk.jobserver.BinaryManager [] [akka://JobServer/user/binary-manager] - Starting actor spark.jobserver.BinaryManager
[2018-02-05 17:32:34,547] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Starting actor spark.jobserver.AkkaClusterSupervisorActor
[2018-02-05 17:32:34,548] INFO  ark.jobserver.JobInfoActor [] [akka://JobServer/user/job-info] - Starting actor spark.jobserver.JobInfoActor
[2018-02-05 17:32:34,599] ERROR ka.actor.OneForOneStrategy [] [akka://JobServer/user/context-supervisor] - exception during creation
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:166)
        at akka.actor.ActorCell.create(ActorCell.scala:596)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at akka.util.Reflect$.instantiate(Reflect.scala:66)
        at akka.actor.ArgsReflectConstructor.produce(Props.scala:352)
        at akka.actor.Props.newActor(Props.scala:252)
        at akka.actor.ActorCell.newActor(ActorCell.scala:552)
        at akka.actor.ActorCell.create(ActorCell.scala:578)
        ... 9 more
Caused by: java.lang.NoSuchMethodError: spark.jobserver.util.SparkJobUtils$.getContextDeletionTimeout(Lcom/typesafe/config/Config;)I
        at spark.jobserver.AkkaClusterSupervisorActor.<init>(AkkaClusterSupervisorActor.scala:50)
        ... 18 more
[2018-02-05 17:32:34,607] INFO  .actor.RepointableActorRef [] [akka://JobServer/user/context-supervisor] - Message [spark.jobserver.ContextSupervisor$AddContextsFromConfig$] from Actor[akka://JobServer/deadLetters] to Actor[akka://JobServer/user/context-supervisor#2025362775] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

or as attached file (see below)
[sjs_err.txt](https://github.com/spark-jobserver/spark-jobserver/files/1694558/sjs_err.txt)

**Comment by YuanGunGun** [comment]
The reason is my java classpath add other jar that contain old SparkJobUtils class.
so close it.
