### ISSUE TITLE
server_deploy.sh fails on akka and spray dependency retrieval

### ISSUE THREAD

**Issue by bcuster** [spark-jobserver/spark-jobserver#1020]
**Used Spark version**
spark-2.2.1-bin-hadoop2.7

**Used Spark Job Server version**
(Released version, git branch or docker image version)
downloaded git master branch on 2/8/2018

**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
client on local[4] (as set in <root>/config/local.conf, but didn't get far enough to submit anything)

**Actual (wrong) behavior**
After executing "sbt package" (from within the project root dir) with no errors reported,
when next executing "bin/server_deploy.sh local",
sbt downloads more dependencies but fails to retrieve 4, reporting:
```
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]     ::          UNRESOLVED DEPENDENCIES         ::
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]     :: com.typesafe.akka#akka-slf4j_2.10;2.4.9: not found
[warn]     :: com.typesafe.akka#akka-cluster_2.10;2.4.9: not found
[warn]     :: io.spray#spray-routing-shapeless23_2.10;1.3.4: not found
[warn]     :: com.typesafe.akka#akka-testkit_2.10;2.4.9: not found
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]     Note: Unresolved dependencies path:
[warn]         com.typesafe.akka:akka-slf4j_2.10:2.4.9 (/usr/local/home_extension/bradley/spark-test/spark-jobserver-master/build.sbt#L11)
[warn]           +- spark.jobserver:akka-app_2.10:0.8.1-SNAPSHOT
[warn]         com.typesafe.akka:akka-cluster_2.10:2.4.9 (/usr/local/home_extension/bradley/spark-test/spark-jobserver-master/build.sbt#L11)
[warn]           +- spark.jobserver:akka-app_2.10:0.8.1-SNAPSHOT
[warn]         io.spray:spray-routing-shapeless23_2.10:1.3.4 (/usr/local/home_extension/bradley/spark-test/spark-jobserver-master/build.sbt#L11)
[warn]           +- spark.jobserver:akka-app_2.10:0.8.1-SNAPSHOT
[warn]         com.typesafe.akka:akka-testkit_2.10:2.4.9 (/usr/local/home_extension/bradley/spark-test/spark-jobserver-master/build.sbt#L11)
[warn]           +- spark.jobserver:akka-app_2.10:0.8.1-SNAPSHOT
```
The versions requested for these packages are not the most recent available in Maven Central.

**Comment by velvia** [comment]
Hmm that's odd. Even though these packages are not the latest, they should still be in maven central.

**Comment by bcuster** [comment]
Not seeing the requested version numbers in central.
For example
https://search.maven.org/#search|ga|1|spray-routing-shapeless

**Comment by PZaytsevUSC** [comment]
Can confirm I am getting the same issue for 0.8.0 release:

`
sbt.ResolveException: unresolved dependency: com.typesafe.akka#akka-slf4j_2.10;2.4.9: not found
unresolved dependency: com.typesafe.akka#akka-cluster_2.10;2.4.9: not found
unresolved dependency: io.spray#spray-routing-shapeless23_2.10;1.3.4: not found
unresolved dependency: com.typesafe.akka#akka-testkit_2.10;2.4.9: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1442)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1438)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1473)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1471)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1476)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1470)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1493)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1420)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1372)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (akka-app/*:update) sbt.ResolveException: unresolved dependency: com.typesafe.akka#akka-slf4j_2.10;2.4.9: not found
[error] unresolved dependency: com.typesafe.akka#akka-cluster_2.10;2.4.9: not found
[error] unresolved dependency: io.spray#spray-routing-shapeless23_2.10;1.3.4: not found
[error] unresolved dependency: com.typesafe.akka#akka-testkit_2.10;2.4.9: not found
[error] Total time: 8 s, completed Feb 13, 2018 2:50:18 PM
Assembly failed
`

**Comment by peiht** [comment]
I am getting the same issue for 0.8.0 release

**Comment by giuseppellrusso** [comment]
Getting same issue here. Did anyone find a solution to this problem?

**Comment by bsikander** [comment]
Akka dropped support for Scala 2.10 in Akka 2.4.x. We are using 2.4.9.
Here are the release notes https://akka.io/blog/news/2015/09/30/akka-2.4.0-released

@velvia should we update our README?

**Comment by velvia** [comment]
@bsikander yeah we should. We should also move to akka-HTTP, but that's a separate thing altogether. :)

**Comment by bsikander** [comment]
Ok. I will try to push a patch.

yea akka-HTTP is much needed.

**Comment by linsimiao** [comment]
i met with exactly the same problem. Has anyone figured out how to solve it? Thanks in advance.

**Comment by linsimiao** [comment]
I C. Thank you so much!


Alice

2018-06-26 16:45 GMT+08:00 Behroz Sikander <notifications@github.com>:
