### ISSUE TITLE
org.scala-lang#scala-library;2.11: not found  when run sbt

### ISSUE THREAD

**Issue by I348773** [spark-jobserver/spark-jobserver#1026]
**Used Spark version: 2.1.1**

**Job server version**
git branch: 0.8.1-SNAPSHOT

**Deployed mode**
(client/cluster on Spark Standalone)

**Actual (wrong) behavior**
when I  go to the /spark-jobserver folder, and run "sbt  job-server-extras/reStart" command.

**Steps to reproduce**
1. Copy the project to the ubuntu 16.04
2. Run the command "sbt version"
3. Go to the /spark-jobserver and run the command "sbt job-server-extras/reStart"

**Logs**

```
The error message appears as below:
 ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-lang#scala-library;2.11: not found
[warn]  :: org.scala-lang#scala-reflect;2.11: not found
[warn]  :: org.scala-lang#scalap;2.11: not found
[warn]  :: org.scala-lang#scala-compiler;2.11: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: org.scala-lang#scala-library;2.11: not found
unresolved dependency: org.scala-lang#scala-reflect;2.11: not found
unresolved dependency: org.scala-lang#scalap;2.11: not found
unresolved dependency: org.scala-lang#scala-compiler;2.11: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:128)
        at sbt.IvySbt.withIvy(Ivy.scala:125)
        at sbt.IvySbt$Module.withModule(Ivy.scala:156)
        at sbt.IvyActions$.updateEither(IvyActions.scala:168)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1442)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1438)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1473)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1471)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1476)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1470)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1493)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1420)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1372)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by I348773** [comment]
The scala version is 2.11.6

**Comment by I348773** [comment]
Hi @noorul , @devesh , @jwalgran 

Could you help me have a look on this?
Might a little bit urgent.  Sorry for interrupt you.

Thanks,
Frank

**Comment by noorul** [comment]
Can you try scala 2.11.8 ?

**Comment by I348773** [comment]
Hi Noorul,

Yes I tried, but shall I need add scalaVersion to your build.sbt file such as scalaVersion := 2.11.8?

**Comment by I348773** [comment]
sbt-1.1.0 version is which I use in my local.

**Comment by I348773** [comment]
And do you know
job-server-extras[ERROR] log4j:ERROR Could not read configuration file from URL [file:config/log4j-local.properties].
How can I resolve this?

Thanks,
Frank

**Comment by I348773** [comment]
Hi @noorul,

I run this is in the docker.

For Ex, docker run  -it  imagename  /bin/bash
Inside the docker, I install the scala 2.11.8 and sbt-1.1.0, 
Then go to the /spark-jobserver folder, and run "sbt job-server-extras/reStart"

And the error message appeared.

Thanks,
Frank

**Comment by I348773** [comment]
Ok，this issue I resolved, I will close it.

**Comment by YiddishKop** [comment]
Hi @I348773  

I has same issue now, could you tell me how you fix it

I recently move my project from mac to ubuntu 18.04, and install the sbt 1.1.5 by `apt-get`. 
when running `sbt -version`, it gives me `unresolved dependency: org.scala-lang#scala-library;2.11.8`

Thanks.

**Comment by I348773** [comment]
Hi @YiddishKop,

please check your environment in your linux server (run "env" command), and check which scala version you installed.
Then please select the correct verion of scala and install, then setup the environment use "export" command to setup the scala version.
