### ISSUE TITLE
 java.io.FileNotFoundException: config/log4j-local.properties (Not a directory)

### ISSUE THREAD

**Issue by I348773** [spark-jobserver/spark-jobserver#1031]
**Used Spark version**
spark-2.1.1-bin-hadoop2.7

**Used Spark Job Server version**
(Released version, git branch or docker image version)
[info] job-server-python/*:version
[info]  0.8.1-SNAPSHOT

**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
Spark Standalone

**Actual (wrong) behavior**
 java.io.FileNotFoundException: config/log4j-local.properties (Not a directory)

**Steps to reproduce**
run "sbt job-server-extras/reStart"

**Logs**

```
 job-server-extras[ERROR] log4j:ERROR Could not read configuration file from URL [file:config/log4j-local.properties].
job-server-extras[ERROR] java.io.FileNotFoundException: config/log4j-local.properties (Not a directory)
job-server-extras[ERROR]        at java.io.FileInputStream.open0(Native Method)
job-server-extras[ERROR]        at java.io.FileInputStream.open(FileInputStream.java:195)
job-server-extras[ERROR]        at java.io.FileInputStream.<init>(FileInputStream.java:138)
job-server-extras[ERROR]        at java.io.FileInputStream.<init>(FileInputStream.java:93)
job-server-extras[ERROR]        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
job-server-extras[ERROR]        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
job-server-extras[ERROR]        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:557)
job-server-extras[ERROR]        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
job-server-extras[ERROR]        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
job-server-extras[ERROR]        at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:81)
job-server-extras[ERROR]        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:329)
job-server-extras[ERROR]        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:349)
job-server-extras[ERROR]        at spark.jobserver.JobServer$.<init>(JobServer.scala:34)
job-server-extras[ERROR]        at spark.jobserver.JobServer$.<clinit>(JobServer.scala)
job-server-extras[ERROR]        at spark.jobserver.JobServer.main(JobServer.scala)
job-server-extras[ERROR] log4j:ERROR Ignoring configuration file [file:config/log4j-local.properties].
job-server-extras Could not find configuration file -Xmx8g
job-server-extras ... finished with exit code 1

```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by I348773** [comment]
Hi @noorul, @devesh, @jwalgran 

Could you help me to have a look on this? Does any operate I missed or not? Shall I need copy or paste some files to specific folder?


Thanks,
Frank
