### ISSUE TITLE
curl localhost:8090/contexts/ connection refused

### ISSUE THREAD

**Issue by I348773** [spark-jobserver/spark-jobserver#1036]
But I re deploy again.
And start the server run server_start.sh in the INSTALL DIR
Then access to "curl localhost:8080/contexts/"
The error message says "**curl: (7) Failed to connect to localhost port 8090: Connection refused**"

**Comment by I348773** [comment]
Hi @noorul 

And the log shows below:
Caused by: org.flywaydb.core.api.FlywayException: Validate failed. Migration Checksum mismatch for migration 0.7.0

**Comment by bsikander** [comment]
Jobserver by default runs on port 8090. So, please use
`curl localhost:8090/contexts/`

**Comment by I348773** [comment]
Yes， sorry here's the mistake, I use 8090.

**Comment by I348773** [comment]
Hi @noorul ,
Because this error message:
Caused by: org.flywaydb.core.api.FlywayException: Validate failed. Migration Checksum mismatch for migration 0.7.0
Could not start the server.

**Comment by I348773** [comment]
[2018-03-02 09:38:33,723] ERROR spark.jobserver.JobServer$ [] [] - Unable to start Spark JobServer:
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at spark.jobserver.JobServer$.start(JobServer.scala:102)
        at spark.jobserver.JobServer$.main(JobServer.scala:190)
        at spark.jobserver.JobServer.main(JobServer.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.flywaydb.core.api.FlywayException: Validate failed. Migration Checksum mismatch for migration 0.7.0
-> Applied to database : -1525917736
-> Resolved locally    : -108510031
        at org.flywaydb.core.Flyway.doValidate(Flyway.java:1108)
        at org.flywaydb.core.Flyway.access$300(Flyway.java:62)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1012)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
        at spark.jobserver.io.JobSqlDAO.init(JobSqlDAO.scala:134)
        at spark.jobserver.io.JobSqlDAO.<init>(JobSqlDAO.scala:122)

**Comment by bsikander** [comment]
Somehow your database is messed up.

I am assuming that you are testing jobserver. If you are not running in production then use the following to fix the problem.
You can change the name of database in your config file and then start the jobserver again. It will create a new database with all the migrations. It should work.

**Comment by I348773** [comment]
Ok, Thanks @bsikander, let me try

**Comment by bsikander** [comment]
@I348773 did it solve your problem?

**Comment by I348773** [comment]
Hi @bsikander , It works, thanks a lot
