### ISSUE TITLE
Question about test failures when building Spark-Joberver master (0.8.1)

### ISSUE THREAD

**Issue by barrybecker4** [spark-jobserver/spark-jobserver#1037]
I have spark 2.2-branch checked out and built locally (version 2.2.2)

I cloned the latest spark-jobserver master

Deployed mode: client  (default)

My relevant env vars are:
  SPARK_HOME=/home/barrybecker/work/spark  (2.2-branch)
  SPARK_CONF_DIR=/home/barrybecker/work/spark/conf
  SPARK_LOCAL_IP=localhost

I cloned the latest spark-jobserver master and in the root directory ran "sbt".
The "compile" target ran fine with no errors.
However, when I try to run "test", I get some failures.

All the tests passed except for the following:

5 failed tests in AkkaClusterSupervisorActorSpec:
 - should be able to start multiple contexts *** FAILED *** (11 seconds, 22 milliseconds)
 - should be able to list all the started contexts *** FAILED *** (10 seconds)
 - should return valid result actor *** FAILED *** (10 seconds)
 - should return valid appId and webUiUrl if context is running *** FAILED *** (10 seconds)
 - should return NoSuchContext if the context is dead *** FAILED *** (10 seconds, 1 milliseconds)
 
These 5 tests all fail with errors like this:
 ```
 java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for ContextInitialized
  [info]   at scala.Predef$.assert(Predef.scala:170)
  [info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:350)
```
1 failed test in  PythonSessionContextFactorySpec:

```
[info] - should successfully run jobs using python3 *** FAILED *** (5 seconds, 804 milliseconds)
[info]   java.lang.Exception: Python job failed with error code 1 and standard err [Traceback (most recent call last):  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main    "__main__", mod_spec)  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code    exec(code, run_globals)  File "/home/barrybecker/work/tmp/sjs/job-server-python/target/python/sjs_python_examples-0.8.1_SNAPSHOT-py2.7.egg/sparkjobserver/subprocess.py", line 22, in <module>    ImportError: No module named 'pyhocon']
[info]   at spark.jobserver.python.PythonJob$$anonfun$1.apply(PythonJob.scala:87)
```

I have python 3.5 installed and did "pip install pyhocon" before running test. What did I forget to do?

**Comment by bsikander** [comment]
Regarding the `AkkaClusterSupervisorActorSpec ` testcases, do have the following commit in your master ?
`fix(jobserver): Fix randomly failing testcase in AkkaClusterSupervison` with commit id
`16dcb620ddc46128bef067443424a2830221b025` ?

**Comment by barrybecker4** [comment]
Yes, I have it locally. That is the change that suffixed all the "test-context" string with numbers.

**Comment by bsikander** [comment]
umm strange. This testcase seems to work fine on my setup and also on the CI build of SJS.

In `AkkaClusterSupervisorActorSpec` class, you will find a config file at the very top. Can you comment out the the following properties and then execute the testcases again. This will log all the output to console. Then maybe you can share the output so that we can analyze what is happening.

```
log-dead-letters = 0
loglevel = "OFF" # Other options INFO, OFF, DEBUG, WARNING
stdout-loglevel = "OFF"
log-dead-letters-during-shutdown = off
cluster.log-info = off
```

**Comment by barrybecker4** [comment]
It's probably something not configured correctly in my local environment (ubuntu).
I commented those lines and tried again. 

The errors seem different now. They are:
```
[info] Run completed in 2 minutes, 22 seconds.
[info] Total number of tests run: 331
[info] Suites: completed 29, aborted 0
[info] Tests: succeeded 313, failed 18, canceled 0, ignored 1, pending 0
[info] *** 18 TESTS FAILED ***
[error] Failed tests:
[error] 	spark.jobserver.WebApiMainRoutesSpec
[error] 	spark.jobserver.routes.DataRoutesSpec
[error] 	spark.jobserver.WebApiSpec
```

Sample of the sort of error is:
```
 - Should return valid JSON when resetting a context *** FAILED *** (1 second, 2 milliseconds)
[info]   The future returned an exception of type: spray.can.Http$ConnectionException, with message: Premature connection close (the server doesn't appear to support request pipelining). (WebApiSpec.scala:280)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:531)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:558)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:74)
[info]   at org.scalatest.concurrent.Futures$class.whenReady(Futures.scala:684)
[info]   at spark.jobserver.WebApiSpec.whenReady(WebApiSpec.scala:28)
```

Futher down, there is python related error:
```
info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	spark.jobserver.python.PythonSessionContextFactorySpec
[error] (job-server/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] (job-server-extras/test:test) sbt.TestsFailedException: Tests unsuccessful
:
[info] - should successfully run jobs using python3 *** FAILED *** (6 seconds, 957 milliseconds)
[info]   java.lang.Exception: Python job failed with error code 1 and standard err [Traceback (most recent call last):  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main    "__main__", mod_spec)  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code    exec(code, run_globals)  File "/home/barrybecker/work/tmp/sjs/job-server-python/target/python/sjs_python_examples-0.8.1_SNAPSHOT-py2.7.egg/sparkjobserver/subprocess.py", line 22, in <module>    ImportError: No module named 'pyhocon']
[info]   at spark.jobserver.python.PythonJob$$anonfun$1.apply(PythonJob.scala:87)
[info]   at scala.util.Try$.apply(Try.scala:192)
[info]   at spark.jobserver.python.PythonJob.runJob(PythonJob.scala:60)
[info]   at spark.jobserver.python.PythonSessionContextFactorySpec$$anonfun$2.spark$jobserver$python$PythonSessionContextFactorySpec$$anonfun$$runSessionTest$1(PythonSessionContextFactorySpec.scala:135)



```

**Comment by bsikander** [comment]
Did you figure out the problem?

**Comment by bsikander** [comment]
can we close the ticket?
