### ISSUE TITLE
Passing a large json request to jobServer causes it to fail (whether using JobFileDao or JobSqlDao)

### ISSUE THREAD

**Issue by barrybecker4** [spark-jobserver/spark-jobserver#1065]
spark 2.1.1 and also spark 2.3.0
spark 0.7.0, 0.8.0, 0.8.1-SNAPSHOT
client mode

Different (but similar) wrong behavior depending on whether you are using JobFileDao or JobSqlDao when issueing a large request. In my case, I am issuing a JSON request to our scala "TransformationJob". The actual content of the JSON request is irrelevant because it is our own format, but we are trying to remove a list of 200 columns from our dataframe in a transformation operation. It's the list of 200 columns that causes the request to be very large and cause the problems.

If using the JobFileDao and jobserver 0.8.0, then the exception looks like this:
> java.io.UTFDataFormatException: encoded string too long: 69726 bytes
>         at java.io.DataOutputStream.writeUTF(DataOutputStream.java:364)
>         at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
>         at spark.jobserver.io.JobFileDAO.writeJobConfig(JobFileDAO.scala:220)
>         at spark.jobserver.io.JobFileDAO.saveJobConfig(JobFileDAO.scala:212)
>         at spark.jobserver.JobInfoActor$$anonfun$wrappedReceive$1.applyOrElse(JobInfoActor.scala:71)
>         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
>         at spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
>         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
>         at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
>         at spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)
>         at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)
>         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
>         at spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)
>         at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
>         at spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
>         at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
>         at akka.actor.ActorCell.invoke(ActorCell.scala:495)
>         at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
>         at akka.dispatch.Mailbox.run(Mailbox.scala:224)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)

We were really hoping that switching to using the JobSqlDao in conjunction with MySql would fix this problem, but alas, we see a very similar problem with a different exception. The exception is now this:
> [2018-05-03 07:08:35,165] ERROR ark.jobserver.JobInfoActor [] [] - About to restart actor due to exception:
> com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'JOB_CONFIG' at row 1
>         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4185)
>         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4119)
>         at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2570)
>         at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2731)
>         at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2815)
>         at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
>         at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
>         at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
>         at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
>         at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction$$anonfun$run$7.apply(JdbcActionComponent.scala:507)
>         at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction$$anonfun$run$7.apply(JdbcActionComponent.scala:504)
>         at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:347)
>         at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:407)
>         at slick.driver.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:498)
>         at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:504)
>         at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:32)
>         at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:29)
>         at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
>         at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
> [2018-05-03 07:08:35,168] ERROR ka.actor.OneForOneStrategy [] [akka://JobServer/user/job-info] - Data truncation: Data too long for column 'JOB_CONFIG' at row 1
> com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'JOB_CONFIG' at row 1
>         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4185)
>         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4119)
>         at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2570)
>         at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2731)
>         at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2815)
>         at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
>         at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
>         at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
>         at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
>         at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction$$anonfun$run$7.apply(JdbcActionComponent.scala:507)
>         at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction$$anonfun$run$7.apply(JdbcActionComponent.scala:504)
>         at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:347)
>         at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:407)
>         at slick.driver.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:498)
>         at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:504)
>         at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:32)
>         at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:29)
>         at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
>         at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
> [2018-05-03 07:08:35,168] WARN  ark.jobserver.JobInfoActor [] [] - Shutting down spark.jobserver.JobInfoActor
> [2018-05-03 07:08:35,169] INFO  ark.jobserver.JobInfoActor [] [akka://JobServer/user/job-info] - Starting actor spark.jobserver.JobInfoActor
> [2018-05-03 07:08:35,269] INFO  ions.codegen.CodeGenerator [] [akka://JobServer/user/context-supervisor/sql-context] - Code generated in 10.098508 ms

The behavior is worse in this case because the sql-context gets destroyed and now the server is broken. In the FileDao case, work could continue. Is there a workaround? Can we change the mysql type for that column? Can we consider just truncating the config in cases when it is very large? Why does it need to be persisted?

To reproduce, you could just create a fake JSON request to a jobserver job that has many thousands of characters.

**Comment by velvia** [comment]
What is your SQL config? That probably has a big effect on how reliable it is.

**Comment by ecandreev** [comment]
How you determine that a job is finished if you receive 404 on a get?
If you use "sync" flag for a job, than you receive the result immediately after the job is finished and if you do not use this flag, you need not 404 response on a get to find out the sate of a job.

**Comment by barrybecker4** [comment]
@velvia, I'm not sure exactly what you mean by sql config, but here is the sqlcontext section in the local.conf file:
```
sqldao {
      slick-driver = slick.driver.MySQLDriver
      jdbc-driver = com.mysql.jdbc.Driver
      rootdir = /home/product/tmp/spark-jobserver/sqldao/data
      jdbc {
        url = "jdbc:mysql://localhost/spark_jobserver?createDatabaseIfNotExist=true&useSSL=false"
        user = "jobserver"
        password = "****"
      }

      # DB connection pool settings
      dbcp {
        enabled = false
        maxactive = 20
        maxidle = 10
        initialsize = 10
      }
    }
```
Is this what you are looking for?
We are using default my.cnf settings for mariadb installed on linux. The only thing that was changed was to increase max_packet_size to allow our 38m jar file to be uploaded. (Separate issue, why does the uploaded jar file need to be inserted in the db? could we just add a location to is?). Here is our server.cnf. Are there certain configurations that you think might help?
```
[root@xxx my.cnf.d]# cat server.cnf
#
# These groups are read by MariaDB server.
# Use it for options that only the server (but not clients) should see
#
# See the examples of server my.cnf files in /usr/share/mysql/
#

# this is read by the standalone daemon and embedded servers
[server]

# this is only for the mysqld standalone daemon
[mysqld]
max_allowed_packet = 80000000

# this is only for embedded server
[embedded]

# This group is only read by MariaDB-5.5 servers.
# If you use the same .cnf file for MariaDB of different versions,
# use this group for options that older servers don't understand
[mysqld-5.5]

# These two groups are only read by MariaDB servers, not by MySQL.
# If you use the same .cnf file for MySQL and MariaDB,
# you can put MariaDB-only options here
[mariadb]

[mariadb-5.5]
```

**Comment by ecandreev** [comment]
@barrybecker4 is there any reason why you are using async? If you need the result immediately after the job is finished, you could just use sync. It takes some time to write the result to DB, it is a normal behaviour.

**Comment by barrybecker4** [comment]
Yes, we  need to use sync because a) we want to show progress for long running jobs, and b) a long sync request will trigger timeouts in jobserver. I don't think getting a 404 should be normal behavior. If it takes time to write to the db, it should not be done running until after it has done that.

**Comment by sgautrin** [comment]
Encountered this issue as well (to be honest, the pretty big job config we got is really not ideal and we have work planned on it).

The most problematic thing in my opinion is that if the configuration is too big to be persisted, then the jobserver returns an error with no jobId reference, while the job is actually started and can possibly complete successfully.

Possible solutions could be:

1. store the job config before running the job (this would also means that config which do not validate would be stored with the job, see #1202 ): in that case however (unless next option is done as well), the job would not run at all, but this would be at least coherent with getting an error on submission
1. prevent job config persistence errors to bubble up to the API: if the job could actually be started, tell it to the caller; error would then be most likely just logged
1. obviously, for the sql dao, changing the column type to allow for bigger configurations is also an option, but might not work with all persistence backends, so that option would probably come on top of other solutions
