### ISSUE TITLE
actor name [endpointWriter] is not unique!

### ISSUE THREAD

**Issue by dashrathc** [spark-jobserver/spark-jobserver#1101]
**Used Spark version**
1.6.3
**Used Spark Job Server version**
jobserver-0.6.2-spark-1.6.1

**Deployed mode**
yarn-client

**Jobserver configuration for akka**
akka {
  cluster {
    failure-detector {
      threshold = 12
      acceptable-heartbeat-pause = 60s
      heartbeat-interval = 5s
      heartbeat-request {
        expected-response-after = 20s
      }
    }
	auto-down = off
    auto-down-unreachable-after = off
  }
}

**Logs**
[2018-07-29 10:36:01,578] ERROR Remoting [] [Remoting] - Monitored actor [Actor[akka://JobServer/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A40267-4/endpointWriter#225576570]] terminated
akka.actor.DeathPactException: Monitored actor [Actor[akka://JobServer/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A40267-4/endpointWriter#225576570]] terminated
[2018-07-29 10:36:43,181] WARN  ReliableDeliverySupervisor [] [akka.tcp://JobServer@127.0.0.1:41516/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A40267-9] - Association with remote system [akka.tcp://JobServer@127.0.0.1:40267] has failed, address is now gated for [5000] ms. Reason: [Disassociated]
[2018-07-29 10:37:24,984] WARN  ReliableDeliverySupervisor [] [akka.tcp://JobServer@127.0.0.1:41516/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A40267-9] - Association with remote system [akka.tcp://JobServer@127.0.0.1:40267] has failed, address is now gated for [5000] ms. Reason: [Disassociated]
[2018-07-29 10:37:24,992] ERROR Remoting [] [Remoting] - actor name [endpointWriter] is not unique!
akka.actor.InvalidActorNameException: actor name [endpointWriter] is not unique!
        at akka.actor.dungeon.ChildrenContainer$TerminatingChildrenContainer.reserve(ChildrenContainer.scala:192)
        at akka.actor.dungeon.Children$class.reserveChild(Children.scala:76)
        at akka.actor.ActorCell.reserveChild(ActorCell.scala:369)
        at akka.actor.dungeon.Children$class.makeChild(Children.scala:201)
        at akka.actor.dungeon.Children$class.actorOf(Children.scala:37)
        at akka.actor.ActorCell.actorOf(ActorCell.scala:369)
        at akka.remote.ReliableDeliverySupervisor.akka$remote$ReliableDeliverySupervisor$$createWriter(Endpoint.scala:395)
        at akka.remote.ReliableDeliverySupervisor$$anonfun$idle$1.applyOrElse(Endpoint.scala:345)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:188)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[2018-07-29 10:38:02,737] WARN  ReliableDeliverySupervisor [] [akka.tcp://JobServer@127.0.0.1:41516/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A40267-11] - Association with remote system [akka.tcp://JobServer@127.0.0.1:40267] has failed, address is now gated for [5000] ms. Reason: [Disassociated]

[2018-07-29 10:38:42,317] WARN  ReliableDeliverySupervisor [] [akka.tcp://JobServer@127.0.0.1:41516/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A40267-11] - Association with remote system [akka.tcp://JobServer@127.0.0.1:40267] has failed, address is now gated for [5000] ms. Reason: [Disassociated]

Getting lots of warnings and sometimes errors.
Could anyone please share input on above issue?

**Comment by bsikander** [comment]
`endpointWriter` is a system actor. Somehow you have 2 of them running in your actor system. This shouldn't be the case. Have you tried to restart SJS?

Further, `auto-down-unreachable-after` should not be off because SJS relies on it. I know that it is not recommended but for correct working of SJS you should set it to something like 20s.

**Comment by dashrathc** [comment]
@bsikander  Thanks for your input.

Restarting SJS will solve the problem but that is not the solution because it appears regularly.
Following is the default configuration according to https://github.com/spark-jobserver/spark-jobserver/blob/jobserver-0.6.2-spark-1.6.1/job-server/src/main/resources/application.conf

akka {
  # Use SLF4J/logback for deployed environment logging
  loggers = ["akka.event.slf4j.Slf4jLogger"]

  actor {
    provider = "akka.cluster.ClusterActorRefProvider"
    warn-about-java-serializer-usage = off
  }

  remote {
    log-remote-lifecycle-events = off
    netty.tcp {
      hostname = "127.0.0.1"
      port = 0
      send-buffer-size = 512000b
      receive-buffer-size = 512000b
      # This controls the maximum message size, including job results, that can be sent
      maximum-frame-size = 10 MiB
    }
  }

  cluster {
    auto-down-unreachable-after = 20s
    metrics.enabled = off
    failure-detector.acceptable-heartbeat-pause = 3s
    failure-detector.threshold = 12.0
  }
}

When I have't set anything it shows following warning when job is running for long time,
WARN  Remoting [] [Remoting] - Tried to associate with unreachable remote address [akka.tcp://JobServer@127.0.0.1:41069]. Address is now gated for 5000 ms, all messages to this address will be delivered to dead letters. Reason: [The remote system has quarantined this system. No further associations to the remote system are possible until this system is restarted.]

After above incident, SJS keeps current job as running even though all the jobs are completed in spark.
