### ISSUE TITLE
spark-jobserver can not use mysql backend

### ISSUE THREAD

**Issue by highmoutain** [spark-jobserver/spark-jobserver#1115]
**Used Spark version**
2.2.1
**Used Spark Job Server version**
(Released version, git branch or docker image version)
0.8.0
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
YARN client
**Actual (wrong) behavior**
use mysql backend.when execute server_start.sh , job server can not start. Logs are:
[2018-09-10 11:12:55,837] ERROR spark.jobserver.JobServer$ [] [] - Unable to start Spark JobServer:
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at spark.jobserver.JobServer$.start(JobServer.scala:102)
        at spark.jobserver.JobServer$.main(JobServer.scala:190)
        at spark.jobserver.JobServer.main(JobServer.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:775)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.flywaydb.core.api.FlywayException: Schema `spark_jobserver` contains a failed migration to version 0.7.0 !
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:196)
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:156)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1059)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
        at spark.jobserver.io.JobSqlDAO.init(JobSqlDAO.scala:134)
        at spark.jobserver.io.JobSqlDAO.<init>(JobSqlDAO.scala:122)
        ... 16 more
when use h2 backend , everything is ok!
**Steps to reproduce**
use mysql backend, then execute server_start.sh.
**Logs**

```
some log
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by bsikander** [comment]
Somehow your migration failed. umm
I sometimes use MySql and generally, I don't have a problem.

Are you using a new MySql database or upgrading from an old version?

**Comment by highmoutain** [comment]
I have solved this problem.This problem occurs when config
"flyway.locations" in wrong location, this config must be in rootdir.
I can not close this issue, can you close it ?

Behroz Sikander <notifications@github.com> 于2018年9月11日周二 下午9:07写道：
