### ISSUE TITLE
 java.nio.file.NoSuchFileException: /app/spark-job-server.jar

### ISSUE THREAD

**Issue by apclement** [spark-jobserver/spark-jobserver#1133]
**Used Spark version**
2.3.1
**Used Spark Job Server version**
(Released version, git branch or docker image version)
master branch, 0.8.1-snapshot, docker
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
Spark Standalone cluster mode

Unable to launch a simple Job in cluster mode. What is the purpose of  REMOTE_JOBSERVER_DIR ? Isn't Spark submit supposed to take care of deploying everything automatically on the cluster ?

**Logs**
 ERROR ClientEndpoint: Exception from cluster was: java.nio.file.NoSuchFileException: /app/spark-job-server.jar
java.nio.file.NoSuchFileException: /app/spark-job-server.jar
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
        at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
        at java.nio.file.Files.copy(Files.java:1274)
        at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$copyRecursive(Utils.scala:635)
        at org.apache.spark.util.Utils$.copyFile(Utils.scala:606)
        at org.apache.spark.util.Utils$.doFetchFile(Utils.scala:691)
        at org.apache.spark.util.Utils$.fetchFile(Utils.scala:488)
        at org.apache.spark.deploy.worker.DriverRunner.downloadUserJar(DriverRunner.scala:155)
        at org.apache.spark.deploy.worker.DriverRunner.prepareAndRunDriver(DriverRunner.scala:173)
        at org.apache.spark.deploy.worker.DriverRunner$$anon$1.run(DriverRunner.scala:92)

```

**Comment by bsikander** [comment]
>> Isn't Spark submit supposed to take care of deploying everything automatically on the cluster ?

It depends what you pass to spark-submit or set for variable `REMOTE_JOBSERVER_DIR`. If the path that you specify is a local path then it is your responsibility to make the jar file available on the same path on each worker node.

If you specify hdfs/s3... based file paths then Spark can automatically download from these distributed storages.

In your case, it seems that on the workers you don't have the jobserver jar file in /app folder. You need to put it there. 

With current master, you should use local path because hadoop based paths have a problem. A fix will be uploaded hopefully this week or start of next week.

If you use `server_deploy.sh` script in `bin` folder of jobserver then jobserver can copy the files to remote machine for you.

**Comment by apclement** [comment]
I deploy SJS as a docker container in a swarm stack. And yes, in **cluster mode** and spark standalone mode,  application.jar has to be visible from all the worker nodes.

**Comment by bsikander** [comment]
@apclement with following PR, you can use hdfs/s3 paths.
https://github.com/spark-jobserver/spark-jobserver/pull/1136
