### ISSUE TITLE
Identify the state of Spark-JobServer actors

### ISSUE THREAD

**Issue by SrivigneshM** [spark-jobserver/spark-jobserver#1149]
**Spark: 2.2.4**

**SJS: v0.6.2**

**Deployment: Cluster**

**Issue:**
Actors like JobInfoActor, JobManagerActor etc., gets shut down sometimes with below exception. Auto-restart of the actors does not happen in this case and it becomes dead.

Is it possible to know if all the actors are alive through an API or through some other means? If so, it might help in identifying the non-alive actors and bring back the system.

**Logs:**

```
18/08/22 08:52:00 ERROR OneForOneStrategy: [akka://JobServer/user/job-info] - Futures timed out after [3 seconds]
java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:167)
at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:165)
at scala.concurrent.Await$.result(package.scala:190)
at spark.jobserver.JobInfoActor$$anonfun$wrappedReceive$1$$anonfun$applyOrElse$1.apply$mcV$sp(JobInfoActor.scala:64)
at scala.util.control.Breaks.breakable(Breaks.scala:38)
at spark.jobserver.JobInfoActor$$anonfun$wrappedReceive$1.applyOrElse(JobInfoActor.scala:46)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)
at ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)
at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
at ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
at akka.actor.ActorCell.invoke(ActorCell.scala:495)
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
at akka.dispatch.Mailbox.run(Mailbox.scala:224)
at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
18/08/22 08:52:01 ERROR JobInfoActor: [] - About to restart actor due to exception:
java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:167)
at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:165)
at scala.concurrent.Await$.result(package.scala:190)
at spark.jobserver.JobInfoActor$$anonfun$wrappedReceive$1$$anonfun$applyOrElse$1.apply$mcV$sp(JobInfoActor.scala:64)
at scala.util.control.Breaks.breakable(Breaks.scala:38)
at spark.jobserver.JobInfoActor$$anonfun$wrappedReceive$1.applyOrElse(JobInfoActor.scala:46)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)
at ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)
at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
at ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
at akka.actor.ActorCell.invoke(ActorCell.scala:495)
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
at akka.dispatch.Mailbox.run(Mailbox.scala:224)
at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
18/08/22 08:52:01 WARN JobInfoActor: [] - Shutting down spark.jobserver.JobInfoActor
```

**Comment by bsikander** [comment]
Interesting, I have never seen this happening. After an exceptions actors always recover by restarting.

>> Is it possible to know if all the actors are alive through an API or through some other means? If so, it might help in identifying the non-alive actors and bring back the system.
Jobserver has no API which gives this information. Jobserver code can be modified to get this information.

But in the first place it shouldn't happen. Have you tried asking this question in Akka's github?

**Comment by SrivigneshM** [comment]
Implemented healthz API by passing messages to the actors. If an expected response is received from the actor, it means that the actor is alive.

**Comment by bsikander** [comment]
+1

If that could be interesting for other users also, then you can also contribute back :)
