### ISSUE TITLE
dependent-jar-uris not picked up

### ISSUE THREAD

**Issue by walmir** [spark-jobserver/spark-jobserver#1151]
**Used Spark version**: 2.3.1

**Used Spark Job Server version**: Master
(Released version, git branch or docker image version)

**Deployed mode**: Cluster - Spark Standalone

**Actual (wrong) behavior**: dependent-jar-uris parameter is not picked up. 

**Steps to reproduce**
1. Placed `base.jar` on SJS machine under `/tmp/base.jar`.
2. Created new context with `dependent-jar-uris`
3. Started Job that requires `base.jar`
-> Always results in `ClassNotFoundException`

I've tried using `dependent-jar-uris` as a URL parameter and in the POST body when creating the context. I've tried setting it in the context-settings as: `context-settings.dependent-jar-uris = ["file:///tmp/base.jar"]`
And I've tried submitting it when deploying a job, that requires this jar. Non worked.

I would really appreciate your help on this.

Thanks.

**Comment by walmir** [comment]
I just noticed the following log statements when I try to start a Job:
```
[2019-01-28 20:36:32,950] INFO  AkkaClusterSupervisorActor [] [] - SparkContext new-context joined
[2019-01-28 20:36:40,484] WARN  ReliableDeliverySupervisor [] [akka.tcp://JobServer@ec2----.compute.amazonaws.com:38386/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%4010.10.2.61%3A40499-6] - Association with remote system [akka.tcp://JobServer@10.10.2.61:40499] has failed, address is now gated for [5000] ms. Reason: [Disassociated]
[2019-01-28 20:36:44,760] WARN  .cluster.ClusterCoreDaemon [] [akka.tcp://JobServer@ec2----.compute.amazonaws.com:38386/system/cluster/core/daemon] - Cluster Node [akka.tcp://JobServer@ec2----.compute.amazonaws.com:38386] - Marking node(s) as UNREACHABLE [Member(address = akka.tcp://JobServer@10.10.2.61:40499, status = Up)]. Node roles [supervisor]
[2019-01-28 20:36:45,524] WARN  ReliableDeliverySupervisor [] [akka.tcp://JobServer@ec2----.compute.amazonaws.com:38386/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%4010.10.2.61%3A40499-6] - Association with remote system [akka.tcp://JobServer@10.10.2.61:40499] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://JobServer@10.10.2.61:40499]] Caused by: [Connection refused: /10.10.2.61:40499]
[2019-01-28 20:36:51,523] WARN  ReliableDeliverySupervisor [] [akka.tcp://JobServer@ec2-----.compute.amazonaws.com:38386/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%4010.10.2.61%3A40499-6] - Association with remote system [akka.tcp://JobServer@10.10.2.61:40499] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://JobServer@10.10.2.61:40499]] Caused by: [Connection refused: /10.10.2.61:40499]
[2019-01-28 20:36:57,524] WARN  ReliableDeliverySupervisor [] [akka.tcp://JobServer@ec2-----.compute.amazonaws.com:38386/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%4010.10.2.61%3A40499-6] - Association with remote system [akka.tcp://JobServer@10.10.2.61:40499] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://JobServer@10.10.2.61:40499]] Caused by: [Connection refused: /10.10.2.61:40499]
[2019-01-28 20:37:03,525] WARN  ReliableDeliverySupervisor [] [akka.tcp://JobServer@ec2----.compute.amazonaws.com:38386/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%4010.10.2.61%3A40499-6] - Association with remote system [akka.tcp://JobServer@10.10.2.61:40499] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://JobServer@10.10.2.61:40499]] Caused by: [Connection refused: /10.10.2.61:40499]
[2019-01-28 20:37:06,309] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Actor terminated: jobManager-a76f9b7c-7a0d-4dc7-b740-f5361f41e4da
[2019-01-28 20:37:06,372] INFO  .Cluster(akka://JobServer) [] [akka.cluster.Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@ec2----.compute.amazonaws.com:38386] - Ignoring down of unknown node [akka.tcp://JobServer@10.10.2.61:40499]
```

Is the port 40499 supposed to be the spark worker? Because in that case, it's the wrong port.

**Comment by walmir** [comment]
A bit more context I guess. This is the response I'm receiving from the API:
```
{
"status": "ERROR",
"result": {
"message": "Ask timed out on [Actor[akka.tcp://JobServer@10.10.3.24:35317/user/jobManager-b32441f0-6679-47f9-820d-90796db5a7be#-514849208]] after [10000 ms]. Sender[null] sent message of type "spark.jobserver.JobManagerActor$StartJob".",
"errorClass": "akka.pattern.AskTimeoutException",
"stack": "akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka.tcp://JobServer@10.10.3.24:35317/user/jobManager-b32441f0-6679-47f9-820d-90796db5a7be#-514849208]] after [10000 ms]. Sender[null] sent message of type "spark.jobserver.JobManagerActor$StartJob". at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604) at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126) at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601) at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109) at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599) at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:331) at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:282) at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:286) at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:238) at java.lang.Thread.run(Thread.java:748) "
}
}
```

My current assumption is that the dependency jar (`base.jar`) is too big to transmit in 10 s. It is around 100MB. 
However, I was not able to find out where can I change this timeout value?

**Comment by walmir** [comment]
I was finally able to get my jobs working by manually uploading the jar to all workers under the same location, and setting `dependent-jar-uris = ["local:/tmp/base.jar"]`.

Is it possible to get JobServer to handle uploading necessary dependency jars to workers? And if so, how can I increase the timeout to allow a larger jar file to be copied?

**Comment by valan4ik** [comment]
If you want to increase the timeout for the context creation, you can try setting larger value for the setting `spark.jobserver.yarn-context-creation-timeout` in case of yarn or `spark.jobserver.context-creation-timeout` in case of standalone.
If you use dependent-jar-uris with `file://` protocol, then it's enough to have jar only on driver node.

**Comment by ducphamle2** [comment]
I have the same problem here (Spark standalone cluster mode with spark job server HA). Currently my solution is to append every jars i need whenever i submit a job, but this will not work well if the number of dependencies increases. I tested a lot of cases such as adding jars in the conf file, using `dependent-jar-uris` when setting a context, using --jars / --packages when starting the job server. However, none of these methods worked. i would highly appreciate if someone can help me or anyone facing this issue. Thanks !

**Comment by valan4ik** [comment]
Hi @ducphamle2,
`dependent-jar-uris` should work for the context exactly the same way as for the job.
As mentioned in the comments above, if you use `local:/some/path` protocol, then it's your responsibility to make dependent jars **available on each worker** machine under `/some/path`. Alternatively, you can upload dependent jar to Jobserver (e.g. `curl -X POST localhost:8090/binaries/$BINARY_NAME`) and then just add uploaded binary name to `dependent-jar-uris` (e.g. `dependent-jar-uris = ["$BINARY_NAME"]`.

**Comment by ducphamle2** [comment]
Thanks for your quick reply @valan4ik !!
Your solution of uploading dependent jars to Jobserver works very well ! I did not even think of that haha. 
My jobserver version is 0.8.0 by the way. For the context, do you understand why it does not work while submitting jobs does ? I used `file:///path/to/jar` instead of `local:/`. And lastly, how can i make my jars available on each worker ?. Many thanks !!

To some who are struggling with dependent jars, you can follow @valan4ik 's answer. My implementation that worked is below:

```
curl -X POST localhost:8090/binaries/streaming -H "Content-Type: application/java-archive" --data-binary @/home/spark/job-server/spark-streaming-kafka-0-10_2.11-2.3.2.jar
```
```
curl -d '{dependent-jar-uris = ["streaming"]}' "localhost:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample&context=test-context&sync=true"
```

**Comment by valan4ik** [comment]
@ducphamle2 , glad it worked.
Regarding making jars available on each worker, it's just by manually uploading to each machine. Jobserver is no help here.

Actually, I am really confused, that dependent jars work for you for the job, but not for the context. Do you see the same behavior, if you upload jar to jobserver and add it as a dependency for the context?

**Comment by ducphamle2** [comment]
@valan4ik i just tested. Suprisingly it did not work either !! I used the same method with jars uploaded to jobserver. Instead of adding them as dependencies for jobs, i used for context instead. When i submitted a streaming application job (without adding dependencies in this step), `NoClassDefFoundError` error occured.

**Comment by valan4ik** [comment]
@ducphamle2 hm, interesting. Maybe there is a bug in jobserver. I will then also test today in the evening or tomorrow and will get back to you :)

**Comment by valan4ik** [comment]
Hi, I can confirm it's a bug.
Some time ago I made a change introducing dependent jars from Jobserver DB and introduced a new parameter name (`cp`). I mapped the old parameter name (`dependent-jar-uris`) to the new one for the jobs but didn't do it for the contexts.
But if you use `cp` instead of `dependent-jar-uris` then it should work.

I am working on the fix.

**Comment by ducphamle2** [comment]
@valan4ik Thanks for your update !!
Good to know that we have discovered a bug haha, now others will not have to spend much time on this thinking they do something wrong. Have a good day sir, and hope that the bug is fixed soon !

**Comment by valan4ik** [comment]
The fix was merged. Closing the issue, please reopen if you find problems with the snapshot version of the jobserver.
