### ISSUE TITLE
The job not finished with an error for `java.lang.OutOfMemoryError: Java heap space`

### ISSUE THREAD

**Issue by fengxucn** [spark-jobserver/spark-jobserver#1161]
**Used Spark version**
2.2.0

**Used Spark Job Server version**
(Released version, git branch or docker image version)
0.8.0

**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
YARN Client

**Actual (wrong) behavior**
The job should finished with an error

**What I did in my code**
`sparkSession.sparkContext.broadcast(castarData.map(row => row.getAs[String]("id")).distinct().collect.toSet)`

**Logs**

```
2019-02-25 20:44:36 ERROR JobManagerActor:606 - Got Throwable
java.lang.OutOfMemoryError: Java heap space
        at scala.collection.mutable.ResizableArray$class.ensureSize(ResizableArray.scala:103)
        at scala.collection.mutable.ArrayBuffer.ensureSize(ArrayBuffer.scala:48)
        at scala.collection.mutable.ArrayBuffer.$plus$eq(ArrayBuffer.scala:84)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeCollect$1$$anonfun$apply$2.apply(SparkPlan.scala:279)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeCollect$1$$anonfun$apply$2.apply(SparkPlan.scala:279)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at org.apache.spark.sql.execution.SparkPlan$$anon$1.foreach(SparkPlan.scala:257)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeCollect$1.apply(SparkPlan.scala:279)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeCollect$1.apply(SparkPlan.scala:278)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:278)
        at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:2854)
        at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2391)
        at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2391)
        at org.apache.spark.sql.Dataset$$anonfun$55.apply(Dataset.scala:2838)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:65)
        at org.apache.spark.sql.Dataset.withAction(Dataset.scala:2837)
        at org.apache.spark.sql.Dataset.collect(Dataset.scala:2391)
        at com.walmartlabs.castar.tools.jobServer.BulkQuery$$anonfun$runJob$1.apply(BulkQuery.scala:85)
        at com.walmartlabs.castar.tools.jobServer.BulkQuery$$anonfun$runJob$1.apply(BulkQuery.scala:43)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at com.walmartlabs.castar.tools.jobServer.BulkQuery$.runJob(BulkQuery.scala:43)
        at com.walmartlabs.castar.tools.jobServer.BulkQuery$.runJob(BulkQuery.scala:20)
        at spark.jobserver.SparkSessionJob$class.runJob(SparkSessionJob.scala:16)
        at com.walmartlabs.castar.tools.jobServer.BulkQuery$.runJob(BulkQuery.scala:20)
        at com.walmartlabs.castar.tools.jobServer.BulkQuery$.runJob(BulkQuery.scala:20)
        at spark.jobserver.JobManagerActor$$anonfun$getJobFuture$4.apply(JobManagerActor.scala:594)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
```

**What I expect Log looks like**
```
2019-02-15 20:16:26 ERROR JobManagerActor:606 - Got Throwable
java.lang.NullPointerException
        at com.walmartlabs.castar.tools.jobServer.BulkQueryDummy$.validate(BulkQueryDummy.scala:40)
        at spark.jobserver.SparkSessionJob$class.validate(SparkSessionJob.scala:24)
        at com.walmartlabs.castar.tools.jobServer.BulkQueryDummy$.validate(BulkQueryDummy.scala:18)
        at com.walmartlabs.castar.tools.jobServer.BulkQueryDummy$.validate(BulkQueryDummy.scala:18)
        at spark.jobserver.JobManagerActor$$anonfun$getJobFuture$4.apply(JobManagerActor.scala:585)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2019-02-15 20:16:26 ERROR JobManagerActor:626 - Exception from job d503a00e-d22d-4133-8f60-bf17e369c2a9:
java.lang.NullPointerException
        at com.walmartlabs.castar.tools.jobServer.BulkQueryDummy$.validate(BulkQueryDummy.scala:40)
        at spark.jobserver.SparkSessionJob$class.validate(SparkSessionJob.scala:24)
        at com.walmartlabs.castar.tools.jobServer.BulkQueryDummy$.validate(BulkQueryDummy.scala:18)
        at com.walmartlabs.castar.tools.jobServer.BulkQueryDummy$.validate(BulkQueryDummy.scala:18)
        at spark.jobserver.JobManagerActor$$anonfun$getJobFuture$4.apply(JobManagerActor.scala:585)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
**My Question is**
The job server can catch the exception at JobManagerActor:606, why not run to JobManagerActor:625 to stop the job?

**Comment by thoHeinze** [comment]
@fengxucn Can you please add a bit more information on what you are doing here? This error looks like an issue with your Spark job.

**Comment by fengxucn** [comment]
In my code I broadcast an id set, some times, the id set was too big, so, there has OutOfMemoryError Exception. my question is the job server can catch the exception at JobManagerActor:606, why not run to JobManagerActor:623 to stop the job?

**Comment by fengxucn** [comment]
using following code to fix the issue:

```
try{
   code
}catch{
    case unknown: Throwable => {
        code
        throw new RuntimeException(unknown)
    }
}
```

**Comment by sgautrin** [comment]
I guess this issue should probably be reopened and dealt with: as it is, if a job encounters a “fatal” throwable (any non matched by `util.control.NonFatal`), then the future running the job in `JobManagerActor` will never complete and thus the `andThen` instructions will never be called, which means that then the `JobErroredOut` is never sent to the JobStatusActor, and the job is not removed from current running jobs.

Fatal throwables include `VirtualMachineError` (which include `StackOverflowError and `OutOfMemoryError`) and `InterruptedException`.

Obviously we can workaround this currently in jobs implementation with the code given above by @fengxucn , but this is something that should most likely be handled by the jobserver; indeed, those fatal errors are meant to indicate it is not recoverable, but in this case the jobserver needs to register the error and clean up.

An option could be to wrap all throwables in a `RuntimeException` (or more specific exception eventually) within the catch part of the future
```scala
 catch {
  case e: java.lang.AbstractMethodError => {
    logger.error("Oops, there's an AbstractMethodError... maybe you compiled " +
      "your code with an older version of SJS? here's the exception:", e)
    throw new RuntimeException(e)
  }
  case e: Throwable => {
    logger.error("Got Throwable", e)
    throw new RuntimeException(e)
  };
}
```
and then within the first `andThen` to unwrap it with `error.getCause` and use that unwrapped error where the error was used.

**Comment by bsikander** [comment]
Good idea. Contributions are welcomed.

**Comment by sgautrin** [comment]
> Good idea. Contributions are welcomed.

I'll see if I can take some time for it then. Would such a fix be made on master or on older targets?

> If i understand you correct, then you mean that `case Failure(error: Throwable)` inside `andthen.` won't work since `scala.util.Failure` only catches non-fatal exceptions and wrapping the fatal exceptions into non-fatal one's would allow to do a cleanup.

Exactly, fatal exceptions result in actual processing stopping in the `Future` block and the Future never completing (neither with a Success nor a Failure), so wrapping them allows the Future to complete as a Failure and the cleanup to occur.

**Comment by bsikander** [comment]
This fix should go on Master branch.
