### ISSUE TITLE
cannot starting on kerberos-secured cluster

### ISSUE THREAD

**Issue by cswt** [spark-jobserver/spark-jobserver#1162]
**Used Spark version**
2.3.0
**Used Spark Job Server version**
(Released version, git branch or docker image version)
0.7.0
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
client on YARN
**Actual (wrong) behavior**
Unable to start Spark JobServer
**Steps to reproduce**
1. install mysql 5.7.14
2. modify settings.conf to adapt to the CDH environment
3. starting server_restart.sh
**Logs**

```
[2019-02-28 17:00:32,838] INFO  ka.event.slf4j.Slf4jLogger [] [] - Slf4jLogger started
[2019-02-28 17:00:32,964] INFO  akka.remote.Remoting [] [akka.remote.Remoting] - Starting remoting
[2019-02-28 17:00:33,150] INFO  akka.remote.Remoting [] [akka.remote.Remoting] - Remoting started; listening on addresses :[akka.tcp://JobServer@127.0.0.1:46769]
[2019-02-28 17:00:33,161] INFO  .Cluster(akka://JobServer) [] [akka.cluster.Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:46769] - Starting up...
[2019-02-28 17:00:33,198] INFO  .Cluster(akka://JobServer) [] [akka.cluster.Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:46769] - Registered cluster JMX MBean [akka:type=Cluster]
[2019-02-28 17:00:33,198] INFO  .Cluster(akka://JobServer) [] [akka.cluster.Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:46769] - Started up successfully
[2019-02-28 17:00:33,267] INFO  .Cluster(akka://JobServer) [] [akka.cluster.Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:46769] - No seed-nodes configured, manual cluster join required
[2019-02-28 17:00:34,178] INFO  ark.jobserver.io.JobSqlDAO [] [] - rootDir is /tmp/spark-jobserver/sqldao/data
[2019-02-28 17:00:34,184] INFO  ark.jobserver.io.JobSqlDAO [] [] - DBCP enabled
[2019-02-28 17:00:34,231] INFO  ternal.util.VersionPrinter [] [] - Flyway 3.2.1 by Boxfuse
[2019-02-28 17:00:34,448] INFO  dbsupport.DbSupportFactory [] [] - Database: jdbc:mysql://127.0.0.1/spark_jobserver (MySQL 5.7)
[2019-02-28 17:00:34,577] INFO  nternal.command.DbValidate [] [] - Validated 6 migrations (execution time 00:00.091s)
[2019-02-28 17:00:34,597] INFO  internal.command.DbMigrate [] [] - Current version of schema `spark_jobserver`: 0.7.0
[2019-02-28 17:00:34,599] ERROR spark.jobserver.JobServer$ [] [] - Unable to start Spark JobServer: 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at spark.jobserver.JobServer$.start(JobServer.scala:102)
	at spark.jobserver.JobServer$.main(JobServer.scala:190)
	at spark.jobserver.JobServer.main(JobServer.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.flywaydb.core.api.FlywayException: Schema `spark_jobserver` contains a failed migration to version 0.7.0 !
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:196)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:156)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1059)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
	at spark.jobserver.io.JobSqlDAO.init(JobSqlDAO.scala:132)
	at spark.jobserver.io.JobSqlDAO.<init>(JobSqlDAO.scala:120)
	... 17 more
[2019-02-28 17:00:34,602] INFO  k.util.ShutdownHookManager [] [] - Shutdown hook called
[2019-02-28 17:00:34,603] INFO  k.util.ShutdownHookManager [] [] - Deleting directory /tmp/spark-b7073eb2-ec71-4cd0-8f14-97e3c31703c3

```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by bsikander** [comment]
Do you know why you have a failed migration ?
`Schema `spark_jobserver` contains a failed migration to version 0.7.0 !`

If DB is not important or you are just testing then having a new DB will solve the issue.

**Comment by bsikander** [comment]
Closing the issue due to inactivity. Please reopen if the problem is not solved.
