### ISSUE TITLE
SJS 0.9.0 still searching for manager_start.sh 

### ISSUE THREAD

**Issue by AadhiKat** [spark-jobserver/spark-jobserver#1186]
Im trying to catch up with the new SJS 0.9.0 in my application.  Initiallly , when I am trying to create a context , it throws me an error that cannot find manager_start.sh . I cannot find anything like sparklauncher. 

Further when tried with deploy mode as client  , it dosent search for the manager_start.sh
When I tried using the manager_start from 0.8.0 , then it showed me this 
 
```
19/04/10 21:45:06 ERROR JobDAOActor: About to restart actor due to exception:
org.postgresql.util.PSQLException: ERROR: null value in column "CONTEXT_ID" violates not-null constraint
  Detail: Failing row contains (c144684e-3dad-459d-acff-2ac353709092, SJS_512_MB_shared_prioritized@1, 1, spark.jobserver.DPAASExecutor, 2019-04-10 21:45:06.602, null, null, null, null, null, null).
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:366)
    at slick.driver.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction$$anonfun$nativeUpsert$1.apply(JdbcActionComponent.scala:560)
    at slick.driver.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction$$anonfun$nativeUpsert$1.apply(JdbcActionComponent.scala:557)
    at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:347)
    at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:407)
    at slick.driver.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:498)
    at slick.driver.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.nativeUpsert(JdbcActionComponent.scala:557)
    at slick.driver.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.f$1(JdbcActionComponent.scala:540)
    at slick.driver.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.run(JdbcActionComponent.scala:545)
    at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:32)
    at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:29)
    at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
    at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

https://github.com/spark-jobserver/spark-jobserver/pull/1058 . This is the feature that has been added in SJS 0.9.0

Any suggestions on what needs to be done ?

**Comment by bsikander** [comment]
In 0.9.0, we don't have manager_launcher.sh anymore. We have switched to SparkLauncher. But SparkLauncher is not a file located somewhere, it is just a class from Spark that we are using in code.

The code is [here](https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/main/scala/spark/jobserver/util/Launcher.scala) and [here](https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/main/scala/spark/jobserver/util/ManagerLauncher.scala)

For your `null` issue, I am not sure how you reached this state. Please give us some information so that we can reproduce this.

**Comment by AadhiKat** [comment]
The null issue occurred when I copied the manager_start from 0.8 to solve the issue. [Can be ignored]

The major issue is this :
[```
2019-04-11 18:55:49,646] ERROR AkkaClusterSupervisorActor [] [] - About to restart actor due to exception:
java.io.IOException: Cannot run program "./manager_start.sh": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:69)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:100)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:99)
        at spark.jobserver.AkkaClusterSupervisorActor.spark$jobserver$AkkaClusterSupervisorActor$$startContext(AkkaClusterSupervisorActor.scala:252)
        at spark.jobserver.AkkaClusterSupervisorActor$$anonfun$wrappedReceive$1.applyOrElse(AkkaClusterSupervisorActor.scala:128)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
        at spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)
        at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 24 more

```

I am trying to use SJS with Spark standalone (2.4.0) in cluster mode.  When used in client mode it works fine.

**Comment by thoHeinze** [comment]
@AadhiKat  Can you please share your SJS config? As mentioned by @bsikander , there is no manager_start.sh anymore. Most likely you need to adapt your config.

**Comment by AadhiKat** [comment]
Hi @thoHeinze ,
 
Here is my conf .. 
```

This is as similar to what has been in SJS 0.8.0 and as suggessted in here.  Can you please tell me what should I change ? 

spark {
  master = "spark://xxx.xx.xx.xx:xxxx,yyy.yy.yy.yy:yyyy"
  submit.deployMode = "cluster"
  job-number-cpus = 4

  jobserver {
    port = 9090
    context-per-jvm = true
    ignore-akka-hostname=false
    jobdao = spark.jobserver.io.JobSqlDAO

    filedao {
      rootdir = /home/sas/zdpas/job-server/filedao/data
    }

    datadao {
      rootdir = /home/sas/zdpas/job-server/upload
    }

    sqldao {
      slick-driver = slick.driver.PostgresDriver
      jdbc-driver = org.postgresql.Driver
      rootdir = /home/sas/zdpas/job-server/sqldao/data
      jdbc {
        url = "jdbc:postgresql://zzz.zz.zz.zz:zzzz/spark_jobserver"
        user = "jobserver"
        password = ""
      }
      dbcp {
        enabled = false
        maxactive = 20
        maxidle = 10
        initialsize = 10
      }
    }
    result-chunk-size = 1m
  }

  context-settings {
    passthrough {
		spark.executor.extraJavaOptions = "-Dorg.xerial.snappy.tempdir=/home/sas/zdpas/spark/snappydata"
		spark.driver.extraJavaOptions =  "-Dorg.xerial.snappy.tempdir=/home/sas/zdpas/spark/snappydata"
      #es.nodes = "192.1.1.1"
    }
  }
  home = "/home/sas/zdpas/spark"
}

akka {
  remote.netty.tcp {
	hostname="zzz.zz.zz.zz"

  # maximum-frame-size = 10 MiB
  }
}

flyway.locations="db/postgresql/migration"

shiro{
  authentication = on
  config.path = /home/sas/zdpas/job-server/shiro.ini
  authentication-timeout = 10s
}


spray.can.server {
	idle-timeout = 120s
	request-timeout = 100s
	parsing {
		max-content-length = 30m
		#max-uri-length = 8k
	}
}
```

**Comment by bsikander** [comment]
It seems that you are still using SJS 0.8.0 jar file because [Ln#252](https://github.com/spark-jobserver/spark-jobserver/blob/v0.8.0/job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala#L252) is the exact line which triggers the spark-submit using `manager_start.sh`


See the following stack trace where Ln#252 is being called in AkkaClusterSupervisor.
```
        at **spark.jobserver.AkkaClusterSupervisorActor.spark$jobserver$AkkaClusterSupervisorActor$$startContext(AkkaClusterSupervisorActor.scala:252)**
```

Please make sure that you have the latest jar file.

**Comment by AadhiKat** [comment]
@bsikander Thanks! You were right ! I did use the job-server jar which was from 0.8.0 ! Thanks!
