### ISSUE TITLE
Fail to read HDFS text file then saveAsHdfsFile from spark-jobserver job due to HDFS _temporary folder not found. 

### ISSUE THREAD

**Issue by svendx4f** [spark-jobserver/spark-jobserver#12]
I am failing to execute a basic read from HDFS / process / write to HDFS Spark job executed from the Spark job server. 

We are running the latest version of the job-server from the master branch with Spark 1.1, Mesos 0.20 and HDFS from CDH 5.1 (the same issue is visible with Spark 1.0.2). 

The code of the process(..) method works successfully on Spark/Mesos when executed from the spark-shell but fails when bundled in a SparkJob and ran from the Spark job server. 

```
class JobServerTest extends SparkJob {

  override def runJob(sparkContext: SparkContext, jobConfig: Config): Any =
    new Tool().process(sparkContext, jobConfig.getString("destinationFoler"))

  override def validate(sc: SparkContext, config: Config): SparkJobValidation = SparkJobValid

}

class Tool extends Serializable{

  case class Data (part: Int, word1: String, amount1: Double, amount2: Double, letter1: String, word2: String) extends Serializable

  def process(sparkContext: SparkContext, destinationFolder: String) =
    sparkContext.textFile("hdfs://vm28-hulk-priv:8020/svend/test-jobserver/source")
      .map(_.split(","))
      .filter(_.length == 6)
      .map(raw => new Data(raw(0).toInt, raw(1), raw(2).toDouble, raw(3).toDouble, raw(4), raw(5)) )

      // some silly operations just to shuffle + process data
      .map (data => data.copy(amount1 = data.amount2 * Math.sqrt(data.amount1)))
      .groupBy(_.part)
      .flatMap { case (part, data) => data}
      .saveAsTextFile(destinationFolder)
}
```

On each Mesos slave nodes, the following stack traces are visible: 

```
14/09/22 11:27:33 INFO BlockFetcherIterator$BasicBlockFetcherIterator: Getting 16 non-empty blocks out of 16 blocks
14/09/22 11:27:33 INFO BlockFetcherIterator$BasicBlockFetcherIterator: Started 0 remote fetches in 6 ms
14/09/22 11:27:33 INFO BlockFetcherIterator$BasicBlockFetcherIterator: Started 0 remote fetches in 2 ms
14/09/22 11:27:33 INFO BlockFetcherIterator$BasicBlockFetcherIterator: Started 0 remote fetches in 1 ms
14/09/22 11:27:33 INFO BlockFetcherIterator$BasicBlockFetcherIterator: Started 2 remote fetches in 15 ms
14/09/22 11:27:33 INFO SendingConnection: Initiating connection to [vm21-hulk-priv.mtl.mnubo.com/10.237.241.21:54104]
14/09/22 11:27:33 INFO SendingConnection: Connected to [vm21-hulk-priv.mtl.mnubo.com/10.237.241.21:54104], 2 messages pending
14/09/22 11:27:33 INFO BlockFetcherIterator$BasicBlockFetcherIterator: Started 2 remote fetches in 12 ms
14/09/22 11:27:33 INFO BlockFetcherIterator$BasicBlockFetcherIterator: Started 2 remote fetches in 16 ms
14/09/22 11:27:33 INFO BlockFetcherIterator$BasicBlockFetcherIterator: Started 2 remote fetches in 16 ms
14/09/22 11:27:33 INFO ConnectionManager: Accepted connection from [vm21-hulk-priv.mtl.mnubo.com/10.237.241.21:32981]
14/09/22 11:27:33 INFO BlockFetcherIterator$BasicBlockFetcherIterator: Started 2 remote fetches in 22 ms
14/09/22 11:27:33 ERROR Executor: Exception in task 12.0 in stage 0.0 (TID 28)
java.io.IOException: The temporary job-output directory file:/svend/test-jobserver/dest6/_temporary doesn't exist!
	at org.apache.hadoop.mapred.FileOutputCommitter.getWorkPath(FileOutputCommitter.java:250)
	at org.apache.hadoop.mapred.FileOutputFormat.getTaskOutputPath(FileOutputFormat.java:240)
	at org.apache.hadoop.mapred.TextOutputFormat.getRecordWriter(TextOutputFormat.java:116)
	at org.apache.spark.SparkHadoopWriter.open(SparkHadoopWriter.scala:89)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$13.apply(PairRDDFunctions.scala:980)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$13.apply(PairRDDFunctions.scala:974)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:62)
	at org.apache.spark.scheduler.Task.run(Task.scala:54)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
14/09/22 11:27:33 ERROR Executor: Exception in tas
```

The data read in that folder is just a bunch of random csv lines, generated as follows (from spark-shell): 

```
class generator() {

    val letters = 'a' to 'z'        
    val rand = new scala.util.Random()

    def letter = letters(rand.nextInt(26))
    def word = 1 to rand.nextInt(15) map (_ => letter) mkString
    def amount = rand.nextGaussian * rand.nextInt(100)
    def part = rand.nextInt(10)

    def line = part :: word :: amount :: amount :: letter :: word :: Nil mkString(",")
    def lines = (1 to 500000).foldLeft(List[String]()) { case (acc, _) => line :: acc } 

}

sc.parallelize(1 to 16, 16).map (_ => new generator()).flatMap (_.lines).saveAsTextFile("/svend/test-jobserver/source")

```

**Comment by velvia** [comment]
Closing, feel free to reopen if this still happens with latest Spark and master.
