### ISSUE TITLE
Job Server does not automatically reconnect to spark master when master shuts down the TCP connection

### ISSUE THREAD

**Issue by SrivigneshM** [spark-jobserver/spark-jobserver#1203]
Spark: 2.2.4

SJS: v0.6.2

Deployment: Cluster

Issue: Due to some reason, if spark master forcefully disconnects the inbound connections (including SJS), SJS does not automatically reconnects after some time when spark master is stable. Due to this the jobs submitted after this issue, keeps failing.

Steps to reproduce:
This can be reproduced by killing the TCP connection inside SJS container using killcx or tcpkill tools.

Logs:

```
19/05/22 09:47:28 WARN TransportChannelHandler: [akka://JobServer/user/jobManager-52-84b8-3cb322c4603f] - Exception in connection from spark-master-1.system.svc.cluster.local./xx:xx:xx:xx:yyyy
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:221)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:899)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:275)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
19/05/22 09:47:28 WARN StandaloneAppClient$ClientEndpoint: [akka://JobServer/user/jobManager-52-84b8-3cb322c4603f] - Could not connect to spark-master-1.system.svc.cluster.local.:yyyy: java.io.IOException: Connection reset by peer
19/05/22 09:48:43 WARN TransportChannelHandler: [akka://JobServer/user/jobManager-52-84b8-3cb322c4603f] - Exception in connection from spark-master-2.system.svc.cluster.local./xx:xx:xx:xx:yyyy
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:221)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:899)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:275)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
19/05/22 09:48:43 WARN StandaloneAppClient$ClientEndpoint: [akka://JobServer/user/jobManager-52-84b8-3cb322c4603f] - Could not connect to spark-master-2.system.svc.cluster.local.:yyyy: java.io.IOException: Connection reset by peer
19/05/22 09:48:43 WARN StandaloneAppClient$ClientEndpoint: [akka://JobServer/user/jobManager-52-84b8-3cb322c4603f] - Connection to xx:xx:xx:xx:yyyy failed; waiting for master to reconnect...

```

**Comment by bsikander** [comment]
I don't understand the problem fully.
Jobserver uses Spark master only to launch the driver process. Once it does that, it is not used anymore. Where should jobserver reconnect?

**Comment by SrivigneshM** [comment]
> 
> 
> I don't understand the problem fully.
> Jobserver uses Spark master only to launch the driver process. Once it does that, it is not used anymore. Where should jobserver reconnect?

Basically the TCP connection between spark master and SJS is cut. Also the SparkContext in the master is dead and so SJS is unable to submit any further jobs in this case. (executor count is zero)

**Comment by bsikander** [comment]
This is a problem of Spark.
Jobserver doesnot manage the connection to spark master.Spark context/driver does.
Generally, in an HA setup of Spark, the context would automatically connect to the other spark master. If both are not available then it i think it fails.

You can also see it from the last log message. Class `StandaloneAppClient` is from Spark.

**Comment by Nibooor** [comment]
Closing because of inactivity
