### ISSUE TITLE
standalone  client error

### ISSUE THREAD

**Issue by whuawell** [spark-jobserver/spark-jobserver#1217]
**Used Spark version**
2.4.3
**Used Spark Job Server version**
(Released version, git branch or docker image version)
0.9.0-SNAPSHOT
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
client spark standalone
**Actual (wrong) behavior**
curl -d "input.string = a b c a b see hello world ssdsds " 'localhost:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample'.

   

**Steps to reproduce**

**Logs**

```
some log
```
scala.MatchError: (Actor[akka://JobServer/user/context-supervisor/346391bd-spark.jobserver.WordCountExample#1663204467],Actor[akka://JobServer/user/context-supervisor/global-result-actor#-1619000807]) (of class scala.Tuple2)\r\n\t
at spark.jobserver.WebApi.spark$jobserver$WebApi$$getJobManagerForContext(WebApi.scala:829)\r\n\t
at spark.jobserver.WebApi$$anonfun$jobRoutes$1$$anonfun$apply$73$$anonfun$apply$74.apply(WebApi.scala:739)\r\n\t
or as attached file (see below)

Unused parts of this template should be removed (including this line).
  
  For current solution, I add [ case Tuple2(_1: ActorRef, _2: ActorRef) => Some(_1) ] in  
 function getJobManagerForContext of webApi.scala .

  private def getJobManagerForContext(context: Option[String],
                                      contextConfig: Config,
                                      classPath: String): Option[ActorRef] = {
    import ContextSupervisor._
    val msg =
      if (context.isDefined) {
        GetContext(context.get)
      } else {
        StartAdHocContext(classPath, contextConfig)
      }
    val future = (supervisor ? msg)(contextTimeout.seconds)
    Await.result(future, contextTimeout.seconds) match {
      case (manager: ActorRef) => Some(manager)
      case NoSuchContext => None
      case ContextInitError(err) => throw new RuntimeException(err)
      case Tuple2(_1: ActorRef, _2: ActorRef) => Some(_1)
      case x => logger.warn("Unexpected message received by startContext: {}", x);None
    }
  }

**Comment by valan4ik** [comment]
Hi @whuawell ,

I think the issue is in the line: https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/main/scala/spark/jobserver/LocalContextSupervisorActor.scala#L154
Contexts hashmap contains tuples (contextRef, jobResultActorRef): https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/main/scala/spark/jobserver/LocalContextSupervisorActor.scala#L220

So instead of hacking WebApi, I think the fix is to fix  LocalContextSupervisorActor.scala to return ActorRef instead of a tuple.

Would you maybe like to check it and contribute to the project? :)
