### ISSUE TITLE
org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource

### ISSUE THREAD

**Issue by rvsharma-cmu** [spark-jobserver/spark-jobserver#1222]
**Used Spark version**
Spark 2.2.0

**Used Spark Job Server version**
(Released version, git branch or docker image version)
v0.9.0

**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
Cluster on YARN

**Actual (wrong) behavior**
When attempting to start jobserver start_server.sh getting flyway exception 

**Steps to reproduce**
./start_server.sh

**Logs**

```
19/06/27 12:28:33 INFO slf4j.Slf4jLogger: Slf4jLogger started
19/06/27 12:28:33 INFO remote.Remoting: Starting remoting
19/06/27 12:28:33 INFO remote.Remoting: Remoting started; listening on addresses :[akka.tcp://JobServer@localhost:36591]
19/06/27 12:28:33 INFO cluster.Cluster(akka://JobServer): Cluster Node [akka.tcp://JobServer@localhost:36591] - Starting up...
19/06/27 12:28:33 INFO cluster.Cluster(akka://JobServer): Cluster Node [akka.tcp://JobServer@localhost:36591] - Registered cluster JMX MBean [akka:type=Cluster]
19/06/27 12:28:33 INFO cluster.Cluster(akka://JobServer): Cluster Node [akka.tcp://JobServer@localhost:36591] - Started up successfully
19/06/27 12:28:33 INFO cluster.Cluster(akka://JobServer): Cluster Node [akka.tcp://JobServer@localhost:36591] - No seed-nodes configured, manual cluster join required
19/06/27 12:28:33 INFO jobserver.JobServer$: Embeded H2 server started with base dir /tmp/spark-jobserver/sqldao/data and URL tcp://172.18.40.62:9092
19/06/27 12:28:34 INFO io.SqlCommon: DBCP disabled
19/06/27 12:28:34 INFO io.JobSqlDAO: rootDir is /tmp/spark-jobserver/sqldao/data
19/06/27 12:28:34 INFO util.VersionPrinter: Flyway 3.2.1 by Boxfuse
19/06/27 12:28:34 ERROR jobserver.JobServer$: Unable to start Spark JobServer:
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at spark.jobserver.JobServer$.start(JobServer.scala:116)
        at spark.jobserver.JobServer$.main(JobServer.scala:313)
        at spark.jobserver.JobServer.main(JobServer.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:h2:tcp://127.0.0.1//tmp;AUTO_SERVER=TRUE) for user 'secret': IO Exception: "/tmp outside /tmp/spark-jobserver/sqldao/data" [90028-176]
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:302)
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:261)
        at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1385)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
        at spark.jobserver.io.SqlCommon.initFlyway(SqlCommon.scala:126)
        at spark.jobserver.io.JobSqlDAO.<init>(JobSqlDAO.scala:54)
        at spark.jobserver.io.JobSqlDAO.<init>(JobSqlDAO.scala:29)
        ... 16 more
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "/tmp outside /tmp/spark-jobserver/sqldao/data" [90028-176]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.h2.message.DbException.get(DbException.java:178)
        at org.h2.message.DbException.get(DbException.java:154)
        at org.h2.engine.ConnectionInfo.setBaseDir(ConnectionInfo.java:183)
        at org.h2.server.TcpServerThread.run(TcpServerThread.java:137)
        at java.lang.Thread.run(Thread.java:748)

        at org.h2.engine.SessionRemote.done(SessionRemote.java:606)
        at org.h2.engine.SessionRemote.initTransfer(SessionRemote.java:119)
        at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:430)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:311)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
        at org.h2.Driver.connect(Driver.java:74)
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:299)
        ... 23 more

```

full log file attached

[Uploading settings.sh.txt…]()
[Uploading start_server.log…]()

 (see below)

**Comment by rvsharma-cmu** [comment]
Figured it out and got the server to start 
setting the h2 jdbc url to the setting below helped and also this [issue](https://github.com/spark-jobserver/spark-jobserver/issues/980) and [document](https://github.com/spark-jobserver/spark-jobserver#configuring-spark-jobserver-h2-database-backend)

yarn.conf file: 

```
hqgtrhad02 bin $ more yarn.conf
# Template for a Spark Job Server configuration file
# When deployed these settings are loaded when job server starts
#
# Spark Cluster / Job Server configuration
spark {
  # spark.master will be passed to each job's JobContext
  # local[...], yarn, mesos://... or spark://...
  master = "yarn"

  # client or cluster deployment
  submit.deployMode = "cluster"

  # Default # of CPUs for jobs to use for Spark standalone cluster
  job-number-cpus = 4

  jobserver {
    port = 8090

    context-per-jvm = true
    startH2Server = true

    # Note: JobFileDAO is deprecated from v0.7.0 because of issues in
    # production and will be removed in future, now defaults to H2 file.
    jobdao = spark.jobserver.io.JobSqlDAO

    filedao {
      rootdir = /tmp/spark-jobserver/filedao/data
    }

    datadao {
      # storage directory for files that are uploaded to the server
      # via POST/data commands
      rootdir = /tmp/spark-jobserver/upload
    }

    sqldao {
      # Slick database driver, full classpath
      slick-driver = slick.driver.H2Driver

      # JDBC driver, full classpath
      jdbc-driver = org.h2.Driver

      # Directory where default H2 driver stores its data. Only needed for H2.
      rootdir = /tmp/spark-jobserver/sqldao/data

      # Full JDBC URL / init string, along with username and password.  Sorry, needs to match above.
      # Substitutions may be used to launch job-server, but leave it out here in the default or tests won't pass
      jdbc {
        url = "jdbc:h2:tcp://127.0.0.1/tmp;AUTO_SERVER=TRUE"
        user = "secret"
        password = "secret"
      }

      # DB connection pool settings
      dbcp {
        #enabled = false
        maxactive = 20
        maxidle = 10
        initialsize = 10
      }
    }
    # When using chunked transfer encoding with scala Stream job results, this is the size of each chunk
    result-chunk-size = 1m
  }

  # Predefined Spark contexts
  # contexts {
  #   my-low-latency-context {
  #     num-cpu-cores = 1           # Number of cores to allocate.  Required.
  #     memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, 1G, etc.
  #   }
  #   # define additional contexts here
  # }

  # Universal context configuration.  These settings can be overridden, see README.md
  context-settings {
    num-cpu-cores = 2           # Number of cores to allocate.  Required.
    memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, #1G, etc.

    # In case spark distribution should be accessed from HDFS (as opposed to being installed on every Mesos slave)
    # spark.executor.uri = "hdfs://namenode:8020/apps/spark/spark.tgz"

    # URIs of Jars to be loaded into the classpath for this context.
    # Uris is a string list, or a string separated by commas ','
    # dependent-jar-uris = ["file:///some/path/present/in/each/mesos/slave/somepackage.jar"]

    # Add settings you wish to pass directly to the sparkConf as-is such as Hadoop connection
    # settings that don't use the "spark." prefix
    passthrough {
      #es.nodes = "192.1.1.1"
    }
  }

  # This needs to match SPARK_HOME for cluster SparkContexts to be created successfully
  home = "/opt/mapr/spark/spark-2.2.0-bin-without-hadoop"
}
flyway.locations="db/h2/migration"

# Note that you can use this file to define settings not only for job server,
# but for your Spark jobs as well.  Spark job configuration merges with this configuration file as defaults.

akka {
  remote.netty.tcp {
    # This controls the maximum message size, including job results, that can be sent
    hostname = localhost
    maximum-frame-size = 100 MiB
  }
}
```
