### ISSUE TITLE
fiald to start job server 

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [spark-jobserver/spark-jobserver#123]
./server_start.sh 
./server_start.sh: line 52: kill: (7043) - No such process
[sbenkhaoua@sbenkhaoua-PC bin]$ log4j:WARN No such property [datePattern] in org.apache.log4j.RollingFileAppender.
Exception in thread "main" java.lang.NoSuchMethodError: com.typesafe.config.Config.getDuration(Ljava/lang/String;Ljava/util/concurrent/TimeUnit;)J
	at akka.util.Helpers$ConfigOps$.akka$util$Helpers$ConfigOps$$getDuration$extension(Helpers.scala:125)
	at akka.util.Helpers$ConfigOps$.getMillisDuration$extension(Helpers.scala:120)
	at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:171)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:504)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:141)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:118)
	at spark.jobserver.JobServer$$anonfun$main$1.apply(JobServer.scala:75)
	at spark.jobserver.JobServer$$anonfun$main$1.apply(JobServer.scala:75)
	at spark.jobserver.JobServer$.start(JobServer.scala:49)
	at spark.jobserver.JobServer$.main(JobServer.scala:75)
	at spark.jobserver.JobServer.main(JobServer.scala)

**Comment by velvia** [comment]
So, you deployed the server and are trying to start it?
It sounds like a dependencies issue, which version of Spark, did you modify
your spark-classpath etc?

On Sun, Apr 12, 2015 at 2:07 PM, Benkhaoua <notifications@github.com> wrote:

> ./server_start.sh
> ./server_start.sh: line 52: kill: (7043) - No such process
> [sbenkhaoua@sbenkhaoua-PC bin]$ log4j:WARN No such property [datePattern]
> in org.apache.log4j.RollingFileAppender.
> Exception in thread "main" java.lang.NoSuchMethodError:
> com.typesafe.config.Config.getDuration(Ljava/lang/String;Ljava/util/concurrent/TimeUnit;)J
> at
> akka.util.Helpers$ConfigOps$.akka$util$Helpers$ConfigOps$$getDuration$extension(Helpers.scala:125)
> at
> akka.util.Helpers$ConfigOps$.getMillisDuration$extension(Helpers.scala:120)
> at akka.actor.ActorSystem$Settings.(ActorSystem.scala:171)
> at akka.actor.ActorSystemImpl.(ActorSystem.scala:504)
> at akka.actor.ActorSystem$.apply(ActorSystem.scala:141)
> at akka.actor.ActorSystem$.apply(ActorSystem.scala:118)
> at spark.jobserver.JobServer$$anonfun$main$1.apply(JobServer.scala:75)
> at spark.jobserver.JobServer$$anonfun$main$1.apply(JobServer.scala:75)
> at spark.jobserver.JobServer$.start(JobServer.scala:49)
> at spark.jobserver.JobServer$.main(JobServer.scala:75)
> at spark.jobserver.JobServer.main(JobServer.scala)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/123>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by sidahmedbenkhaoua** [comment]
i resved this probleme but when i start job with @id is not excuted i found this responce from jobserver 
url localhost:8090/jobs/0971787d-b924-44bd-dda-f5f9195399c3 
{
 "status": "RUNNING"
 } 
b mean I haven't the result data I use Java 1.8 and Scala 2.10 adn job server 0.5.1 and spark 1.3  
the simple exemple for wordcountnumber

**Comment by aamend** [comment]
How did you solve this issue about typesafe Config?

**Comment by kkarthik21** [comment]
@sidahmedbenkhaoua : Can you please tell me how did you resolve this issue. I am facing this issue in Spark 1.6.1 and Job Server 0.6.2.
