### ISSUE TITLE
SJS 0.9 Not able to create the context.It is giving context tomeout

### ISSUE THREAD

**Issue by shikhar7** [spark-jobserver/spark-jobserver#1232]
**Used Spark version**
Spark: 2.4.0
**Used Spark Job Server version**
(Released version, git branch or docker image version)
Spark-Job-Server:0.9

**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
K8s Client

**Actual (wrong) behavior**

**Steps to reproduce**

**Logs**

[2019-07-22 14:33:31,883] INFO  spark-launcher [] [akka://JobServer/user/context-supervisor] - Initializing spark launcher
--
  | [2019-07-22 14:33:31,884] INFO  spark-launcher [] [akka://JobServer/user/context-supervisor] - Adding custom arguments to launcher
  | [2019-07-22 14:33:31,890] INFO  spark-launcher [] [akka://JobServer/user/context-supervisor] - Start launcher application
  | [2019-07-22 14:33:31,949] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Scheduling a time out message for forked JVM
  | [2019-07-22 14:34:01,960] WARN  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Context forked JVM failed to initialize for actor jobManager-5aaf77b7-3d02-4857-960c-806b59018630
  | [2019-07-22 14:34:01,966] INFO  spark.jobserver.WebApi$ [] [] - StatusCode: 500, ErrorMessage: CONTEXT INIT ERROR, StackTrace: spark.jobserver.util.ContextJVMInitializationTimeout: Context failed to connect back within initialization time
  | at spark.jobserver.AkkaClusterSupervisorActor$$anonfun$wrappedReceive$1.applyOrElse(AkkaClusterSupervisorActor.scala:328)
  | at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
  | at spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
  | at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
  | at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
  | at spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)
  | at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)
  | at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
  | at spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
  | at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
  | at spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
  | at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
  | at akka.actor.ActorCell.invoke(ActorCell.scala:495)
  | at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
  | at akka.dispatch.Mailbox.run(Mailbox.scala:224)
  | at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
  | at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  | at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  | at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  | at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```
some log
```

or as attached file (see below)
docker.conf

[dockerjobserver.txt](https://github.com/spark-jobserver/spark-jobserver/files/3418094/dockerjobserver.txt)

**Comment by bsikander** [comment]
The error is "Context failed to connect back within initialization
time" which means that the forked JVM fails to connect back with
spark-jobserver master.

Explanation:
Jobserver uses "spark launcher" to launch driver/contexts. In cluster
mode, a JVM is launched on the jobserver VM which submits the
driver/context process to spark. This jvm then shuts down. Then spark
launches the JVM in spark cluster on one of the worker nodes. As soon
as this JVM comes up, it has to connect back with jobserver master to
initialize.

Jobserver is complaining that the driver/context submitted to spark
cluster never connected back. If you see the exception again, it would
make more sense.


To figure out the problem, I would do 2 things
1- Change the spark master address to master = "spark://server1:6066".
2- On the jobserver VM, look into the spark launcher log. The log file
name would be spark-job-sever.out. Check in the file if the spark
launcher was successful in submitting the driver/context to spark
master or not. If not then fix the problem and everything should work.
If it was successful then see next step.
3- Inside the worker nodes, see where the driver/context JVM was
launched by Spark. Look into the logs and see why the driver failed to
connect back. If you don't get the problem then you can write me back.

**Comment by shikhar7** [comment]
Hi bSikander we are using spark on k8s in jobserver so because of that....we are setting master="k8s://<kubectl cluster-info> in the jobserver.conf file that i have attached before..(I have removed the master field for security reason in above attached file).

So in our case the cluster is transient hence the job-server will first create pods and then will create a context....for this we have added extra parameters in the server_start.sh since there is no manager_start.sh in 0.9 so we can not add that in manager_start.sh for context creation.With context-per-jvm=false it is working fine but it is giving error with only when we are setting context-per-jvm to true.

[server_start.txt](https://github.com/spark-jobserver/spark-jobserver/files/3420677/server_start.txt)
[jobserver_logs.txt](https://github.com/spark-jobserver/spark-jobserver/files/3420680/jobserver_logs.txt)


I am attaching the server_start.sh and the jobserver logs with the post.

**Comment by bsikander** [comment]
jobserver_logs are the spark launcher logs (which is a replcement to manager_start), this file looks okay. It seems that the context was submitted to k8s spark cluster.

The next thing to check would be the spark UI for the launched driver and see its logs. You should find the problem there.

**Comment by shikhar7** [comment]
Actually that is the only issue driver pods are not being created when using context-per-jvm=true because it is not able to create context.

**Comment by shikhar7** [comment]
There is no static cluster the cluster is created automatically when request comes.But in our case it is getting stucked in context creation only.

**Comment by bsikander** [comment]
umm well, spark launcher is an abstraction on the underlying resource manager.
Jobserver just sets the correct parameters and rest should be handled by SparkLauncher/spark itself.

This is strange. What happens if you execute a normal spark-submit against your k8s spark cluster?

**Comment by shikhar7** [comment]
Then it works for me if i do that.

**Comment by shikhar7** [comment]
Thats why i have modified in server_start.sh and it is working fine but with 0.9 since there is no manager_start.sh so i don't know how to override that and but extra configuration needed in that.

**Comment by bsikander** [comment]
You want to deploy your context in client mode or cluster?

**Comment by shikhar7** [comment]
In any mode is fine currently we are using client mode but it is also not working in cluster mode also.In client mode context-per-jvm=false is working fine.

**Comment by bsikander** [comment]
Ok, I see. You have added the k8s specific spark configurations to jobserver master process.

To add these configurations to driver process, you can pass them while creating context.

```
curl -X POST localhost:8090/contexts/myContext?launcher.spark.executor.extraJavaOptions=$LOGGING_OPTS&launcher.spark.driver.host=$MY_POD_IP ....
```

Basically, any configuration can be passed to driver by appending the Spark configuration with `launcher.*`

**Comment by shikhar7** [comment]
Oh Thanks i will try with that but just one thing if it works then can i add this in jobserver.conf under the passthrough and will it work?

**Comment by bsikander** [comment]
Give this a try, if this works then in the configuration, we also have a [launcher section](https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/main/resources/application.conf#L215). You can append the configurations directly there and it will be added to all the drivers.

**Comment by shikhar7** [comment]
Ok Thankyou so much....I will get back to you

**Comment by bsikander** [comment]
Great. If this works out for you, then please if possible, contribute back in the form of documentation. A lot of people are looking to run jobserver against k8s and basic steps would help the community :)

**Comment by shikhar7** [comment]
Yup Sure!!....

**Comment by shikhar7** [comment]
Hi it is not working some how it is not taking image as a argument
<img width="1532" alt="Screenshot 2019-07-23 at 1 22 00 PM" src="https://user-images.githubusercontent.com/18174818/61693783-ccb4d180-ad4d-11e9-9bad-044c86da1369.png">

**Comment by bsikander** [comment]
umm, this seems to be typesafe specific problem in combination with curl. I guess we have to escape the characters in the url or maybe encode the special characters.

Maybe try putting the image property in config first.

**Comment by shikhar7** [comment]
Hi I have done that still it is not working.....it is giving same timeout error...i have also set spark.master (i.e. spark-submit --master) still no pod is showing up.I don't know why it now able to create any pod

**Comment by bsikander** [comment]
Can you post you new logs again?

**Comment by bsikander** [comment]
Also, client mode is a bit special in k8s. Have you followed the spark docu about client mode?
https://spark.apache.org/docs/latest/running-on-kubernetes.html#client-mode

**Comment by shikhar7** [comment]
Yup...I have attached both the pod and jobserver logs
[pod_jobserver_logs.txt](https://github.com/spark-jobserver/spark-jobserver/files/3420965/pod_jobserver_logs.txt)
[jobserver_logs.txt](https://github.com/spark-jobserver/spark-jobserver/files/3420966/jobserver_logs.txt)

**Comment by shikhar7** [comment]
Yes i have followed that i told you na that with only one field that is context-per-jvm=true is not working otherwise if i set it it false then it works fine.

**Comment by bsikander** [comment]
In pod_jobserver_logs.txt, the last request failed because you didn't have "spark" in side the property 'launcher.master'. 

Next thing you should check if all the properties that you want for contexts are printed inside `jobserver_logs.txt` file. If not, then pass missing ones. If all configs are there then we move to the next step. Once launcher launches the driver process on the host VM, there should also be some logs for that JVM. Generally, they are stored in the logs directory (has format jobserver-<context_name>-<random string>. In this directory, there should be 2 logs. One with the logs from spark launcher then other one with the driver logs. Do you have the driver log or it is totally missing?

**Comment by shikhar7** [comment]
Yes i have passed all the required arguments and driver logs are completely missing.

**Comment by bsikander** [comment]
Ok, can you try once with cluster mode instead of client?

**Comment by bsikander** [comment]
are you building your own jobserver with Spark 2.4.0?

**Comment by shikhar7** [comment]
Yes I have built my own image with 0.9 jar that I compiled with SBT docker command on master branch

**Comment by bsikander** [comment]
I was asking because client mode was introduced in 2.4.0. The default jobserver is building against 2.3.2.

If cluster mode works then we know that building of jobserver is the problem. If not, then we look in other direciton.

**Comment by shikhar7** [comment]
Yes with cluster mode driver pod is coming up.So I am going to change some configuration for the cluster mode then will come back to you again.Thanks for help

**Comment by bsikander** [comment]
ok cool. Then the problem was that jobserver was built against 2.3.2.

**Comment by shikhar7** [comment]
But SparkJobserver Supports version above 2.3.2 right.And if we go the path of cluster mode then we have to make alot many changes is there any way with which i can get the jobserver jar build againt 2.4.0?

**Comment by shikhar7** [comment]
Because if we go through the path of the cluster mode then we have to make the driver as the replica of the job server and then it will call with client mode only the executors so that will again create an issue.So if it is possible to get the jobserver jar build against 2.4.0 then it will be great.

**Comment by bsikander** [comment]
You can follow this PR and do similar steps to make sjs compatable with 2.4.0
https://github.com/spark-jobserver/spark-jobserver/pull/1145/files

**Comment by bsikander** [comment]
>> Because if we go through the path of the cluster mode then we have to make the driver as the replica of the job server and then it will call with client mode only the executors so that will again create an issue.So if it is possible to get the jobserver jar build against 2.4.0 then it will be great.

The driver runs almost the same code in both cluster/client mode. There is no difference. The only difference is the location of the JVM. In cluster mode, driver resides in the Spark cluster and is managed by Spark and in client mode, it resides on the JVM where spark-submit/SparkLauncher is executed.

To move to cluster mode, you don't need too much changes. This document should cover most of the changes that you want to do
https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/cluster.md

**Comment by bsikander** [comment]
Since your driver in cluster mode will be launched by k8s resource manager, communication between executos and drivers shouldn't be an issue.

**Comment by shikhar7** [comment]
ok Thanks bsikander...But same issue we are facing in cluster mode if we use the current job server only....we are able to create the drivers  but it is getting completed and the executors and not being created.

**Comment by bsikander** [comment]
Then you should check the logs for drivers, there must be some exception at the startup of driver which is causing the driver going down without executor creation.

**Comment by shikhar7** [comment]
With spark-jobserver with 2.4.0 image we are facing the same issue.

**Comment by shikhar7** [comment]
what you are doing for creating context in 0.9 is it internally calling spark-submit only or there is something different?

**Comment by bsikander** [comment]
You did not post the driver logs. There should be driver logs with an exception that should give us clues.

**Comment by shikhar7** [comment]
<img width="1649" alt="Screenshot 2019-07-23 at 4 29 52 PM" src="https://user-images.githubusercontent.com/18174818/61716366-980c3e80-ad7c-11e9-91c1-fa5b6b98b7c1.png">
This is complete Driver’s  Log of pod

**Comment by bsikander** [comment]
I meant after running in cluster mode.

**Comment by shikhar7** [comment]
Yup this driver’s  logs only after running in cluster mode.

**Comment by bsikander** [comment]
Well, the screen shot says that you are deploying in `client` mode.

**Comment by shikhar7** [comment]
Yup internally it uses client mode only cluster mode also...It is by k8s

**Comment by shikhar7** [comment]
![image](https://user-images.githubusercontent.com/18174818/61785031-7cf70880-ae28-11e9-8875-adaeaa83a66a.png)

I think there is some issue with job manager because above logs are of driver when i run job through job server but when we run directly spark submit then it runs fine and the below logs come
![image](https://user-images.githubusercontent.com/18174818/61785169-be87b380-ae28-11e9-80e2-8f3d50abbb53.png)

**Comment by shikhar7** [comment]
Can we have meeting online if possible...so we can discuss more about this.Lets skype whenever you are free.

**Comment by bsikander** [comment]
The thing that I find strange is that you don't have any logs in the driver. It is very strange.

Maybe try 1 more thing, copy the spark-submit command that jobserver is generating to launch the driver and execute it directly without jobserver and analyze the logs.

**Comment by shikhar7** [comment]
Surely I will try that....but it worked when i used 0.8 jobserver along with manager_start.sh.After making some modification in manager_start.sh it worked.Thanks i will test the ablive suggested for 0.9 also.

**Comment by valan4ik** [comment]
Closing due to inactivity, please reopen the ticket if you have any further questions.
