### ISSUE TITLE
SJS 0.8/0.9  yarn client context shut down after creating successfully.

### ISSUE THREAD

**Issue by tosen1990** [spark-jobserver/spark-jobserver#1242]
**Used Spark version**
Spark:2.2.0 (in Ambari)
**Used Spark Job Server version**
(Released version, git branch or docker image version)
Spark-Job-Server:0.9 / 0.8
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
 yarn client
**Actual (wrong) behavior**

**Steps to reproduce**
1: curl -d "" "192.168.101.23:8090/contexts/test-contextt?num-cpu-cores=8&memory-per-node=20g"

{
  "status": "SUCCESS",
  "result": "Context initialized"
}
2: Serveral seconds later,the context shut down.
**Logs**
[2019-08-31 18:44:50,448] INFO  spark.jobserver.WebApi [] [] - [GET] http://192.168.101.23:8090/contexts/test-contextt
[2019-08-31 18:44:50,519] INFO  spark.jobserver.WebApi [] [] - Response: 200 OK HttpEntity(application/json; charset=UTF-8,{ "name": "test-contextt", "startTime": "2019-08-31T18:43:59.643+08:00", "state": "RUNNING", "url": "http://10.0.10.23:35083", "applicationId": "application_1567245589068_0012", "endTime": "Empty", "id": "c196d9b7-f845-4e44-b3d8-1e0c42aad645" })(...) to request: http://192.168.101.23:8090/contexts/test-contextt
Aug 31, 2019 6:44:51 PM org.apache.spark.launcher.ChildProcAppHandle setState
WARNING: Backend requested transition from final state FAILED to FINISHED.
[2019-08-31 18:44:52,253] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Actor terminated: jobManager-c196d9b7-f845-4e44-b3d8-1e0c42aad645
[2019-08-31 18:44:52,275] WARN  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Terminated received for context (test-contextt) which is already in final state KILLED
[2019-08-31 18:44:52,277] INFO  .Cluster(akka://JobServer) [] [akka.cluster.Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:38675] - Marking node [akka.tcp://JobServer@127.0.0.1:41608] as [Down]
[2019-08-31 18:44:53,078] INFO  r$RemoteDeadLetterActorRef [] [akka://JobServer/deadLetters] - Message [akka.cluster.ClusterHeartbeatSender$Heartbeat] from Actor[akka://JobServer/system/cluster/core/daemon/heartbeatSender#-1331711339] to Actor[akka://JobServer/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2019-08-31 18:44:53,086] INFO  r$RemoteDeadLetterActorRef [] [akka://JobServer/deadLetters] - Message [akka.cluster.GossipEnvelope] from Actor[akka://JobServer/system/cluster/core/daemon#711112832] to Actor[akka://JobServer/deadLetters] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2019-08-31 18:44:54,076] INFO  r$RemoteDeadLetterActorRef [] [akka://JobServer/deadLetters] - Message [akka.cluster.ClusterHeartbeatSender$Heartbeat] from Actor[akka://JobServer/system/cluster/core/daemon/heartbeatSender#-1331711339] to Actor[akka://JobServer/deadLetters] was not delivered. [3] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2019-08-31 18:44:54,086] INFO  r$RemoteDeadLetterActorRef [] [akka://JobServer/deadLetters] - Message [akka.cluster.GossipEnvelope] from Actor[akka://JobServer/system/cluster/core/daemon#711112832] to Actor[akka://JobServer/deadLetters] was not delivered. [4] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2019-08-31 18:44:55,077] INFO  r$RemoteDeadLetterActorRef [] [akka://JobServer/deadLetters] - Message [akka.cluster.ClusterHeartbeatSender$Heartbeat] from Actor[akka://JobServer/system/cluster/core/daemon/heartbeatSender#-1331711339] to Actor[akka://JobServer/deadLetters] was not delivered. [5] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2019-08-31 18:44:55,087] INFO  r$RemoteDeadLetterActorRef [] [akka://JobServer/deadLetters] - Message [akka.cluster.GossipEnvelope] from Actor[akka://JobServer/system/cluster/core/daemon#711112832] to Actor[akka://JobServer/deadLetters] was not delivered. [6] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2019-08-31 18:44:56,076] INFO  r$RemoteDeadLetterActorRef [] [akka://JobServer/deadLetters] - Message [akka.cluster.ClusterHeartbeatSender$Heartbeat] from Actor[akka://JobServer/system/cluster/core/daemon/heartbeatSender#-1331711339] to Actor[akka://JobServer/deadLetters] was not delivered. [7] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2019-08-31 18:44:56,086] INFO  r$RemoteDeadLetterActorRef [] [akka://JobServer/deadLetters] - Message [akka.cluster.GossipEnvelope] from Actor[akka://JobServer/system/cluster/core/daemon#711112832] to Actor[akka://JobServer/deadLetters] was not delivered. [8] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

```
The time of brief logs above may be not as same as the log below,because I test many times and saved the early files. But I'm sure it's in the same situation.
```

or as attached file (see below)

[log from yarn.txt](https://github.com/spark-jobserver/spark-jobserver/files/3562359/log.from.yarn.txt)

[docker-conf.log](https://github.com/spark-jobserver/spark-jobserver/files/3562365/docker-conf.log)

[Dockerfile.txt](https://github.com/spark-jobserver/spark-jobserver/files/3562370/Dockerfile.txt)

[spark-job-server.log](https://github.com/spark-jobserver/spark-jobserver/files/3562360/spark-job-server.log)

Unused parts of this template should be removed (including this line).

**Comment by valan4ik** [comment]
Hi @tosen1990,

As I wrote in Gitter, I don't see the problem on Jobserver side. Your context is successfully created, but has an exception later and is getting killed. You need to check the exception from context (Spark driver) `java.nio.channels.ClosedChannelException`:
```
[2019-08-31 15:34:25,298] ERROR rg.apache.spark.util.Utils [] [akka://JobServer/user/jobManager-5fe4d1df-6fe1-4538-a341-9c038e37a6b1] - Uncaught exception in thread Yarn application state monitor
org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:205)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.scheduler.cluster.CoarseGrainedSchedulerBackend.requestTotalExecutors(CoarseGrainedSchedulerBackend.scala:551)
	at org.apache.spark.scheduler.cluster.YarnSchedulerBackend.stop(YarnSchedulerBackend.scala:93)
	at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.stop(YarnClientSchedulerBackend.scala:151)
	at org.apache.spark.scheduler.TaskSchedulerImpl.stop(TaskSchedulerImpl.scala:517)
	at org.apache.spark.scheduler.DAGScheduler.stop(DAGScheduler.scala:1652)
	at org.apache.spark.SparkContext$$anonfun$stop$8.apply$mcV$sp(SparkContext.scala:1921)
	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1317)
	at org.apache.spark.SparkContext.stop(SparkContext.scala:1920)
	at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend$MonitorThread.run(YarnClientSchedulerBackend.scala:108)
Caused by: java.io.IOException: Failed to send RPC 9026581505546884293 to /10.0.10.20:59854: java.nio.channels.ClosedChannelException
	at org.apache.spark.network.client.TransportClient.lambda$sendRpc$2(TransportClient.java:237)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:34)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:431)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:399)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
```

I guess you need to check your Spark/Docker settings and maybe some [suggestions on StackOverflo](https://stackoverflow.com/questions/37733004/spark-job-failure-due-to-closedchannelexception-dfsoutputstream-checkclosed) will help. 

Please comment if you find an answer :)

**Comment by valan4ik** [comment]
Closing due to inactivity, please reopen the ticket if you have any further questions.
