### ISSUE TITLE
Cannot run program "python3": error=2, No such file or directory

### ISSUE THREAD

**Issue by yuwenxing** [spark-jobserver/spark-jobserver#1265]
**Used Spark version**
2.3.0
**Used Spark Job Server version**
(Released version, git branch or docker image version)
master
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
default
**Logs**
[2019-11-08 16:56:18,858] INFO  spark.jobserver.WebApi [] [] - [POST] http://localhost:8090/jobs?appName=my_py_job&classPath=example_jobs.word_count.WordCountSparkSessionJob&context=py-context
[2019-11-08 16:56:19,236] INFO  .jobserver.JobManagerActor [] [] - Creating new JobId for current job
[2019-11-08 16:56:19,236] INFO  .jobserver.JobManagerActor [] [] - Starting Spark job 1aeee1ce-a553-4deb-9065-bd5bd2dcd6f3 [example_jobs.word_count.WordCountSparkSessionJob]...
[2019-11-08 16:56:19,237] INFO  .jobserver.JobManagerActor [] [] - Starting job future thread
[2019-11-08 16:56:19,237] INFO  jobserver.python.PythonJob [] [] - Running example_jobs.word_count.WordCountSparkSessionJob from /tmp/spark-jobserver/sqldao/data/my_py_job-20191107_165454_587.egg
[2019-11-08 16:56:19,237] INFO  k.jobserver.JobStatusActor [] [akka://JobServer/user/context-supervisor/py-context/status-actor] - Job 1aeee1ce-a553-4deb-9065-bd5bd2dcd6f3 started
[2019-11-08 16:56:19,243] INFO  jobserver.python.PythonJob [] [] - Using Python path of /tmp/spark-jobserver/sqldao/data/my_py_job-20191107_165454_587.egg:/opt/python3/bin/python3:/opt/spark-jobserver/spark_jobserver_python-0.9.1_SNAPSHOT-py3.7.egg
[2019-11-08 16:56:19,390] INFO  spark.jobserver.WebApi [] [] - Response: 202 Accepted HttpEntity(application/json; charset=UTF-8,{ "duration": "Job not done yet", "classPath": "example_jobs.word_count.WordCountSparkSessionJob", "startTime": "2019-11-08T16:56:19.236+08:00", "context": "py-context", "status": "STARTED", "jobId": "1aeee1ce-a553-4deb-9065-bd5bd2dcd6f3", "contextId": "" })(...) to request: http://localhost:8090/jobs?appName=my_py_job&classPath=example_jobs.word_count.WordCountSparkSessionJob&context=py-context
[2019-11-08 16:56:20,396] INFO  .apache.spark.SparkContext [] [] - Starting job: countByValue at /tmp/spark-jobserver/sqldao/data/my_py_job-20191107_165454_587.egg/example_jobs/word_count/__init__.py:41
[2019-11-08 16:56:20,401] INFO  storage.memory.MemoryStore [] [akka://JobServer/user/context-supervisor/py-context] - Block broadcast_1 stored as values in memory (estimated size 4.8 KB, free 414.4 MB)
[2019-11-08 16:56:20,410] INFO  storage.memory.MemoryStore [] [akka://JobServer/user/context-supervisor/py-context] - Block broadcast_1_piece0 stored as bytes in memory (estimated size 3.3 KB, free 414.4 MB)
[2019-11-08 16:56:20,410] INFO  k.storage.BlockManagerInfo [] [akka://JobServer/user/context-supervisor/py-context] - Added broadcast_1_piece0 in memory on master:19007 (size: 3.3 KB, free: 414.4 MB)
[2019-11-08 16:56:20,411] INFO  .apache.spark.SparkContext [] [akka://JobServer/user/context-supervisor/py-context] - Created broadcast 1 from broadcast at DAGScheduler.scala:1039
[2019-11-08 16:56:20,412] INFO  uler.cluster.YarnScheduler [] [akka://JobServer/user/context-supervisor/py-context] - Adding task set 1.0 with 2 tasks
[2019-11-08 16:56:20,476] INFO  k.storage.BlockManagerInfo [] [akka://JobServer/user/context-supervisor/py-context] - Added broadcast_1_piece0 in memory on node1:56506 (size: 3.3 KB, free: 93.3 MB)
[2019-11-08 16:56:20,504] WARN  k.scheduler.TaskSetManager [] [akka://JobServer/user/context-supervisor/py-context] - Lost task 1.0 in stage 1.0 (TID 9, node1, executor 2): java.io.IOException: Cannot run program "python3": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.apache.spark.api.python.PythonWorkerFactory.startDaemon(PythonWorkerFactory.scala:168)
        at org.apache.spark.api.python.PythonWorkerFactory.createThroughDaemon(PythonWorkerFactory.scala:94)
        at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:70)
        at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:117)
        at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:86)
        at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:109)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 14 more

**Comment by thoHeinze** [comment]
The error just tells that the executable "python3" is not inside the default path on your jobserver VM. Please adjust the $PATH and it should work.
