### ISSUE TITLE
Support for Spark 3

### ISSUE THREAD

**Issue by jeynesrya** [spark-jobserver/spark-jobserver#1269]
Is there a plan to add support for Apache Spark 3, with the preview being release in November?

**Comment by valan4ik** [comment]
As far as I know, it is not planned for the near future, especially because Spark 3 it is in preview/beta so far.
Usually, the version is upgraded several months after a stable release is done.

**Comment by bsikander** [comment]
@jeynesrya you are always welcome to contribute to jobserver :). Once the stable Spark 3 is out, we can help you adapt jobserver for Spark 3. There are many previous version upgrade commits and we just need to follow them and test.

**Comment by dberardo-com** [comment]
is there a way we can upgrade to spark 3 within a dockerfile ? what are the steps to follow? it seems that the docker repo is pretty unmaintained: https://hub.docker.com/r/sparkjobserver/spark-jobserver/tags?page=1&ordering=last_updated

**Comment by dberardo-com** [comment]
i have create a pull request:

https://github.com/spark-jobserver/spark-jobserver/pull/1353

this is the output of the tests after i run the docker run <image> command for the compiled Dockerfile.test:


```bash
Attaching to spark_job-server_1
job-server_1    | Running sbt test and coverage report
job-server_1    | [info] Loading settings for project app-build from plugins.sbt ...
job-server_1    | [info] Loading project definition from /usr/src/app/project
job-server_1    | [info] Updating ProjectRef(uri("file:/usr/src/app/project/"), "app-build")...
job-server_1    | [info] Done updating.
job-server_1    | [warn] There may be incompatibilities among your library dependencies.
job-server_1    | [warn] Run 'evicted' to see detailed eviction warnings
job-server_1    | [info] Compiling 6 Scala sources to /usr/src/app/project/target/scala-2.12/sbt-1.0/classes ...
job-server_1    | [info] Done compiling.
job-server_1    | [info] Loading settings for project root from build.sbt,version.sbt ...
job-server_1    | [info] Set current project to root (in build file:/usr/src/app/)
job-server_1    | [success] Total time: 0 s, completed Mar 11, 2021 3:53:20 PM
job-server_1    | [info] Defining ThisBuild / coverageEnabled
job-server_1    | [info] The new value will be used by Compile / compile / scalacOptions, akka-app / Compile / compile / scalacOptions and 11 others.
job-server_1    | [info]        Run `last` for details.
job-server_1    | [info] Reapplying settings...
job-server_1    | [info] Set current project to root (in build file:/usr/src/app/)
job-server_1    | 21/03/11 15:53:28 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
job-server_1    | Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
job-server_1    | Setting default log level to "WARN".
job-server_1    | To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
/tmp/spark-3.0.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/context.py:499: DeprecationWarning: HiveContext is deprecated in Spark 2.0.0. Please use SparkSession.builder.enableHiveSupport().getOrCreate() instead.
job-server_1    | /tmp/spark-3.0.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/context.py:77: DeprecationWarning: Deprecated in 3.0.0. Use SparkSession.builder.getOrCreate() instead.
job-server_1    | /tmp/spark-3.0.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/dataframe.py:141: DeprecationWarning: Deprecated in 2.0, use createOrReplaceTempView instead.
job-server_1    | /usr/lib/python3.7/socket.py:660: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 35394), raddr=('127.0.0.1', 44565)>
job-server_1    |   self._sock = None
job-server_1    | ResourceWarning: Enable tracemalloc to get the object allocation traceback
job-server_1    | ./usr/lib/python3.7/socket.py:660: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 41382), raddr=('127.0.0.1', 40597)>
job-server_1    |   self._sock = None
job-server_1    | ResourceWarning: Enable tracemalloc to get the object allocation traceback
job-server_1    | .E...
job-server_1    | ======================================================================
job-server_1    | ERROR: test_run_sql_job (__main__.TestSJSApi)
job-server_1    | ----------------------------------------------------------------------
job-server_1    | Traceback (most recent call last):
job-server_1    |   File "test/apitests.py", line 118, in test_run_sql_job
job-server_1    |     sqlContext = SQLContext(self.sc)
job-server_1    |   File "/tmp/spark-3.0.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/context.py", line 83, in __init__
job-server_1    |     sparkSession = SparkSession.builder.getOrCreate()
job-server_1    |   File "/tmp/spark-3.0.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/session.py", line 189, in getOrCreate
job-server_1    |     session = SparkSession(sc)
job-server_1    |   File "/tmp/spark-3.0.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in __init__
job-server_1    |     jsparkSession = self._jvm.SparkSession(self._jsc.sc())
job-server_1    | AttributeError: 'NoneType' object has no attribute 'sc'
job-server_1    |
job-server_1    | ----------------------------------------------------------------------
job-server_1    | Ran 6 tests in 30.744s
job-server_1    |
job-server_1    | FAILED (errors=1)
job-server_1    | [error] java.lang.RuntimeException: Running python tests received non-zero exit code 1
job-server_1    | [error]       at scala.sys.package$.error(package.scala:26)
job-server_1    | [error]       at PythonTasks$.testPythonTask(PythonTasks.scala:17)
job-server_1    | [error]       at $7113ede0339ace12ecba$.$anonfun$jobServerPythonSettings$4(build.sbt:125)
job-server_1    | [error]       at $7113ede0339ace12ecba$.$anonfun$jobServerPythonSettings$4$adapted(build.sbt:125)
job-server_1    | [error]       at scala.Function1.$anonfun$compose$1(Function1.scala:44)
job-server_1    | [error]       at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
job-server_1    | [error]       at sbt.std.Transform$$anon$4.work(System.scala:67)
job-server_1    | [error]       at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
job-server_1    | [error]       at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
job-server_1    | [error]       at sbt.Execute.work(Execute.scala:278)
job-server_1    | [error]       at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
job-server_1    | [error]       at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
job-server_1    | [error]       at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
job-server_1    | [error]       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
job-server_1    | [error]       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
job-server_1    | [error]       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
job-server_1    | [error]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
job-server_1    | [error]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
job-server_1    | [error]       at java.lang.Thread.run(Thread.java:748)
job-server_1    | [error] (job-server-python / testPython) Running python tests received non-zero exit code 1
job-server_1    | [error] Total time: 33 s, completed Mar 11, 2021 3:53:57 PM
spark_job-server_1 exited with code 1
```

**Comment by dberardo-com** [comment]
@bsikander i can see here: https://github.com/spark-jobserver/spark-jobserver/pull/1283/commits/66f61509aafbdeed179aa19f766c1891215df9ac#diff-516a045c5344d8b0ba4e9c136186415916237dd438d509e334278ec0b3012b38R131
that the tests fail because of an hadoop / hive version mismatch. however i cannot find out which version should be installed. any hint here?
