### ISSUE TITLE
java.lang.SecurityException: class "org.codehaus.janino.ClassBodyEvaluator"'s signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by Nikhith-kudumula** [spark-jobserver/spark-jobserver#1333]
**Used Spark version - 2.4.0

**Used Spark Job Server version** - 0.10.1

**git branch - master
 
**Deployed mode** (client)

Hi Team,

I am getting the below error, but if execute without job server then the job is getting succeeded.

java.lang.SecurityException: class "org.codehaus.janino.ClassBodyEvaluator"'s signer information does not match signer information of other classes in the same package
        at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$.org$apache$spark$sql$catalyst$expressions$codegen$CodeGenerator$$doCompile(CodeGenerator.scala:1251)
        at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$$anon$1.load(CodeGenerator.scala:1383)
        at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$$anon$1.load(CodeGenerator.scala:1380)
        at org.spark_project.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at org.spark_project.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at org.spark_project.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
        at org.spark_project.guava.cache.LocalCache$Segment.get(LocalCache.java:2045)
        at org.spark_project.guava.cache.LocalCache.get(LocalCache.java:3953)
        at org.spark_project.guava.cache.LocalCache.getOrLoad(LocalCache.java:3976)
        at org.spark_project.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4960)
        at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$.compile(CodeGenerator.scala:1238)
        at org.apache.spark.sql.catalyst.expressions.codegen.GenerateSafeProjection$.create(GenerateSafeProjection.scala:205)
        at org.apache.spark.sql.catalyst.expressions.codegen.GenerateSafeProjection$.create

**Comment by waynecookie** [comment]
So how to solve this

**Comment by muyu66** [comment]
So how to solve this

**Comment by waynecookie** [comment]
您好，已收到您的邮件
