### ISSUE TITLE
SJS 0.10.0 getting  CONTEXT INIT ERROR, StackTrace: java.lang.Exception: Unexpected error occurred while reading file.

### ISSUE THREAD

**Issue by jainarpitspark** [spark-jobserver/spark-jobserver#1337]
Spark version 2.4.4
Spark job version tag 0.10.0

**Deployed mode**
Spark Standalone

When trying to create a new context using curl -X POST  http://localhost:8090/contexts/traitsContext getting CONTEXT INIT ERROR.

**Logs**

```
2020-12-28 08:52:26,608 INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
2020-12-28 08:52:26,727 INFO  akka.remote.Remoting - Starting remoting
2020-12-28 08:52:26,960 INFO  akka.remote.Remoting - Remoting started; listening on addresses :[akka.tcp://JobServer@127.0.0.1:40445]
2020-12-28 08:52:26,978 INFO  akka.cluster.Cluster(akka://JobServer) - Cluster Node [akka.tcp://JobServer@127.0.0.1:40445] - Starting up...
2020-12-28 08:52:27,165 INFO  akka.cluster.Cluster(akka://JobServer) - Cluster Node [akka.tcp://JobServer@127.0.0.1:40445] - Registered cluster JMX MBean [akka:type=Cluster]
2020-12-28 08:52:27,165 INFO  akka.cluster.Cluster(akka://JobServer) - Cluster Node [akka.tcp://JobServer@127.0.0.1:40445] - Started up successfully
2020-12-28 08:52:27,217 INFO  akka.cluster.Cluster(akka://JobServer) - Cluster Node [akka.tcp://JobServer@127.0.0.1:40445] - No seed-nodes configured, manual cluster join required
2020-12-28 08:52:27,218 WARN  akka.cluster.AutoDown - Don't use auto-down feature of Akka Cluster in production. See 'Auto-downing (DO NOT USE)' section of Akka Cluster documentation.
2020-12-28 08:52:28,613 INFO  spark.jobserver.io.SqlCommon - DBCP disabled
2020-12-28 08:52:28,624 INFO  spark.jobserver.io.JobSqlDAO - File caching rootDir is /tmp/spark-jobserver/sqldao/data
2020-12-28 08:52:28,668 INFO  org.flywaydb.core.internal.util.VersionPrinter - Flyway 3.2.1 by Boxfuse
2020-12-28 08:52:28,855 INFO  org.flywaydb.core.internal.dbsupport.DbSupportFactory - Database: jdbc:h2:tcp://localhost:9092/spark_jobserver (H2 1.3)
2020-12-28 08:52:28,993 INFO  org.flywaydb.core.internal.command.DbValidate - Validated 10 migrations (execution time 00:00.087s)
2020-12-28 08:52:29,015 INFO  org.flywaydb.core.internal.command.DbMigrate - Current version of schema "PUBLIC": 0.7.9
2020-12-28 08:52:29,016 INFO  org.flywaydb.core.internal.command.DbMigrate - Schema "PUBLIC" is up to date. No migration necessary.
2020-12-28 08:52:29,333 INFO  spark.jobserver.io.JobDAOActor - Starting actor spark.jobserver.io.JobDAOActor
2020-12-28 08:52:29,336 INFO  spark.jobserver.DataManagerActor - Starting actor spark.jobserver.DataManagerActor
2020-12-28 08:52:29,336 INFO  spark.jobserver.JobServer$ - Startup dao cleanup is disabled.
2020-12-28 08:52:29,336 INFO  spark.jobserver.BinaryManager - Starting actor spark.jobserver.BinaryManager
2020-12-28 08:52:29,337 INFO  spark.jobserver.io.zookeeper.AutoPurgeActor$ - Zookeeper autopurge feature is not configured.
2020-12-28 08:52:29,725 INFO  spark.jobserver.JobServer$ - Joining newly created cluster at akka.tcp://JobServer@127.0.0.1:40445
2020-12-28 08:52:29,738 INFO  akka.cluster.Cluster(akka://JobServer) - Cluster Node [akka.tcp://JobServer@127.0.0.1:40445] - Node [akka.tcp://JobServer@127.0.0.1:40445] is JOINING, roles [supervisor]
2020-12-28 08:52:29,746 INFO  akka.cluster.Cluster(akka://JobServer) - Cluster Node [akka.tcp://JobServer@127.0.0.1:40445] - Leader is moving node [akka.tcp://JobServer@127.0.0.1:40445] to [Up]
2020-12-28 08:52:29,770 INFO  spark.jobserver.JobInfoActor - Starting actor spark.jobserver.JobInfoActor
2020-12-28 08:52:29,805 INFO  spark.jobserver.AkkaClusterSupervisorActor - Starting actor spark.jobserver.AkkaClusterSupervisorActor
2020-12-28 08:52:29,806 INFO  akka.cluster.singleton.ClusterSingletonManager - Singleton manager starting singleton actor [akka://JobServer/user/singleton/context-supervisor]
2020-12-28 08:52:29,806 INFO  akka.cluster.singleton.ClusterSingletonManager - ClusterSingletonManager state change [Start -> Oldest]
2020-12-28 08:52:29,809 INFO  spark.jobserver.AkkaClusterSupervisorActor - Subscribing to MemberUp event
2020-12-28 08:52:29,809 INFO  spark.jobserver.JobResultActor - Starting actor spark.jobserver.JobResultActor
2020-12-28 08:52:29,889 INFO  spark.jobserver.AkkaClusterSupervisorActor - Regaining watch on 0 existing contexts.
2020-12-28 08:52:29,890 INFO  spark.jobserver.AkkaClusterSupervisorActor - AkkaClusterSupervisor initialized on akka.tcp://JobServer@127.0.0.1:40445
2020-12-28 08:52:29,898 INFO  spark.jobserver.AkkaClusterSupervisorActor - Current Akka cluster has members akka.tcp://JobServer@127.0.0.1:40445
2020-12-28 08:52:29,898 INFO  spark.jobserver.AkkaClusterSupervisorActor - Current Akka leader has address akka.tcp://JobServer@127.0.0.1:40445
2020-12-28 08:52:29,898 INFO  spark.jobserver.AkkaClusterSupervisorActor - Role/Address entry: supervisor/akka.tcp://JobServer@127.0.0.1:40445
2020-12-28 08:52:29,961 INFO  spark.jobserver.WebApi - No authentication.
2020-12-28 08:52:30,125 INFO  spark.jobserver.WebApi - Starting browser web service...
2020-12-28 08:52:30,618 INFO  spray.can.server.HttpListener - Bound to /0.0.0.0:8090
2020-12-28 08:52:30,787 INFO  akka.cluster.singleton.ClusterSingletonProxy - Singleton identified at [akka://JobServer/user/singleton/context-supervisor]
2020-12-28 08:52:38,995 INFO  spark.jobserver.WebApi - [POST] http://localhost:8090/contexts/traitsContext
2020-12-28 08:52:39,151 INFO  spark.jobserver.AkkaClusterSupervisorActor - Starting context with actor name jobManager-55a52221-e340-4074-8c18-db77bc1bc505
2020-12-28 08:52:39,154 INFO  spark.jobserver.AkkaClusterSupervisorActor - Created working directory /var/log/jobserver-traitsContext4486647004978727010 for context traitsContext
2020-12-28 08:52:39,166 ERROR spark.jobserver.util.HadoopFSFacade - Can not create a Path from an empty string
2020-12-28 08:52:39,176 INFO  spark.jobserver.WebApi$ - StatusCode: 500, ErrorMessage: CONTEXT INIT ERROR, StackTrace: java.lang.Exception: Unexpected error occurred while reading file. Check logs
        at spark.jobserver.AkkaClusterSupervisorActor.spark$jobserver$AkkaClusterSupervisorActor$$startContext(AkkaClusterSupervisorActor.scala:534)
        at spark.jobserver.AkkaClusterSupervisorActor$$anonfun$wrappedReceive$1.applyOrElse(AkkaClusterSupervisorActor.scala:277)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
        at spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)
        at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
        at spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2020-12-28 08:52:39,218 INFO  spark.jobserver.WebApi - Response: 500 Internal Server Error HttpEntity(application/json; charset=UTF-8,{ "status": "CONTEXT INIT ERROR", "result": { "message": "Unexpected error occurred while reading file. Check logs", "errorClass": "java.lang.Exception", "stack": "java.lang.Exception: Unexpected error occurred while reading file. Check logs\n\tat spark.jobserver.AkkaClusterSupervisorActor.spark$jobserver$AkkaClusterSupervisorActor$$startContext(AkkaClust(...) to request: http://localhost:8090/contexts/traitsContext
2020-12-28 08:57:16,153 INFO  spark.jobserver.WebApi - [GET] http://localhost:8090/

```
Any idea what configuration I might be missing? Looks like HDFS Path is going as empty. How do I make it take the correct path?

**Comment by valan4ik** [comment]
Hi @jainarpitspark ,

Could you please share your configuration files? You should have a pair of `.conf` and `.sh` files. 

Please check https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/config/local.sh.template#L46 setting and that it is not empty.
`MANAGER_CONF_FILE` and `MANAGER_JAR_FILE` are the paths to Jobserver jar and configuration for the driver. When driver is created, it starts Jobserver in itself. If you are experimenting with Jobserver locally then you can just put the path to the config file and jar on you computer.

**Comment by jainarpitspark** [comment]
@valan4ik  Thanks! I had forgotten to export the MANAGER_JAR_FILE  property. After doing that its working!
