### ISSUE TITLE
Flaky unit tests

### ISSUE THREAD

**Issue by vglagoleva** [spark-jobserver/spark-jobserver#1363]
Travis CI tests are very flaky lately and need some additional check/debugging.

Some of the tests, which are failing:

```
[info] - should start job, return JobStarted (async) and invoke callback *** FAILED *** (161 milliseconds)
[info]   0 was not equal to 1 (JobManagerActorSpec.scala:487)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
```

```
[info] - should be able to stop a running context *** FAILED *** (2 seconds, 993 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected ContextStopped, found NoSuchContext
```

```
[info] - should not kill itself if Initialize message is received *** FAILED *** (2 seconds, 22 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected class spark.jobserver.JobManagerActor$Initialized, found class spark.jobserver.CommonMessages$JobValidationFailed (JobValidationFailed(c99e4e69-8533-41b2-a3bd-8b4fd261f9d1,2021-05-06T17:29:48.564Z,java.lang.Throwable: One(SingleProblem(No input.string param))))
```

``` 
[info] - should restart if running job was found with valid config *** FAILED *** (13 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected SaveBinaryResult(Success(())), found Initialized(ctx,Actor[akka://test/user/$Eb/$a#2133199883])
```

**Comment by valan4ik** [comment]
```
[info] - should return valid managerActorRef if context exists *** FAILED *** (1 second, 923 milliseconds)
[info]   false was not true (AkkaClusterSupervisorActorSpec.scala:345)
```

**Comment by Ennosigaeon** [comment]
@valan4ik You were right, there is indeed a race condition in the callback job test. Should be stable now.

**Comment by Ennosigaeon** [comment]
@valan4ik There still seem to be some problems in `JobManagerActorSpec`. In Spark 3, only a single context can be running per JVM, so the error message looks a bit different, but the underlying problem should be the same. See [Travis CI](https://travis-ci.com/github/spark-jobserver/spark-jobserver/builds/227261146#L2246). I will add some similar logic to `JobMangerActorSpec`'s `before` and `after` methods in the Spark3 PR.
