### ISSUE TITLE
Not able to create context

### ISSUE THREAD

**Issue by venkatkrishna110** [spark-jobserver/spark-jobserver#1376]
**Used Spark version -- 2.4**

**Used Spark Job Server version -- 2.11.0.10**
(Released version, git branch or docker image version)

**Deployed mode -- yarn-client**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)

**Actual (wrong) behavior**
![image](https://user-images.githubusercontent.com/53960090/123899264-6b65f600-d999-11eb-8ce2-faa56469bc17.png)
Exception in thread "main" java.lang.NoClassDefFoundError: com/typesafe/config/ConfigValue
        at spark.jobserver.JobManager.main(JobManager.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:847)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:922)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:931)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigValue
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 13 more

**Steps to reproduce**
Set these parameters in application.conf: 
spark.master = "yarn"
spark.jobserver.context-per-jvm = true

**Please let me know if any other details needed.**

**Comment by venkatkrishna110** [comment]
Hi @velvia ,

Can you please help us on this.. I think this is only due to some configuration issue only which is blocking us in prod deployments. 
Thanks in advance :)

**Comment by vglagoleva** [comment]
@venkatkrishna110 Is this issue now resolved? Was it a problem with Scala versions mismatch?
I saw [your comment on another issue](https://github.com/spark-jobserver/spark-jobserver/issues/1371#issuecomment-871842067), that things work for you now.

**Comment by venkatkrishna110** [comment]
Hi @vglagoleva , 
I got this issue as I was sending the dependent job uri's in wrong syntax in application.conf file. it should be 
dependent-jar-uris = jar1","jar2","jar3
This resolved my issue.
