### ISSUE TITLE
Job Server going Out of Memory

### ISSUE THREAD

**Issue by saif-17** [spark-jobserver/spark-jobserver#1386]
**Used Spark version**
Spark 3.0.2

**Used Spark Job Server version**
Spark Job Server 0.11

**Deployed mode**
Spark Standalone

**Actual (wrong) behavior**
1) I've enabled Spark Thrift JDBC on the spark code is deployed on the Job Server. I use the Thrift JDBC endpoint to query the data from the Spark temp view. I tried pulling 1 million records (260 MB), the job server context went down due to being out of memory.

2) Query a big data set (260MB) from a spark temp view, the job server context went down due to being out of memory.

A hprof file is generated when the context goes down. Analyzing the file show scala List is taking most of the memory (65%).

4 Spark Executor per context (each executor 1Core, 2GB memory)

**Steps to reproduce**
Mentioned above

**Logs**
Below entries are made when context went out of memory

```
[2021-09-07 10:53:36,602] INFO  spark.jobserver.WebApi$ [] [] - StatusCode: 500 Internal Server Error, ErrorMessage: Request timed out. Try using the /jobs/<jobID>, /jobs APIs to get status/results
[2021-09-07 10:53:36,623] INFO  spark.jobserver.WebApi$ [] [] - StatusCode: 500, ErrorMessage: ERROR, StackTrace: akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka.tcp://JobServer@127.0.0.1:36500/user/jobManager-c36dcbe5-e2e1-42e1-9778-a2dcec6a7293#-1913373602]] after [180000 ms]. Message of type [spark.jobserver.JobManagerActor$StartJob]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.
        at akka.pattern.PromiseActorRef$.$anonfun$defaultOnTimeout$1(AskSupport.scala:667)
        at akka.pattern.PromiseActorRef$.$anonfun$apply$1(AskSupport.scala:688)
        at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:202)
        at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
        at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:113)
        at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
        at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:334)
        at akka.actor.LightArrayRevolverScheduler$$anon$3.executeBucket$1(LightArrayRevolverScheduler.scala:285)
        at akka.actor.LightArrayRevolverScheduler$$anon$3.nextTick(LightArrayRevolverScheduler.scala:289)
        at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:241)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by vglagoleva** [comment]
Hi @saif-17 ,

Spark 3.0.2 is not supported by Jobserver yet. There is an unreviewed PR with this feature https://github.com/spark-jobserver/spark-jobserver/pull/1359, which you may try to use. But so far the project supports only Spark 2.4.

Best,
Valentina

**Comment by saif-17** [comment]
Hi @vglagoleva 

Thanks for your reply, everything else is working fine with the Job Server with Spark 3. Only in the case of a little bigger dataset, it's causing out of memory. Any idea why that could be happening?

**Comment by vglagoleva** [comment]
Hi @saif-17,
No, I guess then you just need to tune your Spark job and the memory settings for your context.

**Comment by yaelda** [comment]
@vglagoleva - can you please update when is it planned to support Spark 3?

@saif-17  - did you manage to use it with spark3?

**Comment by saif-17** [comment]
@yaelda 
Yes, I'm able to use it with Spark 3.0.3 with scala 12.10.0. it's quite stable.

**Comment by saif-17** [comment]
@yaelda 
I'm using Spark-Jobserver version 0.11. I did not change anything to support Spark 3.
