### ISSUE TITLE
Kryo serializer error 

### ISSUE THREAD

**Issue by emmekappa** [spark-jobserver/spark-jobserver#192]
I'm using Kryo serializer and my jobserver config is like 

    spark.serializer = org.apache.spark.serializer.KryoSerializer
    spark.kryo.classesToRegister = "org.apache.spark.mllib.recommendation.Rating,com.roar.yprediction.engine.YPredictionRating"
    spark.kryoserializer.buffer = "8mb"

I'm also using a custom ContextFactory but when I create the context I got this error 

```
2015-07-13T17:05:22.420274277Z Caused by: org.apache.spark.SparkException: Failed to register classes with Kryo
2015-07-13T17:05:22.420274277Z 	at org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:101)
2015-07-13T17:05:22.420274277Z 	at org.apache.spark.serializer.KryoSerializerInstance.<init>(KryoSerializer.scala:153)
2015-07-13T17:05:22.420274277Z 	at org.apache.spark.serializer.KryoSerializer.newInstance(KryoSerializer.scala:115)
2015-07-13T17:05:22.420274277Z 	at org.apache.spark.broadcast.TorrentBroadcast$.unBlockifyObject(TorrentBroadcast.scala:214)
2015-07-13T17:05:22.420274277Z 	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1.apply(TorrentBroadcast.scala:177)
2015-07-13T17:05:22.420274277Z 	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1153)
2015-07-13T17:05:22.420274277Z 	... 11 more
2015-07-13T17:05:22.420274277Z Caused by: java.lang.ClassNotFoundException: com.roar.yprediction.engine.YPredictionRating
2015-07-13T17:05:22.420274277Z 	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
2015-07-13T17:05:22.420274277Z 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
2015-07-13T17:05:22.420274277Z 	at java.security.AccessController.doPrivileged(Native Method)
2015-07-13T17:05:22.420274277Z 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
2015-07-13T17:05:22.420274277Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
2015-07-13T17:05:22.420274277Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
2015-07-13T17:05:22.420274277Z 	at java.lang.Class.forName0(Native Method)
2015-07-13T17:05:22.420274277Z 	at java.lang.Class.forName(Class.java:278)
2015-07-13T17:05:22.420274277Z 	at org.apache.spark.serializer.KryoSerializer$$anonfun$newKryo$2.apply(KryoSerializer.scala:94)
2015-07-13T17:05:22.420274277Z 	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
2015-07-13T17:05:22.420274277Z 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
2015-07-13T17:05:22.420274277Z 	at org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:94)
2015-07-13T17:05:22.420274277Z 	... 16 more
```

It seems there is a problem with the classpath even though I run the jobserver specifing my jar

```
CLASSPATH="/yprediction-engine.jar:$appdir:$appdir/spark-job-server.jar:$($SPARK_HOME/bin/compute-classpath.sh)"
CONFFILE=sparkcluster.conf
JAVA_OPTS="-Xmx20g"
exec java -cp $CLASSPATH $GC_OPTS $JAVA_OPTS $LOGGING_OPTS $CONFIG_OVERRIDES $MAIN $CONFFILE 2>&1 &
```

yprediction-engine is the jar file containing YPredictionRating class.

**Comment by velvia** [comment]
Hi Michele,

Have you tried the latest SJS that uses server_start.sh with
spark_submit?   You can combine that with the --jars option of
spark-submit, which should help with the classpath issues.

-Evan

On Mon, Jul 13, 2015 at 10:21 AM, Michele Cantelli <notifications@github.com
> wrote:

> I'm using Kryo serializer and my jobserver config is like
>
> spark.serializer = org.apache.spark.serializer.KryoSerializer
> spark.kryo.classesToRegister = "org.apache.spark.mllib.recommendation.Rating,com.roar.yprediction.engine.YPredictionRating"
> spark.kryoserializer.buffer = "8mb"
>
> I'm also using a custom ContextFactory but when I create the context I got
> this error
>
> 2015-07-13T17:05:22.420274277Z Caused by: org.apache.spark.SparkException: Failed to register classes with Kryo
> 2015-07-13T17:05:22.420274277Z  at org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:101)
> 2015-07-13T17:05:22.420274277Z  at org.apache.spark.serializer.KryoSerializerInstance.<init>(KryoSerializer.scala:153)
> 2015-07-13T17:05:22.420274277Z  at org.apache.spark.serializer.KryoSerializer.newInstance(KryoSerializer.scala:115)
> 2015-07-13T17:05:22.420274277Z  at org.apache.spark.broadcast.TorrentBroadcast$.unBlockifyObject(TorrentBroadcast.scala:214)
> 2015-07-13T17:05:22.420274277Z  at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1.apply(TorrentBroadcast.scala:177)
> 2015-07-13T17:05:22.420274277Z  at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1153)
> 2015-07-13T17:05:22.420274277Z  ... 11 more
> 2015-07-13T17:05:22.420274277Z Caused by: java.lang.ClassNotFoundException: com.roar.yprediction.engine.YPredictionRating
> 2015-07-13T17:05:22.420274277Z  at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
> 2015-07-13T17:05:22.420274277Z  at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
> 2015-07-13T17:05:22.420274277Z  at java.security.AccessController.doPrivileged(Native Method)
> 2015-07-13T17:05:22.420274277Z  at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
> 2015-07-13T17:05:22.420274277Z  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
> 2015-07-13T17:05:22.420274277Z  at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
> 2015-07-13T17:05:22.420274277Z  at java.lang.Class.forName0(Native Method)
> 2015-07-13T17:05:22.420274277Z  at java.lang.Class.forName(Class.java:278)
> 2015-07-13T17:05:22.420274277Z  at org.apache.spark.serializer.KryoSerializer$$anonfun$newKryo$2.apply(KryoSerializer.scala:94)
> 2015-07-13T17:05:22.420274277Z  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
> 2015-07-13T17:05:22.420274277Z  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
> 2015-07-13T17:05:22.420274277Z  at org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:94)
> 2015-07-13T17:05:22.420274277Z  ... 16 more
>
> It seems there is a problem with the classpath even though I run the
> jobserver specifing my jar
>
> CLASSPATH="/yprediction-engine.jar:$appdir:$appdir/spark-job-server.jar:$($SPARK_HOME/bin/compute-classpath.sh)"
> CONFFILE=sparkcluster.conf
> JAVA_OPTS="-Xmx20g"
> exec java -cp $CLASSPATH $GC_OPTS $JAVA_OPTS $LOGGING_OPTS $CONFIG_OVERRIDES $MAIN $CONFFILE 2>&1 &
>
> yprediction-engine is the jar file containing YPredictionRating class.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/192>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by emmekappa** [comment]
I find out that the issue was not related to class path but I forgot the to extend my class with Serializable.
