### ISSUE TITLE
Job Info serialization: encoded string too long

### ISSUE THREAD

**Issue by TimMaltGermany** [spark-jobserver/spark-jobserver#198]
Hi,
(this is for Version 0.5.0)
we are using the job server to serialize relatively large files to Spark (for example, 32k rows). We are sending these records via the Job Config to the JobServer. This may not the best way to do this, but that's how we do it right now. It all works fine with one exception - the job info cannot be serialized to disk. The Job-Server throws the following exception when trying to serialize the job configuration to disk: 

java.io.UTFDataFormatException: encoded string too long: 6653559 bytes
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:364)
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
        at spark.jobserver.io.JobFileDAO.writeJobConfig(JobFileDAO.scala:183)
        at spark.jobserver.io.JobFileDAO.saveJobConfig(JobFileDAO.scala:175)

This exception can be ignored. The problem is that the JobServer fails to start properly when restarted:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at spark.jobserver.JobServer$.start(JobServer.scala:50)
        at spark.jobserver.JobServer$.main(JobServer.scala:63)
        at spark.jobserver.JobServer.main(JobServer.scala)
Caused by: com.typesafe.config.ConfigException$Parse: String: 1: Key '"5d25d9f7-a4e4-41cb-b739-9021c6fe4f51"' may not be followed by token: end of file (if you intended '"5d25d9f7-a4e4-41cb-b739-9021c6fe4f51"' to be part of a value, instead of a key, try adding double quotes around the whole value)
        at com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:435)
        at com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:431)
        at com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:786)
        at com.typesafe.config.impl.Parser$ParseContext.parse(Parser.java:993)
        at com.typesafe.config.impl.Parser.parse(Parser.java:34)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:222)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:210)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170)
        at com.typesafe.config.impl.Parseable.parse(Parseable.java:227)
        at com.typesafe.config.ConfigFactory.parseString(ConfigFactory.java:823)
        at com.typesafe.config.ConfigFactory.parseString(ConfigFactory.java:827)
        at spark.jobserver.io.JobFileDAO.readJobConfig(JobFileDAO.scala:188)
        at spark.jobserver.io.JobFileDAO.init(JobFileDAO.scala:79)
        at spark.jobserver.io.JobFileDAO.<init>(JobFileDAO.scala:31)
        ... 7 more

The work around is to delete the config files.

Thanks,
Tim

**Comment by velvia** [comment]
I would recommend changing to use a JobSQLDao in which case a database can be configured to support larger config sizes.  And yes serializing a large config would be a disadvantage.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by zeitos** [comment]
Should I close this one?

**Comment by velvia** [comment]
@TimMaltGermany feel free to reopen, but I'm going to close.  Instead, we should file a separate ticket to get rid of the JobFileDao.  With the default of H2, we don't need the FileDao anymore, and should solve this issue.

**Comment by arunzz** [comment]
Can you pls suggest a solution for this error with filedao itself
[akka://JobServer/user/job-info] - encoded string too long

**Comment by velvia** [comment]
I suggest you use H2 DAo instead - we are deprecating the FileDAO and it will soon be removed. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by arunzz** [comment]
Thanks Velvia, Can you pls let know the steps to use H2 DAO

**Comment by velvia** [comment]
If you look in master you will see the config file now defaults to H2.  Just copy the DAo config to your config file. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead
