### ISSUE TITLE
Using external Dependencies with jobserver

### ISSUE THREAD

**Issue by hackercompany** [spark-jobserver/spark-jobserver#326]
I am using the DataBricks spark-avro to read an avro file.
The jar is loaded to the server but when executed 

gives 

```
Exception in thread "pool-14-thread-1" java.lang.NoClassDefFoundError: com/databricks/spark/avro/package$
job-server-extras[ERROR] 	at spark.jobserver.SqlLoaderJob2$.runJob(SparkAddAvro.scala:21)
job-server-extras[ERROR] 	at spark.jobserver.SqlLoaderJob2$.runJob(SparkAddAvro.scala:10)
job-server-extras[ERROR] 	at spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:254)
job-server-extras[ERROR] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
job-server-extras[ERROR] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
job-server-extras[ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
job-server-extras[ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
job-server-extras[ERROR] 	at java.lang.Thread.run(Thread.java:745)
job-server-extras[ERROR] Caused by: java.lang.ClassNotFoundException: com.databricks.spark.avro.package$
job-server-extras[ERROR] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
job-server-extras[ERROR] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
job-server-extras[ERROR] 	at java.security.AccessController.doPrivileged(Native Method)
job-server-extras[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
job-server-extras[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
job-server-extras[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
job-server-extras[ERROR] 	... 8 more
```

my sbt looks something like 

```
name := "sparkJob"

version := "1.0"

scalaVersion := "2.10.4"

resolvers += "Job Server Bintray" at "https://dl.bintray.com/spark-jobserver/maven"

libraryDependencies += "spark.jobserver" %% "job-server-api" % "0.6.1" % "provided"
libraryDependencies += "spark.jobserver" %% "job-server-extras" % "0.6.1" % "provided"
libraryDependencies += "org.apache.spark" % "spark-core_2.10" % "1.5.1"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "1.5.1"
libraryDependencies += "com.databricks" %% "spark-avro" % "2.0.1"

assemblyMergeStrategy in assembly := {
  case PathList("META-INF", xs @ _*) => MergeStrategy.discard
  case x => MergeStrategy.first
}
```

**Comment by endriju** [comment]
You can pass --packages com.databricks:spark-avro:2.0.1 to server_start.sh. The same parameter works also if you run spark-jobserver docker image.

**Comment by noorul** [comment]
@hackercompany Is this solved? Shall we close this?

**Comment by velvia** [comment]
@hackercompany closing, feel free to reopen if this is still an issue.  There are also various docs and most folks have experience in Gitter / google groups etc.
