### ISSUE TITLE
Deploy to a local staging dir failed

### ISSUE THREAD

**Issue by dharm82465** [spark-jobserver/spark-jobserver#34]
Hi,
   After modifying config/local.sh and config/local.conf files to use local setting. The deployment of spark-jobserver fails with the following error. Note that I am using

1) Mac OS Maverick
2) Java 1.7.0
3) Spark 1.2.0

 

$ ./server_start.sh 

./server_start.sh: line 52: kill: (9343) - No such process
Spark assembly has been built with Hive, including Datanucleus jars on classpath
glide:job-server pdharma$ log4j:WARN No such property [datePattern] in org.apache.log4j.RollingFileAppender.
Exception in thread "main" java.lang.NoSuchMethodError: com.typesafe.config.Config.getDuration(Ljava/lang/String;Ljava/util/concurrent/TimeUnit;)J
	at akka.util.Helpers$ConfigOps$.akka$util$Helpers$ConfigOps$$getDuration$extension(Helpers.scala:125)
	at akka.util.Helpers$ConfigOps$.getMillisDuration$extension(Helpers.scala:120)
	at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:171)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:504)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:141)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:118)
	at spark.jobserver.JobServer$$anonfun$main$1.apply(JobServer.scala:68)
	at spark.jobserver.JobServer$$anonfun$main$1.apply(JobServer.scala:68)
	at spark.jobserver.JobServer$.start(JobServer.scala:47)
	at spark.jobserver.JobServer$.main(JobServer.scala:68)
	at spark.jobserver.JobServer.main(JobServer.scala)

**Comment by dharm82465** [comment]
It turns out the error is gone after switching Spark to version 1.1.1.
