### ISSUE TITLE
Estimate for feature/context-per-jvm to be merged into main branch

### ISSUE THREAD

**Issue by annakepler** [spark-jobserver/spark-jobserver#354]
@velvia Is there an estimate on when feature/context-per-jvm will be merged into the main branch?

**Comment by velvia** [comment]
It has been merged recently. Try it out!  :)

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by annakepler** [comment]
context-per-jvm = true

When trying to create context I am running into issue
`Exception in thread "main" com.typesafe.config.ConfigException$NotResolved: need to Config#resolve() each config before using it, see the API docs for Config#resolve()
	at com.typesafe.config.impl.SimpleConfig.checkValid(SimpleConfig.java:844)
	at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:161)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:505)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
	at spark.jobserver.JobManager$.spark$jobserver$JobManager$$makeManagerSystem$1(JobManager.scala:69)
	at spark.jobserver.JobManager$$anonfun$main$1.apply(JobManager.scala:71)
	at spark.jobserver.JobManager$$anonfun$main$1.apply(JobManager.scala:71)
	at spark.jobserver.JobManager$.start(JobManager.scala:51)
	at spark.jobserver.JobManager$.main(JobManager.scala:71)
	at spark.jobserver.JobManager.main(JobManager.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)`

I believe the issue is job-server/src/spark.jobserver/JobManager.scala. `resolve()` must be called

`- ConfigFactory.parseFile(configFile).withFallback(defaultConfig)
+ ConfigFactory.parseFile(configFile).withFallback(defaultConfig).resolve()`

**Comment by velvia** [comment]
Hmm… good find @annakepler.  Should be easily fixable.

**Comment by velvia** [comment]
@annakepler just fixed this on master.  :)

**Comment by annakepler** [comment]
@velvia Thank you!
