### ISSUE TITLE
java.lang.ClassNotFoundException: spark.jobserver.JobServer

### ISSUE THREAD

**Issue by peterklipfel** [spark-jobserver/spark-jobserver#355]
I am submitting the jobserver to marathon with the following json

```
{
  "id": "spark.jobserver",
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "velvia/spark-jobserver:0.6.1.mesos-0.25.0.spark-1.5.2",
      "network": "BRIDGE",
      "portMappings": [{
        "containerPort": 8090,
        "hostPort": 0,
        "protocol": "tcp"
      }],
      "privileged": false
    }
  },
  "args": [
    "--packages", "com.datastax.spark:spark-cassandra-connector_2.10:1.4.1,com.github.sstone:amqp-client_2.10:1.5, com.rabbitmq:amqp-client:3.2.1, com.typesafe.akka:akka-actor_2.10:2.3.11, com.github.nscala-time:nscala-time_2.10:1.6.0, com.fasterxml.jackson.core:jackson-core:2.2.2, com.fasterxml.jackson.core:jackson-databind:2.2.2, com.fasterxml.jackson.module:jackson-module-scala_2.10:2.2.2, org.scalaj:scalaj-http_2.10:1.1.4,org.elasticsearch:elasticsearch-spark_2.10:2.1.0.Beta3,spark.jobserver:job-server-api:0.6.1,spark.jobserver:job-server-extras:0.6.1"
  ],
  "env": {
    "SPARK_MASTER": "mesos.ourcluster.internal:5050"
  },
  "cpus": 0.5,
  "mem": 100,
  "instances": 1
}
```

Here's the output that I get from `docker log`

```
com.datastax.spark#spark-cassandra-connector_2.10 added as a dependency
com.github.sstone#amqp-client_2.10 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
        confs: [default]
        found com.datastax.spark#spark-cassandra-connector_2.10;1.4.1 in central
        found org.apache.cassandra#cassandra-clientutil;2.1.9 in central
        found com.datastax.cassandra#cassandra-driver-core;2.1.7.1 in central
        found io.netty#netty-handler;4.0.27.Final in central
        found io.netty#netty-buffer;4.0.27.Final in central
        found io.netty#netty-common;4.0.27.Final in central
        found io.netty#netty-transport;4.0.27.Final in central
        found io.netty#netty-codec;4.0.27.Final in central
        found com.codahale.metrics#metrics-core;3.0.2 in central
        found org.slf4j#slf4j-api;1.7.5 in central
        found org.apache.commons#commons-lang3;3.3.2 in central
        found com.google.guava#guava;14.0.1 in central
        found org.joda#joda-convert;1.2 in central
        found joda-time#joda-time;2.3 in central
        found com.twitter#jsr166e;1.1.0 in central
        found org.scala-lang#scala-reflect;2.10.5 in central
        found com.github.sstone#amqp-client_2.10;1.5 in central
        found com.rabbitmq#amqp-client;3.5.2 in central
downloading https://repo1.maven.org/maven2/com/datastax/spark/spark-cassandra-connector_2.10/1.4.1/spark-cassandra-connector_2.10-1.4.1.jar ...
        [SUCCESSFUL ] com.datastax.spark#spark-cassandra-connector_2.10;1.4.1!spark-cassandra-connector_2.10.jar (1493ms)
downloading https://repo1.maven.org/maven2/com/github/sstone/amqp-client_2.10/1.5/amqp-client_2.10-1.5.jar ...
        [SUCCESSFUL ] com.github.sstone#amqp-client_2.10;1.5!amqp-client_2.10.jar (334ms)
downloading https://repo1.maven.org/maven2/org/apache/cassandra/cassandra-clientutil/2.1.9/cassandra-clientutil-2.1.9.jar ...
        [SUCCESSFUL ] org.apache.cassandra#cassandra-clientutil;2.1.9!cassandra-clientutil.jar (134ms)
downloading https://repo1.maven.org/maven2/com/datastax/cassandra/cassandra-driver-core/2.1.7.1/cassandra-driver-core-2.1.7.1.jar ...
        [SUCCESSFUL ] com.datastax.cassandra#cassandra-driver-core;2.1.7.1!cassandra-driver-core.jar(bundle) (535ms)
downloading https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar ...
        [SUCCESSFUL ] org.apache.commons#commons-lang3;3.3.2!commons-lang3.jar (320ms)
downloading https://repo1.maven.org/maven2/com/google/guava/guava/14.0.1/guava-14.0.1.jar ...
        [SUCCESSFUL ] com.google.guava#guava;14.0.1!guava.jar(bundle) (1384ms)
downloading https://repo1.maven.org/maven2/org/joda/joda-convert/1.2/joda-convert-1.2.jar ...
        [SUCCESSFUL ] org.joda#joda-convert;1.2!joda-convert.jar (198ms)
downloading https://repo1.maven.org/maven2/joda-time/joda-time/2.3/joda-time-2.3.jar ...
        [SUCCESSFUL ] joda-time#joda-time;2.3!joda-time.jar (344ms)
downloading https://repo1.maven.org/maven2/com/twitter/jsr166e/1.1.0/jsr166e-1.1.0.jar ...
        [SUCCESSFUL ] com.twitter#jsr166e;1.1.0!jsr166e.jar (129ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.5/scala-reflect-2.10.5.jar ...
        [SUCCESSFUL ] org.scala-lang#scala-reflect;2.10.5!scala-reflect.jar (1827ms)
downloading https://repo1.maven.org/maven2/io/netty/netty-handler/4.0.27.Final/netty-handler-4.0.27.Final.jar ...
        [SUCCESSFUL ] io.netty#netty-handler;4.0.27.Final!netty-handler.jar (225ms)
downloading https://repo1.maven.org/maven2/com/codahale/metrics/metrics-core/3.0.2/metrics-core-3.0.2.jar ...
        [SUCCESSFUL ] com.codahale.metrics#metrics-core;3.0.2!metrics-core.jar(bundle) (141ms)
downloading https://repo1.maven.org/maven2/io/netty/netty-buffer/4.0.27.Final/netty-buffer-4.0.27.Final.jar ...
        [SUCCESSFUL ] io.netty#netty-buffer;4.0.27.Final!netty-buffer.jar (163ms)
downloading https://repo1.maven.org/maven2/io/netty/netty-transport/4.0.27.Final/netty-transport-4.0.27.Final.jar ...
        [SUCCESSFUL ] io.netty#netty-transport;4.0.27.Final!netty-transport.jar (224ms)
downloading https://repo1.maven.org/maven2/io/netty/netty-codec/4.0.27.Final/netty-codec-4.0.27.Final.jar ...
        [SUCCESSFUL ] io.netty#netty-codec;4.0.27.Final!netty-codec.jar (150ms)
downloading https://repo1.maven.org/maven2/io/netty/netty-common/4.0.27.Final/netty-common-4.0.27.Final.jar ...
        [SUCCESSFUL ] io.netty#netty-common;4.0.27.Final!netty-common.jar (670ms)
downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar ...
        [SUCCESSFUL ] org.slf4j#slf4j-api;1.7.5!slf4j-api.jar (104ms)
downloading https://repo1.maven.org/maven2/com/rabbitmq/amqp-client/3.5.2/amqp-client-3.5.2.jar ...
        [SUCCESSFUL ] com.rabbitmq#amqp-client;3.5.2!amqp-client.jar (247ms)
:: resolution report :: resolve 20741ms :: artifacts dl 10351ms
        :: modules in use:
        com.codahale.metrics#metrics-core;3.0.2 from central in [default]
        com.datastax.cassandra#cassandra-driver-core;2.1.7.1 from central in [default]
        com.datastax.spark#spark-cassandra-connector_2.10;1.4.1 from central in [default]
        com.github.sstone#amqp-client_2.10;1.5 from central in [default]
        com.google.guava#guava;14.0.1 from central in [default]
        com.rabbitmq#amqp-client;3.5.2 from central in [default]
        com.twitter#jsr166e;1.1.0 from central in [default]
        io.netty#netty-buffer;4.0.27.Final from central in [default]
        io.netty#netty-codec;4.0.27.Final from central in [default]
        io.netty#netty-common;4.0.27.Final from central in [default]
        io.netty#netty-handler;4.0.27.Final from central in [default]
        io.netty#netty-transport;4.0.27.Final from central in [default]
        joda-time#joda-time;2.3 from central in [default]
        org.apache.cassandra#cassandra-clientutil;2.1.9 from central in [default]
        org.apache.commons#commons-lang3;3.3.2 from central in [default]
        org.joda#joda-convert;1.2 from central in [default]
        org.scala-lang#scala-reflect;2.10.5 from central in [default]
        org.slf4j#slf4j-api;1.7.5 from central in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   18  |   18  |   18  |   0   ||   18  |   18  |
        ---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent
        confs: [default]
        18 artifacts copied, 0 already retrieved (11547kB/214ms)
Warning: Skip remote jar com.rabbitmq:amqp-client:3.2.1,.
java.lang.ClassNotFoundException: spark.jobserver.JobServer
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:278)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:173)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:641)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by peterklipfel** [comment]
Also, this is not a problem without the packages flag

**Comment by peterklipfel** [comment]
0.6.0 contains the same error.

I was able to make 0.5.2 work

**Comment by peterklipfel** [comment]
Removing the spaces from the packages list solves the problem

**Comment by velvia** [comment]
Thanks.  I think the problem is that with the spaces, then spark-submit thinks one of the other packages is the class name or something.

**Comment by velvia** [comment]
@peterklipfel may we share your Marathon config btw?

**Comment by peterklipfel** [comment]
I'm not quite sure what you mean. Do you want me to submit a PR with my marathon config? Do you want me to post it here?

**Comment by velvia** [comment]
no, im asking if I can post it for you.  I already put it in a branch. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by peterklipfel** [comment]
Yeah, go ahead

**Comment by velvia** [comment]
Thanks.

**Comment by giaosudau** [comment]
```
I0610 10:11:51.835660  7966 exec.cpp:143] Version: 0.28.1
I0610 10:11:51.839177  7972 exec.cpp:217] Executor registered on slave 4c56de66-cb91-420a-9a20-12197dae0eba-S4
Ivy Default Cache set to: /root/.ivy2/cache
The jars for the packages stored in: /root/.ivy2/jars
:: loading settings :: url = jar:file:/spark/lib/spark-assembly-1.6.1-hadoop2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.datastax.spark#spark-cassandra-connector_2.10 added as a dependency
com.github.sstone#amqp-client_2.10 added as a dependency
com.rabbitmq#amqp-client added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
	confs: [default]
	found com.datastax.spark#spark-cassandra-connector_2.10;1.6.0-M2 in central
	found org.apache.cassandra#cassandra-clientutil;3.0.2 in central
	found com.datastax.cassandra#cassandra-driver-core;3.0.0 in central
	found io.netty#netty-handler;4.0.33.Final in central
	found io.netty#netty-buffer;4.0.33.Final in central
	found io.netty#netty-common;4.0.33.Final in central
	found io.netty#netty-transport;4.0.33.Final in central
	found io.netty#netty-codec;4.0.33.Final in central
	found io.dropwizard.metrics#metrics-core;3.1.2 in central
	found org.slf4j#slf4j-api;1.7.7 in central
	found org.apache.commons#commons-lang3;3.3.2 in central
	found com.google.guava#guava;16.0.1 in central
	found org.joda#joda-convert;1.2 in central
	found joda-time#joda-time;2.3 in central
	found com.twitter#jsr166e;1.1.0 in central
	found org.scala-lang#scala-reflect;2.10.5 in central
	found com.github.sstone#amqp-client_2.10;1.5 in central
	found com.rabbitmq#amqp-client;3.5.2 in central
downloading https://repo1.maven.org/maven2/com/datastax/spark/spark-cassandra-connector_2.10/1.6.0-M2/spark-cassandra-connector_2.10-1.6.0-M2.jar ...
	[SUCCESSFUL ] com.datastax.spark#spark-cassandra-connector_2.10;1.6.0-M2!spark-cassandra-connector_2.10.jar (1913ms)
downloading https://repo1.maven.org/maven2/com/github/sstone/amqp-client_2.10/1.5/amqp-client_2.10-1.5.jar ...
	[SUCCESSFUL ] com.github.sstone#amqp-client_2.10;1.5!amqp-client_2.10.jar (383ms)
downloading https://repo1.maven.org/maven2/org/apache/cassandra/cassandra-clientutil/3.0.2/cassandra-clientutil-3.0.2.jar ...
	[SUCCESSFUL ] org.apache.cassandra#cassandra-clientutil;3.0.2!cassandra-clientutil.jar (198ms)
downloading https://repo1.maven.org/maven2/com/datastax/cassandra/cassandra-driver-core/3.0.0/cassandra-driver-core-3.0.0.jar ...
	[SUCCESSFUL ] com.datastax.cassandra#cassandra-driver-core;3.0.0!cassandra-driver-core.jar(bundle) (578ms)
downloading https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar ...
	[SUCCESSFUL ] org.apache.commons#commons-lang3;3.3.2!commons-lang3.jar (203ms)
downloading https://repo1.maven.org/maven2/com/google/guava/guava/16.0.1/guava-16.0.1.jar ...
	[SUCCESSFUL ] com.google.guava#guava;16.0.1!guava.jar(bundle) (1148ms)
downloading https://repo1.maven.org/maven2/org/joda/joda-convert/1.2/joda-convert-1.2.jar ...
	[SUCCESSFUL ] org.joda#joda-convert;1.2!joda-convert.jar (195ms)
downloading https://repo1.maven.org/maven2/joda-time/joda-time/2.3/joda-time-2.3.jar ...
	[SUCCESSFUL ] joda-time#joda-time;2.3!joda-time.jar (388ms)
downloading https://repo1.maven.org/maven2/com/twitter/jsr166e/1.1.0/jsr166e-1.1.0.jar ...
	[SUCCESSFUL ] com.twitter#jsr166e;1.1.0!jsr166e.jar (194ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.5/scala-reflect-2.10.5.jar ...
	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.10.5!scala-reflect.jar (1526ms)
downloading https://repo1.maven.org/maven2/io/netty/netty-handler/4.0.33.Final/netty-handler-4.0.33.Final.jar ...
	[SUCCESSFUL ] io.netty#netty-handler;4.0.33.Final!netty-handler.jar (208ms)
downloading https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2.jar ...
	[SUCCESSFUL ] io.dropwizard.metrics#metrics-core;3.1.2!metrics-core.jar(bundle) (196ms)
downloading https://repo1.maven.org/maven2/io/netty/netty-buffer/4.0.33.Final/netty-buffer-4.0.33.Final.jar ...
	[SUCCESSFUL ] io.netty#netty-buffer;4.0.33.Final!netty-buffer.jar (197ms)
downloading https://repo1.maven.org/maven2/io/netty/netty-transport/4.0.33.Final/netty-transport-4.0.33.Final.jar ...
	[SUCCESSFUL ] io.netty#netty-transport;4.0.33.Final!netty-transport.jar (389ms)
downloading https://repo1.maven.org/maven2/io/netty/netty-codec/4.0.33.Final/netty-codec-4.0.33.Final.jar ...
	[SUCCESSFUL ] io.netty#netty-codec;4.0.33.Final!netty-codec.jar (197ms)
downloading https://repo1.maven.org/maven2/io/netty/netty-common/4.0.33.Final/netty-common-4.0.33.Final.jar ...
	[SUCCESSFUL ] io.netty#netty-common;4.0.33.Final!netty-common.jar (386ms)
downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar ...
	[SUCCESSFUL ] org.slf4j#slf4j-api;1.7.7!slf4j-api.jar (193ms)
downloading https://repo1.maven.org/maven2/com/rabbitmq/amqp-client/3.5.2/amqp-client-3.5.2.jar ...
	[SUCCESSFUL ] com.rabbitmq#amqp-client;3.5.2!amqp-client.jar (384ms)
:: resolution report :: resolve 30716ms :: artifacts dl 8902ms
	:: modules in use:
	com.datastax.cassandra#cassandra-driver-core;3.0.0 from central in [default]
	com.datastax.spark#spark-cassandra-connector_2.10;1.6.0-M2 from central in [default]
	com.github.sstone#amqp-client_2.10;1.5 from central in [default]
	com.google.guava#guava;16.0.1 from central in [default]
	com.rabbitmq#amqp-client;3.5.2 from central in [default]
	com.twitter#jsr166e;1.1.0 from central in [default]
	io.dropwizard.metrics#metrics-core;3.1.2 from central in [default]
	io.netty#netty-buffer;4.0.33.Final from central in [default]
	io.netty#netty-codec;4.0.33.Final from central in [default]
	io.netty#netty-common;4.0.33.Final from central in [default]
	io.netty#netty-handler;4.0.33.Final from central in [default]
	io.netty#netty-transport;4.0.33.Final from central in [default]
	joda-time#joda-time;2.3 from central in [default]
	org.apache.cassandra#cassandra-clientutil;3.0.2 from central in [default]
	org.apache.commons#commons-lang3;3.3.2 from central in [default]
	org.joda#joda-convert;1.2 from central in [default]
	org.scala-lang#scala-reflect;2.10.5 from central in [default]
	org.slf4j#slf4j-api;1.7.7 from central in [default]
	:: evicted modules:
	com.rabbitmq#amqp-client;3.2.1 by [com.rabbitmq#amqp-client;3.5.2] in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   19  |   18  |   18  |   1   ||   18  |   18  |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent
	confs: [default]
	18 artifacts copied, 0 already retrieved (12329kB/38ms)
Warning: Skip remote jar com.typesafe.akka:akka-actor_2.10:2.3.11,com.github.nscala-time:nscala-time_2.10:1.6.0,com.fasterxml.jackson.core:jackson-core:2.2.2,.
java.lang.ClassNotFoundException: spark.jobserver.JobServer
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:174)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:689)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
W0610 10:11:51.839177  7967 logging.cpp:88] RAW: Received signal SIGTERM from process 2893 of user 0; exiting
```

I have the same too
```json
{
  "id": "/spark.jobserver",
  "cmd": null,
  "cpus": 0.5,
  "mem": 1024,
  "disk": 0,
  "instances": 1,
  "container": {
    "type": "DOCKER",
    "volumes": [],
    "docker": {
      "image": "velvia/spark-jobserver:0.6.2.mesos-0.28.1.spark-1.6.1",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 8090,
          "hostPort": 0,
          "servicePort": 10000,
          "protocol": "tcp",
          "labels": {}
        }
      ],
      "privileged": false,
      "parameters": [],
      "forcePullImage": false
    }
  },
  "env": {
    "SPARK_MASTER": "mesos.ourcluster.internal:5050"
  },
  "portDefinitions": [
    {
      "port": 10000,
      "protocol": "tcp",
      "labels": {}
    }
  ],
  "args": [
    "--packages",
    "com.datastax.spark:spark-cassandra-connector_2.10:1.6.0-M2,com.github.sstone:amqp-client_2.10:1.5,com.rabbitmq:amqp-client:3.2.1, com.typesafe.akka:akka-actor_2.10:2.3.11,com.github.nscala-time:nscala-time_2.10:1.6.0,com.fasterxml.jackson.core:jackson-core:2.2.2, com.fasterxml.jackson.core:jackson-databind:2.2.2,com.fasterxml.jackson.module:jackson-module-scala_2.10:2.2.2,org.scalaj:scalaj-http_2.10:1.1.4,org.elasticsearch:elasticsearch-spark_2.10:2.1.0.Beta3,spark.jobserver:job-server-api:0.6.2,spark.jobserver:job-server-extras:0.6.2"
  ]
}
```

How to fix it?

**Comment by noorul** [comment]
I think the --packages is creating problem here. 

See here http://stackoverflow.com/questions/37712334/how-to-run-spark-jobserver-on-mesospheres-dc-os
