### ISSUE TITLE
Will it support Maven features in the future?

### ISSUE THREAD

**Issue by loveyanbei** [spark-jobserver/spark-jobserver#362]
like what spark-submit --master Master:PORT --package artifact:name:ver, , , ,  --class CP  JARFILE does?

**Comment by loveyanbei** [comment]
It seems that the job server create contexts through spark-submit, and spark-submit supports using maven through --packages option, I tried to use a package downloaded from maven repository and used it through dependencies-jar-uris but results in error, and later I used "spark-submit --jars DEPS MAIN --class CP", but also fails in NoSuchClassError. Finally I tried using --packages option ,and made it. It can be a hell to just submit jobs without maven when using packages from maven repos,

**Comment by loveyanbei** [comment]
t org.apache.spark.sql.SQLContext
import org.apache.spark.sql.types.{FloatType, StructField, StructType}
import spark.jobserver._
import spark.jobserver.SparkJobValidation
import com.typesafe.config._
// Load and parse the data
object hello1 extends SparkSqlJob {
  override def runJob(sqlc:SQLContext, jobConfig: Config): Any =
  {
    val customSchema = new StructType(Array(
      StructField("x", FloatType, false),
      StructField("y", FloatType, false)))
    val datafield = sqlc.read.format("com.databricks.spark.csv")
      .option("header","true")
      .schema(customSchema)
      .load("hdfs://master:9000/test1.csv")
    val selecteddata = datafield.select("x","y")
    //K = 14 , B = 9
    //X = WIDTH ,Y = LENGTH

    val parsed = selecteddata.map(Row => new LabeledPoint(Row.getFloat(1), Vectors.dense(Row.getFloat(0))));
    val splits = parsed.randomSplit(Array(0.8,0.2))
    val train = splits(0)
    val test = splits(1)
    val numIterations = parsed.count()
    val tmdl = new LinearRegressionWithSGD().setIntercept(true)
    tmdl.optimizer.setNumIterations(parsed.count().toInt)
    tmdl.optimizer.setStepSize(0.0001)  //Important ! Wrong setting could return weird results
    val mdl = tmdl.run(parsed)
    val count = parsed.count()
    val value_and_prediction = test.map {
      pt =>
        val pre = mdl.predict(pt.features)
        (pt.features(0), pt.label, pre)
    }
    val MSE = value_and_prediction.map{
      case(x,v,p) => math.pow((v-p),2)
    }.mean()
    value_and_prediction.collect().foreach(println)
    //selecteddata.collect().foreach(println)
    println(MSE)
    value_and_prediction
    // val log_data = sc.textFile("file:///usr/local/hadoop/logs/hadoop-hadoop-datanode-Master.log")
    // val res = log_data.flatMap(line => line.split(" ")).map(word => (word,1)).reduceByKey((a,b)=>a + b).collect()
    // res.foreach(j => println(j))
  }
  override def validate(sc:SQLContext, config: Config): SparkJobValidation =
  {
    SparkJobValid;
  }
}

**Comment by loveyanbei** [comment]
This program can perfectly run on a local spark without spark-jobserver. I used package sparkcsv and uploaded jar and dep to server , but I left 2 additional deps behind,  I found the problem when I used maven ulitity of spark-submit, It gave me 3 dep jars. Spark jobserver gave me stack trace like below. I cannot figure out the dep problem through this orz.
[{
  "duration": "0.502 secs",
  "classPath": "hello1",
  "startTime": "2016-01-17T17:24:51.737+08:00",
  "context": "umi",
  "result": {
    "errorClass": "java.util.concurrent.ExecutionException",
    "cause": "org.apache.spark.sql.sources.DataSourceRegister: Error reading configuration file",
    "stack": ["java.util.ServiceLoader.fail(ServiceLoader.java:232)", "java.util.ServiceLoader.parse(ServiceLoader.java:309)", "java.util.ServiceLoader.access$200(ServiceLoader.java:185)", "java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357)", "java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)", "java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)", "scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:41)", "scala.collection.Iterator$class.foreach(Iterator.scala:727)", "scala.collection.AbstractIterator.foreach(Iterator.scala:1157)", "scala.collection.IterableLike$class.foreach(IterableLike.scala:72)", "scala.collection.AbstractIterable.foreach(Iterable.scala:54)", "scala.collection.TraversableLike$class.filter(TraversableLike.scala:263)", "scala.collection.AbstractTraversable.filter(Traversable.scala:105)", "org.apache.spark.sql.execution.datasources.ResolvedDataSource$.lookupDataSource(ResolvedDataSource.scala:59)", "org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:102)", "org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)", "org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:109)", "hello1$.runJob(example.scala:23)", "hello1$.runJob(example.scala:14)", "spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:274)", "scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)", "scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)", "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)", "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)", "java.lang.Thread.run(Thread.java:745)"],
    "causingClass": "java.util.ServiceConfigurationError",
    "message": "Boxed Error"
  },
  "status": "ERROR",
  "jobId": "68295926-3026-43d3-9a10-33c1ec36dfc9"
}

**Comment by loveyanbei** [comment]
spark-submit gave me good result,The REAL CAUSE of my failure.
16/01/17 20:31:06 INFO SparkDeploySchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/csv/CSVFormat
	at com.databricks.spark.csv.package$.<init>(package.scala:27)
	at com.databricks.spark.csv.package$.<clinit>(package.scala)
	at com.databricks.spark.csv.CsvRelation.tokenRdd(CsvRelation.scala:79)
	at com.databricks.spark.csv.CsvRelation.buildScan(CsvRelation.scala:104)
	at com.databricks.spark.csv.CsvRelation.buildScan(CsvRelation.scala:152)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$4.apply(DataSourceStrategy.scala:64)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$4.apply(DataSourceStrategy.scala:64)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:274)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:273)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProjectRaw(DataSourceStrategy.scala:352)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProject(DataSourceStrategy.scala:269)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.apply(DataSourceStrategy.scala:60)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:59)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:47)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:45)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:52)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:52)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:55)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:55)
	at org.apache.spark.sql.DataFrame.rdd$lzycompute(DataFrame.scala:1676)
	at org.apache.spark.sql.DataFrame.rdd(DataFrame.scala:1673)
	at org.apache.spark.sql.DataFrame.map(DataFrame.scala:1449)
	at Hello$.main(main.scala:29)
	at Hello.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.csv.CSVFormat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more

**Comment by velvia** [comment]
@loveyanbei looks like the question was answered on the other email thread.  You can pass --packages flag when starting job server or use dependent-jar-uris properly (one config, use comma to split).  Feel free to reopen if that doesn't work.
