### ISSUE TITLE
Deploying Spark jobserver on YARN 

### ISSUE THREAD

**Issue by hackercompany** [spark-jobserver/spark-jobserver#374]
I am trying to deploy spark job server on YARN
I am doing 
```
./bin/server_package.sh ec2 
```
This make a folder in `/tmp/jobserver`
When i try to `./sever_start.sh`

I receive this error
```
Uncaught error from thread [JobServer-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[JobServer]
Uncaught error from thread [JobServer-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[JobServer]
java.lang.NoClassDefFoundError: ooyala/common/akka/ActorMetrics$$anonfun$receive$1
        at ooyala.common.akka.ActorMetrics$class.receive(ActorMetrics.scala:20)
        at ooyala.common.akka.InstrumentedActor.receive(InstrumentedActor.scala:8)
        at akka.actor.ActorCell.newActor(ActorCell.scala:558)
        at akka.actor.ActorCell.create(ActorCell.scala:578)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Uncaught error from thread [JobServer-akka.actor.default-dispatcher-5] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[JobServer]
java.lang.NoClassDefFoundError: ooyala/common/akka/ActorMetrics$$anonfun$receive$1
        at ooyala.common.akka.ActorMetrics$class.receive(ActorMetrics.scala:20)
        at ooyala.common.akka.InstrumentedActor.receive(InstrumentedActor.scala:8)
        at akka.actor.ActorCell.newActor(ActorCell.scala:558)
        at akka.actor.ActorCell.create(ActorCell.scala:578)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
java.lang.NoClassDefFoundError: scala/runtime/AbstractPartialFunction$mcVL$sp
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
```

Tried reducing version of akka no effect
Any suggestions ?

**Comment by hackercompany** [comment]
In this I am also chainging in **ec2.conf** 
`master=yarn-client`

**Comment by velvia** [comment]
Assuming you figured this out?

**Comment by hackercompany** [comment]
Yes
Version issue between spark and server_package
