### ISSUE TITLE
akka.pattern.AskTimeoutException in docker deployed on AWS

### ISSUE THREAD

**Issue by timkral** [spark-jobserver/spark-jobserver#416]
I'm attempting to deploy the SJS via docker on Elastic Beanstalk. We're using Spark 1.6.0 so I'm building the SJS from the master branch. I'm trying to run this on a Mesos 0.26.0 cluster.

```
ENV SPARK_VERSION 1.6.0
ENV MESOS_BUILD_VERSION 0.26.0-0.2.145
ENV SPARK_JOBSERVER_BRANCH master
```

I've successfully build and used my docker image on my local dev box. However, when I deploy to Beanstalk, I'm getting the following error:

```
2016-04-06 23:02:31,373:17(0x7f93608a8700):ZOO_INFO@check_events@1703: initiated connection to server [xx.xx.xx.xx:2181]
2016-04-06 23:02:31,378:17(0x7f93608a8700):ZOO_INFO@check_events@1750: session establishment complete on server [xx.xx.xx.xx:2181], sessionId=0x54ec048cc5603e4, negotiated timeout=10000
I0406 23:02:31.379031   141 group.cpp:331] Group process (group(1)@xx.xx.xx.xx:55935) connected to ZooKeeper
I0406 23:02:31.379117   141 group.cpp:805] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I0406 23:02:31.379130   141 group.cpp:403] Trying to create path '/mesos' in ZooKeeper
I0406 23:02:31.410980   141 detector.cpp:156] Detected a new leader: (id='8')
I0406 23:02:31.411058   144 group.cpp:674] Trying to get '/mesos/json.info_0000000008' in ZooKeeper
I0406 23:02:31.412586   144 detector.cpp:482] A new leading master (UPID=master@xx.xx.xx.xx:5050) is detected
I0406 23:02:31.412695   144 sched.cpp:264] New master detected at master@xx.xx.xx.xx:5050
I0406 23:02:31.412853   144 sched.cpp:274] No credentials provided. Attempting to register without authentication
[2016-04-06 23:05:28,007] ERROR ocalContextSupervisorActor [] [] - Exception after sending Initialize to JobManagerActor
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://JobServer/user/context-supervisor/root-context#-1387449221]] after [180000 ms]
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)
	at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
	at java.lang.Thread.run(Thread.java:745)
[2016-04-06 23:05:28,012] INFO  r$RemoteDeadLetterActorRef [] [akka://JobServer/deadLetters] - Message [spark.jobserver.ContextSupervisor$ContextInitError] from Actor[akka://JobServer/user/context-supervisor#-2068044449] to Actor[akka://JobServer/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'
```

I've read through the Troubleshooting guide and tried upping all the timeouts mentioned there (you can see in the trace above that my context creation timeout is 180s). Also, I know that this exception has been listed in several issues already, however the general advice there is to upgrade mesos. But I'm already at a later version of mesos.

I also tried setting the `context-per-jvm = true` with `context-init-timeout = 90s`, but still basically the same error:

```
[2016-04-07 00:13:54,998] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Starting context with actor name jobManager-99-970c-5e22540b2883
[2016-04-07 00:13:55,024] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Created working directory /var/log/job-server/jobserver-root-context2450977807346879154 for context root-context
[2016-04-07 00:13:55,033] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Starting to execute sub process [/app/manager_start.sh, /var/log/job-server/jobserver-root-context2450977807346879154, akka.tcp://JobServer@127.0.0.1:56433]
[2016-04-07 00:13:56,547] INFO  Cluster(akka://JobServer) [] [Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:56433] - Node [akka.tcp://JobServer@127.0.0.1:53928] is JOINING, roles [manager]
[2016-04-07 00:13:56,860] INFO  Cluster(akka://JobServer) [] [Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:56433] - Leader is moving node [akka.tcp://JobServer@127.0.0.1:53928] to [Up]
[2016-04-07 00:13:56,906] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Received identify response, attempting to initialize context at akka.tcp://JobServer@127.0.0.1:53928/user/*
[2016-04-07 00:13:56,907] INFO  k.jobserver.JobResultActor [] [akka://JobServer/user/context-supervisor/$a] - Starting actor spark.jobserver.JobResultActor
[2016-04-07 00:15:26,921] INFO  AkkaClusterSupervisorActor [] [] - Failed to send initialize message to context Actor[akka.tcp://JobServer@127.0.0.1:53928/user/jobManager-99-970c-5e22540b2883#-212649211]
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka.tcp://JobServer@127.0.0.1:53928/user/jobManager-99-970c-5e22540b2883#-212649211]] after [90000 ms]
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)
	at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
	at java.lang.Thread.run(Thread.java:745)
```

This feels like a networking issue since it works locally and I get the same akka exception in each case. However, I'm new to akka so I'm really not sure how to debug this. The Troubleshooting guide mentions using IPs instead of DNS for deployment in AWS. But I'm not sure what exactly that's referring to.

Any idea on how I can resolve this?

**Comment by velvia** [comment]
@David-Durst @apivovarov @zeitos any of you able to help @timkral ?

**Comment by zeitos** [comment]
I don't have experience with the docker image or mesos so there's not much I can help here
This looks related to https://github.com/spark-jobserver/spark-jobserver/issues/267 but as you said you're on the last version :S

**Comment by timkral** [comment]
Looks like perhaps this setup just isn't possible due to how Beanstalk handles multiple ports from a docker container. See [here](http://stackoverflow.com/questions/27381651/app-running-in-docker-on-eb-refuses-connecting-to-self). I'm going to try a deployment with less moving parts.

**Comment by timkral** [comment]
For what it's worth, I finally solved this by turning on host networking for my docker container. Just in case someone is trying to research in the future.

**Comment by velvia** [comment]
Thanks Tim.  Will add a note on the docker README and troubleshooting guide as well.

Can this be closed?

**Comment by timkral** [comment]
Yes, I had closed it because I felt it was unrelated to the Spark JobServer itself.
