### ISSUE TITLE
the count of running app is error 

### ISSUE THREAD

**Issue by gaoshui87** [spark-jobserver/spark-jobserver#417]
when kill a job,it may be not write now cancle the on in spark,so ,the web ui may be show a error.
the runnig job do  not show  the job message,but the context count is error. so ,i have solve the probram

`  

 processStatus(msg, "killed", remove = false) {
        case (info, msg) =>
          info.copy(endTime = Some(msg.endTime), logstatus = Some(info.logstatus.getOrElse("") + "killed "))
      }

`

the remove should be false,the real result will be wrote in the job result

![image](https://cloud.githubusercontent.com/assets/5254220/14343444/97e6ad94-fcd3-11e5-8da8-81cf71744b4e.png)

the error messate is bellow 
 
[2016-04-08 19:25:56,843] ERROR k.scheduler.TaskSetManager [] [akka://JobServer/user/jobManager-98-94b3-af83fce37faa] - Task 1 in stage 1.0 failed 4 times; aborting job
[2016-04-08 19:25:56,849] INFO  cheduler.TaskSchedulerImpl [] [akka://JobServer/user/jobManager-98-94b3-af83fce37faa] - Cancelling stage 1
[2016-04-08 19:25:56,853] INFO  cheduler.TaskSchedulerImpl [] [akka://JobServer/user/jobManager-98-94b3-af83fce37faa] - Stage 1 was cancelled
[2016-04-08 19:25:56,857] WARN  .jobserver.JobManagerActor [] [akka://JobServer/user/jobManager-98-94b3-af83fce37faa] - Exception from job 7bfeb089-db7b-420f-a4b1-f961bb6524f9: 
org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 1.0 failed 4 times, most recent failure: Lost task 1.3 in stage 1.0 (TID 14,  ): org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: Found unrecoverable error [ :9200] returned Bad Request(400) - failed to parse [uid];For input string: "\N"; Bailing out..
        at org.elasticsearch.hadoop.rest.RestClient.retryFailedEntries(RestClient.java:206)
        at org.elasticsearch.hadoop.rest.RestClient.bulk(RestClient.java:169)
        at org.elasticsearch.hadoop.rest.RestRepository.tryFlush(RestRepository.java:220)
        at org.elasticsearch.hadoop.rest.RestRepository.flush(RestRepository.java:243)
        at org.elasticsearch.hadoop.rest.RestRepository.doWriteToIndex(RestRepository.java:196)
        at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:158)
        at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:49)
        at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:57)
        at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:57)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at scala.Option.foreach(Option.scala:236)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
		
	
i find that ,the actor letters is dead ,so cant not remove the jobinfo in the  sparkJobServer memory	
		
		[2016-04-08 19:25:44,610] INFO  rk.jobserver.io.JobFileDAO [] [akka://JobServer/user/dao-manager] - end start to saveJobInfo
[2016-04-08 19:25:44,619] INFO  r$RemoteDeadLetterActorRef [] [akka://JobServer/deadLetters] - Message [spark.jobserver.JobInfoActor$JobConfigStored$] from Actor[akka://JobServer/user/job-info#105172698] to Actor[akka://JobServer/deadLet
ters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2016-04-08 19:25:56,907] WARN  ReliableDeliverySupervisor [] [akka.tcp://JobServer@127.0.0.1:25266/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A29251-2] - Association with remote system [akka.tc
p://JobServer@127.0.0.1:29251] has failed, address is now gated for [5000] ms. Reason: [org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest] 
[2016-04-08 19:25:56,912] INFO  akka.actor.LocalActorRef [] [akka://JobServer/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A29251-2/endpointWriter/endpointReader-akka.tcp%3A%2F%2FJobServer%40127.0
.0.1%3A29251-0] - Message [akka.remote.transport.AssociationHandle$InboundPayload] from Actor[akka://JobServer/deadLetters] to Actor[akka://JobServer/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A
29251-2/endpointWriter/endpointReader-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A29251-0#-1017811468] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-le
tters' and 'akka.log-dead-letters-during-shutdown'.
[2016-04-08 19:25:56,912] INFO  akka.actor.LocalActorRef [] [akka://JobServer/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A29251-2/endpointWriter/endpointReader-akka.tcp%3A%2F%2FJobServer%40127.0
.0.1%3A29251-0] - Message [akka.remote.transport.AssociationHandle$InboundPayload] from Actor[akka://JobServer/deadLetters] to Actor[akka://JobServer/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A
29251-2/endpointWriter/endpointReader-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A29251-0#-1017811468] was not delivered. [3] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-le
tters' and 'akka.log-dead-letters-during-shutdown'.

**Comment by gaoshui87** [comment]
----  the problem is solved

the reason is that ,the remote akka process throw a excetion ,
the   AkkaClusterSupervisorActor don not contail the class ,so seriseris is error
it must contail the dependis jars

**Comment by velvia** [comment]
Hmmm….   we fixed this with a workaround for throwing error exceptions…

**Comment by zeitos** [comment]
Closing since it's fixed, thanks @gaoshui87 feel free to reopen if you need it.
