### ISSUE TITLE
reStart failing with recent clone

### ISSUE THREAD

**Issue by glennmurray** [spark-jobserver/spark-jobserver#443]
I've just done a new clone of master and ran sbt (sbt-0.13.5 on Ubuntu).  While "compile" completed successfully, "reStart" failed.  Unlike two days ago, when I run "reStart" now it wants to run a main in the examples.  I have.

```
spark-jobserver/$ echo $VER
0.7.0-SNAPSHOT
```
From the sbt console after running "reStart":
```
...
[info] Resolving org.apache.thrift#libfb303;0.9.2 ...
[info] Application job-server-api not yet started
[info] Application akka-app not yet started
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list

Multiple main classes detected, select one to run:

 [1] spark.jobserver.LongPiJob
 [2] spark.jobserver.NoOpJob
 [3] spark.jobserver.VeryShortDoubleJob
 [4] spark.jobserver.WordCountExample
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
```
At this point the console waits for me to enter an integer, presumably to choose a main().  After I enter one I get the following (if I just enter no value I get `Invalid number: java.lang.NumberFormatException: For input string: ""`).
```
[info] Application job-server-tests not yet started
[info] Updating {file:/home/gamurray/Projects/sandbox-odecs/user/gamurray/Projects/spark-jobserver/}root...
[info] Starting application job-server-tests in the background ...
job-server-tests Starting spark.jobserver.WordCountExample.main()
[info] Resolving io.netty#netty-all;4.0.29.Final ...
[info] Application job-server not yet started
[info] Starting application job-server in the background ...
job-server Starting spark.jobserver.JobServer.main()
[info] Resolving org.parboiled#parboiled-scala_2.10;1.1.7 ...
[info] Resolving org.parboiled#parboiled-core;1.1.7 ...
job-server-tests[ERROR]         at java.lang.Class.getDeclaredMethods0(Native Method)
job-server-tests[ERROR]         at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
job-server-tests[ERROR]         at java.lang.Class.getMethod0(Class.java:2866)
job-server-tests[ERROR]         at java.lang.Class.getMethod(Class.java:1676)
job-server-tests[ERROR]         at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
job-server-tests[ERROR]         at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
job-server-tests[ERROR] Caused by: java.lang.ClassNotFoundException: org.apache.spark.SparkContext
job-server-tests[ERROR]         at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
job-server-tests[ERROR]         at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
job-server-tests[ERROR]         at java.security.AccessController.doPrivileged(Native Method)
job-server-tests[ERROR]         at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
job-server-tests[ERROR]         at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
job-server-tests[ERROR]         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
job-server-tests[ERROR]         at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[info] Resolving io.spray#spray-caching_2.10;1.3.3 ...
[info] Resolving commons-dbcp#commons-dbcp;1.4 ...
[info] Application job-server-extras not yet started
[info] Starting application job-server-extras in the background ...
job-server-extras Starting spark.jobserver.JobServer.main()
...
```
then I get the usual SLF4J errors (these don't seem to have been fixed in (https://github.com/spark-jobserver/spark-jobserver/issues/262)
```
...
[info] Resolving org.apache.hadoop#hadoop-auth;2.2.0 ...
job-server[ERROR] log4j:WARN Please initialize the log4j system properly.
[info] Resolving org.apache.hadoop#hadoop-yarn-client;2.2.0 ...
[info] Resolving org.apache.hadoop#hadoop-yarn-client;2.2.0 ...
job-server-extras[ERROR] log4j:WARN No appenders could be found for logger (spark.jobserver.JobServer$).
job-server-extras[ERROR] log4j:WARN Please initialize the log4j system properly.
...
```
and finally
```
...
[info] Application root not yet started
[trace] Stack trace suppressed: run last root/*:reStart for the full output.
[trace] Stack trace suppressed: run last akka-app/*:reStart for the full output.
[trace] Stack trace suppressed: run last job-server-api/*:reStart for the full output.
[error] (root/*:reStart) No main class detected!
[error] (akka-app/*:reStart) No main class detected!
[error] (job-server-api/*:reStart) No main class detected!
[error] Total time: 34 s, completed Apr 27, 2016 2:28:26 PM
...
```
Thanks for any suggestions.

Glenn

P.S.  I was able to get a working version by falling back to 

Evan Chan, 2262f1a Added user impersonation fix by @mateilucianstefan 8 days ago. Wed Apr 20 00:24:34 2016 -0700

**Comment by velvia** [comment]
Can you try ‘job-server/reStart’?   Running reStart from the main causes reStart to be run in all subprojects.  Will try to disable this.

-Evan

**Comment by jomach** [comment]
job-server/reStart

**Comment by jomach** [comment]
@velvia it works as you described.

**Comment by noorul** [comment]
@jomach Is everything working fine now? Shall we close this issue?

**Comment by noorul** [comment]
Closing as I see that solution was provided and it works.
