### ISSUE TITLE
jar upload returns "OK" eventhough log indicates exception

### ISSUE THREAD

**Issue by d-ee** [spark-jobserver/spark-jobserver#444]
SJS 0.6.2

1 Preparation: Have a running SJS and context. Then delete the temporary folder `/tmp/spark-job-server`.

2 Upload a jar with:
`curl --data-binary @/tmp/sparksjs001.jar localhost:8090/jars/sparksjs001`

It immediately returns `OK`.

3 Try to call the jar with:
`curl -d "" "localhost:8090/jobs?appName=sparksjs001&classPath=xxx&context=test-context&sync=true"`

Which returns `{
  "status": "ERROR",
  "result": "appName sparksjs001 not found"
}`.

This indicates the jar is not available. It is also not shown unter `/jars`, so it really is not there.

4 The log shows what's going on:
`[2016-04-28 09:38:20,266] ERROR ka.actor.OneForOneStrategy [] [akka://JobServer/user/dao-manager] - /tmp/spark-job-server/filedao/data/sparksjs
001-2016-04-28T09_38_20.265+02_00.jar (No such file or directory)
java.io.FileNotFoundException: /tmp/spark-job-server/filedao/data/sparksjs001-2016-04-28T09_38_20.265+02_00.jar (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at spark.jobserver.io.JobFileDAO.saveJar(JobFileDAO.scala:98)
        at spark.jobserver.io.JobDAOActor$$anonfun$wrappedReceive$1.applyOrElse(JobDAOActor.scala:45)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
        at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
        at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)
        at ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)
        at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
        at ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

I somehow expected something different than the returned `OK`...

**Comment by velvia** [comment]
Thanks for the bug report.  Yeah, it should not return OK.

**Comment by noorul** [comment]
@velvia I think this will happen only the case with filedao. We were discussing to deprecate filedao, is this the right time?

**Comment by velvia** [comment]
Yeah it probably is. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by noorul** [comment]
I created a ticket to track that. https://github.com/spark-jobserver/spark-jobserver/issues/526

@d-ee Closing this ticket as file dao has issues and we are going to deprecate it. We could have avoided this issue by not removing /tmp/spark-jobserver.
