### ISSUE TITLE
Failed to Start Job Server v0.6.2

### ISSUE THREAD

**Issue by kkarthik21** [spark-jobserver/spark-jobserver#448]
It fails to start the job server, got below exception. I am using Spark 1.6.1 and Job Server 0.6.2. This issue is similar to #123

```
Exception in thread "main" java.lang.NoSuchMethodError: com.typesafe.config.Config.getDuration(Ljava/lang/String;Ljava/util/concurrent/TimeUnit;)J
	at akka.util.Helpers$ConfigOps$.akka$util$Helpers$ConfigOps$$getDuration$extension(Helpers.scala:126)
	at akka.util.Helpers$ConfigOps$.getMillisDuration$extension(Helpers.scala:121)
	at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:172)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:505)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
	at spark.jobserver.JobServer$.spark$jobserver$JobServer$$makeSupervisorSystem$1(JobServer.scala:128)
	at spark.jobserver.JobServer$$anonfun$main$1.apply(JobServer.scala:130)
	at spark.jobserver.JobServer$$anonfun$main$1.apply(JobServer.scala:130)
	at spark.jobserver.JobServer$.start(JobServer.scala:54)
	at spark.jobserver.JobServer$.main(JobServer.scala:130)
	at spark.jobserver.JobServer.main(JobServer.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by hntd187** [comment]
@kkarthik21 you built SJS with java8, but are running it on a java7 JDK, you must build it on the same JDK. Rebuild your SJS on JDK7 and it should be fine.

**Comment by kkarthik21** [comment]
No. I am building and running SJS with Java 1.8, scala 2.10.6 and SBT 0.13.6.

**Comment by hntd187** [comment]
I would then check the classpath you are running on and make sure the version of the typesafe config is correct for your jdk, Java7 runs on 1.2.1 and java8 uses 1.3.0

**Comment by kkarthik21** [comment]
I don't have java 1.7 in my machine. But i had 1.2.1 and 1.3.0 jar in .ivy2 repository location and I have attached the build SJS result of version 0.6.2.

**Comment by hntd187** [comment]
Hmmm, okay everything there seems fine, and to boot getDuration does exist with that signature in the typesafe version, so it's not really missing... https://github.com/typesafehub/config/blob/master/config/src/main/java/com/typesafe/config/Config.java

Try doing a clean rebuild with SBT 0.13.11, we're up to date there, your build tool is out of date and I can't guarantee that isn't causing it.

**Comment by kkarthik21** [comment]
No luck with clean run and 0.13.11. Still it exists and attached the log [build_0.6.2_with_0.13.11_result.txt](https://github.com/spark-jobserver/spark-jobserver/files/243866/build_0.6.2_with_0.13.11_result.txt)

**Comment by hntd187** [comment]
Can you clear your .ivy cache?

**Comment by kkarthik21** [comment]
yes i did now. same exception.

**Comment by kkarthik21** [comment]
Can you tell me, why SJS downloads both (1.2.1 & 1.3.0) the version of Config jar.

[Build.txt](https://github.com/spark-jobserver/spark-jobserver/files/243872/Build.txt)
[Dependencies.txt](https://github.com/spark-jobserver/spark-jobserver/files/243871/Dependencies.txt)

**Comment by hntd187** [comment]
I  am thinking this is because of akka's use of 1.2.1 and we're conflicting with it there. Try hard setting the config to 1.2.1 and see what happens.

**Comment by velvia** [comment]
I would try using the sbt dependency-graph plugin.   Then go into job-server project and verify what dependency is getting included.

Try  dependencyGraph

then look in the graph for com.typesafe.config.  Any version being deprecated will be marked.

-Evan

**Comment by kkarthik21** [comment]
please see the dependency tree result. for more 
[tree.txt](https://github.com/spark-jobserver/spark-jobserver/files/244148/tree.txt)
 
```
[info] spark.jobserver:job-server_2.10:0.6.2 [S]
[info]   +-com.databricks:spark-csv_2.10:1.4.0 [S]
[info]   | +-com.univocity:univocity-parsers:1.5.1
[info]   | +-org.apache.commons:commons-csv:1.1
[info]   | 
[info]   +-com.h2database:h2:1.3.176
[info]   +-com.sun.jersey:jersey-client:1.19
[info]   +-com.typesafe.slick:slick_2.10:2.1.0 [S]
[info]   | +-com.typesafe:config:1.2.1 (evicted by: 1.3.0)
[info]   | +-com.typesafe:config:1.3.0
[info]   | +-org.slf4j:slf4j-api:1.6.4 (evicted by: 1.7.2)
[info]   | +-org.slf4j:slf4j-api:1.7.2
[info]   | 
[info]   +-com.typesafe:config:1.2.1 (evicted by: 1.3.0)
[info]   +-com.typesafe:config:1.3.0
```

**Comment by hntd187** [comment]
Yea, it's being evicted so it seems like it's correct, but I'm not 100% sure with sbt. I'd say, just try changing the build to just be hard coded to 1.2.1 since the problem seems to bubble up through akka, that was akka has what it wants and the 1.2.1 is compatible with java8 I believe, it's just the 1.3.0 version uses Java8 features so it's not backwards compatible. Might also want to think about an eviction rule on the 1.2.1 dependency if the 1.3.0 is being used, but then again, we should also probably update akka if that were possible :-p

**Comment by kkarthik21** [comment]
Now i hardcoded to 1.2.1 and tried. no luck. 
[tree_1.2.0.txt](https://github.com/spark-jobserver/spark-jobserver/files/244178/tree_1.2.0.txt)

**Comment by noorul** [comment]
Did you try the container?

**Comment by velvia** [comment]
I think the problem is not the version of type safe config that is bundled with SJS.  The problem is that somehow the Spark class path of config is overtaking the one built into SJS.

**Comment by kkarthik21** [comment]
Yes you are correct @velvia. after updating the classpath of spark, It works.

Thanks a lot!!
