### ISSUE TITLE
Unable to start context

### ISSUE THREAD

**Issue by larghir** [spark-jobserver/spark-jobserver#450]
Hi,

I am running spark-jobserver in a Docker container from tagspark-jobserver:0.6.1.mesos-0.25.0.spark-1.5.2 where I only adjusted the configuration. I am getting this exception when querying the jobs or contexts:

`ERROR ocalContextSupervisorActor [] [] - Exception after sending Initialize to JobManagerActor
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://JobServer/user/context-supervisor/my-low-latency-context#129850906]] after [15000 ms]
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)
	at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
	at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
	at java.lang.Thread.run(Thread.java:745)
[2016-05-03 12:03:03,982] ERROR ocalContextSupervisorActor [] [] - Unable to start context my-low-latency-context
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://JobServer/user/context-supervisor/my-low-latency-context#129850906]] after [15000 ms]
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)
	at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
	at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
	at java.lang.Thread.run(Thread.java:745)
[2016-05-03 12:05:17,223] ERROR rkUncaughtExceptionHandler [] [akka://JobServer/user/context-supervisor/my-low-latency-context] - Uncaught exception in thread Thread[appclient-registration-retry-thread,5,main]
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1e85376a rejected from java.util.concurrent.ThreadPoolExecutor@3bf91fcd[Running, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2048)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:110)
	at org.apache.spark.deploy.client.AppClient$ClientEndpoint$$anonfun$tryRegisterAllMasters$1.apply(AppClient.scala:96)
	at org.apache.spark.deploy.client.AppClient$ClientEndpoint$$anonfun$tryRegisterAllMasters$1.apply(AppClient.scala:95)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:108)
	at org.apache.spark.deploy.client.AppClient$ClientEndpoint.tryRegisterAllMasters(AppClient.scala:95)
	at org.apache.spark.deploy.client.AppClient$ClientEndpoint.org$apache$spark$deploy$client$AppClient$ClientEndpoint$$registerWithMaster(AppClient.scala:121)
	at org.apache.spark.deploy.client.AppClient$ClientEndpoint$$anon$2$$anonfun$run$1.apply$mcV$sp(AppClient.scala:132)
	at org.apache.spark.util.Utils$.tryOrExit(Utils.scala:1119)
	at org.apache.spark.deploy.client.AppClient$ClientEndpoint$$anon$2.run(AppClient.scala:124)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-05-03 12:05:17,229] INFO  k.storage.DiskBlockManager [] [akka://JobServer/user/context-supervisor/my-low-latency-context] - Shutdown hook called
[2016-05-03 12:05:17,232] INFO  k.util.ShutdownHookManager [] [akka://JobServer/user/context-supervisor/my-low-latency-context] - Shutdown hook called
[2016-05-03 12:05:17,233] INFO  k.util.ShutdownHookManager [] [akka://JobServer/user/context-supervisor/my-low-latency-context] - Deleting directory /tmp/spark-e41795f9-7be0-44a8-be09-7419aa631e98/httpd-8238ee6d-ea33-4156-b6b4-37c2140d7561
[2016-05-03 12:05:17,236] INFO  k.util.ShutdownHookManager [] [akka://JobServer/user/context-supervisor/my-low-latency-context] - Deleting directory /tmp/spark-e41795f9-7be0-44a8-be09-7419aa631e98/userFiles-d3202b49-3bd3-44e1-ab3c-0f7c8d61c359
[2016-05-03 12:05:17,236] INFO  k.util.ShutdownHookManager [] [akka://JobServer/user/context-supervisor/my-low-latency-context] - Deleting directory /tmp/spark-e41795f9-7be0-44a8-be09-7419aa631e98
`

Context (config): 
`my-low-latency-context {
       num-cpu-cores = 1           # Number of cores to allocate.  Required.
       memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, 1G, etc.
     }
`

Don't see anything in logs about not being able to connect to master, so I assume it can connect (otherwise I saw there should be error). 
I run spark standalone with master on the same node as jobserver.

Thanks for any hints

**Comment by velvia** [comment]
See the troubleshooting docs

https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/troubleshooting.md <https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/troubleshooting.md>

You might want to adjust the context-creation-timeout.

**Comment by larghir** [comment]
Thanks for the reply. I did, but I still get:

`[2016-05-04 12:02:17,616] ERROR rkUncaughtExceptionHandler [] [akka://JobServer/user/context-supervisor/my-low-latency-context] - Uncaught exception in thread Thread[appclient-registration-retry-thread,5,main]
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@795e6aa7 rejected from java.util.concurrent.ThreadPoolExecutor@25ac3831[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2048)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:110)
	at org.apache.spark.deploy.client.AppClient$ClientEndpoint$$anonfun$tryRegisterAllMasters$1.apply(AppClient.scala:96)
	at org.apache.spark.deploy.client.AppClient$ClientEndpoint$$anonfun$tryRegisterAllMasters$1.apply(AppClient.scala:95)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:108)
	at org.apache.spark.deploy.client.AppClient$ClientEndpoint.tryRegisterAllMasters(AppClient.scala:95)
	at org.apache.spark.deploy.client.AppClient$ClientEndpoint.org$apache$spark$deploy$client$AppClient$ClientEndpoint$$registerWithMaster(AppClient.scala:121)
	at org.apache.spark.deploy.client.AppClient$ClientEndpoint$$anon$2$$anonfun$run$1.apply$mcV$sp(AppClient.scala:132)
	at org.apache.spark.util.Utils$.tryOrExit(Utils.scala:1119)
	at org.apache.spark.deploy.client.AppClient$ClientEndpoint$$anon$2.run(AppClient.scala:124)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-05-04 12:02:17,625] INFO  k.storage.DiskBlockManager [] [akka://JobServer/user/context-supervisor/my-low-latency-context] - Shutdown hook called
[2016-05-04 12:02:17,628] INFO  k.util.ShutdownHookManager [] [akka://JobServer/user/context-supervisor/my-low-latency-context] - Shutdown hook called
[2016-05-04 12:02:17,629] INFO  k.util.ShutdownHookManager [] [akka://JobServer/user/context-supervisor/my-low-latency-context] - Deleting directory /tmp/spark-f25af88e-9004-4c8c-b83b-17ef6c5656ca/httpd-4ff26a55-28f9-4333-a3d1-6b82a14b1cb3
[2016-05-04 12:02:17,633] INFO  k.util.ShutdownHookManager [] [akka://JobServer/user/context-supervisor/my-low-latency-context] - Deleting directory /tmp/spark-f25af88e-9004-4c8c-b83b-17ef6c5656ca/userFiles-6cf94c46-7930-4b4a-8568-5d506692ec56
[2016-05-04 12:02:17,633] INFO  k.util.ShutdownHookManager [] [akka://JobServer/user/context-supervisor/my-low-latency-context] - Deleting directory /tmp/spark-f25af88e-9004-4c8c-b83b-17ef6c5656c`

**Comment by larghir** [comment]
So it appears from the logs that there is a timeout when the client tries to register with the master (no error connecting to master though, that succeeds).
Is it possible to change the value of registration-timeout (which shows in the effective config as 1s) ?

**Comment by larghir** [comment]
Could it be an incompatibility in the Scala versions? I use Spark 1.5.2 built for Scala 2.11

**Comment by noorul** [comment]
@larghir Are you still facing this issue?

**Comment by noorul** [comment]
Closing this. @larghir Please feel free to re-open this if you still have issues.

**Comment by bjdas** [comment]
@larghir @noorul  I'm seeing same issue with version 0.6.2 and mesos , I have tried pretty much changing _context creation time_  till 120 s, docker _network both HOST/BRIDGE_ . 
I'm able to run standalone as [local] with same image  inside mesos/marathon

**Comment by vasyaod** [comment]
@bjdas Have You resolved the issue? What is the problem?
