### ISSUE TITLE
Can't find __spark_conf__ files with yarn-client, docker, on HDP 2.4 yarn cluster

### ISSUE THREAD

**Issue by seglo** [spark-jobserver/spark-jobserver#465]
I'm having a problem running the jobserver test app with my setup.

I'm using the spark-jobserver docker image to run jobserver.  I followed the yarn setup guide and modified the docker image as instructed.  It looks like the test jar is being submitted to yarn, but I get an error

```
- Application report for application_1463424826707_0015 (state: FAILED)
[2016-05-17 21:33:15,223] INFO  e.spark.deploy.yarn.Client [] [akka://JobServer/user/context-supervisor/f4450686-spark.jobserver.WordCountExample] 
- 
         client token: N/A
         diagnostics: Application application_1463424826707_0015 failed 2 times due to AM Container for appattempt_1463424826707_0015_000002 exited
 with  exitCode: -1000
For more detailed output, check application tracking page:http://ip-10-147-0-22.ec2.internal:8088/cluster/app/application_1463424826707_0015Then, c
lick on links to logs of each attempt.
Diagnostics: File file:/tmp/spark-cbd0f5ec-2eb3-4cf9-bf21-5dbb86169476/__spark_conf__1422283008988134334.zip does not exist
java.io.FileNotFoundException: File file:/tmp/spark-cbd0f5ec-2eb3-4cf9-bf21-5dbb86169476/__spark_conf__1422283008988134334.zip does not exist
        at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:609)
        at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:822)
        at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:599)
        at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:421)
        at org.apache.hadoop.yarn.util.FSDownload.copy(FSDownload.java:253)
        at org.apache.hadoop.yarn.util.FSDownload.access$000(FSDownload.java:63)
        at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:361)
        at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:359)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1709)
        at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:358)
        at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:62)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

```

As indicated, YARN can't find `/tmp/spark-cbd0f5ec-2eb3-4cf9-bf21-5dbb86169476/__spark_conf__1422283008988134334.zip` because it doesn't exist on the local YARN nodemanager the job was running on.  This file exists inside my spark jobserver docker instance.

I think I'm missing config to put this file into HDFS so everything can read it, but I'm not sure what that could be.

**Comment by hntd187** [comment]
Does your docker image have access to hdfs? If so you can tell SJS to save jars to hdfs and then refer to them there. Unless I'm misunderstanding your purpose.

**Comment by seglo** [comment]
Yes, I can access HDFS from docker.  What configuration are you referring to SJS to save jars to HDFS?  And do you that config will also upload this spark conf related file I'm getting an error on?

**Comment by hntd187** [comment]
Also, just curious, but does the user your SJS is running under have the ability to write things to /tmp/ ? otherwise I believe in the configuration you can specify a different location for where to write jars.

**Comment by seglo** [comment]
I'm running SJS within the docker container, so it's running the actual process as root.  It's apparently writing to /tmp.  The trouble is once the job is submitted to YARN outside of the docker, YARN is trying to read from /tmp as well, but the file is not there because it's only inside the docker image.

**Comment by hntd187** [comment]
Your jobserver should in theory push that jar out with it's job when it actually runs that way each instance has it's own copy of it. Are you sure the individual nodes are able to write to their respective tmp directories?

**Comment by seglo** [comment]
Yes, I'm certain.  I can submit jobs fine without jobserver.

This appears to be a configuration problem with the way SJS is working with YARN.

**Comment by stannie42** [comment]
I have a similar issue. Running sjs version 0.6.2 on docker.
But this issue appears on my YARN HDP 2.4 Cluster, 

Diagnostics:	
Application application_1460647304485_0668 failed 2 times due to AM Container for appattempt_1460647304485_0668_000002 exited with exitCode: -1000 due to: File file:/tmp/spark-9e5b4f9b-b4e6-492d-a11f-12c8b9a8d2b6/__spark_conf__4867814115004385855.zip does not exist
.Failing this attempt.. Failing the application.

Any idea ? :/

**Comment by glennmurray** [comment]
I have this issue without docker.  Running SJS 0.6.2 with YARN on CDH5 (Hadoop 2.6).

```
Diagnostics: File file:/tmp/spark-ac99bc43-9eca-4c30-a1cf-666c07500f75/__spark_conf__8841178034360178585.zip does not exist
java.io.FileNotFoundException: File file:/tmp/spark-ac99bc43-9eca-4c30-a1cf-666c07500f75/__spark_conf__8841178034360178585.zip does not exist
        at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:590)
```

Note that the file exists.

```
$ ls -lh /tmp/spark-ac99bc43-9eca-4c30-a1cf-666c07500f75/
total 8.0K
drwxr-xr-x 4 gamurray dba 4.0K Aug 31 13:20 httpd-f36ec81c-9103-4551-af0e-99593ce6c28e/
-rw-r--r-- 1 gamurray dba 2.0K Aug 31 13:20 __spark_conf__8841178034360178585.zip
```

**Comment by noorul** [comment]
Closing this
