### ISSUE TITLE
Plugin for SparkJob?

### ISSUE THREAD

**Issue by mqsoh** [spark-jobserver/spark-jobserver#471]
I tried bundling [one of the Spark examples][] into a jar, but I end up with an error because it doesn't have the SparkJob trait. The SparkJob trait seems to be a spark-jobserver convention and not Spark.

How do I add that dependency? Or must all spark-jobserver jobs be built with spark-jobserver itself?

I'm using the docker image `velvia/spark-jobserver:0.6.2.mesos-0.28.1.spark-1.6.1` with Spark `spark-1.6.1-bin-hadoop2.6-4`.

The error, incidentally:

    java.lang.ClassCastException: samplejob.SparkPi$ cannot be cast to spark.jobserver.SparkJobBase
     at spark.jobserver.JobManagerActor$$anonfun$startJobInternal$1.apply$mcV$sp(JobManagerActor.scala:231)
     at scala.util.control.Breaks.breakable(Breaks.scala:37)
     at spark.jobserver.JobManagerActor.startJobInternal(JobManagerActor.scala:192)
     at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:144)
     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
     at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
     at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)
     at ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)
     at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)
     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
     at ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
     at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
     at ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
     at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
     at akka.actor.ActorCell.invoke(ActorCell.scala:487)
     at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
     at akka.dispatch.Mailbox.run(Mailbox.scala:220)
     at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[one of the Spark examples]: https://github.com/apache/spark/blob/master/examples/src/main/scala/org/apache/spark/examples/SparkPi.scala

**Comment by mqsoh** [comment]
I should also mention that I tested my sample job with [spark-submit][], which is distributed with Spark. I think spark-jobserver should be able to run a job that can be run by Spark itself.

[spark-submit]: https://github.com/apache/spark/blob/master/bin/spark-submit

**Comment by mqsoh** [comment]
Oops. I didn't see this: https://github.com/spark-jobserver/spark-jobserver#create-a-job-server-project
