### ISSUE TITLE
DB h2 issues, The database has been closed

### ISSUE THREAD

**Issue by stannie42** [spark-jobserver/spark-jobserver#497]
Sometimes I am encountering the h2 issue "database has been closed" while trying to GET some info about my Job running. 

I am using the following settings in my conf:
sqldao {
      # Directory where default H2 driver stores its data. Only needed for H2.
      rootdir = /database

      # Full JDBC URL / init string.  Sorry, needs to match above.
      # Substitutions may be used to launch job-server, but leave it out here in the default or tests won't pass
      jdbc.url = "jdbc:h2:file:/database/h2-db"
}

SJS version: 0.6.2
Java version: 1.8.0_91

[2016-06-10 14:04:31,745] ERROR ka.actor.OneForOneStrategy [] [akka://JobServer/user/job-info] - The database has been closed [90098-176]
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.engine.Database.checkPowerOff(Database.java:490)
	at org.h2.command.Command.executeQuery(Command.java:221)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:193)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
	at scala.slick.jdbc.JdbcBackend$SessionDef$LoggingPreparedStatement$$anonfun$execute$5.apply$mcZ$sp(JdbcBackend.scala:329)
	at scala.slick.jdbc.JdbcBackend$SessionDef$LoggingPreparedStatement$$anonfun$execute$5.apply(JdbcBackend.scala:329)
	at scala.slick.jdbc.JdbcBackend$SessionDef$LoggingPreparedStatement$$anonfun$execute$5.apply(JdbcBackend.scala:329)
	at scala.slick.jdbc.JdbcBackend$SessionDef$LoggingStatement.logged(JdbcBackend.scala:264)
	at scala.slick.jdbc.JdbcBackend$SessionDef$LoggingPreparedStatement.execute(JdbcBackend.scala:329)
	at scala.slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
	at scala.slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at scala.slick.jdbc.Invoker$class.foreach(Invoker.scala:64)
	at scala.slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at scala.slick.jdbc.Invoker$class.build(Invoker.scala:47)
	at scala.slick.jdbc.StatementInvoker.build(StatementInvoker.scala:16)
	at scala.slick.jdbc.Invoker$class.list(Invoker.scala:39)
	at scala.slick.jdbc.StatementInvoker.list(StatementInvoker.scala:16)
	at spark.jobserver.io.JobSqlDAO$$anonfun$getJobInfos$1.apply(JobSqlDAO.scala:272)
	at spark.jobserver.io.JobSqlDAO$$anonfun$getJobInfos$1.apply(JobSqlDAO.scala:261)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
	at spark.jobserver.io.JobSqlDAO.getJobInfos(JobSqlDAO.scala:260)
	at spark.jobserver.JobInfoActor$$anonfun$wrappedReceive$1.applyOrElse(JobInfoActor.scala:35)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)
	at ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)
	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by hntd187** [comment]
Does the entire SJS crash? Or does it continue running? Also how are you running this? Are you deploying it or are you running it via reStart?

**Comment by stannie42** [comment]
Entirer SJS crash, It has been via the docker container

**Comment by hntd187** [comment]
How much memory are you giving it? It could be crashing because of lack of ability to hold things in memory.

**Comment by noorul** [comment]
@stannie42 Is this issue recurring?

**Comment by stannie42** [comment]
thanks for the replies, I am now using the postgres driver so I am not anymore affected by this issue.

**Comment by noorul** [comment]
Closing this issue.

**Comment by marcoboi** [comment]
I've encountered the same issue, also using the H2 database.
Switching to a different database is not a solution for me.
@noorul, you mentioned the issue could be due to the database not having access to sufficient memory. Could you be a little more specific? 
* Are you referring to disk space or RAM memory?
* I had a look at the H2 database settings and found no mention of memory settings. Which parameters should I look into?

**Comment by noorul** [comment]
@marcoboi I don't remember mentioning that it could be because of memory. Btw, which version are you using?

**Comment by marcoboi** [comment]
@noorul , you mean _SJS_ version? I'm on 0.8.0, master, cfc0c2db59a35aef2669a6df4b84bd9cea031f36.
