### ISSUE TITLE
got java.lang.NoClassDefFoundError: org/apache/spark/SparkContext

### ISSUE THREAD

**Issue by larryzhao** [spark-jobserver/spark-jobserver#499]
I am trying out to run `spark-jobserver` locally. 

I pull the code and run `sbt reStart` after selecting a listed job, I got the following error, I am running on Mac Yosemite, with spark 1.6.1 installed by Homebrew and sbt 0.13.11. How could I fix this and start jobserver on my machine?

Thank you very much.

```
job-server Starting spark.jobserver.JobServer.main()
job-server[ERROR] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
job-server-tests[ERROR] Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/SparkContext
job-server-tests[ERROR] 	at java.lang.Class.getDeclaredMethods0(Native Method)
job-server-tests[ERROR] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
job-server-tests[ERROR] 	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
job-server-tests[ERROR] 	at java.lang.Class.getMethod0(Class.java:3010)
job-server-tests[ERROR] 	at java.lang.Class.getMethod(Class.java:1776)
job-server-tests[ERROR] 	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
job-server-tests[ERROR] 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
job-server-tests[ERROR] Caused by: java.lang.ClassNotFoundException: org.apache.spark.SparkContext
job-server-tests[ERROR] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
job-server-tests[ERROR] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
job-server-tests[ERROR] 	at java.security.AccessController.doPrivileged(Native Method)
job-server-tests[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
job-server-tests[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
job-server-tests[ERROR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
job-server-tests[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
job-server-tests[ERROR] 	... 7 more
job-server-tests ... finished with exit code 1
[info] Application job-server-extras not yet started
[info] Starting application job-server-extras in the background ...
job-server-extras Starting spark.jobserver.JobServer.main()
job-server-extras[ERROR] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
job-server[ERROR] log4j:WARN No appenders could be found for logger (spark.jobserver.JobServer$).
job-server[ERROR] log4j:WARN Please initialize the log4j system properly.
job-server[ERROR] log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
job-server-extras[ERROR] log4j:WARN No appenders could be found for logger (spark.jobserver.JobServer$).
job-server-extras[ERROR] log4j:WARN Please initialize the log4j system properly.
job-server-extras[ERROR] log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[info] Done updating.
[info] scalastyle using config /Users/Larry/Westeros/spark-jobserver/scalastyle-config.xml
[info] Processed 35 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 1 ms
[success] created output: /Users/Larry/Westeros/spark-jobserver/job-server/target
[info] scalastyle using config /Users/Larry/Westeros/spark-jobserver/scalastyle-config.xml
[info] Processed 11 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 0 ms
[success] created output: /Users/Larry/Westeros/spark-jobserver/akka-app/target
[info] scalastyle using config /Users/Larry/Westeros/spark-jobserver/scalastyle-config.xml
[info] Processed 13 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 1 ms
[success] created output: /Users/Larry/Westeros/spark-jobserver/job-server-extras/target
[info] scalastyle using config /Users/Larry/Westeros/spark-jobserver/scalastyle-config.xml
[info] Processed 5 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 1 ms
[success] created output: /Users/Larry/Westeros/spark-jobserver/job-server-api/target
[info] Application root not yet started
java.lang.RuntimeException: No main class detected!
	at scala.sys.package$.error(package.scala:27)
	at spray.revolver.Actions$$anonfun$1.apply(Actions.scala:37)
	at spray.revolver.Actions$$anonfun$1.apply(Actions.scala:37)
	at scala.Option.getOrElse(Option.scala:120)
	at spray.revolver.Actions$.startApp(Actions.scala:37)
	at spray.revolver.Actions$.restartApp(Actions.scala:29)
	at spray.revolver.RevolverPlugin$$anonfun$settings$2$$anonfun$apply$1.apply(RevolverPlugin.scala:51)
	at spray.revolver.RevolverPlugin$$anonfun$settings$2$$anonfun$apply$1.apply(RevolverPlugin.scala:51)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: No main class detected!
	at scala.sys.package$.error(package.scala:27)
	at spray.revolver.Actions$$anonfun$1.apply(Actions.scala:37)
	at spray.revolver.Actions$$anonfun$1.apply(Actions.scala:37)
	at scala.Option.getOrElse(Option.scala:120)
	at spray.revolver.Actions$.startApp(Actions.scala:37)
	at spray.revolver.Actions$.restartApp(Actions.scala:29)
	at spray.revolver.RevolverPlugin$$anonfun$settings$2$$anonfun$apply$1.apply(RevolverPlugin.scala:51)
	at spray.revolver.RevolverPlugin$$anonfun$settings$2$$anonfun$apply$1.apply(RevolverPlugin.scala:51)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: No main class detected!
	at scala.sys.package$.error(package.scala:27)
	at spray.revolver.Actions$$anonfun$1.apply(Actions.scala:37)
	at spray.revolver.Actions$$anonfun$1.apply(Actions.scala:37)
	at scala.Option.getOrElse(Option.scala:120)
	at spray.revolver.Actions$.startApp(Actions.scala:37)
	at spray.revolver.Actions$.restartApp(Actions.scala:29)
	at spray.revolver.RevolverPlugin$$anonfun$settings$2$$anonfun$apply$1.apply(RevolverPlugin.scala:51)
	at spray.revolver.RevolverPlugin$$anonfun$settings$2$$anonfun$apply$1.apply(RevolverPlugin.scala:51)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (root/*:reStart) No main class detected!
[error] (job-server-api/*:reStart) No main class detected!
[error] (akka-app/*:reStart) No main class detected!
[error] Total time: 256 s, completed Jun 12, 2016 10:14:37 PM
job-server-extras ... killing ...
job-server ... killing ...
```

**Comment by noorul** [comment]
Do not run 'sbt reStart' from shell. Load sbt first and from sbt prompt run 'job-server/reStart'

See the documentation.

**Comment by larryzhao** [comment]
@noorul Thank you very much. Sorry for my ignorance, I think I've misunderstood it for a time.

**Comment by noorul** [comment]
If job-server/reStart worked for you, shall we close this issue?

**Comment by larryzhao** [comment]
@noorul Sure, thanks again.
