### ISSUE TITLE
Spark Job Server not accepting 10th streaming job after 9 jobs deployed and in running state

### ISSUE THREAD

**Issue by kishorez** [spark-jobserver/spark-jobserver#533]
We ran into following address binding exception after submitting 9 jobs successfully and running.

Spark Job server not able to create a new spark context after 9 contexts are created. 

Environment - Yarn, Spark 1.6, Scala 2.10.6, ContextPerJVM is enabled

[2016-06-29 00:54:05,323] INFO  Cluster(akka://JobServer) [] [Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:34085] - Leader can currently not perform its duties, reachability status: [akka.tcp://JobServer@127.0.0.1:34745 -> akka.tcp://JobServer@127.0.0.1:58589: Unreachable [Unreachable](2), akka.tcp://JobServer@127.0.0.1:38139 -> akka.tcp://JobServer@127.0.0.1:58589: Unreachable [Unreachable](3), akka.tcp://JobServer@127.0.0.1:41299 -> akka.tcp://JobServer@127.0.0.1:58589: Unreachable [Unreachable](3), akka.tcp://JobServer@127.0.0.1:48074 -> akka.tcp://JobServer@127.0.0.1:58589: Unreachable [Unreachable](3), akka.tcp://JobServer@127.0.0.1:60912 -> akka.tcp://JobServer@127.0.0.1:58589: Unreachable [Unreachable](1)], member status: [akka.tcp://JobServer@127.0.0.1:34085 Up seen=true, akka.tcp://JobServer@127.0.0.1:34745 Up seen=true, akka.tcp://JobServer@127.0.0.1:35773 Up seen=true, akka.tcp://JobServer@127.0.0.1:38139 Up seen=true, akka.tcp://JobServer@127.0.0.1:41299 Up seen=true, akka.tcp://JobServer@127.0.0.1:47528 Up seen=true, akka.tcp://JobServer@127.0.0.1:48074 Up seen=true, akka.tcp://JobServer@127.0.0.1:51443 Up seen=true, akka.tcp://JobServer@127.0.0.1:52303 Up seen=true, akka.tcp://JobServer@127.0.0.1:54885 Joining seen=true, akka.tcp://JobServer@127.0.0.1:58589 Up seen=false, akka.tcp://JobServer@127.0.0.1:60912 Up seen=true]
[2016-06-29 00:54:06,343] INFO  Cluster(akka://JobServer) [] [Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:34085] - Leader is auto-downing unreachable node [akka.tcp://JobServer@127.0.0.1:58589]
[2016-06-29 00:54:06,343] INFO  Cluster(akka://JobServer) [] [Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:34085] - Marking unreachable node [akka.tcp://JobServer@127.0.0.1:58589] as [Down]
[2016-06-29 00:54:10,332] INFO  Cluster(akka://JobServer) [] [Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:34085] - Leader can perform its duties again
[2016-06-29 00:54:10,333] INFO  Cluster(akka://JobServer) [] [Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:34085] - Leader is moving node [akka.tcp://JobServer@127.0.0.1:54885] to [Up]
[2016-06-29 00:54:10,333] INFO  Cluster(akka://JobServer) [] [Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:34085] - Leader is removing unreachable node [akka.tcp://JobServer@127.0.0.1:58589]
[2016-06-29 00:54:10,356] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Received identify response, attempting to initialize context at akka.tcp://JobServer@127.0.0.1:54885/user/*
[2016-06-29 00:54:11,160] INFO  AkkaClusterSupervisorActor [] [] - Failed to initialize context Actor[akka.tcp://JobServer@127.0.0.1:54885/user/jobManager-5b-891b-859f23f0a14d#1261055084]
java.net.BindException: Address already in use: Service 'sparkDriver' failed after 16 retries!
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:433)
    at sun.nio.ch.Net.bind(Net.java:425)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:485)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1089)
    at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:430)
    at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:415)
    at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:903)
    at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:198)
    at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadE

**Comment by zeitos** [comment]
those were 9 parallel jobs?

Did you use the same context for all of them or you are trying to create 9 contexts?

**Comment by kishorez** [comment]
Yes they are running in parallel. It is not same context

Using Spark Job Server jobs rest endpoint I have created a job and SJS internally created different spark context for each job.

**Comment by kishorez** [comment]
Anyone experienced this issue ?

**Comment by zeitos** [comment]
:( never happened to me but I only use 3 contexts and run jobs on them.

**Comment by kishorez** [comment]
We were able to tune it to support upto 35 jobs with our resource settings. But looks like running the jobs in client mode will always be a bottle neck to support streaming jobs in large scale. Is there a roadmap to support cluster mode in future ?

**Comment by noorul** [comment]
@kishorez I have done some work to support cluster mode. I am in the process of submitting PRs related to this.

**Comment by noorul** [comment]
Closing

**Comment by pawantlor** [comment]
@kishorez Could you please provide the resource setting you did for this problem. We are also facing same issue.
