### ISSUE TITLE
Accept error: could not accept new connection java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by liu-hongwei** [spark-jobserver/spark-jobserver#55]
hi,

i saw tons of below errors on spark job server when my app sent multi requests to the server.

is this a bug? how to fix it?

[2015-01-27 16:40:59,292] ERROR akka.io.TcpListener [] [akka://JobServer/system/IO-TCP/selectors/$a/0] - Accept error: could not accept new connection
java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:241)
        at akka.io.TcpListener.acceptAllPending(TcpListener.scala:96)
        at akka.io.TcpListener$$anonfun$bound$1.applyOrElse(TcpListener.scala:76)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
        at akka.actor.ActorCell.invoke(ActorCell.scala:456)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by velvia** [comment]
Hi @liu-hongwei, sorry for the long response.  You may wish to try the Spray I/O mailing lists.  I must say, though, that you may need to put a queue in front of the job server, to be honest Spark itself is not really designed for huge concurrency scenario.

**Comment by hntd187** [comment]
Closing this issue because of age, if you are still having problems give the latest code a try and open a new issue. Thanks.
