### ISSUE TITLE
$.validate error

### ISSUE THREAD

**Issue by ChenZhaobin** [spark-jobserver/spark-jobserver#582]
when I go along with the example ,everything is ok.
but when I create a new project , after assembling a fat jar ,even with the save code as  spark-jobserver-test, it comes exception just show below :
```
[ERROR] Exception in thread "pool-1-thread-1" java.lang.AbstractMethodError: spark.jobserver.WordCountExample$.validate(Ljava/lang/Object;Lspark/jobserver/api/JobEnvironment;Lcom/typesafe/config/Config;)Lorg/scalactic/Or;
job-server-extras[ERROR] 	at spark.jobserver.JobManagerActor$$anonfun$getJobFuture$4.apply(JobManagerActor.scala:279)
job-server-extras[ERROR] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
job-server-extras[ERROR] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
job-server-extras[ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
job-server-extras[ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
job-server-extras[ERROR] 	at java.lang.Thread.run(Thread.java:745)

```
My build.sbt code 
```
name := "ChenZhaobin.SparkMLlib"
version := "1.0"
scalaVersion := "2.11.8"
val sparkVersion = "1.6.2"
val excludeScalaTest = ExclusionRule(organization = "org.scalatest")
val excludeNettyIo = ExclusionRule(organization = "io.netty", artifact = "netty-all")
val excludeQQ = ExclusionRule(organization = "org.scalamacros")
resolvers ++= Seq(
  "apache-snapshots" at "http://repository.apache.org/snapshots/"
)
libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-mllib" % sparkVersion % "provided" excludeAll(excludeNettyIo, excludeQQ),
  "org.apache.spark" %% "spark-sql" % sparkVersion % "provided" excludeAll(excludeNettyIo, excludeQQ),
  "org.apache.spark" %% "spark-streaming" % sparkVersion % "provided" excludeAll(excludeNettyIo, excludeQQ),
  "org.apache.spark" %% "spark-hive" % sparkVersion % "provided" excludeAll(excludeNettyIo, excludeQQ, excludeScalaTest)
)
resolvers += "Job Server Bintray" at "https://dl.bintray.com/spark-jobserver/maven"
libraryDependencies += "spark.jobserver" %% "job-server-api" % "0.6.2" % "provided"
libraryDependencies += "com.owlike" % "genson-scala_2.10" % "1.4"
libraryDependencies += "spark.jobserver" %% "job-server-extras" % "0.6.2" % "provided"


assemblyMergeStrategy in assembly := {
  case PathList("META-INF", xs @ _*) => MergeStrategy.discard
  case x => MergeStrategy.first
}
    
```

**Comment by ChenZhaobin** [comment]
solved by using  the released version0.6.2 package
