### ISSUE TITLE
Python Jobs sometimes lose jobContext

### ISSUE THREAD

**Issue by CalebFenton** [spark-jobserver/spark-jobserver#586]
The exception is here:
```
[2016-09-08 15:13:28,365] ERROR .jobserver.JobManagerActor [] [] - About to restart actor due to exception:
java.lang.NullPointerException
       	at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:166)
       	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
       	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
       	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
       	at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
       	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
       	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
       	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
       	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
       	at ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)
       	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)
       	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
       	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
       	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
       	at ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)
       	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
       	at ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
       	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
       	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
       	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
       	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
       	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
       	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
       	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
       	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
       	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Afterwards is a similar error, partially truncated is:
```
[2016-09-08 15:25:14,210] ERROR ka.actor.OneForOneStrategy [] [akka://JobServer/user/context-supervisor/scala-ctx] -
java.lang.NullPointerException
       	at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:166)
       	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
       	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
       	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
       	at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
       	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
       	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
       	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
       	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
```

The line with the error is [`spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:166)`](https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/spark.jobserver/JobManagerActor.scala#L166)

The line is:
```scala
if (jobContext.sparkContext == null)
```

Since it's a NPE, I'm guessing that jobContext is null for some reason. This causes almost all of my python jobs to fail, so I'm going to try and figure it out. If you have any clues, please let me know.

**Comment by CalebFenton** [comment]
I think it has something to do with a 3 second timeout being hit, which seems to confuse the state of jobserver so it loses track of the context. I'm sorry I don't have time to dig into it more. I simply adjusted this line here: https://github.com/ooyala/spark-jobserver/issues/120 to be 20 seconds instead of 3. Sometimes my cluster is a little slow.

**Comment by noorul** [comment]
@CalebFenton Were you able to fix this?

**Comment by CalebFenton** [comment]
For the record, was never able to fix. I just used a work around.
