### ISSUE TITLE
use park-jobserver 0.6.2 to run in cloudera spark 1.6.0 

### ISSUE THREAD

**Issue by mahuichao** [spark-jobserver/spark-jobserver#592]
I got this error:
Exception in thread "main" java.lang.NoSuchMethodError: akka.util.Helpers$.ConfigOps(Lcom/typesafe/config/Config;)Lcom/typesafe/config/Config;
    at akka.cluster.ClusterSettings.<init>(ClusterSettings.scala:28)
    at akka.cluster.Cluster.<init>(Cluster.scala:67)
    at akka.cluster.Cluster$.createExtension(Cluster.scala:42)
    at akka.cluster.Cluster$.createExtension(Cluster.scala:37)
    at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:654)
    at akka.actor.ExtensionId$class.apply(Extension.scala:79)
    at akka.cluster.Cluster$.apply(Cluster.scala:37)
    at akka.cluster.ClusterActorRefProvider.createRemoteWatcher(ClusterActorRefProvider.scala:66)
    at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:186)
    at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:58)
    at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:579)
    at akka.actor.ActorSystemImpl._start(ActorSystem.scala:577)
    at akka.actor.ActorSystemImpl.start(ActorSystem.scala:588)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:111)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:104)
    at spark.jobserver.JobServer$.spark$jobserver$JobServer$$makeSupervisorSystem$1(JobServer.scala:128)
    at spark.jobserver.JobServer$$anonfun$main$1.apply(JobServer.scala:130)
    at spark.jobserver.JobServer$$anonfun$main$1.apply(JobServer.scala:130)
    at spark.jobserver.JobServer$.start(JobServer.scala:54)
    at spark.jobserver.JobServer$.main(JobServer.scala:130)
    at spark.jobserver.JobServer.main(JobServer.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)__

here is my local.conf:
spark {
  # spark.master will be passed to each job's JobContext
  master = "yarn-client"
  # master = "mesos://vm28-hulk-pub:5050"
  # master = "yarn-client"

  # Default # of CPUs for jobs to use for Spark standalone cluster
  job-number-cpus = 4

  jobserver {
    port = 8090
    jar-store-rootdir = /usr/local/job-server/jars

```
context-per-jvm = false

jobdao = spark.jobserver.io.JobFileDAO

filedao {
  rootdir = /usr/local/job-server/filedao
}

# When using chunked transfer encoding with scala Stream job results, this is the size of each chunk
result-chunk-size = 1m
```

  }

  # predefined Spark contexts
  # contexts {
  #   my-low-latency-context {
  #     num-cpu-cores = 1           # Number of cores to allocate.  Required.
  #     memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, 1G, etc.
  #   }
  #   # define additional contexts here
  # }

  # universal context configuration.  These settings can be overridden, see README.md
  context-settings {
    num-cpu-cores = 2           # Number of cores to allocate.  Required.
    memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, #1G, etc.
    spark.dirver.port=32456
    spark.yarn.jar="/opt/cloudera/parcels/CDH/lib/spark/assembly/lib/spark-assembly-1.6.0-cdh5.8.0-hadoop2.6.0-cdh5.8.0.jar"
    # in case spark distribution should be accessed from HDFS (as opposed to being installed on every mesos slave)
    # spark.executor.uri = "hdfs://namenode:8020/apps/spark/spark.tgz"

```
# uris of jars to be loaded into the classpath for this context. Uris is a string list, or a string separated by commas ','
# dependent-jar-uris = ["file:///some/path/present/in/each/mesos/slave/somepackage.jar"]

# If you wish to pass any settings directly to the sparkConf as-is, add them here in passthrough,
# such as hadoop connection settings that don't use the "spark." prefix
passthrough {
  #es.nodes = "192.1.1.1"
}
```

  }

  # This needs to match SPARK_HOME for cluster SparkContexts to be created successfully
  # home = "/home/spark/spark"
}
# Note that you can use this file to define settings not only for job server,
# but for your Spark jobs as well.  Spark job configuration merges with this configuration file as defaults.

akka {
  remote.netty.tcp {
    # This controls the maximum message size, including job results, that can be sent
    # maximum-frame-size = 10 MiB
  }
}
and here is my settings.sh:
# Environment and deploy file
# For use with bin/server_deploy, bin/server_package etc.

DEPLOY_HOSTS="114.55.230.225"

APP_USER=root
APP_GROUP=root
# optional SSH Key to login to deploy server
# SSH_KEY=/path/to/keyfile.pem

INSTALL_DIR=/usr/local/job-server
LOG_DIR=/usr/local/job-server/logs
PIDFILE=spark-jobserver.pid
JOBSERVER_MEMORY=512m
SPARK_VERSION=1.6.0
MAX_DIRECT_MEMORY=512M
SPARK_HOME=/opt/cloudera/parcels/CDH-5.8.0-1.cdh5.8.0.p0.42/lib/spark
SPARK_CONF_DIR=/etc/spark/conf
# Only needed for Mesos deploys
# SPARK_EXECUTOR_URI=/home/spark/spark-1.6.0.tar.gz
# Only needed for YARN running outside of the cluster
# You will need to COPY these files from your cluster to the remote machine
# Normally these are kept on the cluster in /etc/hadoop/conf
# YARN_CONF_DIR=/pathToRemoteConf/conf
# HADOOP_CONF_DIR=/pathToRemoteConf/conf
# Also optional: extra JVM args for spark-submit
# export SPARK_SUBMIT_OPTS+="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5433"

SCALA_VERSION=2.10.5 # or 2.11.6

anyone know why this happened?

**Comment by shashwat7** [comment]
I am facing the same issue. Did you got any lead?

I read on some other post that it might be due to akka version mismatch in Cloudera and Spark-JobServer.

**Comment by mahuichao** [comment]
you are right,it seems due to akka version mismatch,and i make a test with my own standalone cluster: 
Spark	Sjs	    Result
1.6.0  	0.6.2	false
1.6.0	       0.6.1	        false
1.6.1	       0.6.2	        True
1.6.1	       0.6.1	                false
so I think,spark-jobserver must run with the corresponding spark version,If the version of spark is higher than sjs,you can not initialize sc correctly,if the version of sjs is higher than spark,I got the problem above,This is just a testing,just my views。hoping it can help you.

**Comment by koettert** [comment]
Hi,
have a look at [Bjoerns repository](https://github.com/bjoernlohrmann/spark-jobserver/tree/0.6.2-KNIME_cdh-5.7) which is the adapted 0.6.2 branch that works with Cloudera CDH 5.7. There you will also find builds for other Cloudera versions.
If you want to you can also download a ready to use build of the job server for different Cloudera and Hortonworks distributions from our [homepage](https://www.knime.org/knime-spark-executor#install). Just open the "For KNIME Analytics Platform 3.2 and KNIME Server 4.3" section.
Bye
Tobias

**Comment by mahuichao** [comment]
@koettert Thanx,I will have a look of it ,very appreciate.

**Comment by velvia** [comment]
Tobias, would you mind if we posted this link somewhere?   It’s not direct link to job server build, but your platform, but perhaps it might help some folks.

**Comment by koettert** [comment]
@velvia you are welcome to post the link in the job server repository if you want to

**Comment by noorul** [comment]
Closing this!
