### ISSUE TITLE
 server was not able to produce a timely response to your request

### ISSUE THREAD

**Issue by CocoaWang** [spark-jobserver/spark-jobserver#602]
# #Reproduce

   1) sbt assembly 
            this process package scala files into jar 
  2) curl -X DELETE http://172.16.27.126:8090/contexts/testbaidu-context
           delete the context  if exists 
  3) sleep 2 && curl --data-binary @target/scala-2.10/sentiment-jar-assembly-1.0.jar http://172.16.27.126:8090/jars/testbaidu
             this process send the jar file to jobserver 
  4 ) sleep 10 && curl -d "" "http://172.16.27.126:8090/contexts/testbaidu-context?context-factory=spark.jobserver.context.SQLContextFactory"
             this process I create a spark context 
# In the process 4   I met this problem. And the log  is as follows :

 16/09/21 22:44:53 ERROR LocalContextSupervisorActor: Exception after sending Initialize to JobManagerActor
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://JobServer/user/context-supervisor/testbaidu-context#-1445061667]] after [15000 ms]
        at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)
        at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
        at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)
        at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
        at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
        at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
        at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
        at java.lang.Thread.run(Thread.java:785)
16/09/21 22:44:53 INFO RemoteActorRefProvider$RemoteDeadLetterActorRef: Message [spark.jobserver.ContextSupervisor$ContextInitError] from Actor[akka://JobServer/user/context-supervisor#-1236925279] to Actor[akka://JobServer/deadLetters] was not delivered. [5] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

**Comment by CocoaWang** [comment]
I am using the master branch and spark version is  spark-dk-1.6.2.1  from IBM

**Comment by CocoaWang** [comment]
@hntd187

**Comment by hntd187** [comment]
The extras jar is in the assembly correct? Since you are using an SQLContext

**Comment by CocoaWang** [comment]
@hntd187  Sorry,extras jar means the downloaded jars When I run sbt assembly ?   It seems I have some test errors when running sbt assembly.

**Comment by velvia** [comment]
Try sbt job-server-extras/assembly

**Comment by CocoaWang** [comment]
@hntd187   I replace " sbt assembly"   with "sbt job-server-extras/assembly" ,but I still get the error.

**Comment by CocoaWang** [comment]
I am using spark-jobserver with docker. By compiling  the source code

**Comment by noorul** [comment]
Closing this issue because of inactivity.
