### ISSUE TITLE
spark-jobserver on spark cluster 

### ISSUE THREAD

**Issue by gavishal** [spark-jobserver/spark-jobserver#609]
I am trying to run spark-jobserver with spark as cluster (one master, two workers). I could see some statement on the consoles of master and worker, but the task is getting failed with the following error in the job-server-local.log

[2016-09-26 13:38:36,039] INFO  ocalContextSupervisorActor [] [] - SparkContext 877cbbe0-com.sti.demo.spark.JavaWordCount initialized
[2016-09-26 13:38:36,042] INFO  t.AppClient$ClientEndpoint [] [akka://JobServer/user/context-supervisor/877cbbe0-com.sti.demo.spark.JavaWordCount] - Executor updated: app-20160926133835-0000/0 is now RUNNING
[2016-09-26 13:38:36,048] INFO  t.AppClient$ClientEndpoint [] [akka://JobServer/user/context-supervisor/877cbbe0-com.sti.demo.spark.JavaWordCount] - Executor updated: app-20160926133835-0000/1 is now RUNNING
[2016-09-26 13:38:39,062] ERROR ka.actor.OneForOneStrategy [] [akka://JobServer/user/context-supervisor/877cbbe0-com.sti.demo.spark.JavaWordCount] - Futures timed out after [3 seconds]
java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169)
	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:167)
	at scala.concurrent.Await$.result(package.scala:107)
	at spark.jobserver.JobManagerActor.startJobInternal(JobManagerActor.scala:219)
	at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:157)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
	at ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)
	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

My configuration in local.conf

spark {
  # spark.master will be passed to each job's JobContext
  spark.master = "spark://10.10.10.112:7077"
  master = "spark://10.10.10.112:7077"

other changes are untouched in local.conf

I am passing the following parameters while starting jobServer: 
job-server/reStart ---  -Dspark.master="spark://10.10.10.112:7077"  -Dspark.jobserver.port=8090 

After I started getting the above error, tried changing the parameters as follows, but in vain:

job-server/reStart ---  -Dspark.master="spark://10.10.10.112:7077"  -Dspark.jobserver.port=8090 -Dspray.can.server.idle-timeout = 100 s -Dspray.can.server.request-timeout = 80 s   -Dspray.can.server.parsing.max-content-length = 200m

**Comment by gavishal** [comment]
I am using the following : 

Spark Version on which cluster is running - 1.6.0
Got the latest spark-jobserver from git and run using job-server/reStart with parameters as mentioned in the last post.

Thanks,
Vishal

**Comment by velvia** [comment]
If you are running against a real cluster I highly recommend you deploy job server first.  You can deploy and run locally using bin/server_package.sh.

**Comment by gavishal** [comment]
Thanks for the comment, Evan. I was able to package the job-server and used server_start.sh to start the job-server on spark cluster. Could you please address the below queries.
1. I am basically writing my applications in java. Does spark-jobserver support sharing RDD created in a context, across multiple application running on same context. Didnt find any sample which could guide me. Any pointers?
2. Also I am looking for HiveContext support in Java for spark-jobserver. Didn't find any help on this too. Any help or API on this.

Thanks,
Vishal

**Comment by velvia** [comment]
HI Vishal,

So JobServer NamedObjects is just designed for sharing RDDs amongst jobs running within the same context.  That is the paradigm we support.  For across contexts, you need something like HDFS or Tachyon.

For Java support, some new APIs are on their way that will help with this.  For now getting HiveContext support will not be easy in Java.

-Evan

**Comment by gavishal** [comment]
Hi Evan,

As suggested by you, I am trying to use NamedObjects to achieve sharing of RDDs in the same context. In one of the application I have the below code, where I want to cache a RDD and use it in another application. But I am facing few implementation issues. If I add 'implements NamedObjects' to my class, it is asking to add 'unimplemented methods'. 

//ERROR: The type CSVToMemory must implement the inherited abstract method NamedObjects.update(String, Function0<O>, Timeout, NamedObjectPersister<O>)

`public class CSVToMemory extends JavaSparkJob implements NamedObjects{

	static NamedObjectPersister<NamedRDD<RDD>> rddPersister = new RDDPersister<RDD>();

	public Object runJob(JavaSparkContext jsc, Config config) {
		try {
			JavaRDD<String> lines = jsc.textFile("/home/csv_files/GasMeters.csv", 1);
			
			RDD<String> rddR = JavaRDD.toRDD(lines); 
			
			Function0 func = new Function0() {
	            public NamedObject apply() {
	                return (NamedObject) (new NamedRDD(rddR, true,StorageLevel.MEMORY_AND_DISK()));
	            }

				@Override
				public Object call() throws Exception {
					// TODO Auto-generated method stub
					return null;
				}
			};
			
			NamedRDD nRDD = new NamedRDD(rddR, true, StorageLevel.MEMORY_AND_DISK());
                        //error on this line
			this.update("csv-rdd", func, this.defaultTimeout(), rddPersister);
			
			return "success";
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
	}
}
`

I was assuming once I add 'implement NamedObjects', I can use the below line to cache RDD.
this.namedObjects().update("csv-rdd",nRDD );

Am I missing something?

Thanks,
Vishal

**Comment by velvia** [comment]
Hi Vishal,

You need to extend NamedObjectSupport instead.  

If you are on master and you using JavaSparkJob then you should have a class member called namedObjects.  You should not need to implement NamedObjects at all.

-Evan

**Comment by gavishal** [comment]
Hi Evan,

I am not able to extend **NamedObjectSupport** in my **Java** program directly, because the error says **NamedObjectSupport** is an interface, which I should implement rather than extend.

After adding the below wrapper for **NamedObjectSupport**, was to be able to extend in Java
`class NamedObjectSupportWrapper extends NamedObjectSupport`

Now my **Java** program looks like below.

```
public class CSVToMemory extends NamedObjectSupportWrapper {

	public Object runJob(JavaSparkContext jsc, Config config) {
		NamedObjectPersister<NamedRDD<NamedObject>> rddPersister = new RDDPersister<NamedObject>();
		SparkContext sc = JavaSparkContext.toSparkContext(jsc);
		try {

			JavaRDD<String> lines = jsc.textFile(
					"/home/csv_files/GasMeters.csv", 1);

			RDD<String> rddR = JavaRDD.toRDD(lines); 

			Function0<NamedObject> func = new Function0<NamedObject>() {

				@Override
				public NamedObject call() throws Exception {
					return (NamedObject) (new NamedRDD(rddR, true,StorageLevel.MEMORY_AND_DISK()));
				}
			};
			
// ERROR HERE - The method update(String, Function0<O>, Timeout, NamedObjectPersister<O>) in //the type NamedObjects is not applicable for the arguments (String, Function0<NamedObject>, //Timeout, NamedObjectPersister<NamedRDD<NamedObject>>)

			this.namedObjects().update("hello", func, this.namedObjects().defaultTimeout(), rddPersister);

			return "SUCCESS";
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
	}
}
```
1. I am getting compilation error at the line as mentioned in the code. Any comments why its not taking func with Function0<NamedObject> as correct parameter. What should be the datatype of Function0?
2. Does sharing RDDs in the same context is tested/works in Java? If so, could you please point to any of the implementation details/person.

Thanks,
Vishal

**Comment by velvia** [comment]
Hi Vishal,

I’m sorry but I think it might really be better to wait for @htnd187 ’s new Java API…..   @htnd187 what do you think?

**Comment by gavishal** [comment]
Hi Evan,

Thanks for the response. On a different note, once I submit the job as .jar on a spark-jobserver and store some final result in a RDD or a dataframe, what are the different ways, I can fetch this from my application. Any ideas outside of spark-jobserver would also be helpful.

Thanks,
Vishal

**Comment by velvia** [comment]
In SJS, your app can submit a job query to query your cached DataFrame or RDD and get results back via JSON.

There are obviously many other ways to do this - store it to a database, to HDFS, to Alluxio…. the means are too many :)

**Comment by Ccxlp** [comment]
@velvia  
Can I use the namedobject feature of jobserver in a Java project now???
