### ISSUE TITLE
What does this exception mean?

### ISSUE THREAD

**Issue by cgeorge-rms** [spark-jobserver/spark-jobserver#611]
We got the following exception then our persistent context died. Any idea what would cause this?

[2016-09-26 23:21:01,300] ERROR .jobserver.JobManagerActor [] [] - About to restart actor due to exception:
java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
       	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
       	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
       	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
       	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169)
       	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
       	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:167)
       	at scala.concurrent.Await$.result(package.scala:190)
       	at spark.jobserver.JobManagerActor$$anonfun$startJobInternal$1.apply$mcV$sp(JobManagerActor.scala:200)
       	at scala.util.control.Breaks.breakable(Breaks.scala:38)
       	at spark.jobserver.JobManagerActor.startJobInternal(JobManagerActor.scala:192)
       	at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:144)
       	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
       	at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
       	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
       	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)
       	at ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)
       	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)
       	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
       	at ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
       	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
       	at ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
       	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
       	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
       	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
       	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
       	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
       	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
       	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
       	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
       	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[2016-09-26 23:21:01,301] ERROR ka.actor.OneForOneStrategy [] [akka://JobServer/user/jobManager-44-b920-143805c679de] - Futures timed out after [3 seconds]
java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
       	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
       	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
       	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
       	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169)
       	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
       	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:167)
       	at scala.concurrent.Await$.result(package.scala:190)
       	at spark.jobserver.JobManagerActor$$anonfun$startJobInternal$1.apply$mcV$sp(JobManagerActor.scala:200)
       	at scala.util.control.Breaks.breakable(Breaks.scala:38)
       	at spark.jobserver.JobManagerActor.startJobInternal(JobManagerActor.scala:192)
       	at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:144)
       	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
       	at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
       	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
       	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)
       	at ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)
       	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)
       	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
       	at ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
       	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
       	at ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
       	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
       	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
       	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
       	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
       	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
       	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
       	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
       	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
       	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[2016-09-26 23:21:01,302] INFO  .jobserver.JobManagerActor [] [] - Shutting down SparkContext sql-context-1

**Comment by hntd187** [comment]
It looks like an akka ask timed out while asking another actor for a response to something, I'm not sure what would cause this other than some persistence source like a DB or something no longer being available and thus the request to it timing out. But I'm purely speculating.

**Comment by barrybecker4** [comment]
We started getting this same error after moving to the latest spark-jobserver SNAPSHOT and upgrading to spark 1.6.3. It happens when we have a lot of (simulated) users (about 40 of them) all submitting job server requests at the same time. Please consider reopening this as I think it may be a regression. We ran this exact same test a month ago (before upgrading) and it worked. Possibly related is the fact that we are seeing spark processing slow over time. We are accessing the filesystem directly and not using a db.
` [2016-11-28 13:36:52,654] ERROR .jobserver.JobManagerActor [] [] - About to restart actor due to exception:
java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169)
`

**Comment by velvia** [comment]
This exception indicates a general slowdown in the system.  Is GC pressure a problem?   You will get more exceptions but the job server should be able to recover when the load lightens.  Alternatively, it might be possible to increase the timeout. 

Have you considered using a dB?

**Comment by anshupitlia** [comment]
hey, is the problem identified and solved?

**Comment by barrybecker4** [comment]
I'm getting a similar timeout issue when issuing a request to load a large dataset using sjs 0.8.1 and spark 2.3.0 and using the JobSqlDao with mysql db. See https://github.com/spark-jobserver/spark-jobserver/issues/1068
