### ISSUE TITLE
Job submit fails in Spark Job Server with NullPointerException

### ISSUE THREAD

**Issue by borisvu** [spark-jobserver/spark-jobserver#655]
I'm using Spark Job Server 0.6.2 with Spark 1.6.1 and in some of job submit attempts I get the following exception:

```
[ERROR] 2016-11-16 08:01:59,595 spark.jobserver.context.DefaultSparkContextFactory$$anon$1 logError - Error initializing SparkContext.
java.lang.NullPointerException
at org.apache.spark.scheduler.TaskSchedulerImpl.<init>(TaskSchedulerImpl.scala:106)
at org.apache.spark.scheduler.TaskSchedulerImpl.<init>(TaskSchedulerImpl.scala:60)
at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:2630)
at org.apache.spark.SparkContext.<init>(SparkContext.scala:522)
at spark.jobserver.context.DefaultSparkContextFactory$$anon$1.<init>(SparkContextFactory.scala:53)
at spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:53)
at spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:48)
at spark.jobserver.context.SparkContextFactory$class.makeContext(SparkContextFactory.scala:37)
at spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:48)
at spark.jobserver.JobManagerActor.createContextFromConfig(JobManagerActor.scala:378)
at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:122)
```

**Comment by velvia** [comment]
Hm, how are you submitting or running job server and Spark?

**Comment by borisvu** [comment]
Spark docker is based on official 1.6.1 with JDK 8.2.
SJS is being submitted via manager_start.sh, setenv.sh and settings.sh scripts with minor modifications (--conf "spark.task.maxFailures=1"   --conf "spark.driver.allowMultipleContexts = true", increased memory and different logging configuration).

**Comment by noorul** [comment]
@borisvu did you find a suction for this? Or are you still facing any issues?

**Comment by noorul** [comment]
Closing this as this has been open for long. Please feel free to re-open if you need further clarification.
