### ISSUE TITLE
NoClassDefFoundError: spark/jobserver/DataFramePersister

### ISSUE THREAD

**Issue by whitish** [spark-jobserver/spark-jobserver#665]
Trying to implement named objects storing/reading.
I'm using:

- spark 2.0
- scala 2.11

Here is my build.sbt file:
```
name := "MRI test"

version := "1.0"

scalaVersion := "2.11.8"

libraryDependencies += "org.apache.spark" %% "spark-core" % "2.0.2"

libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.0.2"

resolvers += "Job Server Bintray" at "https://dl.bintray.com/spark-jobserver/maven"

libraryDependencies += "spark.jobserver" %% "job-server-api" % "0.6.2" % "provided"

libraryDependencies += "spark.jobserver" %% "job-server-extras" % "0.6.2" % "provided"
```

Error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: spark/jobserver/DataFramePersister
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:119)
Caused by: java.lang.ClassNotFoundException: spark.jobserver.DataFramePersister
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
```

Is that expected or I missed smth?

**Comment by velvia** [comment]
I don’t think this is supported in 0.6.2, you probably need to use master.
