### ISSUE TITLE
java.lang.NoSuchMethodError: com.datastax.driver.core.ResultSet.fetchMoreResults

### ISSUE THREAD

**Issue by zhaorongsheng** [spark-jobserver/spark-jobserver#688]
Hi, I hava a problem. 
My env is： 
spark: 2.0.2
spark job server: 2.0-preview

When I initial the context by `curl` the spark job will succeed.
But when I initial the context through the 'local.conf', the job will  be failed.
The exception is like this:

java.lang.NoSuchMethodError: com.datastax.driver.core.ResultSet.fetchMoreResults()Lshade/com/datastax/spark/connector/google/common/util/concurrent/ListenableFuture;
	at com.datastax.spark.connector.rdd.reader.PrefetchingResultSetIterator.maybePrefetch(PrefetchingResultSetIterator.scala:26)
	at com.datastax.spark.connector.rdd.reader.PrefetchingResultSetIterator.next(PrefetchingResultSetIterator.scala:39)
	at com.datastax.spark.connector.rdd.reader.PrefetchingResultSetIterator.next(PrefetchingResultSetIterator.scala:17)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at com.datastax.spark.connector.util.CountingIterator.next(CountingIterator.scala:16)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:147)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:79)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:47)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

The contexts setting is 
sql-context-for-update-on-sale-85 {
  num-cpu-cores = 2           # Number of cores to allocate.  Required.
  memory-per-node = 4G         # Executor memory per node, -Xmx style eg 512m, 1G, etc.
  context-factory = spark.jobserver.context.HiveContextFactory
}

Do you have some suggestiong? Thanks~

**Comment by zhaorongsheng** [comment]
I submit spark job using '--packages datastax:spark-cassandra-connector:2.0.0-M2-s_2.11' and this project depends on 'cassandra-driver-core'. 

There are some conflicts between the two jars. 'com.datastax.driver.core.ResultSet' depends on two different 'ListenableFuture'.

**Comment by noorul** [comment]
Closing this.
