### ISSUE TITLE
unhandled exception cause spark job server crashed (java.lang.ClassNotFoundException: org.apache.spark.SparkContext)

### ISSUE THREAD

**Issue by liu-hongwei** [spark-jobserver/spark-jobserver#69]
hi,

i debuged the spark job server in intellij ,  when client post jobs to it, it crashed with below logs:

one of the reasons is it unable to find SparkContext
java.lang.ClassNotFoundException: org.apache.spark.SparkContext

but if i deploy the same code with bin/server_deploy.sh command,and ran it with ./server_start.sh command, it did not report this error.

so how can i make it not crash in debuger? 

Connected to the target VM, address: '127.0.0.1:37764', transport: 'socket'
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
Uncaught error from thread [JobServer-akka.actor.default-dispatcher-14] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[JobServer]
java.lang.NoClassDefFoundError: Lorg/apache/spark/SparkContext;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2575)
	at java.lang.Class.getDeclaredField(Class.java:2060)
	at akka.actor.ActorCell.lookupAndSetField(ActorCell.scala:602)
	at akka.actor.ActorCell.setActorFields(ActorCell.scala:627)
	at akka.actor.ActorCell.clearActorFields(ActorCell.scala:620)
	at akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:211)
	at akka.actor.dungeon.FaultHandling$class.handleChildTerminated(FaultHandling.scala:283)
	at akka.actor.ActorCell.handleChildTerminated(ActorCell.scala:338)
	at akka.actor.dungeon.DeathWatch$class.watchedActorTerminated(DeathWatch.scala:62)
	at akka.actor.ActorCell.watchedActorTerminated(ActorCell.scala:338)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:424)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:447)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:262)
	at akka.dispatch.Mailbox.run(Mailbox.scala:218)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
Disconnected from the target VM, address: '127.0.0.1:37764', transport: 'socket'
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.SparkContext
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more

**Comment by velvia** [comment]
You need to include spark in the CLASSPATH.  For some reason IntelliJ
doesn't handle provided dependencies correctly.

On Mon, Feb 9, 2015 at 5:50 PM, liu-hongwei <notifications@github.com>
wrote:

> hi,
>
> i debuged the spark job server in intellij , when client post jobs to it,
> it crashed with below logs:
>
> one of the reasons is it unable to find SparkContext
> java.lang.ClassNotFoundException: org.apache.spark.SparkContext
>
> but if i deploy the same code with bin/server_deploy.sh command,and ran it
> with ./server_start.sh command, it did not report this error.
>
> so how can i make it not crash in debuger?
>
> Connected to the target VM, address: '127.0.0.1:37764', transport:
> 'socket'
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further
> details.
> SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
> SLF4J: Defaulting to no-operation MDCAdapter implementation.
> SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for
> further details.
> Uncaught error from thread [JobServer-akka.actor.default-dispatcher-14]
> shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for
> ActorSystem[JobServer]
> java.lang.NoClassDefFoundError: Lorg/apache/spark/SparkContext;
> at java.lang.Class.getDeclaredFields0(Native Method)
> at java.lang.Class.privateGetDeclaredFields(Class.java:2575)
> at java.lang.Class.getDeclaredField(Class.java:2060)
> at akka.actor.ActorCell.lookupAndSetField(ActorCell.scala:602)
> at akka.actor.ActorCell.setActorFields(ActorCell.scala:627)
> at akka.actor.ActorCell.clearActorFields(ActorCell.scala:620)
> at
> akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:211)
> at
> akka.actor.dungeon.FaultHandling$class.handleChildTerminated(FaultHandling.scala:283)
> at akka.actor.ActorCell.handleChildTerminated(ActorCell.scala:338)
> at
> akka.actor.dungeon.DeathWatch$class.watchedActorTerminated(DeathWatch.scala:62)
> at akka.actor.ActorCell.watchedActorTerminated(ActorCell.scala:338)
> at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:424)
> at akka.actor.ActorCell.systemInvoke(ActorCell.scala:447)
> at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:262)
> at akka.dispatch.Mailbox.run(Mailbox.scala:218)
> at
> akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385)
> at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
> at
> scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
> at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
> Disconnected from the target VM, address: '127.0.0.1:37764', transport:
> 'socket'
> at
> scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
> Caused by: java.lang.ClassNotFoundException: org.apache.spark.SparkContext
> at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
> at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> ... 20 more
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/69>.
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by zeitos** [comment]
Closing for inactivity
