### ISSUE TITLE
NoClassDefFoundError: shapeless error running jobserver built with spark 2.1.0

### ISSUE THREAD

**Issue by barrybecker4** [spark-jobserver/spark-jobserver#699]
I am trying to build and run a version of spark-jobserver using spark 2.1.0 (recently released).
My branch (https://github.com/barrybecker4/spark-jobserver/tree/spark-2.1.0-bb) is based on spark-2.0-preview branch.

Everything builds, but when I try to start the job-server, I get this error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: shapeless/PrependAux$
	at spray.routing.directives.PathDirectives$class.pathPrefix(PathDirectives.scala:40)
	at spark.jobserver.WebApi.pathPrefix(WebApi.scala:113)
	at spray.routing.directives.PathDirectives$class.path(PathDirectives.scala:33)
	at spark.jobserver.WebApi.path(WebApi.scala:113)
	at spark.jobserver.common.akka.web.CommonRoutes$class.$init$(CommonRoutes.scala:15)
	at spark.jobserver.WebApi.<init>(WebApi.scala:120)
	at spark.jobserver.JobServer$.start(JobServer.scala:85)
	at spark.jobserver.JobServer$.main(JobServer.scala:156)
	at spark.jobserver.JobServer.main(JobServer.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: shapeless.PrependAux$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```
Is this because job-server uses a different version of akka? Job-server depends on 2.4.9, while spark relies on 2.3.10. I will try changing to akka 2.3.10 in jobserver's versions file, but I don't know if that is the right way to address this.

**Comment by barrybecker4** [comment]
Downgrading akka to 2.3.10 did not help.
When I look at the dependencies using sbt coursierDependencyTree, I see
```
  |  ├─ io.spray:spray-routing_2.11:1.3.3
   |  |  ├─ com.chuusai:shapeless_2.11:1.2.4 -> 2.0.0
```
So something is forcing shapeless 1.2.4 to be evicted in favor of 2.0.0.
Based on http://stackoverflow.com/questions/30941202/spray-can-noclassdeffounderror
It might be spray-can or parboiled doing that. It suggests adding a dependency on spray-routing-shapeless2. Am I on the right path? Any specific suggestions?

**Comment by barrybecker4** [comment]
I was able to start the server and upload a context after I replaced spray-routing with spray-routing-shapeless23.
 ```
   //"io.spray" %% "spray-routing" % spray,
    "io.spray" %% "spray-routing-shapeless23" % "1.3.3",
```

**Comment by velvia** [comment]
Thanks for the hint.  Do you want to submit a PR for that?

**Comment by ChrisALarson** [comment]
Thanks a ton for pointing out the solution @barrybecker4 -- we ran into the same issue and you saved us a bunch of time.

**Comment by txuwh** [comment]
@barrybecker4  Thanks a lot for the solution. I've got the same problem.

**Comment by noorul** [comment]
Closing this as I don't see any issues on master.
