### ISSUE TITLE
job-server-extras/reStart doesn't work on master

### ISSUE THREAD

**Issue by noorul** [spark-jobserver/spark-jobserver#705]
It looks like https://github.com/spark-jobserver/spark-jobserver/blob/master/project/plugins.sbt#L2 is the culprit.

> > job-server-extras/reStart
[info] scalastyle using config /Users/nislam/projects/spark-jobserver/scalastyle-config.xml
[info] Processed 19 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 8 ms
[success] created output: /Users/nislam/projects/spark-jobserver/job-server-extras/target
[warn] Credentials file /Users/nislam/.bintray/.credentials does not exist
[warn] Credentials file /Users/nislam/.bintray/.credentials does not exist
[warn] Credentials file /Users/nislam/.bintray/.credentials does not exist
[warn] Credentials file /Users/nislam/.bintray/.credentials does not exist
[trace] Stack trace suppressed: run 'last job-server-extras/*:coursierResolution' for the full output.
[error] (job-server-extras/*:coursierResolution) java.lang.NoSuchMethodError: coursier.package$Resolution$.apply(Lscala/collection/immutable/Set;Lscala/collection/immutable/Set;Lscala/collection/immutable/Map;Lscala/collection/immutable/Set;Lscala/collection/immutable/Map;Lscala/collection/immutable/Map;Lscala/collection/immutable/Map;Lscala/Option;Lscala/Option;)Lcoursier/core/Resolution;
[error] Total time: 1 s, completed 19 Jan, 2017 8:44:21 PM
> last job-server-extras/*:coursierResolution
java.lang.NoSuchMethodError: coursier.package$Resolution$.apply(Lscala/collection/immutable/Set;Lscala/collection/immutable/Set;Lscala/collection/immutable/Map;Lscala/collection/immutable/Set;Lscala/collection/immutable/Map;Lscala/collection/immutable/Map;Lscala/collection/immutable/Map;Lscala/Option;Lscala/Option;)Lcoursier/core/Resolution;
	at coursier.Tasks$$anonfun$resolutionTask$1.apply(Tasks.scala:438)
	at coursier.Tasks$$anonfun$resolutionTask$1.apply(Tasks.scala:317)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (job-server-extras/*:coursierResolution) java.lang.NoSuchMethodError: coursier.package$Resolution$.apply(Lscala/collection/immutable/Set;Lscala/collection/immutable/Set;Lscala/collection/immutable/Map;Lscala/collection/immutable/Set;Lscala/collection/immutable/Map;Lscala/collection/immutable/Map;Lscala/collection/immutable/Map;Lscala/Option;Lscala/Option;)Lcoursier/core/Resolution;
>

**Comment by noorul** [comment]
@hntd187 Not sure why that plugin is added.

**Comment by hntd187** [comment]
Ahh hmm I dunno why it's broke on that for you. Think we should just remove it?

**Comment by noorul** [comment]
Close
