### ISSUE TITLE
ERROR k.jobserver.io.JobDAOActor on loading python job

### ISSUE THREAD

**Issue by borisiknowthechef** [spark-jobserver/spark-jobserver#715]
Hi ALL!!!!
I will appreciate the help
I have installed the python job server on EMR using the MASTER branch
I have successfully created PYTHON context and uploaded the job
BUT when I try to run the example job I get this error:

[2017-01-26 23:20:39,564] INFO  DefaultSparkContextFactory [] [akka://JobServer/user/context-supervisor/py] - Loading class my_job_package.WordCountSparkJob for app my_py_job
[2017-01-26 23:20:39,644] ERROR k.jobserver.io.JobDAOActor [] [] - About to restart actor due to exception:
java.util.NoSuchElementException: Invoker.first
	at slick.jdbc.Invoker$class.first(Invoker.scala:34)
	at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:16)
	at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
	at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2017-01-26 23:20:39,644] ERROR ka.actor.OneForOneStrategy [] [akka://JobServer/user/dao-manager] - Invoker.first
java.util.NoSuchElementException: Invoker.first
	at slick.jdbc.Invoker$class.first(Invoker.scala:34)
	at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:16)
	at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
	at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2017-01-26 23:20:39,646] WARN  k.jobserver.io.JobDAOActor [] [] - Shutting down spark.jobserver.io.JobDAOActor
[2017-01-26 23:20:39,647] INFO  k.jobserver.io.JobDAOActor [] [akka://JobServer/user/dao-manager] - Starting actor spark.jobserver.io.JobDAOActor

**Comment by pgouda89** [comment]
@borisiknowthechef How did you resolve this issue? I am seeing this issue in my setup as well.
