### ISSUE TITLE
Java API is broken

### ISSUE THREAD

**Issue by VamsiKG** [spark-jobserver/spark-jobserver#716]
Tried running a Java Job using ```curl -d '{name = "blah"}' 'localhost:8090/jobs?appName=djf&classPath=spark.jobserver.api.TestJob'```

Error:
```
[2017-01-26 16:11:08,598] ERROR ka.actor.OneForOneStrategy [] [akka://JobServer/user/context-supervisor/e4186800-spark.jobserver.api.TestJob] - spark.jobserver.api.TestJob cannot be cast to spark.jobserver.api.SparkJobBase
java.lang.ClassCastException: spark.jobserver.api.TestJob cannot be cast to spark.jobserver.api.SparkJobBase
	at spark.jobserver.context.ScalaContextFactory$class.loadAndValidateJob(SparkContextFactory.scala:92)
	at spark.jobserver.context.DefaultSparkContextFactory.loadAndValidateJob(SparkContextFactory.scala:114)
```

**Comment by velvia** [comment]
Is this master?     If so you need to use the JavaSparkContextFactory.

**Comment by VamsiKG** [comment]
@velvia Thanks. We were earlier creating Java jobs against adhoc-context (through DefaultContextFactory), with new Java API this defaults to ScalaContextFactory.
Had to create a persistent context instead with JavaSparkContextFactory.
```curl -d "" 'localhost:8090/contexts/jcontext?context-factory=spark.jobserver.context.JavaSparkContextFactory' ```
