### ISSUE TITLE
Server crash when jar is uploaded, exepction is java.lang.NoSuchMethodError: org.joda.time.DateTime.now()Lorg/joda/time/DateTime

### ISSUE THREAD

**Issue by bronzels** [spark-jobserver/spark-jobserver#741]
hi,

i tried to install and launch spark job server by tips in github home page.
both bin/server_deploy.sh local and bin/server_package.sh local are used.  server can be started by server_start.sh successfully and web UI is displayed as well.

But whenever i tried to upload a test jar(from job server source code by sbt job-server-tests/package). Server is crashed. From server log, execption is due to DateTime.now in joda time package is not absent. But i checked project/Dependencies.scala and find the rev of joda time is 2.9.3. i download the sourcecode of joda 2.9.3 and find the DateTime.now is supported in the rev. Also i checked the depedencies by sbt sbt dependency-tree, only joda time 2.9.3 is included no other revs possible to have conflicts with it.

2 days have been spent for to struggle on this. Hope anyone can help point me a way out. Really appreciate your kind help.

curl return is like:
[hadoop@hadoop1 spark-job-server]$ curl --data-binary @/app/hadoop/spark-jobserver-0.6.2/job-server-tests/target/scala-2.10/job-server-tests_2.10-0.6.2.jar localhost:8090/jars/test
curl: (52) Empty reply from server
[hadoop@hadoop1 spark-job-server]$ 

error in log is like:
[2017-02-16 17:12:47,155] ERROR akka.actor.ActorSystemImpl [] [ActorSystem(JobServer)] - Uncaught error from thread [JobServer-akka.actor.default-dispatcher-7] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.NoSuchMethodError: org.joda.time.DateTime.now()Lorg/joda/time/DateTime;
        at spark.jobserver.BinaryManager.spark$jobserver$BinaryManager$$saveBinary(BinaryManager.scala:48)
        at spark.jobserver.BinaryManager$$anonfun$wrappedReceive$1.applyOrElse(BinaryManager.scala:94)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
        at spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
        at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
        at spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)
        at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
        at spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by noorul** [comment]
I see a similar issue mentioned in troubleshoot guide

https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/troubleshooting.md#javalangnosuchmethoderror-orgjodatimedatetimenow

**Comment by bronzels** [comment]
@noorul ,really appreciate yr intuitive suggestion. so it is due to some jars in CLASSPATH loaded have joda time in different rev. as i have no hive installed at all, any other way to find the problematic jars? i tried the 2 sed preceded lines, server is not started at all, even pid file is not generated. 

look forward to your further suggestions.

**Comment by noorul** [comment]
Closing this
