### ISSUE TITLE
Error in server log when connect to hbase in runJob, java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/HBaseConfiguration.

### ISSUE THREAD

**Issue by bronzels** [spark-jobserver/spark-jobserver#742]
hi,

i run a job in spark job server,  the job is changed to extend SparkJob. in runJob to load data from Hbase to RDD. Before the code is changed to be compatible with spark job server. it is Ok to execut by spark-submit. But when the job is submitted in spark job server to run, there are error in server log:java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/HBaseConfiguration.

HBASE_HOME is set in shell to start job server, even CLASSPATH with HBASE libs is explicitly added, still can't fix this.

BTW, also all source files are in scala, the project is built in maven. spark job server is integrated by adding repository/dependency in POM to extend SparkJob. Built success.

Any one can kindly help give any tips? Really appreciated.

Logs are like these:

job-server[ERROR] 17/02/16 18:33:32 INFO JobManagerActor: Starting Spark job 704227b9-7104-4cec-9657-0ed008ed2fac [com.bqs.risk.bigdata.EventAllCached2Update]...
job-server[ERROR] 17/02/16 18:33:32 INFO JobManagerActor: Starting job future thread
job-server[ERROR] 17/02/16 18:33:32 INFO JobStatusActor: Job 704227b9-7104-4cec-9657-0ed008ed2fac started
job-server[ERROR] 17/02/16 18:33:32 ERROR JobManagerActor: Got Throwable
job-server[ERROR] java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/HBaseConfiguration
job-server[ERROR] 	at com.bqs.risk.bigdata.EventAllCached2Update$.runJob(EventAllCached2Update.scala:43)
job-server[ERROR] 	at com.bqs.risk.bigdata.EventAllCached2Update$.runJob(EventAllCached2Update.scala:23)
job-server[ERROR] 	at spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:301)
job-server[ERROR] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
job-server[ERROR] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
job-server[ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
job-server[ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
job-server[ERROR] 	at java.lang.Thread.run(Thread.java:745)
job-server[ERROR] Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hbase.HBaseConfiguration
job-server[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
job-server[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
job-server[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
job-server[ERROR] 	... 8 more
job-server[ERROR] 17/02/16 18:33:32 INFO RemoteActorRefProvider$RemoteDeadLetterActorRef: Message [spark.jobserver.JobInfoActor$JobConfigStored$] from Actor[akka://JobServer/user/job-info#-668827255] to Actor[akka://JobServer/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
job-server[ERROR] Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/HBaseConfiguration
job-server[ERROR] 	at com.bqs.risk.bigdata.EventAllCached2Update$.runJob(EventAllCached2Update.scala:43)
job-server[ERROR] 	at com.bqs.risk.bigdata.EventAllCached2Update$.runJob(EventAllCached2Update.scala:23)
job-server[ERROR] 	at spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:301)
job-server[ERROR] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
job-server[ERROR] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
job-server[ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
job-server[ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
job-server[ERROR] 	at java.lang.Thread.run(Thread.java:745)
job-server[ERROR] Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hbase.HBaseConfiguration
job-server[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
job-server[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
job-server[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
job-server[ERROR] 	... 8 more

**Comment by bronzels** [comment]
sorry,forget to tell, job server is running in sbt cli by job-server/reStart --- -Xmx4g as local/deploy attempt to run it all failed(pls. refer issue https://github.com/spark-jobserver/spark-jobserver/issues/741 if you are interested as well). job server is really difficult to me.

**Comment by noorul** [comment]
You should be using job-server-extras/reStart

**Comment by bronzels** [comment]
@noorul so kind of you:), tried job-server-extras/reStart, still java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/HBaseConfiguration. the WordCountExample is included in my scala/maven project with only one line "val conf = HBaseConfiguration.create()" added in runJob. Also same exception.

**Comment by noorul** [comment]
Some questions
1. Which version of SJS are you using?
2. Do you mind sharing your project structure?
3. If not can you share your dependencies?

**Comment by bronzels** [comment]
@noorul 
1, 0.6.2 SJS

2, job structure is like:
trait ContactsGraphsCommon extends SparkJob {
object ContactsGraphs extends ContactsGraphsCommon with NamedRddSupport {
BTW, i tried WordCountExample included from SJS source code into my project, with only 1 line added into runJob, also same HBASE class exception
    val conf = HBaseConfiguration.create()

3,my dependencies in POM are like:
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.10</artifactId>
            <version>${spark.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-mllib_2.10</artifactId>
            <version>${spark.version}</version>
            <scope>provided</scope>
        </dependency>


        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-streaming-kafka_${scala.binary.version}</artifactId>
            <version>${spark.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-client</artifactId>
            <version>${hbase.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-server</artifactId>
            <version>${hbase.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-client</artifactId>
            <version>${hadoop.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-mapreduce-client-jobclient</artifactId>
            <version>${hadoop.version}</version>
        </dependency>

        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>${scala.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.3</version>
        </dependency>
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <version>1.1.0.Final</version>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.jexcelapi</groupId>
            <artifactId>jxl</artifactId>
            <version>2.6.10</version>
        </dependency>
        
        <dependency>
            <groupId>com.rabbitmq</groupId>
            <artifactId>amqp-client</artifactId>
            <version>3.6.2</version>
        </dependency>
        
        <dependency>
            <groupId>com.github.davidmoten</groupId>
            <artifactId>geo</artifactId>
            <version>0.7.4</version>
        </dependency>
        
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <version>${version.com.alibaba.druid}</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>${version.mysql}</version>
        </dependency>
        <dependency>
            <groupId>spark.jobserver</groupId>
            <artifactId>job-server_2.11</artifactId>
            <version>0.6.2</version>
        </dependency>
