### ISSUE TITLE
Concurrency issues with H2 file mode

### ISSUE THREAD

**Issue by VamsiKG** [spark-jobserver/spark-jobserver#748]
There seems to be a raise condition between the ```JobResultActor``` and ```JobInfoActor``` causing concurrency issue resulting in error below, when h2:file mode is used.

```
ERROR ka.actor.OneForOneStrategy [] [akka://JobServer/user/job-info] - Database may be already in use: "Locked by another process". Possible solutions: close all other connection(s); use the server mode [90020-176]
org.h2.jdbc.JdbcSQLException: Database may be already in use: "Locked by another process". Possible solutions: close all other connection(s); use the server mode [90020-176]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.h2.message.DbException.get(DbException.java:178)
        at org.h2.message.DbException.get(DbException.java:154)
        at org.h2.store.FileLock.getExceptionAlreadyInUse(FileLock.java:462)
        at org.h2.store.FileLock.lockFile(FileLock.java:356)
        at org.h2.store.FileLock.lock(FileLock.java:136)
        at org.h2.engine.Database.open(Database.java:622)
        at org.h2.engine.Database.openDatabase(Database.java:260)
        at org.h2.engine.Database.<init>(Database.java:254)
        at org.h2.engine.Engine.openSession(Engine.java:57)
        at org.h2.engine.Engine.openSession(Engine.java:164)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:142)
        at org.h2.engine.Engine.createSession(Engine.java:125)
        at org.h2.engine.Engine.createSession(Engine.java:27)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:331)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
        at org.h2.Driver.connect(Driver.java:74)
        at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:98)
        at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:64)
        at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:415)
        at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:414)
        at slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBackend.scala:297)
        at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:407)
        at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:346)
        at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:407)
        at slick.driver.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:498)
        at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:504)
        at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:32)
        at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:29)
        at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
        at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by VamsiKG** [comment]
We are running spark with ```context-per-jvm=true```, and ```yarn-client mode```

**Comment by noorul** [comment]
You should consider using better RDBMS backend like PostgreSQL

**Comment by velvia** [comment]
@VamsiKG see the note I just added to the README about using AUTO_MIXED_MODE, which should solve this problem.

https://github.com/spark-jobserver/spark-jobserver#configuring-spark-jobserver-meta-data-database-backend

**Comment by VamsiKG** [comment]
the README will need an update. To get away with the issue we had to run H2 in server-mode, and use the connection url something like ```jdbc:h2:tcp://localhost/~/db```.
