### ISSUE TITLE
Unable to run Java job 

### ISSUE THREAD

**Issue by dvanegasp** [spark-jobserver/spark-jobserver#750]
I'm getting the same error as in https://github.com/spark-jobserver/spark-jobserver/issues/315 running latest code (master) (Feb 17/2017) when attempting to run `JavaHelloWorldJob`
Opening a new Issue since I can't re=open  https://github.com/spark-jobserver/spark-jobserver/issues/315.
```
{
  "status": "ERROR",
  "result": {
    "message": "Ask timed out on [Actor[akka://JobServer/user/context-supervisor/ee72f766-spark.jobserver.JavaHelloWorldJob#1726726755]] after [10000 ms]",
    "errorClass": "akka.pattern.AskTimeoutException",
    "stack": [
      "akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)",
      "akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)",
      "scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)",
      "scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)",
      "akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)",
      "akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)",
      "akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)",
      "akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)",
      "java.lang.Thread.run(Thread.java:745)"
    ]
  }
}
```
After updating the timeout param along with the request
````
http://ip:8090/jobs?appName=test&classPath=spark.jobserver.JavaHelloWorldJob&sync=true&timeout=50
````
I get 
````
The server was not able to produce a timely response to your request.
````

Scala example `WordCountExample` runs fine. 
Do I have to do anything different to run Java jobs ? 
Thank you!

**Comment by noorul** [comment]
I see the following in the log

    [2017-02-25 11:02:30,289] INFO  k.jobserver.util.JarUtils$ [] [akka://JobServer/user/context-supervisor/f855ab23-spark.jobserver.JavaHelloWorldJob] - Loading class spark.jobserver.JavaHelloWorldJob using loader spark.jobserver.util.ContextURLClassLoader@585e7d1
    [2017-02-25 11:02:30,307] ERROR .jobserver.JobManagerActor [] [] - About to restart actor due to exception:
    java.lang.ClassCastException: spark.jobserver.JavaHelloWorldJob cannot be cast to spark.jobserver.api.SparkJobBase
            at spark.jobserver.context.ScalaContextFactory$class.loadAndValidateJob(SparkContextFactory.scala:92)
            at spark.jobserver.context.DefaultSparkContextFactory.loadAndValidateJob(SparkContextFactory.scala:114)
            at spark.jobserver.JobManagerActor.startJobInternal(JobManagerActor.scala:231)
            at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:157)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
            at spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
            at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
            at spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)
            at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
            at spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)
            at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
            at spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
            at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
            at akka.actor.ActorCell.invoke(ActorCell.scala:487)
            at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
            at akka.dispatch.Mailbox.run(Mailbox.scala:220)
            at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
            at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
            at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
            at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
            at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
    [2017-02-25 11:02:30,308] ERROR ka.actor.OneForOneStrategy [] [akka://JobServer/user/context-supervisor/f855ab23-spark.jobserver.JavaHelloWorldJob] - spark.jobserver.JavaHelloWorldJob cannot be cast to spark.jobserver.api.SparkJobBase
    java.lang.ClassCastException: spark.jobserver.JavaHelloWorldJob cannot be cast to spark.jobserver.api.SparkJobBase
            at spark.jobserver.context.ScalaContextFactory$class.loadAndValidateJob(SparkContextFactory.scala:92)
            at spark.jobserver.context.DefaultSparkContextFactory.loadAndValidateJob(SparkContextFactory.scala:114)
            at spark.jobserver.JobManagerActor.startJobInternal(JobManagerActor.scala:231)
            at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:157)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
            at spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
            at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
            at spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)
            at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
            at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
            at spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)
            at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
            at spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
            at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
            at akka.actor.ActorCell.invoke(ActorCell.scala:487)
            at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
            at akka.dispatch.Mailbox.run(Mailbox.scala:220)
            at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
            at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
            at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
            at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
            at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
    [2017-02-25 11:02:30,315] INFO  .jobserver.JobManagerActor [] [] - Shutting down SparkContext f855ab23-spark.jobserver.JavaHelloWorldJob

**Comment by noorul** [comment]
@hntd187 Are you able to run JavaHelloWorld against master?

**Comment by hntd187** [comment]
Okay dumb question, but you are using JavaSparkContextFactory correct?

**Comment by dvanegasp** [comment]
@hntd187, no I wasn't, I was using the ad-hoc context. 
If I use `JavaSparkContextFactory`, it works fine.
Is the given example supposed to work with the java context _only_?

**Comment by hntd187** [comment]
Yes, it will only work with the given java based context factories.

**Comment by leonsoft** [comment]
Why provide a wrong example in the code base??
