### ISSUE TITLE
2.0.preview branch : java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]

### ISSUE THREAD

**Issue by kaushikranjan** [spark-jobserver/spark-jobserver#759]
Facing this issue on spark 2.0.preview branch

[2017-03-07 17:30:22,472] INFO  k.storage.BlockManagerInfo [] [akka://JobServer/user/jobManager-f9-8735-622780f277f2] - Removed broadcast_605_piece0 on 172.31.49.255:46605 in memory (size: 9.2 KB, free: 2.1 GB)
[2017-03-07 17:30:22,473] INFO  k.storage.BlockManagerInfo [] [akka://JobServer/user/jobManager-f9-8735-622780f277f2] - Removed broadcast_608_piece0 on 172.31.49.255:46605 in memory (size: 26.3 KB, free: 2.1 GB)
[2017-03-07 17:31:12,217] ERROR .jobserver.JobManagerActor [] [] - About to restart actor due to exception:
java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:167)
	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:165)
	at scala.concurrent.Await$.result(package.scala:190)
	at spark.jobserver.JobManagerActor.startJobInternal(JobManagerActor.scala:219)
	at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:157)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
	at spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)
	at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by kaushikranjan** [comment]
this is my settings.sh

APP_USER=hadoop
APP_GROUP=hadoop
INSTALL_DIR=/mnt/lib/spark-jobserver
LOG_DIR=/mnt/var/log/spark-jobserver
PIDFILE=spark-jobserver.pid
JOBSERVER_MEMORY=10G
SPARK_VERSION=2.1.0
SPARK_HOME=/usr/lib/spark
SPARK_CONF_DIR=/etc/spark/conf
HADOOP_CONF_DIR=/etc/hadoop/conf
YARN_CONF_DIR=/etc/hadoop/conf
SCALA_VERSION=2.11.8

**Comment by ASravanthi** [comment]
I am getting the same error, did you get over it?

**Comment by kaushikranjan** [comment]
Ensuring that not running more than 5 jobs in parallel within a context resolved the issue. 
Also H2 was going out of memory in 2/3 days. You might want to move to postgresql DB

**Comment by ASravanthi** [comment]
Thanks for the hint. 
I was uploading too many heavy sized jars(50mb each), after clearing the sqldao and upload folders(in /tmp/spark-jobserver), the issue resolved.

**Comment by bsikander** [comment]
Closing because problem is fixed.
