### ISSUE TITLE
spark-2.0-preview java.lang.NoClassDefFoundError: akka/actor/Actor

### ISSUE THREAD

**Issue by Carl-Hee** [spark-jobserver/spark-jobserver#763]
After compiled, run server_start.sh, Error occurs As follows, and job-server start failed.

Exception in thread "main" java.lang.NoClassDefFoundError: akka/actor/Actor
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(ReflectiveDynamicAccess.scala:21)

**Comment by amarouni** [comment]
@Carl-Hee You compiled the code with SBT ? Can you run the server from SBT by following the https://github.com/spark-jobserver/spark-jobserver#development-mode ?
