### ISSUE TITLE
Persistent RDD Not Working For Java API

### ISSUE THREAD

**Issue by bharatD11** [spark-jobserver/spark-jobserver#766]
NamedRDD<T> namedRDD = new NamedRDD<T>(rdd.rdd(), true, StorageLevel.MEMORY_ONLY());
    NamedObjectPersister<NamedRDD<T>> persister = new RDDPersister<T>();
    persister.persist(namedRDD, "testRDD");
    RDD<T> cachedRDD = (RDD<T>) env.namedObjects().get("testRDD", FiniteDuration.fromNanos(3000000000)).get();
is this the correct way to use the api .As long as i can see rdd is persisted as block memory but ,I get the following exception .Please help
java.util.NoSuchElementException: None.get at scala.None$.get(Option.scala:347) at scala.None$.get(Option.scala:345)

**Comment by hntd187** [comment]
What is T here?

**Comment by bharatD11** [comment]
T is a Java Object which can be serialized

**Comment by hntd187** [comment]
So it's just a class with uninitialized fields and no constructor?

**Comment by bsikander** [comment]
Closing due to inactivity.
