### ISSUE TITLE
Jobserver may run out of memory afer running jobs for several weeks

### ISSUE THREAD

**Issue by barrybecker4** [spark-jobserver/spark-jobserver#777]
I wish I had concrete steps to reliably reproduce this.
It looks like there might be some sort of thread leak in akka.

We have our builds and bdd tests that run in a VM. After a couple weeks of continuously running jobserver jobs (via the bdd tests) in the VM, we sometimes see the below error. I'm reporting this mainly to see if other have encountered something similar, and if there are any workarounds or fixes. Jobserver needs to be running continuously for a long time before it occurs.

We are running spark 2.1.0 and a build of job-server based off of the spark-2.0-preview branch.
I see that there have been additional changes on that preview branch that I could pull in, but I'm not at all sure if those changes will fix this problem. I am using JobFileDAO because we have had other problems using the JobSqlDAO (such as 404 errors and hangs). I am using java 8, and see that there is a warning about MaxPermSize being no longer relevant. I switched to using MaxMetaspaceSize. I read somewhere that increasing this might help, but will probably still fail eventually if there is a leak.

This article talks about how this particular error can arise:
https://plumbr.eu/outofmemoryerror/unable-to-create-new-native-thread

```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Exception in thread "pool-1822-thread-104" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1018)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-1822-thread-107" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1018)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-1822-thread-110" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1018)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Uncaught error from thread [JobServer-akka.actor.default-dispatcher-15] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[JobServer]
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$1.execute(ExecutionContextImpl.scala:136)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:494)
	at spark.jobserver.JobManagerActor.getJobFuture(JobManagerActor.scala:308)
	at spark.jobserver.JobManagerActor.startJobInternal(JobManagerActor.scala:246)
	at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:157)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
	at spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)
	at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by velvia** [comment]
Hi barry,

Would you have any analysis from a heap dump to share?   What information do you have about a possible thread leak in Akka?
Thanks for reporting, once we have more info we can look into solutions.

-Evan

**Comment by barrybecker4** [comment]
So far we have not been able to get a heap dump because when the exception occurs, job-server crashes and does not leave an .hprof file. There is no running java process to get a dump from. The only indication that I have that this is a akka related leak is from the stack trace above, but maybe I am misinterpreting it.

**Comment by velvia** [comment]
There is a JVM flag to do a heap dump on process crash.
-XX:+HeapDumpOnOutOfMemoryError <http://stackoverflow.com/questions/1518839/xxheapdumponoutofmemoryerror-not-creating-hprof-file-in-oom>

**Comment by cgeorge-rms** [comment]
Saw a similar issue to this and analyzed the heap. If your running multiple contexts or even just one and have largish results the LRUCache for results and the JobCache can take up significant amounts of memory (we have 22k objects total in the lru cache's which took up over 8gig)... lower the LRUCache sizes and that fixed our issue... When you analyse the heap dump you see redblack trees in akka taking up space but after enough analysis you see the linkedlist in lrucache taking up the memory.... use something lower for:     job-result-cache-size and spark.job-cache.max-entries

**Comment by velvia** [comment]
Thanks Chris.  That’s great analysis.

I think the LRUCache is based on number of entries.  If we can find one that is sized-based I’m open to replacing that cache;  a setting based on memory might be better for operations.

Evan Chan
velvia@gmail.com
----
“Never doubt that a small group of thoughtful, committed citizens can change the world.” —M. Mead

**Comment by bsikander** [comment]
Closing because JobFileDAO is deprecated and had known memory leaks. JobSqlDao should be used now.
