### ISSUE TITLE
Hive configuration (hive-site.xml) not being populated

### ISSUE THREAD

**Issue by calvin-pietersen** [spark-jobserver/spark-jobserver#791]
Unable to create a HiveContext in a JavaSparkJob which has access to the metastore?

`
HiveContext hiveContext = new HiveContext(sc);
`

```
job-server-extras[ERROR] org.apache.spark.sql.catalyst.analysis.NoSuchTableException
job-server-extras[ERROR] 	at org.apache.spark.sql.hive.client.ClientInterface$$anonfun$getTable$1.apply(ClientInterface.scala:122)
job-server-extras[ERROR] 	at org.apache.spark.sql.hive.client.ClientInterface$$anonfun$getTable$1.apply(ClientInterface.scala:122)
job-server-extras[ERROR] 	at scala.Option.getOrElse(Option.scala:120)
job-server-extras[ERROR] 	at org.apache.spark.sql.hive.client.ClientInterface$class.getTable(ClientInterface.scala:122)
job-server-extras[ERROR] 	at org.apache.spark.sql.hive.client.ClientWrapper.getTable(ClientWrapper.scala:61)
job-server-extras[ERROR] 	at org.apache.spark.sql.hive.HiveMetastoreCatalog.lookupRelation(HiveMetastoreCatalog.scala:391)
job-server-extras[ERROR] 	at org.apache.spark.sql.hive.HiveContext$$anon$2.org$apache$spark$sql$catalyst$analysis$OverrideCatalog$$super$lookupRelation(HiveContext.scala:457)
job-server-extras[ERROR] 	at org.apache.spark.sql.catalyst.analysis.OverrideCatalog$class.lookupRelation(Catalog.scala:161)
job-server-extras[ERROR] 	at org.apache.spark.sql.hive.HiveContext$$anon$2.lookupRelation(HiveContext.scala:457)
job-server-extras[ERROR] 	at org.apache.spark.sql.SQLContext.table(SQLContext.scala:831)
job-server-extras[ERROR] 	at org.apache.spark.sql.SQLContext.table(SQLContext.scala:827)
job-server-extras[ERROR] 	at com.thinkbiganalytics.spark.SparkContextService16.toDataSet(SparkContextService16.java:43)
job-server-extras[ERROR] 	at com.thinkbiganalytics.spark.datavalidator.ValidatorSparkJob.resolveSchema(ValidatorSparkJob.java:625)
job-server-extras[ERROR] 	at com.thinkbiganalytics.spark.datavalidator.ValidatorSparkJob.doValidate(ValidatorSparkJob.java:164)
job-server-extras[ERROR] 	at com.thinkbiganalytics.spark.datavalidator.ValidatorSparkJob.runJob(ValidatorSparkJob.java:659)
job-server-extras[ERROR] 	at spark.jobserver.JavaSparkJob.runJob(JavaSparkJob.scala:14)
job-server-extras[ERROR] 	at spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:301)
job-server-extras[ERROR] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
job-server-extras[ERROR] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
job-server-extras[ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
job-server-extras[ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
job-server-extras[ERROR] 	at java.lang.Thread.run(Thread.java:745)

```

**Comment by amarouni** [comment]
@calvin-pietersen There's a easier way to work with Hive : https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server-extras/src/main/scala/spark/jobserver/HiveTestJob.scala Using the SparkHiveJob.
From the exception it looks like your trying to access a table that doesn't exist `NoSuchTableException`.

**Comment by calvin-pietersen** [comment]
@amarouni ok so I am using a SparkHiveJob now for a Scala application. I create a context with curld "" localhost:8089/contexts/foo?context-factory=spark.jobserver.context.HiveContextFactory. However, in the spark job when I try to reference hive tables I am still getting NoSuchTableException. I have configured job servers default spark directory. Is there some configuration I am missing here?

**Comment by amarouni** [comment]
@calvin-pietersen Do you see in the Spark context logs any reference to Derby or a local metastore ? I think that the HiveContext is starting its own Hive metastore and it's not connecting to your metastore.
Can you try a quick local test using the `spark-shell` on your jobserver node to see if you can access the tables ?

**Comment by noorul** [comment]
Closing this because of inactivity.

**Comment by ruVic101** [comment]
@amarouni I am facing the same issue. For some reason, it's creating a local Derby metastore. Is there any way to make sure that it always connects to the Hive metastore instead of creating a local metastore?
