### ISSUE TITLE
libraries graphx and SQLContext not working and java.io.FileNotFoundException: config\log4j-local.properties

### ISSUE THREAD

**Issue by iamnagesh** [spark-jobserver/spark-jobserver#794]
I have cloned the repo and placed my scala code file viewR.scala in spark-jobserver-master\job-server-tests\src\main\scala\spark\jobserver along with WordCountExample file. I have modified my viewR.scala so that its in the same format as WordCountExample.scala

Here are the error which I get after running reStart command

```
[error] F:\Soft\spark\Projects\spark-jobserver-master\job-server-tests\src\main\scala\spark\jobserver\ViewsRecommender.scala:11: object sql is not a member of package org.apache.spark
[error] import org.apache.spark.sql.SQLContext
[error]                         ^
[error] F:\Soft\spark\Projects\spark-jobserver-master\job-server-tests\src\main\scala\spark\jobserver\ViewsRecommender.scala:12: object graphx is not a member of package org.apache.spark
[error] import org.apache.spark.graphx._
[error]                         ^
```

Also I frequently get the following warning
`[warn] Credentials file C:\Users\path\.bintray\.credentials does not exist`

Also it throws the following FileNotFoundException,
```
job-server-extras Starting spark.jobserver.JobServer.main()
job-server-python[ERROR] Error: Could not find or load main class spark.jobserver.JobServer
job-server-python[ERROR] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
job-server-python ... finished with exit code 1
[info] Application root not yet started
job-server-extras[ERROR] log4j:ERROR Could not read configuration file from URL [file:config/log4j-local.properties].
job-server-extras[ERROR] java.io.FileNotFoundException: config\log4j-local.properties (The system cannot find the path specified)
job-server-extras[ERROR]        at java.io.FileInputStream.open0(Native Method)
job-server-extras[ERROR]        at java.io.FileInputStream.open(FileInputStream.java:195)
job-server-extras[ERROR]        at java.io.FileInputStream.<init>(FileInputStream.java:138)
job-server-extras[ERROR]        at java.io.FileInputStream.<init>(FileInputStream.java:93)
job-server-extras[ERROR]        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
job-server-extras[ERROR]        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
job-server-extras[ERROR]        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:557)
job-server-extras[ERROR]        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
job-server-extras[ERROR]        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
job-server-extras[ERROR]        at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:64)
job-server-extras[ERROR]        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:285)
job-server-extras[ERROR]        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:305)
job-server-extras[ERROR]        at spark.jobserver.JobServer$.<init>(JobServer.scala:33)
job-server-extras[ERROR]        at spark.jobserver.JobServer$.<clinit>(JobServer.scala)
job-server-extras[ERROR]        at spark.jobserver.JobServer.main(JobServer.scala)
job-server-extras[ERROR] log4j:ERROR Ignoring configuration file [file:config/log4j-local.properties].
job-server-extras[ERROR] log4j:WARN No appenders could be found for logger (spark.jobserver.JobServer$).
job-server-extras[ERROR] log4j:WARN Please initialize the log4j system properly.
job-server-extras[ERROR] log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[info] Application job-server not yet started
[info] Starting application job-server in the background ...
job-server Starting spark.jobserver.JobServer.main()
[trace] Stack trace suppressed: run last root/*:reStart for the full output.
[trace] Stack trace suppressed: run last akka-app/*:reStart for the full output.
[trace] Stack trace suppressed: run last job-server-api/*:reStart for the full output.
[error] (root/*:reStart) No main class detected!
[error] (akka-app/*:reStart) No main class detected!
[error] (job-server-api/*:reStart) No main class detected!
[error] (job-server-tests/compile:compileIncremental) Compilation failed
```

I don't know if it is a good idea to place new files in existing project, as a newbie I still have to explore about how to create a new jobserver project. Any resources/links on this is appreciated.

**Comment by bsikander** [comment]
Instead of including your file inside the jobserver, please build your spark jobs outside of the project and submit to jobserver. Closing.
