### ISSUE TITLE
scala.reflect.internal.MissingRequirementError: object slick.driver.H2Driver not found

### ISSUE THREAD

**Issue by paragradke** [spark-jobserver/spark-jobserver#802]
I am trying to deploy spark job server on emr cluster. Here is my configuration.

EMR Version : Amazon EMR 4.7.1
Branch : jobserver-0.6.2-spark-1.6.1

emr.sh
`APP_USER=hadoop
APP_GROUP=hadoop
INSTALL_DIR=/mnt/lib/spark-jobserver
LOG_DIR=/mnt/var/log/spark-jobserver
PIDFILE=spark-jobserver.pid
JOBSERVER_MEMORY=1G
SPARK_VERSION=1.6.1
SPARK_HOME=/usr/lib/spark
SPARK_CONF_DIR=/etc/spark/conf
HADOOP_CONF_DIR=/etc/hadoop/conf
YARN_CONF_DIR=/etc/hadoop/conf
SCALA_VERSION=2.10.5`

I am getting below error while I am running the job server.
`[2017-04-19 07:33:32,179] ERROR spark.jobserver.JobServer$ [] [] - Unable to start Spark JobServer: 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at spark.jobserver.JobServer$.start(JobServer.scala:58)
	at spark.jobserver.JobServer$.main(JobServer.scala:130)
	at spark.jobserver.JobServer.main(JobServer.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:674)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: scala.reflect.internal.MissingRequirementError: object slick.driver.H2Driver not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
	at scala.reflect.internal.Mirrors$RootsBase.ensureModuleSymbol(Mirrors.scala:126)
	at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:161)
	at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:21)
	at spark.jobserver.io.JobSqlDAO.<init>(JobSqlDAO.scala:19)
	... 16 more
`

Please suggest if I am missing anything.

**Comment by jingwangfei** [comment]
hi, wo met too~
did you solve it?

**Comment by anshupitlia** [comment]
Any update on this issue?

**Comment by thoHeinze** [comment]
Did you try with a recent version of the Spark Jobserver? Version 0.6.2 is quite old.

**Comment by anshupitlia** [comment]
I'm trying with version 0.8.0

**Comment by bsikander** [comment]
Closing due to inactivity.
