### ISSUE TITLE
Context creation not working with Mesos cluster deployment mode

### ISSUE THREAD

**Issue by vatsalmevada** [spark-jobserver/spark-jobserver#812]
I have configured job-server for Mesos cluster mode. Here are the changes that I have done in config file:

```
spark.submit.deployMode : "cluster"
spark.master = "mesos://mesos-dispatcher:7077"
```

While trying to create spark context, it is failing with the following message:

`The server was not able to produce a timely response to your request.`

Checking the logs I found following exception:

```
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://JobServer/user/context-supervisor/test-context#1548911283]] after [60000 ms]. Sender[null] sent message of type "spark.jobserver.JobManagerActor$Initialize".
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:331)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:282)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:286)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:238)
	at java.lang.Thread.run(Thread.java:745)
```

I am using spark-2.0-preview branch.

Update:

As mentioned in [https://github.com/spark-jobserver/spark-jobserver/issues/608](https://github.com/spark-jobserver/spark-jobserver/issues/608) I have also set the REMOTE_JOBSERVER_DIR, MESOS_SPARK_DISPATCHER environment variables also I have set driver-mode = mesos-cluster in my config file and I am still facing the issue.

Also as per my understanding, the timeout is happening while creation of SparkContext in spark.jobserver.context.DefaultSparkContextFactory#makeContext.

I logged the spark config used for context creation and the value is as follows:

```
spark.akka.threads=12
spark.app.name=test-context
spark.cores.max=4
spark.driver.allowMultipleContexts=true
spark.driver.extraJavaOptions=-XX:+UseConcMarkSweepGC
         -verbose:gc -XX:+PrintGCTimeStamps -Xloggc:/home/spark/job-server/gc.out
         -XX:MaxPermSize=512m
         -XX:+CMSClassUnloadingEnabled  -XX:MaxDirectMemorySize=512M
           -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Dlog4j.configuration=file:/home/spark/job-server/log4j-server.properties
              -DLOG_DIR=/var/log/job-server/test-context-jobManager-0c-b012-d86e235908ea 
spark.driver.memory=512m
spark.driver.supervise=false
spark.eventLog.dir=/tmp/spark-logs
spark.eventLog.enabled=true
spark.executor.extraJavaOptions=-Dlog4j.configuration=file:/home/spark/job-server/log4j-server.properties
              -DLOG_DIR=/var/log/job-server/test-context-jobManager-0c-b012-d86e235908ea
spark.executor.memory=512m
spark.history.fs.logDirectory=/tmp/spark-logs
spark.jars=file:/var/lib/mesos/slaves/21cd67e3-37da-4cfe-afe4-4c8604b76772-S1/frameworks/670fcbb0-9dfe-40c9-97db-608724cc15b8-0001/executors/driver-20170510143126-0012/runs/fb2249f5-734c-47a5-a9b9-ebe2ea2782c7/./spark-job-server.jar
spark.master=mesos://mesos-dispatcher:7077
spark.submit.deployMode=client
spark.ui.port=0
```

Surprisingly, _spark.submit.deployMode_ is _"client"_ even after setting _spark.jobserver.driver-mode = mesos-cluster_. I have also set spark.submit.deployMode = "cluster" in job-server config file.

I have tried overwriting spark.submit.deployMode to "cluster" by hardcoding the value in code but the issue still persists.

Spark job-server logs: [spark-job-server.txt](https://github.com/spark-jobserver/spark-jobserver/files/992800/spark-job-server.txt)

jobserver config file: [conf.txt](https://github.com/spark-jobserver/spark-jobserver/files/1021484/dev.1.txt)

manager_start.sh file: [manager_start.sh.txt](https://github.com/spark-jobserver/spark-jobserver/files/993250/manager_start.sh.txt)

**Comment by LeightonWong** [comment]
can you show me your spark-jobserver.log when creating new context.

**Comment by vatsalmevada** [comment]
Logs attached inline in the issue details.

**Comment by LeightonWong** [comment]
The log looks like you are using client mode, not cluster mode. But your config `driver-mode = mesos-cluster` does not effect. Have you ever modify the manager_start.sh script?

**Comment by vatsalmevada** [comment]
Attached the config file and manager_start.sh file. I have done some changes in manager_start.sh which is removing the if check hardcoding it to submit with mesos cluster mode always.

**Comment by LeightonWong** [comment]
Could you check your mesos ui, find, open the mesos-dispatcher ui, can you see your spark driver in the Launched Drivers section.

How many agent in your mesos cluster, may be your context is already running in cluster, the log file seem right. I have checked my log file, and also the spark.submit.deployMode is client.

**Comment by vatsalmevada** [comment]
I can see spark driver launched on mesos and mesos-dispatcher UI. However, I can't see any context created on job-server UI and also the context creation REST call fails after 60 sec timeout and I can see this exception in main spark job-server log:

```
 akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://JobServer/user/context-supervisor/test-context#1548911283]] after [60000 ms]. Sender[null] sent message of type "spark.jobserver.JobManagerActor$Initialize".
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:331)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:282)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:286)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:238)
	at java.lang.Thread.run(Thread.java:745)
```

Note that the job-server log file that I attached is for context specific JVM process log since I have context-per-jvm is set to true.

**Comment by LeightonWong** [comment]
In job-server log file for the main process, not the context jobmanager log you atached, did you see this line
```
[2017-05-12 11:02:38,250] INFO Cluster(akka://JobServer) [] [Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@xxxxx.xxx:50992] - Node [akka.tcp://JobServer@xxxxx.xxx:47766] is JOINING, roles [manager]
```

This log means context create successful and join into job-server akka cluster, and the ui will show the joined context name.

**Comment by bsikander** [comment]
@vatsalmevada any update on this ?

**Comment by vatsalmevada** [comment]
@bsikander Unfortunately, I wasn't able to work on this due to some other high priority work. I'll update soon.

**Comment by vatsalmevada** [comment]
@LeightonWong I can not see the message "SparkContext XXXX joined". Here is a snippet from the main process logs:

```
[2017-05-18 17:46:09,707] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Starting context with actor name jobManager-e6-b85a-b5a1eddb8b38
[2017-05-18 17:46:09,709] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Ready to create working directory /var/log/job-server/test-context-jobManager-e6-b85a-b5a1eddb8b38 for context test-context
[2017-05-18 17:46:09,719] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Starting to execute sub process [./manager_start.sh, mesos-cluster, /var/log/job-server/test-context-jobManager-e6-b85a-b5a1eddb8b38, '{"context":{"actorname":"jobManager-e6-b85a-b5a1eddb8b38","name":"test-context"},"context-factory":"spark.jobserver.context.DefaultSparkContextFactory","context-init-timeout":"60s","is-adhoc":"false","memory-per-node":"512m","num-cpu-cores":4,"passthrough":{"spark":{"driver":{"allowMultipleContexts":true}}},"python":{"executable":"python","paths":[]},"spark":{"driver":{"allowMultipleContexts":true},"eventLog":{"dir":"/tmp/spark-logs","enabled":true},"history":{"fs":{"logDirectory":"/tmp/spark-logs"}}},"streaming":{"batch_interval":1000,"stopGracefully":true,"stopSparkContext":true}}', akka.tcp://JobServer@jobserver:43586]
[2017-05-18 17:46:23,814] INFO  .Cluster(akka://JobServer) [] [akka.cluster.Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@jobserver:43586] - Node [akka.tcp://JobServer@jobserver:43711] is JOINING, roles [manager]
[2017-05-18 17:46:24,640] INFO  .Cluster(akka://JobServer) [] [akka.cluster.Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@jobserver:43586] - Leader is moving node [akka.tcp://JobServer@jobserver:43711] to [Up]
[2017-05-18 17:46:24,719] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Received identify response, attempting to initialize context at akka.tcp://JobServer@jobserver:43711/user/*
[2017-05-18 17:46:24,721] INFO  k.jobserver.JobResultActor [] [akka://JobServer/user/context-supervisor/$a] - Starting actor spark.jobserver.JobResultActor
[2017-05-18 17:47:24,749] INFO  AkkaClusterSupervisorActor [] [] - Failed to send initialize message to context Actor[akka.tcp://JobServer@jobserver:43711/user/jobManager-e6-b85a-b5a1eddb8b38#-1963473834]
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka.tcp://JobServer@jobserver:43711/user/jobManager-e6-b85a-b5a1eddb8b38#-1963473834]] after [60000 ms]. Sender[null] sent message of type "spark.jobserver.JobManagerActor$Initialize".
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:331)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:282)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:286)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:238)
	at java.lang.Thread.run(Thread.java:745)
[2017-05-18 17:47:24,755] INFO  r$RemoteDeadLetterActorRef [] [akka://JobServer/deadLetters] - Message [spark.jobserver.ContextSupervisor$ContextInitError] from Actor[akka://JobServer/user/context-supervisor#-1512886145] to Actor[akka://JobServer/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

**Comment by vatsalmevada** [comment]
@LeightonWong Recently my context creation request is passing occasionally and I am able to see the context running on the job-server UI. I can also see the text 'SparkContext test-context joined' in the main process log. However, I can't see the subprocess logs being created in the job-server log directory. 

Also when I submitted the job using the same context I am receiving following response: 

```
curl -d "input.string = a b c a b see" 'jobserver/jobs?appName=wordCount&classPath=spark.jobserver.WordCountExample&context=abc'
{
  "duration": "Job not done yet",
  "classPath": "spark.jobserver.WordCountExample",
  "startTime": "2017-05-19T13:54:59.156+05:30",
  "context": "test-context",
  "status": "STARTED",
  "jobId": "7f5cb7ef-49ce-4c88-b4bf-4ea48816d223"
}

```
Which is expected response as per my knowledge. However, I can't see any job running on the job-server UI. Also when I checked tried to check the job status, I got the response that no job exist with given job ID: 

```
curl 'jobserver:8090/jobs/7f5cb7ef-49ce-4c88-b4bf-4ea48816d223'
{
  "status": "ERROR",
  "result": "No such job ID 7f5cb7ef-49ce-4c88-b4bf-4ea48816d223"
}
```

Note that context creation is not always successful, I am still facing the timeout issue occasionally.

**Comment by vatsalmevada** [comment]
@LeightonWong 
Please ignore my previous update. It was because of the fact that on one of the mesos agent machine `REMOTE_JOBSERVER_DIR` was referring to job-server with different config which was configured for spark standalone client mode which was creating the context on spark standalone cluster and not on Mesos cluster.

I have done the necessary changes and made sure that on all agent `REMOTE_JOBSERVER_DIR` is referring to correct job-server. 

I have also done changes related to [this commit](https://github.com/spark-jobserver/spark-jobserver/commit/9aaa884cdc23ee614d03bd2928f8037fd4a8ad51) (because I was not able to see those changed on `spark-2.0-preview` branch). 

I am still facing the same `AskTimeoutException`. I can see driver started on the Mesos UI and here is the content of `stderr` : 

```
I0523 13:39:06.360623  7716 fetcher.cpp:531] Fetcher Info: {"cache_directory":"\/tmp\/mesos\/fetch\/slaves\/867ea162-e54f-449b-849e-60e1de29b5ca-S0\/root","items":[{"action":"BYPASS_CACHE","uri":{"extract":true,"value":"\/home\/spark\/job-server\/spark-job-server.jar"}}],"sandbox_directory":"\/var\/lib\/mesos\/slaves\/867ea162-e54f-449b-849e-60e1de29b5ca-S0\/frameworks\/e8be76c4-f080-4d8a-9a42-a14a88659d7c-0000\/executors\/driver-20170523133903-0025\/runs\/9046eda3-7362-42ed-a7a8-b3a96b60e699","user":"root"}
I0523 13:39:06.373920  7716 fetcher.cpp:442] Fetching URI '/home/spark/job-server/spark-job-server.jar'
I0523 13:39:06.373970  7716 fetcher.cpp:283] Fetching directly into the sandbox directory
I0523 13:39:06.374014  7716 fetcher.cpp:220] Fetching URI '/home/spark/job-server/spark-job-server.jar'
I0523 13:39:06.409940  7716 fetcher.cpp:205] Copied resource '/home/spark/job-server/spark-job-server.jar' to '/var/lib/mesos/slaves/867ea162-e54f-449b-849e-60e1de29b5ca-S0/frameworks/e8be76c4-f080-4d8a-9a42-a14a88659d7c-0000/executors/driver-20170523133903-0025/runs/9046eda3-7362-42ed-a7a8-b3a96b60e699/spark-job-server.jar'
W0523 13:39:06.410030  7716 fetcher.cpp:322] Copying instead of extracting resource from URI with 'extract' flag, because it does not seem to be an archive: /home/spark/job-server/spark-job-server.jar
I0523 13:39:06.410053  7716 fetcher.cpp:580] Fetched '/home/spark/job-server/spark-job-server.jar' to '/var/lib/mesos/slaves/867ea162-e54f-449b-849e-60e1de29b5ca-S0/frameworks/e8be76c4-f080-4d8a-9a42-a14a88659d7c-0000/executors/driver-20170523133903-0025/runs/9046eda3-7362-42ed-a7a8-b3a96b60e699/spark-job-server.jar'
I0523 13:39:06.541395  7731 exec.cpp:162] Version: 1.2.0
I0523 13:39:06.564935  7749 exec.cpp:237] Executor registered on agent 867ea162-e54f-449b-849e-60e1de29b5ca-S0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
I0523 13:39:13.046183  7869 sched.cpp:232] Version: 1.2.0
I0523 13:39:13.063812  7862 sched.cpp:336] New master detected at master@mesos-dispatcher:7077
I0523 13:39:13.065057  7862 sched.cpp:352] No credentials provided. Attempting to register without authentication
```

Content of `stdout` is as follows: 

```
Received SUBSCRIBED event
Subscribed executor on mesos-agent
Received LAUNCH event
Starting task driver-20170523133903-0025
/home/spark/mesos-1.2.0/build/src/mesos-containerizer launch --help="false" --launch_info="{"command":{"environment":{"variables":[{"name":"SPARK_SCALA_VERSION","value":"2.10"},{"name":"MESOS_NATIVE_JAVA_LIBRARY","value":"\/home\/spark\/mesos\/mesos-1.2.0\/build\/src\/.libs\/libmesos.so"},{"name":"SPARK_EXECUTOR_OPTS","value":"-Dspark.executor.extraJavaOptions=-Dlog4j.configuration=file:\/home\/spark\/job-server\/log4j-server.properties\n              -DLOG_DIR=\/var\/log\/job-server\/test-jobManager-91-8d99-f21008173759 -Dspark.jars=file:\/home\/spark\/job-server\/spark-job-server.jar -Dspark.driver.supervise=false -Dspark.app.name=spark.jobserver.JobManager -Dspark.driver.memory=512m -Dspark.driver.extraJavaOptions=-XX:+UseConcMarkSweepGC\n         -verbose:gc -XX:+PrintGCTimeStamps -Xloggc:\/home\/spark\/job-server\/gc.out\n         -XX:MaxPermSize=512m\n         -XX:+CMSClassUnloadingEnabled  -XX:MaxDirectMemorySize=512M\n           -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Dlog4j.configuration=file:\/home\/spark\/job-server\/log4j-server.properties\n              -DLOG_DIR=\/var\/log\/job-server\/test-jobManager-91-8d99-f21008173759  -Dspark.submit.deployMode=cluster -Dspark.master=mesos:\/\/mesos-dispatcher:7077"}]},"shell":true,"uris":[{"extract":true,"value":"\/home\/spark\/job-server\/spark-job-server.jar"}],"value":"\/home\/spark\/spark-2.0.2\/.\/bin\/spark-submit --name spark.jobserver.JobManager --master mesos:\/\/mesos-master:5050 --driver-cores 1.0 --driver-memory 512M --class spark.jobserver.JobManager --conf \"spark.executor.extraJavaOptions=-Dlog4j.configuration=file:\/home\/spark\/job-server\/log4j-server.properties\n              -DLOG_DIR=\/var\/log\/job-server\/test-jobManager-91-8d99-f21008173759\" --conf \"spark.driver.supervise=false\" --conf \"spark.app.name=spark.jobserver.JobManager\" --conf \"spark.driver.memory=512m\" --conf \"spark.driver.extraJavaOptions=-XX:+UseConcMarkSweepGC\n         -verbose:gc -XX:+PrintGCTimeStamps -Xloggc:\/home\/spark\/job-server\/gc.out\n         -XX:MaxPermSize=512m\n         -XX:+CMSClassUnloadingEnabled  -XX:MaxDirectMemorySize=512M\n           -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Dlog4j.configuration=file:\/home\/spark\/job-server\/log4j-server.properties\n              -DLOG_DIR=\/var\/log\/job-server\/test-jobManager-91-8d99-f21008173759 \" .\/spark-job-server.jar \/var\/log\/job-server\/test-jobManager-91-8d99-f21008173759 '{\"context\":{\"actorname\":\"jobManager-91-8d99-f21008173759\",\"name\":\"test\"},\"context-factory\":\"spark.jobserver.context.DefaultSparkContextFactory\",\"context-init-timeout\":\"60s\",\"is-adhoc\":\"false\",\"memory-per-node\":\"512m\",\"num-cpu-cores\":4,\"passthrough\":{\"spark\":{\"driver\":{\"allowMultipleContexts\":true}}},\"python\":{\"executable\":\"python\",\"paths\":[]},\"spark\":{\"driver\":{\"allowMultipleContexts\":true},\"eventLog\":{\"dir\":\"\/tmp\/spark-logs\",\"enabled\":true},\"history\":{\"fs\":{\"logDirectory\":\"\/tmp\/spark-logs\"}}},\"streaming\":{\"batch_interval\":1000,\"stopGracefully\":true,\"stopSparkContext\":true}}' akka.tcp:\/\/JobServer@job-server:38491 \/home\/spark\/job-server\/dev.conf"},"environment":{"variables":[{"name":"BIN_SH","value":"xpg4"},{"name":"DUALCASE","value":"1"},{"name":"LIBPROCESS_PORT","value":"0"},{"name":"MESOS_AGENT_ENDPOINT","value":"mesos-agent:5051"},{"name":"MESOS_CHECKPOINT","value":"1"},{"name":"MESOS_DIRECTORY","value":"\/var\/lib\/mesos\/slaves\/867ea162-e54f-449b-849e-60e1de29b5ca-S0\/frameworks\/e8be76c4-f080-4d8a-9a42-a14a88659d7c-0000\/executors\/driver-20170523133903-0025\/runs\/9046eda3-7362-42ed-a7a8-b3a96b60e699"},{"name":"MESOS_EXECUTOR_ID","value":"driver-20170523133903-0025"},{"name":"MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD","value":"5secs"},{"name":"MESOS_FRAMEWORK_ID","value":"e8be76c4-f080-4d8a-9a42-a14a88659d7c-0000"},{"name":"MESOS_HTTP_COMMAND_EXECUTOR","value":"0"},{"name":"MESOS_NATIVE_JAVA_LIBRARY","value":"\/home\/spark\/mesos\/mesos-1.2.0\/build\/src\/.libs\/libmesos.so"},{"name":"MESOS_RECOVERY_TIMEOUT","value":"15mins"},{"name":"MESOS_SANDBOX","value":"\/var\/lib\/mesos\/slaves\/867ea162-e54f-449b-849e-60e1de29b5ca-S0\/frameworks\/e8be76c4-f080-4d8a-9a42-a14a88659d7c-0000\/executors\/driver-20170523133903-0025\/runs\/9046eda3-7362-42ed-a7a8-b3a96b60e699"},{"name":"MESOS_SLAVE_ID","value":"867ea162-e54f-449b-849e-60e1de29b5ca-S0"},{"name":"MESOS_SLAVE_PID","value":"slave(1)@mesos-agent:5051"},{"name":"MESOS_SUBSCRIPTION_BACKOFF_MAX","value":"2secs"},{"name":"PATH","value":"\/usr\/local\/sbin:\/usr\/local\/bin:\/usr\/sbin:\/usr\/bin:\/sbin:\/bin"},{"name":"PWD","value":"\/var\/lib\/mesos\/slaves\/867ea162-e54f-449b-849e-60e1de29b5ca-S0\/frameworks\/e8be76c4-f080-4d8a-9a42-a14a88659d7c-0000\/executors\/driver-20170523133903-0025\/runs\/9046eda3-7362-42ed-a7a8-b3a96b60e699"},{"name":"SHLVL","value":"0"},{"name":"SPARK_EXECUTOR_OPTS","value":"-Dspark.executor.extraJavaOptions=-Dlog4j.configuration=file:\/home\/spark\/job-server\/log4j-server.properties\n              -DLOG_DIR=\/var\/log\/job-server\/test-jobManager-91-8d99-f21008173759 -Dspark.jars=file:\/home\/spark\/job-server\/spark-job-server.jar -Dspark.driver.supervise=false -Dspark.app.name=spark.jobserver.JobManager -Dspark.driver.memory=512m -Dspark.driver.extraJavaOptions=-XX:+UseConcMarkSweepGC\n         -verbose:gc -XX:+PrintGCTimeStamps -Xloggc:\/home\/spark\/job-server\/gc.out\n         -XX:MaxPermSize=512m\n         -XX:+CMSClassUnloadingEnabled  -XX:MaxDirectMemorySize=512M\n           -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Dlog4j.configuration=file:\/home\/spark\/job-server\/log4j-server.properties\n              -DLOG_DIR=\/var\/log\/job-server\/test-jobManager-91-8d99-f21008173759  -Dspark.submit.deployMode=cluster -Dspark.master=mesos:\/\/mesos-dispatcher:7077"},{"name":"SPARK_SCALA_VERSION","value":"2.10"},{"name":"SPARK_SCALA_VERSION","value":"2.10"},{"name":"MESOS_NATIVE_JAVA_LIBRARY","value":"\/home\/spark\/mesos\/mesos-1.2.0\/build\/src\/.libs\/libmesos.so"},{"name":"SPARK_EXECUTOR_OPTS","value":"-Dspark.executor.extraJavaOptions=-Dlog4j.configuration=file:\/home\/spark\/job-server\/log4j-server.properties\n              -DLOG_DIR=\/var\/log\/job-server\/test-jobManager-91-8d99-f21008173759 -Dspark.jars=file:\/home\/spark\/job-server\/spark-job-server.jar -Dspark.driver.supervise=false -Dspark.app.name=spark.jobserver.JobManager -Dspark.driver.memory=512m -Dspark.driver.extraJavaOptions=-XX:+UseConcMarkSweepGC\n         -verbose:gc -XX:+PrintGCTimeStamps -Xloggc:\/home\/spark\/job-server\/gc.out\n         -XX:MaxPermSize=512m\n         -XX:+CMSClassUnloadingEnabled  -XX:MaxDirectMemorySize=512M\n           -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Dlog4j.configuration=file:\/home\/spark\/job-server\/log4j-server.properties\n              -DLOG_DIR=\/var\/log\/job-server\/test-jobManager-91-8d99-f21008173759  -Dspark.submit.deployMode=cluster -Dspark.master=mesos:\/\/mesos-dispatcher:7077"}]}}" --unshare_namespace_mnt="false"
Forked command at 7754
Overwriting environment variable 'SPARK_SCALA_VERSION', original: '2.10', new: '2.10'
Overwriting environment variable 'MESOS_NATIVE_JAVA_LIBRARY', original: '/home/spark/mesos/mesos-1.2.0/build/src/.libs/libmesos.so', new: '/home/spark/mesos/mesos-1.2.0/build/src/.libs/libmesos.so'
Overwriting environment variable 'SPARK_EXECUTOR_OPTS', original: '-Dspark.executor.extraJavaOptions=-Dlog4j.configuration=file:/home/spark/job-server/log4j-server.properties
              -DLOG_DIR=/var/log/job-server/test-jobManager-91-8d99-f21008173759 -Dspark.jars=file:/home/spark/job-server/spark-job-server.jar -Dspark.driver.supervise=false -Dspark.app.name=spark.jobserver.JobManager -Dspark.driver.memory=512m -Dspark.driver.extraJavaOptions=-XX:+UseConcMarkSweepGC
         -verbose:gc -XX:+PrintGCTimeStamps -Xloggc:/home/spark/job-server/gc.out
         -XX:MaxPermSize=512m
         -XX:+CMSClassUnloadingEnabled  -XX:MaxDirectMemorySize=512M
           -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Dlog4j.configuration=file:/home/spark/job-server/log4j-server.properties
              -DLOG_DIR=/var/log/job-server/test-jobManager-91-8d99-f21008173759  -Dspark.submit.deployMode=cluster -Dspark.master=mesos://mesos-dispatcher:7077', new: '-Dspark.executor.extraJavaOptions=-Dlog4j.configuration=file:/home/spark/job-server/log4j-server.properties
              -DLOG_DIR=/var/log/job-server/test-jobManager-91-8d99-f21008173759 -Dspark.jars=file:/home/spark/job-server/spark-job-server.jar -Dspark.driver.supervise=false -Dspark.app.name=spark.jobserver.JobManager -Dspark.driver.memory=512m -Dspark.driver.extraJavaOptions=-XX:+UseConcMarkSweepGC
         -verbose:gc -XX:+PrintGCTimeStamps -Xloggc:/home/spark/job-server/gc.out
         -XX:MaxPermSize=512m
         -XX:+CMSClassUnloadingEnabled  -XX:MaxDirectMemorySize=512M
           -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Dlog4j.configuration=file:/home/spark/job-server/log4j-server.properties
              -DLOG_DIR=/var/log/job-server/test-jobManager-91-8d99-f21008173759  -Dspark.submit.deployMode=cluster -Dspark.master=mesos://mesos-dispatcher:7077'

```
I have two doubts from `stdout`:

- On line 5 I can see that somewhere `mesos-master:5050` was passed as spark-submit master. Shouldn't it be `mesos-dispatcher:7077`?
- On line 7 I can see `SPARK_SCALA_VERSION` as `2.10`. I am not sure from where it is picking that version. It should be 2.11. I have tried setting environment variable for SPARK_SCALA_VERSION=2.11 on all agents and also on job-server machine. Still it is picking 2.10 as scala version.

**Comment by LeightonWong** [comment]
In the beginning, this pr is only a temporary solution for driver cluster mode,So I did not modify too much code, it is not so clear to have 2 spark master config, I think they should be combined in the future:

There are 2 config for spark master now:

1. spark.master in xxxx.conf , this is used for default client mode.
1. MESOS_SPARK_DISPATCHER in settings.sh, used in spark-submit command line, only valid in cluster mode.

On line 5, the 5050 master address will be override by 7077 address if they are both passed to spark-submit.

On line 7, maybe your spark is compiled with scala 2.10?

By the way, spark 2.0 version have some problem with mesos, so I have another [pr](https://github.com/apache/spark/pull/15643) to spark , merged into spark in 2.0.2 version.

**Comment by vatsalmevada** [comment]
Finally, I managed to figure out the issue. In my job-server config file, I was passing dispatcher URL in `spark.master` property of jobserver config. Replacing that by mesos master URL fixed the issue for me.

I have raised a pull request (#832) for mesos config documentation.

**Comment by LeightonWong** [comment]
Congratulations!

**Comment by vatsalmevada** [comment]
Closing this issue as the problem is resolved.
