### ISSUE TITLE
java.io.UTFDataFormatException: encoded string too long: 369756 bytes

### ISSUE THREAD

**Issue by jingwangfei** [spark-jobserver/spark-jobserver#817]
Exceptions are as follows: 
```
[2017-05-15 14:51:17,272] ERROR ka.actor.OneForOneStrategy [] [akka://JobServer/user/job-info] - encoded string too long: 369756 bytes
java.io.UTFDataFormatException: encoded string too long: 369756 bytes
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:364)
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
        at spark.jobserver.io.JobFileDAO.writeJobConfig(JobFileDAO.scala:185)
        at spark.jobserver.io.JobFileDAO.saveJobConfig(JobFileDAO.scala:177)
        at spark.jobserver.JobInfoActor$$anonfun$wrappedReceive$1.applyOrElse(JobInfoActor.scala:73)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
        at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
        at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)
        at ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)
        at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
        at ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        va.io.UTFDataFormatException: encoded string too long: 369756 bytesat scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
Can somebody help me?~~

**Comment by velvia** [comment]
Hmm this was probably because you are writing a large job input?   Yes I would suggest not using the default JobFileDAO.

**Comment by jingwangfei** [comment]
OK,  thanks very much.
I've already used H2 database for storing Spark Jobserver related meta data.
but, it errors with following messages:
`object slick.driver.H2Driver not found`

**Comment by noorul** [comment]
Are you facing this issue with H2 as you now fixed the above H2 driver issue?

**Comment by velvia** [comment]
I think they need to include the H2 driver themselves.

**Comment by bsikander** [comment]
Closing due to inactivity.
