### ISSUE TITLE
Unable to start SJS

### ISSUE THREAD

**Issue by FK7** [spark-jobserver/spark-jobserver#837]
I am getting following error when trying to start SJS.

Guys, please tell me why I am getting this error, thanks in advance.

```
[2017-05-30 09:52:31,494] INFO  ka.event.slf4j.Slf4jLogger [] [] - Slf4jLogger started
[2017-05-30 09:52:32,057] ERROR spark.jobserver.JobServer$ [] [] - Unable to start Spark JobServer:
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at spark.jobserver.JobServer$.start(JobServer.scala:59)
        at spark.jobserver.JobServer$.main(JobServer.scala:121)
        at spark.jobserver.JobServer.main(JobServer.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.NoSuchMethodError: scala.reflect.api.JavaUniverse.runtimeMirror(Ljava/lang/ClassLoader;)Lscala/reflect/api/JavaUniverse$JavaMirror;
        at spark.jobserver.io.JobSqlDAO.<init>(JobSqlDAO.scala:18)
        ... 16 more

```

**Comment by Majea** [comment]
Maybe a mismatch between the scala versions of some of your libraries? you should only use libraries compiled for the same scala version. 
E.g in the following gradle dependency, the scala version is 2.11. Having different version of scala mixed in your dependencies can lead to such issues. 
`group: 'org.scala-lang.modules', name: 'scala-xml_2.11', version: '1.0.2'`

**Comment by velvia** [comment]
I would agree with Maxime, likely you are running wrong Scala version or somehow the wrong version of scale-reflect is being bundled.

**Comment by FK7** [comment]
Thanks @Majea, Issue got resolved.
appreciate your assistance !!

**Comment by Cyash** [comment]
Hi I'm getting same error exactly. how do I resolve this? I've installed jobserver as described at [](https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/EMR.md) , I've only followed those steps nothing more. I'm breaking my head from past 2 days on this only to find it is failing after reading logs, what commands do I need to run to resolve this?
