### ISSUE TITLE
SJS not responding with Cloudera Spark 1.6.0 on EC2

### ISSUE THREAD

**Issue by FK7** [spark-jobserver/spark-jobserver#840]
Hi Team,

I am trying to integrate SJS with Cloudera(CDH-5.8.2) on EC2 using Spark 1.6.0. Below is the script which I am using to install SJS on EC2 with spark. 

Script runs successfully without error and also SJS has started, However I can see in logs SJS got stuck and does not responded as you can see in below logs.
```
    #  If set to `infinite` request and connection timeout checking is disabled.
    "reaping-cycle" : "250 ms"
}
[2017-05-31 06:44:40,154] INFO  ka.event.slf4j.Slf4jLogger [] [] - Slf4jLogger started
[2017-05-31 06:44:40,226] INFO  Remoting [] [Remoting] - Starting remoting
[2017-05-31 06:44:40,357] INFO  Remoting [] [Remoting] - Remoting started; listening on addresses :[akka.tcp://JobServer@127.0.0.1:48213]
[2017-05-31 06:44:40,359] INFO  Remoting [] [Remoting] - Remoting now listens on addresses: [akka.tcp://JobServer@127.0.0.1:48213]
[ec2-user@ip-172-31-3-132 ~]$
```
Please let mee know why this is happening. Thanks in advance !!

**_Script_**
```
#!/bin/bash

echo "########################################creating required folders in /mnt.##########################################################"

if [ -d "/mnt/work" ]; then
  sudo rm -rf /mnt/work
fi

sudo mkdir /mnt/work

if [ -d "/mnt/lib/.ivy2" && ! -h "~/.ivy2" ]; then
  sudo rm -rf /mnt/lib
fi

sudo mkdir -p /mnt/lib/.ivy2
ln -s /mnt/lib/.ivy2 ~/.ivy2

echo "########################################creating spark-jobserver log dirs########################################"

if [ -d "/mnt/var/log/spark-jobserver" ]; then
  sudo rm -rf /mnt/var/log/spark-jobserver
fi

sudo mkdir /mnt/var/log/spark-jobserver

echo "########################################Building spark-jobserver distribution.########################################"
echo "########################################Installing SBT########################################"
curl https://bintray.com/sbt/rpm/rpm | sudo tee /etc/yum.repos.d/bintray-sbt-rpm.repo
sudo yum install -y sbt

echo "########################################Installing git########################################"
sudo yum install -y git

cd /mnt/work
echo "########################################Cloning spark-jobserver in /mnt/work and checkout release v0.6.1########################################"
sudo git clone https://github.com/spark-jobserver/spark-jobserver.git
cd spark-jobserver
sudo git checkout jobserver-0.6.2-spark-1.6.1

echo "########################################building spark-jobserver########################################"
sudo sbt clean update package assembly

echo "########################################creating config/ec2.sh########################################"
cd config
sudo /bin/su -c "echo $'APP_USER=ec2-user
APP_GROUP=ec2-user
INSTALL_DIR=/mnt/lib/spark-jobserver
LOG_DIR=/mnt/var/log/spark-jobserver
PIDFILE=spark-jobserver.pid
JOBSERVER_MEMORY=6g
SPARK_VERSION=1.6.0
SPARK_HOME=/opt/cloudera/parcels/CDH-5.8.2-1.cdh5.8.2.p0.3/lib/spark
SPARK_CONF_DIR=/etc/spark/conf
HADOOP_CONF_DIR=/etc/hadoop/conf
YARN_CONF_DIR=/etc/hadoop/conf
SCALA_VERSION=2.10.5' >> ec2.sh"



echo "########################################ec2.sh########################################"
cat ec2.sh

echo "########################################creating config/ec2.conf########################################"

sudo echo $'spark {
  master = "yarn-client"
  # master = "local[4]"
  # master = "mesos://<IP:PORT>"
  # spark web UI port
  webUrlPort = 8080

  jobserver {
    port = 8090
    bind-address = "0.0.0.0"

    # If true, a separate JVM is forked for each Spark context
    context-per-jvm = true

    # Number of job results to keep per JobResultActor/context
    job-result-cache-size = 5000

    jobdao = spark.jobserver.io.JobFileDAO
	#jobdao = spark.jobserver.io.JobSqlDAO
    # Automatically load a set of jars at startup time.  Key is the appName, value is the path/URL.
    job-jar-paths {
	# dbProcess = /home/hadoop/dbProcess.jar
	# cleaningProcess = /home/hadoop/cleaningProcess.jar
	# twitterStream = /home/hadoop/twitterStream.jar
	# visualize = /home/hadoop/visualize.jar
	# CEPProcess = /home/hadoop/CEPProcess.jar
	# load-schema=/home/hadoop/load-schema.jar
	# sentimental-analysis=/home/hadoop/sentimental-analysis.jar
	# create-model=/home/hadoop/create-model.jar
	# read-file=/home/hadoop/read-file.jar
	# kmeansclustering= /home/hadoop/kmeansclustering.jar
	# sparks-ml= /home/hadoop/sparks-ml.jar
	# apacheLogs= /home/hadoop/apacheLogs.jar
	# CSVIngestion= /home/hadoop/CSVIngestion.jar
	
	#Analysis = /home/hadoop/Analysis.jar
	#IngestionNCleaning = /home/hadoop/IngestionNCleaning.jar
	#Streaming = /home/hadoop/Streaming.jar
	#Visualization = /home/hadoop/Visualization.jar
	#load-schema=/home/hadoop/load-schema.jar
    }

    filedao {
      rootdir = /tmp/spark-jobserver/filedao/data
    }

    datadao {
      # storage directory for files that are uploaded to the server
      # via POST/data commands
      rootdir = /tmp/spark-jobserver/upload
    }

    # To load up job jars on startup, place them here,
    # with the app name as the key and the path to the jar as the value
    # job-jar-paths {
    #   test = ../job-server-tests/target/scala-2.10/job-server-tests_2.10-0.5.3-SNAPSHOT.jar
    # }

    sqldao {
      # Slick database driver, full classpath
      slick-driver = scala.slick.driver.H2Driver

      # JDBC driver, full classpath
      jdbc-driver = org.h2.Driver

      # Directory where default H2 driver stores its data. Only needed for H2.
      rootdir = /tmp/spark-jobserver/sqldao/data

      # Full JDBC URL / init string, along with username and password.  Sorry, needs to match above.
      # Substitutions may be used to launch job-server, but leave it out here in the default or tests won\'t pass
      jdbc {
        url = "jdbc:h2:file:/tmp/spark-jobserver/sqldao/data/h2-db"
        user = ""
        password = ""
      }

      # DB connection pool settings
      dbcp {
        maxactive = 20
        maxidle = 10
        initialsize = 10
      }
    }

    # The ask pattern timeout for Api
    short-timeout = 3 s

    # Time out for job server to wait while creating contexts
    context-creation-timeout = 60 s

    # Time out for job server to wait while creating named objects
    named-object-creation-timeout = 60 s

    # Number of jobs that can be run simultaneously per context
    # If not set, defaults to number of cores on machine where jobserver is running
    max-jobs-per-context = 8

    # in yarn deployment, time out for job server to wait while creating contexts
    yarn-context-creation-timeout = 40 s

    # spark broadcst factory in yarn deployment
    # Versions prior to 1.1.0, spark default broadcast factory is org.apache.spark.broadcast.HttpBroadcastFactory.
    # Can\'t start multiple sparkContexts in the same JVM with HttpBroadcastFactory.
    yarn-broadcast-factory = org.apache.spark.broadcast.TorrentBroadcastFactory
  }

  # predefined Spark contexts
  # Below is an example, but do not uncomment it.   Everything defined here is carried over to
  # deploy-time configs, so they will be created in all environments.  :(
  contexts {
    # abc-demo {
    #   num-cpu-cores = 4            # Number of cores to allocate.  Required.
    #   memory-per-node = 1024m      # Executor memory per node, -Xmx style eg 512m, 1G, etc.
    # }
    # define additional contexts here
	  static {
       num-cpu-cores = 2            # Number of cores to allocate.  Required.
       memory-per-node = 1G
    spark.executor.instances = 2    # Executor memory per node, -Xmx style eg 512m, 1G, etc.
     }
  }

  # Default settings for ad hoc as well as manually created contexts
  # You can add any Spark config params here, for example, spark.mesos.coarse = true
  context-settings {
    num-cpu-cores = 2           # Number of cores to allocate.  Required.
    memory-per-node = 2G      # Executor memory per node, -Xmx style eg 512m, 1G, etc.
    spark.executor.instances = 2

    # A zero-arg class implementing spark.jobserver.context.SparkContextFactory
    # Determines the type of jobs that can run in a SparkContext
    context-factory = spark.jobserver.context.DefaultSparkContextFactory

    streaming {
      # Default batch interval for Spark Streaming contexts in milliseconds
      batch_interval = 1000

      # if true, stops gracefully by waiting for the processing of all received data to be completed
      stopGracefully = false

      # if true, stops the SparkContext with the StreamingContext. The underlying SparkContext will be
      # stopped regardless of whether the StreamingContext has been started.
      stopSparkContext = false
    }

    # uris of jars to be loaded into the classpath for this context. Uris is a string list, or a string separated by commas ','
    # dependent-jar-uris = ["file:///some/path/present/in/each/mesos/slave/somepackage.jar"]

    # Timeout for SupervisorActor to wait for forked (separate JVM) contexts to initialize
    context-init-timeout = 60s
	# If you wish to pass any settings directly to the sparkConf as-is, add them here in passthrough,
	# such as hadoop connection settings that do not use the "spark." prefix
    passthrough {
      spark.driver.allowMultipleContexts = true  # Ignore the Multiple context exception related with SPARK-2243
	  spark.serializer = org.apache.spark.serializer.KryoSerializer
    }

    #This adds configuration to the underlying Hadoop configuration in the Spark Context
    #hadoop {
    #  mapreduce.framework.name = "FooFramework"
    #}
  }
  	# This needs to match SPARK_HOME for cluster SparkContexts to be created successfully
	home = "/opt/cloudera/parcels/CDH-5.8.2-1.cdh5.8.2.p0.3/lib/spark"
}

# Flyway locations to scan recursively for migrations
flyway.locations = "db/h2/migration"


# check the reference.conf in spray-can/src/main/resources for all defined settings
spray.can.server {
  # uncomment the next lines for making this an HTTPS example
  # ssl-encryption = on
  # path to keystore
  #keystore = "/some/path/sjs.jks"
  #keystorePW = "changeit"

  # see http://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html#SSLContext for more examples
  # typical are either SSL or TLS
  encryptionType = "SSL"
  keystoreType = "JKS"
  # key manager factory provider
  provider = "SunX509"
  # ssl engine provider protocols
  enabledProtocols = ["SSLv3", "TLSv1"]
  idle-timeout = 120 s
  request-timeout = 80 s
  pipelining-limit = 2 # for maximum performance (prevents StopReading / ResumeReading messages to the IOBridge)
  # Needed for HTTP/1.0 requests with missing Host headers
  default-host-header = "spray.io:8765"

  # Increase this in order to upload bigger job jars
  parsing.max-content-length = 300m
}


deploy {
  manager-start-cmd = "/mnt/lib/spark-jobserver/manager_start.sh"
}' >> /home/ec2-user/ec2.conf

sudo cp /home/ec2-user/ec2.conf /mnt/work/spark-jobserver/config

cat ec2.conf

echo "################################Build tar.gz package. The package location will be /tmp/job-server/job-server.tar.gz###############################"
cd ..
sudo bin/server_package.sh ec2

echo "################################Deploy spark-jobserver###############################"

echo "################################Create directory for spark-jobserver and extract job-server.tar.gz into it###############################"

if [ -d "/mnt/lib/spark-jobserver" ]; then
  sudo rm -rf /mnt/lib/spark-jobserver
fi
sudo mkdir /mnt/lib/spark-jobserver

cd /mnt/lib/spark-jobserver

sudo tar zxf /tmp/job-server/job-server.tar.gz

echo "################################Check ec2.conf and settings.sh############################"

echo "################################Start jobserver############################"
sudo ./server_start.sh
echo "Spark job server started.."
```

**Comment by FK7** [comment]
Hi Team, 
I am getting below exception while starting the SJS with yarn-client.'

Please help me on this to fix the issue.
Thanks in advance.

```
17/06/01 09:34:15 INFO slf4j.Slf4jLogger: Slf4jLogger started
17/06/01 09:34:15 INFO Remoting: Starting remoting
17/06/01 09:34:15 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://JobServer@127.0.0.1:34448]
17/06/01 09:34:15 INFO Remoting: Remoting now listens on addresses: [akka.tcp://JobServer@127.0.0.1:34448]
Exception in thread "main" java.lang.NoSuchMethodError: akka.util.Helpers$.ConfigOps(Lcom/typesafe/config/Config;)Lcom/typesafe/config/Config;
        at akka.cluster.ClusterSettings.<init>(ClusterSettings.scala:28)
        at akka.cluster.Cluster.<init>(Cluster.scala:67)
        at akka.cluster.Cluster$.createExtension(Cluster.scala:42)
        at akka.cluster.Cluster$.createExtension(Cluster.scala:37)
        at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:654)
        at akka.actor.ExtensionId$class.apply(Extension.scala:79)
        at akka.cluster.Cluster$.apply(Cluster.scala:37)
        at akka.cluster.ClusterActorRefProvider.createRemoteWatcher(ClusterActorRefProvider.scala:66)
        at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:186)
        at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:58)
        at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:579)
        at akka.actor.ActorSystemImpl._start(ActorSystem.scala:577)
        at akka.actor.ActorSystemImpl.start(ActorSystem.scala:588)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:111)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:104)
        at spark.jobserver.JobServer$.spark$jobserver$JobServer$$makeSupervisorSystem$1(JobServer.scala:128)
        at spark.jobserver.JobServer$$anonfun$main$1.apply(JobServer.scala:130)
        at spark.jobserver.JobServer$$anonfun$main$1.apply(JobServer.scala:130)
        at spark.jobserver.JobServer$.start(JobServer.scala:54)
        at spark.jobserver.JobServer$.main(JobServer.scala:130)
        at spark.jobserver.JobServer.main(JobServer.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by derSascha** [comment]
Sounds like wrong java/typesafeConfig combination. What java versions are in `/usr/java`, what says `java -version` and does sjs run with same jvm?

**Comment by velvia** [comment]
Yup, this is a problem with an older version of Typesafe Config taking precedence in the class path.

**Comment by FK7** [comment]
@derSascha 
SJS runs with java8 jvm and below are result for your queries.
```
[ec2-user@ip-172-31-9-78 ~]$ ll /usr/java/
total 4
drwxr-xr-x. 8 root root 4096 May 31 03:50 jdk1.7.0_67-cloudera
[ec2-user@ip-172-31-9-78 ~]$
```
```
[ec2-user@ip-172-31-9-78 ~]$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
[ec2-user@ip-172-31-9-78 ~]$
```

**Comment by derSascha** [comment]
@FK7 can you run `spark-shell` and type in `System.getProperty("java.version")` ? if this returns `1.7.0_67` than you have to recompile SJS for java 7.

**Comment by velvia** [comment]
I would also recommend you to look at the jars listed under Spark UI, environment tab, and check the version of type safe config.

**Comment by FK7** [comment]
@derSascha As you can see it is returning java 8 version.
```
scala> System.getProperty("java.version")
res0: String = 1.8.0_131

```

**Comment by bsikander** [comment]
Closing due to inactivity. Please reopen if it is still an issue.
