### ISSUE TITLE
Unable to start the deployed spark job server 

### ISSUE THREAD

**Issue by ReubenBorrison** [spark-jobserver/spark-jobserver#846]
I am trying to  use the spark job server on a cluster on CDH 5.11, spark version 1.6.0
When I try to start the spark jobserver on the deployed machine I get this error log

[ERROR] [06/02/2017 15:30:14.966] [JobServer-akka.actor.default-dispatcher-3] [ActorSystem(JobServer)] Uncaught error from thread [JobServer-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-ex$
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at akka.event.slf4j.Logger$.apply(Slf4jLogger.scala:30)
        at akka.event.slf4j.SLF4JLogging$class.log(Slf4jLogger.scala:19)
        at akka.event.slf4j.Slf4jLogger.log$lzycompute(Slf4jLogger.scala:54)
        at akka.event.slf4j.Slf4jLogger.log(Slf4jLogger.scala:54)
        at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.applyOrElse(Slf4jLogger.scala:80)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
        at akka.actor.ActorCell.invoke(ActorCell.scala:456)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more

Uncaught error from thread [JobServer-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[JobServer]
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at akka.event.slf4j.Logger$.apply(Slf4jLogger.scala:30)
        at akka.event.slf4j.SLF4JLogging$class.log(Slf4jLogger.scala:19)
        at akka.event.slf4j.Slf4jLogger.log$lzycompute(Slf4jLogger.scala:54)
        at akka.event.slf4j.Slf4jLogger.log(Slf4jLogger.scala:54)
        at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.applyOrElse(Slf4jLogger.scala:80)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
        at akka.actor.ActorCell.invoke(ActorCell.scala:456)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more

Did anybody faced the same issue or provide some help ?

**Comment by velvia** [comment]
Hmmm, that’s weird. How are you deploying?   The problem seems to be that somehow the SLF4J jar was left off the class path, but this is built into our assembly jar.  It is possible that there is a version conflict on it, or that somehow SLF4J is being excluded.

**Comment by ReubenBorrison** [comment]
One thing i did to check is that I opened the jar to view if the the dependency is loaded or not and I found that it was there under org/sl4j/
Also there was no error while compiling nor a warning about the version! Also it shows that it was included from the cache. I tried clearing the cache and re build it to download everything once again but even that didn't help!

**Comment by ReubenBorrison** [comment]
I am deploying using server_deploy.sh <environment>

**Comment by velvia** [comment]
Hmm, in that case you’d have to check the spark dependencies in the UI, it is possible whatever distribution you are running it under is messing with it.

**Comment by ReubenBorrison** [comment]
I finally found the problem. The CDH creates a classpath.txt file for dependant jars which was outdated in my case. Also I was using spark version 1.6.0 and using the latest version of spark jobserver which also gave different errors. Also the for spark version 1.6.0 the selected scala version should be 2.10.4 and not 2.11.6. Also there is another repository for CDH users [Bjoern Repo](https://github.com/bjoernlohrmann/spark-jobserver/tree/0.6.2-KNIME_cdh-5.11) which worked flawlessly for me. 

Thanks for the incredible support @velvia . Your comments were really valuable!
