### ISSUE TITLE
Akka.test configurations for running sjs test cases on Jenkins

### ISSUE THREAD

**Issue by bsikander** [spark-jobserver/spark-jobserver#858]
When I execute the SJS testcases on my local machine, everything works fine. When I execute the testcases on Jenkins, random testcases start to timeout because the Akka communication take more time. 
e.g.
`00:05:11.438 SLF4J: spark.jobserver.JobManagerActor
00:05:16.321 - Should return Correct results *** FAILED *** (4 seconds, 928 milliseconds)
00:05:16.321   java.lang.AssertionError: assertion failed: timeout (2 seconds) during expectMsg: No?
00:05:16.322  at scala.Predef$.assert(Predef.scala:179)
00:05:16.322  at akka.testkit.TestKitBase$class.expectMsgPF(TestKit.scala:356)
00:05:16.322  at akka.testkit.TestKit.expectMsgPF(TestKit.scala:718)
`

I think that the reason is heavily loaded Jenkins. 
But still I would like to run my testcases successfully. Akka has some suggestions for example

1- [Increase the default timeout](http://doc.akka.io/docs/akka/current/scala/testing.html#built-in-assertions) 

> In these examples, the maximum durations you will find mentioned below are left out, in which case they use the default value from configuration item akka.test.single-expect-default which itself defaults to 3 seconds (or they obey the innermost enclosing Within as detailed below). The full signatures are:

2- [Scaling the time internally](http://doc.akka.io/docs/akka/current/scala/testing.html#accounting-for-slow-test-systems)
> The tight timeouts you use during testing on your lightning-fast notebook will invariably lead to spurious test failures on the heavily loaded Jenkins server (or similar). To account for this situation, all maximum durations are internally scaled by a factor taken from the Configuration, akka.test.timefactor, which defaults to 1.

Which configurations do you suggest ? And how can I set these configuration globally for my testcases ? (I do not want to modify individual suites)

**Comment by bsikander** [comment]
Should I add the following properties in JobSpecBase.scala file (In JobSpecConfig trait) ?
`
...
"akka.test.single-expect-default" -> "10 seconds",
 "akka.test.timefactor" ->  Integer.valueOf(2)

`

**Comment by bsikander** [comment]
Fixed in https://github.com/spark-jobserver/spark-jobserver/pull/1184 . Closing.
