### ISSUE TITLE
Job server unable to start

### ISSUE THREAD

**Issue by Cyash** [spark-jobserver/spark-jobserver#877]
Hi, guys I'm new to this job server thing I've followed all the instructions given at [**https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/EMR.md**] to install job server, and I'm using same version of spark and job server described in that documentation, now I'm getting a weird error when try to start SJS i.e
`
INFO  ka.event.slf4j.Slf4jLogger [] [] - Slf4jLogger started
 ERROR spark.jobserver.JobServer$ [] [] - Unable to start Spark JobServer:
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at spark.jobserver.JobServer$.start(JobServer.scala:59)
        at spark.jobserver.JobServer$.main(JobServer.scala:121)
        at spark.jobserver.JobServer.main(JobServer.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.NoSuchMethodError: scala.reflect.api.JavaUniverse.runtimeMirror(Ljava/lang/ClassLoader;)Lscala/reflect/api/JavaUniverse$JavaMirror;
        at spark.jobserver.io.JobSqlDAO.<init>(JobSqlDAO.scala:18)
        ... 16 more
`
I'm trying to see if there is any way to correct this? I tried looking at this thread [**https://github.com/spark-jobserver/spark-jobserver/issues/837**], I couldn't understand how to resolve this ? what kind of modifications do I've to make ?

**Comment by hntd187** [comment]
Looks like your jar is missing the scala-reflect dependency somewhere on it's classpath

**Comment by Cyash** [comment]
Is there a way to verify ? and fix it ? I just followed the commands that were posted on that page. Can you please suggest something on this?

**Comment by hntd187** [comment]
You have to ensure the version of scala/java you are compile against is the same as the one you run against. Check your versions and rebuild to make sure you're consistent.

**Comment by Cyash** [comment]
sorry this is a dumb question do we have to verify it is settings.sh file ? all I know is I've installed java through this sudo yum install java-1.7.0-openjdk-devel git and sbt through this http://www.scala-sbt.org/0.13/docs/Manual-Installation.html, not sure how to check scala version it is compiled against, is there a way to find that ?

**Comment by hntd187** [comment]
Well if that is the case, after you run `sbt assembly` you can just open the jar in any zip file program and look at what is included and that will show you the version. Also the SBT output while it's building should show you. This problem might also occur if you tried to run this as a non-fat jar, you build the jar with `sbt assembly` correct? If so, then just make sure where you are running it is also the jdk-7

**Comment by Cyash** [comment]
Hey, I just figured out to see the versions I’m using jdk 1.7.0_99 and found out that sbt version is 0.13.15 and scala version is 2.10.6 and also please look at these warnings
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.10.4, 2.10.3, 2.10.0) -> 2.10.5
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] Run 'evicted' to see detailed eviction warnings


I’ve got several of these warnings while running sbt clean update package assembly this command and I’m confused on which version it compiled against

**Comment by Cyash** [comment]
@hntd187 I figured out what is causing the problem, as you said it's a mismatch of scala version. thanks, you can close this!

**Comment by hntd187** [comment]
Cool, have fun!

**Comment by bashokkum** [comment]
@Cyash hi cyash, can you help me on how did you solve the scala dependency issue. i am following the same procedure but getting error.
![screen shot 2017-07-18 at 3 14 21 pm](https://user-images.githubusercontent.com/29639760/28335268-cd915864-6bcb-11e7-9436-ca55776ac555.png)

**Comment by Cyash** [comment]
@bashokkum  all I did was to change the scala version in settings.sh from SCALA_VERSION=2.10.6 to 2.10.5
for my setup it worked, although your error seems to be different, may be you need to open a new thread
