### ISSUE TITLE
Ask timed out

### ISSUE THREAD

**Issue by QuantumRich** [spark-jobserver/spark-jobserver#895]
I have a local instance of SJS running on my machine.  And I followed the examples to package the test.jar.  However, whenever I run a job I always get.

`Ask timed out on [Actor[akka://JobServer/user/context-supervisor/c22b1c5b-spark.jobserver.WordCountExample#1259343934]] after [10000 ms]"`

This does not happen on my old jars, just any new ones I make.  I have tried increasing the timeout but to no avail.

**Comment by QuantumRich** [comment]
UPDATE: I looked into the logs and found this, saying I may be using an older version of SJS.  However, my job jar is created with Spark 1.6.1 and my SJS 0.6.2 is configured for Spark 1.6.1.  Is there something I missed?

```
[2017-07-18 08:08:32,056] ERROR .jobserver.JobManagerActor [] [akka://JobServer/user/context-supervisor/abee91a1-spark.jobserver.WordCountExample] - Oops, there's an AbstractMethodError... maybe you compiled your code with an older version of SJS? here's the exception:
java.lang.AbstractMethodError
	at spark.jobserver.JobManagerActor$$anonfun$getJobFuture$4.apply(JobManagerActor.scala:283)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by QuantumRich** [comment]
turns out compiling with SJS 0.7.0 worked

**Comment by velvia** [comment]
Is it possible you compiled your job against SJS master or a newer version of SJS than 0.6.2?  The version of SJS compiled against is more important than version of Spark.
