### ISSUE TITLE
Can not instantiate Kafka consumer on a production cluster with Spark Job Server

### ISSUE THREAD

**Issue by therw** [spark-jobserver/spark-jobserver#900]
Hello Everybody,

I am using Spark 2.1.1 and the latest Spark Job Server from GitHub (through jitpack)

My goal is to build a Spark Streaming test software with Kafka as data input and Cassandra as data output

I have built a software using Spark Job Server with new api, this software simply consumes data from Kafka and writes them to Cassandra.

I'm using spark-streaming-kafka-0-10 for kafka connector, using Kafka010.CreateDirectStream()

When running within Intellij IDEA with Spark master being "local[*]", everything works just fine

When I try to deploy to a Spark Standalone Master (with just 1 node for tests), I always get a ClassNotFoundException for org.apache.kafka.clients.consumer.RangeAssignor, despite the fact that I've added it within the same jar file than the software

When looking in the deployed jar, the class is right at its place in org/apache/kafka/clients/consumer/RangeAssignor

And when deploying ont eh same server the exact same software without using Spark Job Server (and of course removing use of Spark Job Server classes within source code), then everything work fine

I have of course tried to setup some classpath (without success obviously) BUT this should be pointless because the missing class is already included within pushed jar.

Does anybody have an idea about what can be wrong here ?

Thanks in advance
Regis

**Comment by hntd187** [comment]
You could try this and see if that fixes your issue?

https://github.com/spark-jobserver/spark-jobserver#dependency-jars

**Comment by thoHeinze** [comment]
@therw I think it would make sense if you send us a bit more details: What version of Scala and C* are you using inside your job? Can you please send a detailed stack trace or log file and a minimal version of your pom.xml or similar.

**Comment by therw** [comment]
Thanks for the replies

I have already tried many solutions regarding ClassPath without success, and decided to include the missing classes within the final jar. When opening it, I can assure you that org/apache/kafka/clients/consumer/RangeAssignor lays in this jar

The jar file is about 9.11MB, and includes extracted classes from kafka-clients-0.10.0.1, spark-cassandra-connector_2.11-2.0.0 and spark-streaming-kafka-0-10_2.11-2.1.1

I'm using Intellij IDEA IDE

I'm guessing at that moment it might be some incompatible version issue, but so far I have no proof of this

As requested, here is my build.sbt (very simple) :
  name := "tests_spark"
  version := "1.0"
  scalaVersion := "2.11.8"
  resolvers += "jitpack" at "https://jitpack.io"
  libraryDependencies += "com.datastax.spark" % "spark-cassandra-connector_2.11" % "2.0.2"
  libraryDependencies += "org.apache.spark" % "spark-sql_2.11" % "2.1.1" % "provided"
  libraryDependencies += "org.apache.spark" % "spark-streaming_2.11" % "2.1.1" % "provided"
  libraryDependencies += "org.apache.spark" % "spark-streaming-kafka-0-10_2.11" % "2.1.1"
  libraryDependencies += "com.github.spark-jobserver" % "spark-jobserver" % "master-SNAPSHOT" % "provided"

And the exception :
[2017-07-23 11:56:56,022] ERROR streaming.StreamingContext [] [akka://JobServer/user/jobManager-31-8410-dfedeac723de] - Error starting the context, marking it as stopped
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:702)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:557)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:540)
	at org.apache.spark.streaming.kafka010.Subscribe.onStart(ConsumerStrategy.scala:83)
	at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.consumer(DirectKafkaInputDStream.scala:75)
	at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.start(DirectKafkaInputDStream.scala:243)
	at org.apache.spark.streaming.DStreamGraph$$anonfun$start$5.apply(DStreamGraph.scala:49)
	at org.apache.spark.streaming.DStreamGraph$$anonfun$start$5.apply(DStreamGraph.scala:49)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:136)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	at ... run in separate thread using org.apache.spark.util.ThreadUtils ... ()
	at org.apache.spark.streaming.StreamingContext.liftedTree1$1(StreamingContext.scala:577)
	at org.apache.spark.streaming.StreamingContext.start(StreamingContext.scala:571)
	at com.thewiw.tests.spark.jobserver.AllData$.runJob(AllData.scala:74)
	at com.thewiw.tests.spark.jobserver.AllData$.runJob(AllData.scala:20)
	at spark.jobserver.JobManagerActor$$anonfun$getJobFuture$4.apply(JobManagerActor.scala:306)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.clients.consumer.RangeAssignor ClassNotFoundException exception occured
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:227)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:637)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:557)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:540)
	at org.apache.spark.streaming.kafka010.Subscribe.onStart(ConsumerStrategy.scala:83)
	at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.consumer(DirectKafkaInputDStream.scala:75)
	at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.start(DirectKafkaInputDStream.scala:243)
	at org.apache.spark.streaming.DStreamGraph$$anonfun$start$5.apply(DStreamGraph.scala:49)
	at org.apache.spark.streaming.DStreamGraph$$anonfun$start$5.apply(DStreamGraph.scala:49)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:136)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.clients.consumer.RangeAssignor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:332)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:225)
	... 23 more
[2017-07-23 11:56:56,027] INFO  .scheduler.ReceiverTracker [] [akka://JobServer/user/jobManager-31-8410-dfedeac723de] - ReceiverTracker stopped
[2017-07-23 11:56:56,028] INFO  ing.scheduler.JobGenerator [] [akka://JobServer/user/jobManager-31-8410-dfedeac723de] - Stopping JobGenerator immediately
[2017-07-23 11:56:56,029] INFO  eaming.util.RecurringTimer [] [akka://JobServer/user/jobManager-31-8410-dfedeac723de] - Stopped timer for JobGenerator after time -1
[2017-07-23 11:56:56,031] INFO  ing.scheduler.JobGenerator [] [akka://JobServer/user/jobManager-31-8410-dfedeac723de] - Stopped JobGenerator
[2017-07-23 11:56:56,034] INFO  ing.scheduler.JobScheduler [] [akka://JobServer/user/jobManager-31-8410-dfedeac723de] - Stopped JobScheduler
[2017-07-23 11:56:56,034] ERROR .jobserver.JobManagerActor [] [akka://JobServer/user/jobManager-31-8410-dfedeac723de] - Got Throwable
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:702)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:557)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:540)
	at org.apache.spark.streaming.kafka010.Subscribe.onStart(ConsumerStrategy.scala:83)
	at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.consumer(DirectKafkaInputDStream.scala:75)
	at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.start(DirectKafkaInputDStream.scala:243)
	at org.apache.spark.streaming.DStreamGraph$$anonfun$start$5.apply(DStreamGraph.scala:49)
	at org.apache.spark.streaming.DStreamGraph$$anonfun$start$5.apply(DStreamGraph.scala:49)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:136)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	at ... run in separate thread using org.apache.spark.util.ThreadUtils ... ()
	at org.apache.spark.streaming.StreamingContext.liftedTree1$1(StreamingContext.scala:577)
	at org.apache.spark.streaming.StreamingContext.start(StreamingContext.scala:571)
	at com.thewiw.tests.spark.jobserver.AllData$.runJob(AllData.scala:74)
	at com.thewiw.tests.spark.jobserver.AllData$.runJob(AllData.scala:20)
	at spark.jobserver.JobManagerActor$$anonfun$getJobFuture$4.apply(JobManagerActor.scala:306)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.clients.consumer.RangeAssignor ClassNotFoundException exception occured
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:227)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:637)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:557)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:540)
	at org.apache.spark.streaming.kafka010.Subscribe.onStart(ConsumerStrategy.scala:83)
	at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.consumer(DirectKafkaInputDStream.scala:75)
	at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.start(DirectKafkaInputDStream.scala:243)
	at org.apache.spark.streaming.DStreamGraph$$anonfun$start$5.apply(DStreamGraph.scala:49)
	at org.apache.spark.streaming.DStreamGraph$$anonfun$start$5.apply(DStreamGraph.scala:49)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:136)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.clients.consumer.RangeAssignor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:332)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:225)
	... 23 more

**Comment by therw** [comment]
FIxed (sort of) the problem by going back to spark-streaming-kafka-0-8_2.11-2.1.1

**Comment by DanyangLinda** [comment]
Any updates on this? I have the same problem with spark-streaming-kafka-0-10_2.11-2.1.1. But I cannot use spark-streaming-kafka-0-8_2.11-2.1.1.

**Comment by therw** [comment]
No problem since going back to spark-streaming-kafka-0-8_2.11-2.1.1, and we haven't tried spark-streaming-kafka-0-10_2.11-2.1.1 again.

**Comment by abhishekmishra17** [comment]
any update on  spark-streaming-kafka-0-10_2.11-2.1.1?,we are getting error on this version

**Comment by thoHeinze** [comment]
@abhishekmishra17  sure, see my reply in https://github.com/spark-jobserver/spark-jobserver/issues/911.
