### ISSUE TITLE
Problem with WordCountExample using Docker Spark-JobServer

### ISSUE THREAD

**Issue by kavemun** [spark-jobserver/spark-jobserver#910]
I am running the WordCountExample from the docker spark-jobserver and i am getting the following exception. 

$ curl -d "input.string = a b c a b see" "localhost:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample"
```
{
  "status": "ERROR",
  "result": {
    "message": "Ask timed out on [Actor[akka://JobServer/user/job-info#-1339288125]] after [3000 ms]",
    "errorClass": "akka.pattern.AskTimeoutException",
    "stack": ["akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)", "akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)", "scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)", "scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)", "akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)", "akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)", "akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)", "akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)", "java.lang.Thread.run(Thread.java:745)"]
  }

```

from the docker logs 

```
[2017-08-26 04:19:56,459] INFO  AkkaClusterSupervisorActor [] [] - SparkContext 396a9d81-spark.jobserver.WordCountExample joined
[2017-08-26 04:20:00,138] ERROR ark.jobserver.JobInfoActor [] [] - About to restart actor due to exception:
org.h2.jdbc.JdbcSQLException: Database may be already in use: "Locked by another process". Possible solutions: close all other connection(s); use the server mode [90020-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.store.FileLock.getExceptionAlreadyInUse(FileLock.java:462)
	at org.h2.store.FileLock.lockFile(FileLock.java:356)
	at org.h2.store.FileLock.lock(FileLock.java:136)
	at org.h2.engine.Database.open(Database.java:622)
	at org.h2.engine.Database.openDatabase(Database.java:260)
	at org.h2.engine.Database.<init>(Database.java:254)
	at org.h2.engine.Engine.openSession(Engine.java:57)
	at org.h2.engine.Engine.openSession(Engine.java:164)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:142)
	at org.h2.engine.Engine.createSession(Engine.java:125)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:331)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:98)
	at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:64)
	at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:415)
	at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:414)
	at slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBackend.scala:297)
	at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:407)
	at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:346)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:407)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:498)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:504)
	at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:32)
	at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:29)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2017-08-26 04:20:00,141] ERROR ka.actor.OneForOneStrategy [] [akka://JobServer/user/job-info] - Database may be already in use: "Locked by another process". Possible solutions: close all other connection(s); use the server mode [90020-176]

```

is this an issue or I am missing something here? please kindly advice.

**Comment by thoHeinze** [comment]
@kavemun Did you set `spark.jobserver.context-per-jvm` to true ? If yes, you can not use the embedded mode of H2, but need to use it in server mode.

**Comment by kavemun** [comment]
@thoHeinze yes i have the spark.jobserver.context-per-jvm on true. do i set the spark.jobserver.driver-mode to server? When i do that, i have intermittent results. sometimes it the job completed successsfully, and sometimes I still get the database lock error.

here's my docker.conf file in case I missed anything.

```
spark {
  #
  master = "local[4]"
  master = ${?SPARK_MASTER}

  # Default # of CPUs for jobs to use for Spark standalone cluster
  job-number-cpus = 4

  jobserver {
    port = 8090
    jobdao = spark.jobserver.io.JobSqlDAO

    context-per-jvm = true

    # Default client mode will start up a new JobManager int local machine
    # You can use mesos-cluster mode with REMOTE_JOBSERVER_DIR and MESOS_SPARK_DISPATCHER
    # environment value set in xxxx.sh file to launch JobManager in remote node
    # Mesos will take responsibility to offer resource to the JobManager process
    driver-mode = server

    sqldao {

      # Slick database driver, full classpath
      slick-driver = slick.driver.H2Driver

      #JDBC driver, full classpath
      jdbc-driver = org.h2.Driver

      # Directory where default H2 driver stores its data. Only needed for H2.
      rootdir = "/var/spark-jobserver/sqldao/data"

      jdbc {
        url = "jdbc:h2:file:/var/spark-jobserver/sqldao/data/h2-db;AUTO_SERVER=TRUE"
        user = "secret"
        password = "secret"
      }

      dbcp {
        maxactive = 20
        maxidle = 10
        initialsize = 10
      }
    }
  }
}
```

**Comment by thoHeinze** [comment]
If you use `spark.jobserver.context-per-jvm` you need to start h2 as separate process see here: https://stackoverflow.com/questions/9318116/how-to-run-h2-database-in-server-mode 
So you start the need to start h2 separately and use tcp:// inside your jdbc.url

**Comment by noorul** [comment]
Closing this as you need h2 over tcp or some other DB that works over network.
