### ISSUE TITLE
run fail in spark 2.1.0 ，CHD version is 5.7.4

### ISSUE THREAD

**Issue by hyitclj** [spark-jobserver/spark-jobserver#936]
spark 2.1.0    CHD version is 5.7.4
 0.8.0-SNAPSHOT
YARN

command  as follow
curl -d "input.string = a b c a b see" 'node4:8090/jobs?appName=test-job2&classPath=com.clj.HelloWordJob&sync=true&timeout=100000'

**Actual [(wrong)](url) behavior**

[2017-09-30 10:19:22,803] INFO  ocalContextSupervisorActor [] [akka://JobServer/user/context-supervisor] - Creating SparkContext for adhoc jobs.
[2017-09-30 10:19:22,803] INFO  ocalContextSupervisorActor [] [akka://JobServer/user/context-supervisor] - Creating a SparkContext named a943d7f6-com.clj.HelloWordJob
[2017-09-30 10:19:22,804] INFO  .jobserver.JobManagerActor [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Starting actor spark.jobserver.JobManagerActor
[2017-09-30 10:19:22,807] INFO  k.jobserver.JobStatusActor [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob/$a] - Starting actor spark.jobserver.JobStatusActor
[2017-09-30 10:19:22,808] WARN  org.apache.spark.SparkConf [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - The configuration key spark.akka.threads is not supported any more because Spark doesn't use Akka since 2.0
[2017-09-30 10:19:22,809] INFO  parkContextFactory$$anon$1 [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Running Spark version 2.1.0.cloudera1
[2017-09-30 10:19:22,811] INFO  ache.spark.SecurityManager [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Changing view acls to: root
[2017-09-30 10:19:22,811] INFO  ache.spark.SecurityManager [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Changing modify acls to: root
[2017-09-30 10:19:22,811] INFO  ache.spark.SecurityManager [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Changing view acls groups to: 
[2017-09-30 10:19:22,811] INFO  ache.spark.SecurityManager [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Changing modify acls groups to: 
[2017-09-30 10:19:22,811] INFO  ache.spark.SecurityManager [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
[2017-09-30 10:19:22,837] INFO  rg.apache.spark.util.Utils [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Successfully started service 'sparkDriver' on port 38069.
[2017-09-30 10:19:22,840] INFO  org.apache.spark.SparkEnv [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Registering MapOutputTracker
[2017-09-30 10:19:22,841] INFO  org.apache.spark.SparkEnv [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Registering BlockManagerMaster
[2017-09-30 10:19:22,841] INFO  BlockManagerMasterEndpoint [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2017-09-30 10:19:22,841] INFO  BlockManagerMasterEndpoint [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - BlockManagerMasterEndpoint up
[2017-09-30 10:19:22,842] INFO  k.storage.DiskBlockManager [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Created local directory at /tmp/blockmgr-8500a8aa-ac49-46a8-bff3-479a25427683
[2017-09-30 10:19:22,843] INFO  storage.memory.MemoryStore [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - MemoryStore started with capacity 413.9 MB
[2017-09-30 10:19:22,891] INFO  org.apache.spark.SparkEnv [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Registering OutputCommitCoordinator
[2017-09-30 10:19:22,900] INFO  roject.jetty.server.Server [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - jetty-9.2.z-SNAPSHOT
[2017-09-30 10:19:22,902] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@3a721d9e{/jobs,null,AVAILABLE}
[2017-09-30 10:19:22,903] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@16ebb4a{/jobs/json,null,AVAILABLE}
[2017-09-30 10:19:22,903] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@35391b47{/jobs/job,null,AVAILABLE}
[2017-09-30 10:19:22,903] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@6f378eef{/jobs/job/json,null,AVAILABLE}
[2017-09-30 10:19:22,903] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@4503f07a{/stages,null,AVAILABLE}
[2017-09-30 10:19:22,903] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@31c3b77b{/stages/json,null,AVAILABLE}
[2017-09-30 10:19:22,903] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@4cdd6127{/stages/stage,null,AVAILABLE}
[2017-09-30 10:19:22,903] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@1f4edea5{/stages/stage/json,null,AVAILABLE}
[2017-09-30 10:19:22,903] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@45146d16{/stages/pool,null,AVAILABLE}
[2017-09-30 10:19:22,903] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@69c072a0{/stages/pool/json,null,AVAILABLE}
[2017-09-30 10:19:22,904] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@4eb3e2e6{/storage,null,AVAILABLE}
[2017-09-30 10:19:22,904] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@27e1a663{/storage/json,null,AVAILABLE}
[2017-09-30 10:19:22,904] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@417b1354{/storage/rdd,null,AVAILABLE}
[2017-09-30 10:19:22,904] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@2bc43ca9{/storage/rdd/json,null,AVAILABLE}
[2017-09-30 10:19:22,904] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@7ab15fe5{/environment,null,AVAILABLE}
[2017-09-30 10:19:22,904] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@50c93c6e{/environment/json,null,AVAILABLE}
[2017-09-30 10:19:22,904] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@49b17490{/executors,null,AVAILABLE}
[2017-09-30 10:19:22,904] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@431a287b{/executors/json,null,AVAILABLE}
[2017-09-30 10:19:22,904] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@33a4098a{/executors/threadDump,null,AVAILABLE}
[2017-09-30 10:19:22,904] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@2a1769dc{/executors/threadDump/json,null,AVAILABLE}
[2017-09-30 10:19:22,905] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@68c09dfa{/static,null,AVAILABLE}
[2017-09-30 10:19:22,905] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@7a8b3969{/,null,AVAILABLE}
[2017-09-30 10:19:22,905] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@697087eb{/api,null,AVAILABLE}
[2017-09-30 10:19:22,905] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@78385a90{/jobs/job/kill,null,AVAILABLE}
[2017-09-30 10:19:22,905] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@147b3720{/stages/stage/kill,null,AVAILABLE}
[2017-09-30 10:19:22,906] INFO  tty.server.ServerConnector [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started ServerConnector@2006d534{HTTP/1.1}{0.0.0.0:40183}
[2017-09-30 10:19:22,906] INFO  roject.jetty.server.Server [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started @82407295ms
[2017-09-30 10:19:22,906] INFO  rg.apache.spark.util.Utils [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Successfully started service 'SparkUI' on port 40183.
[2017-09-30 10:19:22,906] INFO  rg.apache.spark.ui.SparkUI [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Bound SparkUI to 0.0.0.0, and started at http://192.168.1.231:40183
[2017-09-30 10:19:22,928] INFO  parkContextFactory$$anon$1 [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Added JAR file:/home/spark/job-server/spark-job-server.jar at spark://192.168.1.231:38069/jars/spark-job-server.jar with timestamp 1506737962928
[2017-09-30 10:19:22,933] INFO  rg.apache.spark.util.Utils [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Using initial executors = 0, max of spark.dynamicAllocation.initialExecutors, spark.dynamicAllocation.minExecutors and spark.executor.instances
[2017-09-30 10:19:22,995] INFO  hadoop.yarn.client.RMProxy [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Connecting to ResourceManager at node4/192.168.1.231:8032
[2017-09-30 10:19:22,998] INFO  e.spark.deploy.yarn.Client [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Requesting a new application from cluster with 5 NodeManagers
[2017-09-30 10:19:23,000] INFO  e.spark.deploy.yarn.Client [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Verifying our application has not requested more than the maximum memory capability of the cluster (56320 MB per container)
[2017-09-30 10:19:23,000] INFO  e.spark.deploy.yarn.Client [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Will allocate AM container, with 896 MB memory including 384 MB overhead
[2017-09-30 10:19:23,000] INFO  e.spark.deploy.yarn.Client [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Setting up container launch context for our AM
[2017-09-30 10:19:23,001] INFO  e.spark.deploy.yarn.Client [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Setting up the launch environment for our AM container
[2017-09-30 10:19:23,003] INFO  e.spark.deploy.yarn.Client [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Preparing resources for our AM container
[2017-09-30 10:19:23,017] INFO  e.spark.deploy.yarn.Client [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Uploading resource file:/tmp/spark-983bd907-4439-4ab8-95b1-d9c707a98717/__spark_conf__6715708647072320965.zip -> hdfs://node4:8020/user/root/.sparkStaging/application_1505980084027_0072/__spark_conf__.zip
[2017-09-30 10:19:23,053] INFO  ache.spark.SecurityManager [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Changing view acls to: root
[2017-09-30 10:19:23,053] INFO  ache.spark.SecurityManager [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Changing modify acls to: root
[2017-09-30 10:19:23,053] INFO  ache.spark.SecurityManager [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Changing view acls groups to: 
[2017-09-30 10:19:23,053] INFO  ache.spark.SecurityManager [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Changing modify acls groups to: 
[2017-09-30 10:19:23,053] INFO  ache.spark.SecurityManager [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
[2017-09-30 10:19:23,054] INFO  e.spark.deploy.yarn.Client [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Submitting application application_1505980084027_0072 to ResourceManager
[2017-09-30 10:19:23,058] INFO  nt.api.impl.YarnClientImpl [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Submitted application application_1505980084027_0072
[2017-09-30 10:19:23,058] INFO  SchedulerExtensionServices [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Starting Yarn extension services with app application_1505980084027_0072 and attemptId None
[2017-09-30 10:19:24,061] INFO  e.spark.deploy.yarn.Client [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Application report for application_1505980084027_0072 (state: ACCEPTED)
[2017-09-30 10:19:24,061] INFO  e.spark.deploy.yarn.Client [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - 
	 client token: N/A
	 diagnostics: N/A
	 ApplicationMaster host: N/A
	 ApplicationMaster RPC port: -1
	 queue: root.root
	 start time: 1506737963056
	 final status: UNDEFINED
	 tracking URL: http://node4:8088/proxy/application_1505980084027_0072/
	 user: root
[2017-09-30 10:19:25,062] INFO  e.spark.deploy.yarn.Client [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Application report for application_1505980084027_0072 (state: ACCEPTED)
[2017-09-30 10:19:26,064] INFO  e.spark.deploy.yarn.Client [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Application report for application_1505980084027_0072 (state: ACCEPTED)
[2017-09-30 10:19:26,698] INFO  kend$YarnSchedulerEndpoint [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - ApplicationMaster registered as NettyRpcEndpointRef(null)
[2017-09-30 10:19:26,710] INFO  YarnClientSchedulerBackend [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Add WebUI Filter. org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter, Map(PROXY_HOSTS -> node4, PROXY_URI_BASES -> http://node4:8088/proxy/application_1505980084027_0072), /proxy/application_1505980084027_0072
[2017-09-30 10:19:26,710] INFO  apache.spark.ui.JettyUtils [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Adding filter: org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter
[2017-09-30 10:19:27,065] INFO  e.spark.deploy.yarn.Client [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Application report for application_1505980084027_0072 (state: RUNNING)
[2017-09-30 10:19:27,065] INFO  e.spark.deploy.yarn.Client [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - 
	 client token: N/A
	 diagnostics: N/A
	 ApplicationMaster host: 192.168.1.231
	 ApplicationMaster RPC port: 0
	 queue: root.root
	 start time: 1506737963056
	 final status: UNDEFINED
	 tracking URL: http://node4:8088/proxy/application_1505980084027_0072/
	 user: root
[2017-09-30 10:19:27,065] INFO  YarnClientSchedulerBackend [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Application application_1505980084027_0072 has started running.
[2017-09-30 10:19:27,071] INFO  rg.apache.spark.util.Utils [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36874.
[2017-09-30 10:19:27,071] INFO  .NettyBlockTransferService [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Server created on 192.168.1.231:36874
[2017-09-30 10:19:27,073] INFO  spark.storage.BlockManager [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2017-09-30 10:19:27,073] INFO  storage.BlockManagerMaster [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Registering BlockManager BlockManagerId(driver, 192.168.1.231, 36874, None)
[2017-09-30 10:19:27,073] INFO  BlockManagerMasterEndpoint [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Registering block manager 192.168.1.231:36874 with 413.9 MB RAM, BlockManagerId(driver, 192.168.1.231, 36874, None)
[2017-09-30 10:19:27,074] INFO  storage.BlockManagerMaster [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Registered BlockManager BlockManagerId(driver, 192.168.1.231, 36874, None)
[2017-09-30 10:19:27,074] INFO  spark.storage.BlockManager [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - external shuffle service port = 7337
[2017-09-30 10:19:27,074] INFO  spark.storage.BlockManager [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Initialized BlockManager: BlockManagerId(driver, 192.168.1.231, 36874, None)
[2017-09-30 10:19:27,076] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Started o.s.j.s.ServletContextHandler@4e4ae8d3{/metrics/json,null,AVAILABLE}
[2017-09-30 10:19:27,109] INFO  duler.EventLoggingListener [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Logging events to hdfs://node4:8020/user/spark/spark2ApplicationHistory/application_1505980084027_0072
[2017-09-30 10:19:27,110] INFO  rg.apache.spark.util.Utils [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Using initial executors = 0, max of spark.dynamicAllocation.initialExecutors, spark.dynamicAllocation.minExecutors and spark.executor.instances
[2017-09-30 10:19:27,135] INFO  YarnClientSchedulerBackend [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.8
[2017-09-30 10:19:27,136] INFO  ocalContextSupervisorActor [] [] - SparkContext a943d7f6-com.clj.HelloWordJob initialized
[2017-09-30 10:19:27,186] INFO  DefaultSparkContextFactory [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Loading class com.clj.HelloWordJob for app test-job2
[2017-09-30 10:19:27,186] INFO  ark.jobserver.JobCacheImpl [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Begin to get jar path for app test-job2, uploadTime 2017-09-29T10:36:53.150+08:00 from dao akka://JobServer/user/dao-manager#74086597
[2017-09-30 10:19:27,187] INFO  ark.jobserver.JobCacheImpl [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - End of get jar path for app test-job2, uploadTime 2017-09-29T10:36:53.150+08:00, jarPath /tmp/spark-jobserver/sqldao/data/test-job2-20170929_103653_150.jar
[2017-09-30 10:19:27,187] INFO  parkContextFactory$$anon$1 [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Added JAR /tmp/spark-jobserver/sqldao/data/test-job2-20170929_103653_150.jar at spark://192.168.1.231:38069/jars/test-job2-20170929_103653_150.jar with timestamp 1506737967187
[2017-09-30 10:19:27,189] INFO  util.ContextURLClassLoader [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Added URL file:/tmp/spark-jobserver/sqldao/data/test-job2-20170929_103653_150.jar to ContextURLClassLoader
[2017-09-30 10:19:27,189] INFO  k.jobserver.util.JarUtils$ [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Loading object com.clj.HelloWordJob$ using loader spark.jobserver.util.ContextURLClassLoader@797534ac
[2017-09-30 10:19:27,192] INFO  .jobserver.JobManagerActor [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Starting Spark job 8c1ba96b-351f-4699-a75d-3f83dc519429 [com.clj.HelloWordJob]...
[2017-09-30 10:19:27,192] INFO  k.jobserver.JobResultActor [] [akka://JobServer/user/context-supervisor/global-result-actor] - Added receiver Actor[akka://JobServer/temp/$f] to subscriber list for JobID 8c1ba96b-351f-4699-a75d-3f83dc519429
[2017-09-30 10:19:27,193] INFO  .jobserver.JobManagerActor [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Starting job future thread
[2017-09-30 10:19:27,193] ERROR .jobserver.JobManagerActor [] [akka://JobServer/user/context-supervisor/a943d7f6-com.clj.HelloWordJob] - Oops, there's an AbstractMethodError... maybe you compiled your code with an older version of SJS? here's the exception:
java.lang.AbstractMethodError: com.clj.HelloWordJob$.validate(Ljava/lang/Object;Lspark/jobserver/api/JobEnvironment;Lcom/typesafe/config/Config;)Lorg/scalactic/Or;
	at spark.jobserver.JobManagerActor$$anonfun$getJobFuture$4.apply(JobManagerActor.scala:338)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

the other command as follows
[root@node4 home]# curl -d "input.string = a b c a b see" 'node4:8090/jobs?appName=test-job2&classPath=com.clj.HelloWordJob&sync=true'
{
  "status": "ERROR",
  "result": {
    "message": "Ask timed out on [Actor[akka://JobServer/user/context-supervisor/933786ed-com.clj.HelloWordJob#-2028845382]] after [10000 ms]. Sender[null] sent message of type \"spark.jobserver.JobManagerActor$StartJob\".",
    "errorClass": "akka.pattern.AskTimeoutException",
    "stack": ["akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)", "akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)", "scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)", "scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)", "scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)", "akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:331)", "akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:282)", "akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:286)", "akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:238)", "java.lang.Thread.run(Thread.java:748)"]
  }
}[root@node4 home]# 

my local.sh as follow
# Environment and deploy file
# For use with bin/server_deploy, bin/server_package etc.
DEPLOY_HOSTS="192.168.1.231"

APP_USER=root
APP_GROUP=root
JMX_PORT=9999
# optional SSH Key to login to deploy server
#SSH_KEY=/path/to/keyfile.pem
INSTALL_DIR=/home/spark/job-server
LOG_DIR=/var/log/job-server
PIDFILE=spark-jobserver.pid
JOBSERVER_MEMORY=1G
SPARK_VERSION=2.1.0
MAX_DIRECT_MEMORY=512M
SPARK_HOME=/opt/cloudera/parcels/SPARK2/lib/spark2
SPARK_CONF_DIR=/etc/spark2/conf
# Only needed for Mesos deploys
#SPARK_EXECUTOR_URI=/home/spark/spark-1.6.0.tar.gz
# Only needed for YARN running outside of the cluster
# You will need to COPY these files from your cluster to the remote machine
# Normally these are kept on the cluster in /etc/hadoop/conf
# YARN_CONF_DIR=/pathToRemoteConf/conf
# HADOOP_CONF_DIR=/pathToRemoteConf/conf
#
# Also optional: extra JVM args for spark-submit
# export SPARK_SUBMIT_OPTS+="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5433"
SCALA_VERSION=2.11.8 # or 2.11.8
#REMOTE_JOBSERVER_DIR=file://... or hdfs://...
#MESOS_SPARK_DISPATCHER=mesos://127.0.0.1:7077

**Comment by hyitclj** [comment]
I get it by 
git clone https://github.com/spark-jobserver/spark-jobserver.git

**Comment by noorul** [comment]
Master is compiled against 2.2.0 spark libraries.

**Comment by hyitclj** [comment]
fall down

**Comment by hntd187** [comment]
Please stop spamming and referencing this issue everywhere, master runs on Spark 2.2.0, if you want to use an older version you should use the appropriate SJS version.
