### ISSUE TITLE
Python - ImportError: No module named

### ISSUE THREAD

**Issue by rfrohock** [spark-jobserver/spark-jobserver#940]
**Used Spark version** 2.2.0

**Used Spark Job Server version** https://github.com/spark-jobserver/spark-jobserver/tree/master
(Released version, git branch or docker image version)

**Deployed mode**  Spark Standalone client and cluster
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)

**Actual (wrong) behavior**  When a SparkServer Job references Python code outside of the JobServer Class the job fails with " ImportError: No module named" when using map on RDD

**Steps to reproduce** Using one of the Python Examples jobs ( example_jobs/sql_average ) add a function that is pass-through Map function.  Convert DataFrame to RDD and run Map

```
from sparkjobserver.api import SparkJob, build_problems
from pyspark.sql import SQLContext


def map_test(row):
    return row

class SQLAverageJob(SparkJob):

    def validate(self, context, runtime, config):
        problems = []
        job_data = None

        if config.get('input.data', None):
            job_data = config.get('input.data')
        else:
            problems.append('config input.data not found')
        if len(problems) == 0:
            return job_data
        else:
            return build_problems(problems)

    def run_job(self, context, runtime, data):

        rdd = context._sc.parallelize(data)
        df = context.createDataFrame(rdd, ['name', 'age', 'salary'])
        df.registerTempTable('people')
        query = context.sql("SELECT age, AVG(salary) "
                            "from people GROUP BY age ORDER BY age")
        results = query.rdd.map(lambda l: map_test(l)).collect()
        return [(r[0], r[1]) for r in results]
```

**Logs**

```
Trace log is
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: Error while calling 'run_job': Py4JJavaError(u'An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.\n', JavaObject id=o74)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: Traceback (most recent call last):
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:   File "/tmp/bdist/sparkjobserver/subprocess.py", line 113, in <module>
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:   File "/tmp/bdist/example_jobs/sql_average/__init__.py", line 30, in run_job
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:     results = query.rdd.map(lambda l: map_test(l)).collect()
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 809, in collect
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:     port = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:   File "/usr/local/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:     answer, self.gateway_client, self.target_id, self.name)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:     return f(*a, **kw)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:   File "/usr/local/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:     format(target_id, ".", name), value)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: : org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 53.0 failed 1 times, most recent failure: Lost task 2.0 in stage 53.0 (TID 3669, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 166, in main
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:     func, profiler, deserializer, serializer = read_command(pickleSer, infile)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 55, in read_command
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:     command = serializer._read_with_length(file)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 169, in _read_with_length
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:     return self.loads(obj)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 454, in loads
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:     return pickle.loads(obj)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: ImportError: No module named example_jobs.sql_average
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.scheduler.Task.run(Task.scala:108)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at java.lang.Thread.run(Thread.java:748)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: Driver stacktrace:
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1499)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1487)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1486)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1486)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at scala.Option.foreach(Option.scala:257)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1714)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1669)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1658)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2022)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2043)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2062)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2087)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:936)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.rdd.RDD.collect(RDD.scala:935)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:458)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at java.lang.reflect.Method.invoke(Method.java:498)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at py4j.Gateway.invoke(Gateway.java:280)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at py4j.GatewayConnection.run(GatewayConnection.java:214)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at java.lang.Thread.run(Thread.java:748)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 166, in main
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:     func, profiler, deserializer, serializer = read_command(pickleSer, infile)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 55, in read_command
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:     command = serializer._read_with_length(file)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 169, in _read_with_length
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:     return self.loads(obj)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 454, in loads
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:     return pickle.loads(obj)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: ImportError: No module named example_jobs.sql_average
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python:
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
[2017-10-03 17:35:49,716] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
[2017-10-03 17:35:49,717] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
[2017-10-03 17:35:49,717] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
[2017-10-03 17:35:49,717] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
[2017-10-03 17:35:49,717] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
[2017-10-03 17:35:49,717] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.scheduler.Task.run(Task.scala:108)
[2017-10-03 17:35:49,717] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
[2017-10-03 17:35:49,717] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2017-10-03 17:35:49,717] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2017-10-03 17:35:49,717] ERROR jobserver.python.PythonJob [] [akka://JobServer/user/context-supervisor/py-context] - From Python: 	... 1 more
[2
```

**Comment by noorul** [comment]
Are you able to create python context successfully. I could not. See #933

**Comment by rfrohock** [comment]
Yes, I can create a single context after a clean start of SJS using 
 `curl -X POST "localhost:8090/contexts/py-context?context factory=spark.jobserver.python.PythonSessionContextFactory"`

However, if I kill a context then I can't create a new one until SJS is restarted.

**Comment by bsikander** [comment]
Issue fixed by author. Closing.
