### ISSUE TITLE
can't view the front page after startup

### ISSUE THREAD

**Issue by cpp424337111** [spark-jobserver/spark-jobserver#945]
sjs_version: 0.7.0
spark_version: 1.6.2
scala_version: 2.11.7

server_start.log:
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
	at akka.remote.serialization.MiscMessageSerializer.<init>(MiscMessageSerializer.scala:82)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(DynamicAccess.scala:78)
	at scala.util.Try$.apply(Try.scala:161)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:73)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
	at scala.util.Success.flatMap(Try.scala:200)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:84)
	at akka.serialization.Serialization.serializerOf(Serialization.scala:165)
	at akka.serialization.Serialization$$anonfun$3.apply(Serialization.scala:174)
	at akka.serialization.Serialization$$anonfun$3.apply(Serialization.scala:174)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:722)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:224)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:721)
	at akka.serialization.Serialization.<init>(Serialization.scala:174)
	at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:15)
	at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:12)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:713)
	at akka.actor.ExtensionId$class.apply(Extension.scala:79)
	at akka.serialization.SerializationExtension$.apply(SerializationExtension.scala:12)
	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:175)
	at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:31)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:620)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:617)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:617)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:634)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
	at spark.jobserver.JobServer$.spark$jobserver$JobServer$$makeSupervisorSystem$1(JobServer.scala:157)
	at spark.jobserver.JobServer$$anonfun$main$1.apply(JobServer.scala:159)
	at spark.jobserver.JobServer$$anonfun$main$1.apply(JobServer.scala:159)
	at spark.jobserver.JobServer$.start(JobServer.scala:54)
	at spark.jobserver.JobServer$.main(JobServer.scala:159)
	at spark.jobserver.JobServer.main(JobServer.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by noorul** [comment]
Looks like version incompatibility. Are you sure your spark deployment is compiled using scala 2.11.7 ?

**Comment by cpp424337111** [comment]
zombie@zombie-OptiPlex-3020:~$ scala
Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_91).
Type in expressions to have them evaluated.
Type :help for more information.

What I found with the command is this version, and how do make sure that the deployment version is available?

**Comment by bsikander** [comment]
Closing due to inactivity.
