### ISSUE TITLE
MySQL not supported in Jobserver 2.0-preview

### ISSUE THREAD

**Issue by shantanusingh16** [spark-jobserver/spark-jobserver#947]
**Used Spark version**
2.1.1

**Used Spark Job Server version**
(Released version, git branch or docker image version)
2,0 - preview 

**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
Spark YARN

**Actual (wrong) behavior**
I'm trying to use mysql db for jobserver but it fails to start with the error 'java.lang.ClassNotFoundException: com.mysql.jdbc.Driver' 

**Steps to reproduce**
Edit the emr.conf file for jobserver to point to a mysql db and then restart the server. The error can be seen in the spark-job-server.log file.

**Logs**

[2017-10-18 07:56:47,724] ERROR spark.jobserver.JobServer$ [] [] - Unable to start Spark JobServer:
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at spark.jobserver.JobServer$.start(JobServer.scala:69)
        at spark.jobserver.JobServer$.main(JobServer.scala:156)
        at spark.jobserver.JobServer.main(JobServer.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:750)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.flywaydb.core.api.FlywayException: Unable to instantiate JDBC driver: com.mysql.jdbc.Driver
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.<init>(DriverDataSource.java:121)
        at org.flywaydb.core.Flyway.setDataSource(Flyway.java:782)
        at spark.jobserver.io.JobSqlDAO.init(JobSqlDAO.scala:113)
        at spark.jobserver.io.JobSqlDAO.<init>(JobSqlDAO.scala:105)
        ... 16 more
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:49)
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.<init>(DriverDataSource.java:111)
        ... 19 more

**Comment by hntd187** [comment]
You need to include the JDBC driver on the classpath.

**Comment by noorul** [comment]
@shantanusingh16 Please use master branch

**Comment by kaushikranjan** [comment]
@noorul 

Will the master branch work with spark 2.1.0?

**Comment by noorul** [comment]
@kaushikranjan Not sure!

**Comment by velvia** [comment]
Usually patch version differences (2.1.1 vs 2.1.0) should not cause any difficulties

**Comment by kaushikranjan** [comment]
@noorul 
@velvia 

Using postgresql with master branch.

We were trying to upload a jar, and end up with error
Storage failure : column binary in table BINARY cannot be null

curl -d @path_to_jar -H 'Content-Type: application/java-archive' "https://url_of_host/binaries/test"

**Comment by hyitclj** [comment]
why I don's use it ? detail in https://github.com/spark-jobserver/spark-jobserver/issues/936

**Comment by thoHeinze** [comment]
@msohn Have you seen the error of @kaushikranjan before?

**Comment by bsikander** [comment]
@kaushikranjan Have you followed the instructions mentioned in the [documentation](https://github.com/spark-jobserver/spark-jobserver#configuring-spark-jobserver-postgresql-database-backend)? This error that you mentioned will occur if you don't have the postgres extension `lo` installed. Install it and the problem should go away.

**Comment by noorul** [comment]
@kaushikranjan Are you able to find a solution?

**Comment by kaushikranjan** [comment]
Hey @noorul 

I do get the issue if i switch from jars to binaries and vise-versa within active jobserver for same appname

**Comment by bsikander** [comment]
In new release this issue should be fixed. Closing.
