### ISSUE TITLE
Unable to include v0.8.0-SNAPSHOT dependencies

### ISSUE THREAD

**Issue by shalabhsingh** [spark-jobserver/spark-jobserver#953]
Hello,

I am unable to include the following library dependencies in build.sbt of my custom project-
`
libraryDependencies += "spark.jobserver" % "job-server-api_2.11" % "0.8.0-SNAPSHOT" % "provided"
libraryDependencies += "spark.jobserver" % "job-server-extras_2.11" % "0.8.0-SNAPSHOT" % "provided"
`

The readme file of the this project includes a similar dependency using 0.7.0 version, but I am trying to use the 0.8.0-SNAPSHOT version because I want to use the SparkSession context for my jobs (which I believe was introduced in 0.8.0-SNAPSHOT version itself).

Any help on this is highly appreciated !!

JobServer version - 0.8.0-SNAPSHOT (git cloned the latest version)
Spark Version - 2.2.0

**Comment by shalabhsingh** [comment]
The error log generated on using `sbt package` to create the jar is the following-

`
[info] Loading project definition from /home/fastest/project/spark-jobserver/tagprediction/project
[info] Set current project to tagPrediction (in build file:/home/fastest/project/spark-jobserver/tagprediction/)
[warn] Credentials file /home/fastest/.sbt/.credentials does not exist
[info] Updating {file:/home/fastest/project/spark-jobserver/tagprediction/}root...
[warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
[warn]  * org.apache.spark:spark-core_2.11:(1.6.2, 2.2.0)
[warn]  * org.apache.spark:spark-sql_2.11:(1.6.2, 2.2.0)
[info] Resolving spark.jobserver#job-server-api_2.11;0.8.0-SNAPSHOT ...
[warn] 	module not found: spark.jobserver#job-server-api_2.11;0.8.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /home/fastest/.ivy2/local/spark.jobserver/job-server-api_2.11/0.8.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/spark/jobserver/job-server-api_2.11/0.8.0-SNAPSHOT/job-server-api_2.11-0.8.0-SNAPSHOT.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/fastest/.sbt/preloaded/spark.jobserver/job-server-api_2.11/0.8.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/fastest/.sbt/preloaded/spark/jobserver/job-server-api_2.11/0.8.0-SNAPSHOT/job-server-api_2.11-0.8.0-SNAPSHOT.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/spark/jobserver/job-server-api_2.11/0.8.0-SNAPSHOT/job-server-api_2.11-0.8.0-SNAPSHOT.pom
[warn] ==== Job Server Bintray: tried
[warn]   https://dl.bintray.com/spark-jobserver/maven/spark/jobserver/job-server-api_2.11/0.8.0-SNAPSHOT/job-server-api_2.11-0.8.0-SNAPSHOT.pom
[warn] ==== jitpack: tried
[warn]   https://jitpack.io/spark/jobserver/job-server-api_2.11/0.8.0-SNAPSHOT/job-server-api_2.11-0.8.0-SNAPSHOT.pom
[warn] ==== Job Server Bintray: tried
[warn]   https://dl.bintray.com/spark-jobserver/maven/spark/jobserver/job-server-api_2.11/0.8.0-SNAPSHOT/job-server-api_2.11-0.8.0-SNAPSHOT.pom
[info] Resolving spark.jobserver#job-server-extras_2.11;0.8.0-SNAPSHOT ...
[warn] 	module not found: spark.jobserver#job-server-extras_2.11;0.8.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /home/fastest/.ivy2/local/spark.jobserver/job-server-extras_2.11/0.8.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/spark/jobserver/job-server-extras_2.11/0.8.0-SNAPSHOT/job-server-extras_2.11-0.8.0-SNAPSHOT.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/fastest/.sbt/preloaded/spark.jobserver/job-server-extras_2.11/0.8.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/fastest/.sbt/preloaded/spark/jobserver/job-server-extras_2.11/0.8.0-SNAPSHOT/job-server-extras_2.11-0.8.0-SNAPSHOT.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/spark/jobserver/job-server-extras_2.11/0.8.0-SNAPSHOT/job-server-extras_2.11-0.8.0-SNAPSHOT.pom
[warn] ==== Job Server Bintray: tried
[warn]   https://dl.bintray.com/spark-jobserver/maven/spark/jobserver/job-server-extras_2.11/0.8.0-SNAPSHOT/job-server-extras_2.11-0.8.0-SNAPSHOT.pom
[warn] ==== jitpack: tried
[warn]   https://jitpack.io/spark/jobserver/job-server-extras_2.11/0.8.0-SNAPSHOT/job-server-extras_2.11-0.8.0-SNAPSHOT.pom
[warn] ==== Job Server Bintray: tried
[warn]   https://dl.bintray.com/spark-jobserver/maven/spark/jobserver/job-server-extras_2.11/0.8.0-SNAPSHOT/job-server-extras_2.11-0.8.0-SNAPSHOT.pom
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: spark.jobserver#job-server-api_2.11;0.8.0-SNAPSHOT: not found
[warn] 	:: spark.jobserver#job-server-extras_2.11;0.8.0-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		spark.jobserver:job-server-api_2.11:0.8.0-SNAPSHOT (/home/fastest/project/spark-jobserver/tagprediction/build.sbt#L44-45)
[warn] 		  +- com.example:tagprediction_2.11:0.13.12
[warn] 		spark.jobserver:job-server-extras_2.11:0.8.0-SNAPSHOT (/home/fastest/project/spark-jobserver/tagprediction/build.sbt#L45-46)
[warn] 		  +- com.example:tagprediction_2.11:0.13.12
sbt.ResolveException: unresolved dependency: spark.jobserver#job-server-api_2.11;0.8.0-SNAPSHOT: not found
unresolved dependency: spark.jobserver#job-server-extras_2.11;0.8.0-SNAPSHOT: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1442)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1438)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1473)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1471)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1476)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1470)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1493)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1420)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1372)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.ResolveException: unresolved dependency: spark.jobserver#job-server-api_2.11;0.8.0-SNAPSHOT: not found
[error] unresolved dependency: spark.jobserver#job-server-extras_2.11;0.8.0-SNAPSHOT: not found
[error] Total time: 30 s, completed 29 Oct, 2017 11:59:38 PM
`

**Comment by derSascha** [comment]
Hi, call `sbt publishM2` in your jobserver git clone to install the api libs in your local maven repository.

**Comment by shalabhsingh** [comment]
Hi @derSascha 
As it is searching, in local ivy repository, `sbt publishM2` didn't help but `sbt publish-local` helped.

Thanks a lot, for the help !!

**Comment by SriTDT** [comment]
Tell me a way to clone sparkJobserver v 0.8.0 to use my spark v 2.2.0

**Comment by bsikander** [comment]
Please open a separate ticket for issue and also please attach your config and what you have tried already.
