### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by elzinko** [spark-jobserver/spark-jobserver#961]
When I run a job that was compiled using jdk 8 I get this exception : 

> [2017-11-07 11:02:56,028] ERROR akka.actor.ActorSystemImpl [] [ActorSystem(JobServer)] - Uncaught error from thread [JobServer-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.UnsupportedClassVersionError: com.mypackage.MyJob : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at spark.jobserver.util.JarUtils$.loadConstructor(JarUtils.scala:49)
	at spark.jobserver.util.JarUtils$.fallBackToClass$1(JarUtils.scala:31)
	at spark.jobserver.util.JarUtils$.loadClassOrObject(JarUtils.scala:36)
	at spark.jobserver.JobCacheImpl$$anonfun$getSparkJob$1.apply(JobCache.scala:69)
	at spark.jobserver.JobCacheImpl$$anonfun$getSparkJob$1.apply(JobCache.scala:42)
	at spark.jobserver.util.LRUCache.get(LRUCache.scala:35)
	at spark.jobserver.JobCacheImpl.getSparkJob(JobCache.scala:42)
	at spark.jobserver.context.ScalaContextFactory$class.loadAndValidateJob(SparkContextFactory.scala:85)
	at spark.jobserver.context.DefaultSparkContextFactory.loadAndValidateJob(SparkContextFactory.scala:114) when I build using
	at spark.jobserver.JobManagerActor.startJobInternal(JobManagerActor.scala:231)
	at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:157)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
	at spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)
	at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

I understand that there is a difference between my java compilator version (8) and the java version used by jobserver (7 when using jobserver docker image). I got it work after building using java 7. I would prefer use java 8.

Would it be a good idea to have java 8 in the docker jobserver image?
I could create a PR.

Any advices?

Thanks

**Comment by hntd187** [comment]
I think it's going that way. I think a PR to default to Java8 in the docker image would be fantastic.

**Comment by velvia** [comment]
+1 for JDK8 default.  JDK7 is EOL’ed

**Comment by elzinko** [comment]
Hi there!
I managed to manually upgrade the java versoion in the container, but I cannot find a way do that in the docker style (Dockerfile...). Does someone could give me an entrypoint in the code so that I could create a PR?
Thx.

**Comment by noorul** [comment]
I think it already defaults to https://github.com/spark-jobserver/spark-jobserver/blob/master/build.sbt#L145 unless you set JAVA_VERSION environment variable
