### ISSUE TITLE
Spark Version In Master branch

### ISSUE THREAD

**Issue by SushantVarshney** [spark-jobserver/spark-jobserver#967]
I want to know on which version of spark does the master branch supports?

**Comment by bsikander** [comment]
The default version is 2.2.0 in Master branch. You can find it here https://github.com/spark-jobserver/spark-jobserver/blob/master/project/Versions.scala#L4

**Comment by SushantVarshney** [comment]
Getting python exceptions while installing master branch Spark Job Server

`File "/mnt/work/spark-jobserver/job-server-python/src/python/sparkjobserver/subprocess.py", line 21, in <module>
    from py4j.java_gateway import JavaGateway, java_import, GatewayClient
ImportError: No module named py4j.java_gateway
[info] - should successfully run a SQLContext based job *** FAILED *** (85 milliseconds)
[info]   1 was not equal to 0 (SubprocessSpec.scala:210)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6254)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6288)
[info]   at spark.jobserver.python.SubprocessSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply$mcV$sp(SubprocessSpec.scala:210)
[info]   at spark.jobserver.python.SubprocessSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(SubprocessSpec.scala:191)
[info]   at spark.jobserver.python.SubprocessSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(SubprocessSpec.scala:191)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)`

**Comment by noorul** [comment]
Which spark version are you using?

**Comment by SushantVarshney** [comment]
I am using Spark 2.2.0 Version on AWS EMR.

**Comment by bsikander** [comment]
Closing due to inactivity.
