### ISSUE TITLE
HOCON environment variable substituion does not get resolved for jdbc.url

### ISSUE THREAD

**Issue by themanifold** [spark-jobserver/spark-jobserver#971]
**Used Spark version**
2.1.1

**Used Spark Job Server version**
0.8.0

**Deployed mode**
client/cluster on Spark Standalone

**Actual (wrong) behavior**
Specifying an HOCON style environment substitution in configuration file does not get resolved.

**Steps to reproduce**
1. Specify a jdbc url as a HOCON style environment substitution:
```
#include your typical configuration file here
# Now override the jdbc.url
spark {
  jobserver {
    sqldao {
      jdbc {
        url = ${?JDBC_URL}
      }
    }
  }
}
```
2. Set the JDBC_URL: `export JDBC_URL=jdbc:postgresql://foo/jobserver`
3. Start the jobserver using spark submit and giving it the configuration file
4. Will see the correct config in stdout:
```
...
   "jdbc" : {
                # env var JDBC_URL
                "url" : "jdbc:postgresql://foo/jobserver",
            },
...
```
5. But will also see logs that complain `spark.jobserver.sqldao.jdbc.url has` not been resolved (see logs section below).

**Logs**

```
2017/11/16 11:32:44 INFO spark.jobserver.JobServer$: Starting JobServer with config {
...
   "jdbc" : {
                # env var JDBC_URL
                "url" : "jdbc:postgresql://foo/jobserver",
            },
...
2017/11/16 11:33:00 INFO spark.jobserver.io.JobSqlDAO: rootDir is /tmp/spark-jobserver/sqldao/data
Exception in thread "main" com.typesafe.config.ConfigException$NotResolved: spark.jobserver.sqldao.jdbc.url has not been resolved, you need to call Config#resolve(), see API docs for Config#resolve()
        at com.typesafe.config.impl.ConfigImpl.improveNotResolved(ConfigImpl.java:462)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:179)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
        at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
        at spark.jobserver.io.JobSqlDAO.<init>(JobSqlDAO.scala:77)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at spark.jobserver.JobManager$.start(JobManager.scala:68)
        at spark.jobserver.JobManager$.main(JobManager.scala:94)
        at spark.jobserver.JobManager.main(JobManager.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: com.typesafe.config.ConfigException$NotResolved: jobserver.sqldao.jdbc.url has not been resolved, you need to call Config#resolve(), see API docs for Config#resolve()
        at com.typesafe.config.impl.ConfigImpl.improveNotResolved(ConfigImpl.java:462)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:179)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
        ... 20 more
Caused by: com.typesafe.config.ConfigException$NotResolved: sqldao.jdbc.url has not been resolved, you need to call Config#resolve(), see API docs for Config#resolve()
        at com.typesafe.config.impl.ConfigImpl.improveNotResolved(ConfigImpl.java:462)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:179)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
        ... 21 more
Caused by: com.typesafe.config.ConfigException$NotResolved: jdbc.url has not been resolved, you need to call Config#resolve(), see API docs for Config#resolve()
        at com.typesafe.config.impl.ConfigImpl.improveNotResolved(ConfigImpl.java:462)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:179)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
        ... 22 more
Caused by: com.typesafe.config.ConfigException$NotResolved: url has not been resolved, you need to call Config#resolve(), see API docs for Config#resolve()
        at com.typesafe.config.impl.ConfigImpl.improveNotResolved(ConfigImpl.java:462)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:179)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
        ... 23 more
Caused by: com.typesafe.config.ConfigException$NotResolved: called valueType() on value with unresolved substitutions, need to Config#resolve() first, see API docs
        at com.typesafe.config.impl.ConfigDelayedMerge.valueType(ConfigDelayedMerge.java:46)
        at com.typesafe.config.impl.DefaultTransformer.transform(DefaultTransformer.java:21)
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:155)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
        ... 24 more
2017/11/16 11:33:00 INFO spark.jobserver.io.JobSqlDAO: rootDir is /tmp/spark-jobserver/sqldao/data
Exception in thread "main" com.typesafe.config.ConfigException$NotResolved: spark.jobserver.sqldao.jdbc.url has not been resolved, you need to call Config#resolve(), see API docs for Config#resolve()
        at com.typesafe.config.impl.ConfigImpl.improveNotResolved(ConfigImpl.java:462)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:179)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
        at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
        at spark.jobserver.io.JobSqlDAO.<init>(JobSqlDAO.scala:77)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at spark.jobserver.JobManager$.start(JobManager.scala:68)
        at spark.jobserver.JobManager$.main(JobManager.scala:94)
        at spark.jobserver.JobManager.main(JobManager.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: com.typesafe.config.ConfigException$NotResolved: jobserver.sqldao.jdbc.url has not been resolved, you need to call Config#resolve(), see API docs for Config#resolve()
        at com.typesafe.config.impl.ConfigImpl.improveNotResolved(ConfigImpl.java:462)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:179)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
        ... 20 more
Caused by: com.typesafe.config.ConfigException$NotResolved: sqldao.jdbc.url has not been resolved, you need to call Config#resolve(), see API docs for Config#resolve()
        at com.typesafe.config.impl.ConfigImpl.improveNotResolved(ConfigImpl.java:462)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:179)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
        ... 21 more
Caused by: com.typesafe.config.ConfigException$NotResolved: jdbc.url has not been resolved, you need to call Config#resolve(), see API docs for Config#resolve()
        at com.typesafe.config.impl.ConfigImpl.improveNotResolved(ConfigImpl.java:462)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:179)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
        ... 22 more
Caused by: com.typesafe.config.ConfigException$NotResolved: url has not been resolved, you need to call Config#resolve(), see API docs for Config#resolve()
        at com.typesafe.config.impl.ConfigImpl.improveNotResolved(ConfigImpl.java:462)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:179)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
        ... 23 more
Caused by: com.typesafe.config.ConfigException$NotResolved: called valueType() on value with unresolved substitutions, need to Config#resolve() first, see API docs
        at com.typesafe.config.impl.ConfigDelayedMerge.valueType(ConfigDelayedMerge.java:46)
        at com.typesafe.config.impl.DefaultTransformer.transform(DefaultTransformer.java:21)
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:155)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
        ... 24 more
```

**Comment by themanifold** [comment]
I had a brief snoop around the source code. I'm not a scala developer, so I'm of little use there, but I did see some comments in the pre-canned config files that concerned me - almost as though this is a bug someone has already come across, though the wording is a little ambiguous: https://github.com/spark-jobserver/spark-jobserver/blob/08f99339d8427c536948f216e535cc99e8a503bc/job-server/src/main/resources/application.conf#L70-L72

**Comment by velvia** [comment]
My guess is that JobManager.scala is missing a resolve() call somewhere.  It is resolve that resolves things like substitutions.
This does not happen in the main HTTP server because the way it loads the config resolves things.

**Comment by qyf404** [comment]
config.resolve()
