### ISSUE TITLE
(job-server/compile:scalastyle) errors exist

### ISSUE THREAD

**Issue by Matt-JN** [spark-jobserver/spark-jobserver#986]
**Used Spark version**
2.1.1
**Used Spark Job Server version**
latest master

**Deployed mode**
(client on Spark Standalone)

**Actual (wrong) behavior**
compile error

**Steps to reproduce**
cd /spark-job-server-dev/src/spark-jobserver/bin
./server-deploy.sh

local.conf:
 master = "spark://spark-master:7077"
  submit.deployMode = "client"

local.sh:
INSTALL_DIR=/spark-job-server-dev/deploy
LOG_DIR=/spark-job-server-dev/deploy/log
PIDFILE=spark-jobserver.pid
JOBSERVER_MEMORY=1G
SPARK_VERSION=2.1.1
INSTALL_DIR=/spark-job-server-dev/deploy
LOG_DIR=/spark-job-server-dev/deploy/log
PIDFILE=spark-jobserver.pid
JOBSERVER_MEMORY=1G
SPARK_VERSION=2.1.1
MAX_DIRECT_MEMORY=512M
SPARK_HOME=/home/wfj/spark-2.1.1
SPARK_CONF_DIR=$SPARK_HOME/conf
SCALA_VERSION=2.11.8 # or 2.11.6

**Logs**

```
[success] created output: /spark-job-server-dev/src/spark-jobserver/job-server/target
[info] Compiling 11 Scala sources to /spark-job-server-dev/src/spark-jobserver/akka-app/target/scala-2.11/classes...
[info] Compiling 13 Scala sources and 1 Java source to /spark-job-server-dev/src/spark-jobserver/job-server-api/target/scala-2.11/classes...
[warn] /spark-job-server-dev/src/spark-jobserver/akka-app/src/main/scala/spark/jobserver/common/akka/AkkaTestUtils.scala:24: method shutdown in class ActorSystem is deprecated: Use the terminate() method instead
[warn]       system.shutdown()
[warn]              ^
[warn] /spark-job-server-dev/src/spark-jobserver/akka-app/src/main/scala/spark/jobserver/common/akka/AkkaTestUtils.scala:25: method awaitTermination in class ActorSystem is deprecated: Use Await.result(whenTerminated, timeout) instead
[warn]       system.awaitTermination(timeout)
[warn]              ^
[warn] /spark-job-server-dev/src/spark-jobserver/akka-app/src/main/scala/spark/jobserver/common/akka/actor/Reaper.scala:44: method shutdown in class ActorSystem is deprecated: Use the terminate() method instead
[warn]     context.system.shutdown()
[warn]                    ^
[warn] three warnings found
[warn] three warnings found
java.lang.RuntimeException: errors exist
	at scala.sys.package$.error(package.scala:27)
	at org.scalastyle.sbt.Tasks$.onHasErrors$1(Plugin.scala:132)
	at org.scalastyle.sbt.Tasks$.doScalastyleWithConfig$1(Plugin.scala:187)
	at org.scalastyle.sbt.Tasks$.doScalastyle(Plugin.scala:195)
	at org.scalastyle.sbt.ScalastylePlugin$$anonfun$rawScalastyleSettings$1$$anonfun$apply$1$$anonfun$apply$2.apply(Plugin.scala:89)
	at org.scalastyle.sbt.ScalastylePlugin$$anonfun$rawScalastyleSettings$1$$anonfun$apply$1$$anonfun$apply$2.apply(Plugin.scala:77)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (job-server/compile:scalastyle) errors exist
[error] Total time: 115 s, completed 2017-12-7 10:53:33
Assembly failed
```

**Comment by Matt-JN** [comment]
^I^I (Tab) existing in WebApi.scala  causes compilation failure.
