### ISSUE TITLE
0.8 Docker Image

### ISSUE THREAD

**Issue by afking** [spark-jobserver/spark-jobserver#990]
**Used Spark version**
2.2.0

**Used Spark Job Server version**
master

**Deployed mode**
client standalone

How do you build Docker images for spark-jobserver 0.8?

**Comment by endriju** [comment]
:+1:

**Comment by endriju** [comment]
I found this https://github.com/spark-jobserver/spark-jobserver/issues/966 but the Dockerfile.test produces a testing SJS build. I wonder how to adapt the Dockerfile.test to produce an image that would start the job-server like the images in https://hub.docker.com/r/sparkjobserver/spark-jobserver/
Simply changing the entry-point didn't work, there's no app/server_start.sh script.

**Comment by ssmolen2018** [comment]
I am using this image: tcjennings/spark-jobserver

**Comment by dwnichols** [comment]
The Dockerfile is dynamically created via sbt-docker. Here's how I build the image.

- Clone the repo with symlinks enabled: `$ git clone -c core.symlinks=true git@github.com:spark-jobserver/spark-jobserver.git`
- Install sbt: http://www.scala-sbt.org/1.0/docs/Setup.html
- Build your docker image: `$ sbt docker`

**Comment by endriju** [comment]
@dwnichols Thank you for the suggestion. I tried this on Mac, currently I'm troubleshooting the following exception that I get when running `sbt docker` on the current master branch:
```
[info] [warn] Pruning sources from previous analysis, due to incompatible CompileSetup.
[info] [info] Compiling 481 Scala sources and 75 Java sources to /spark-2.2.0/core/target/scala-2.11/classes...
[info] The command '/bin/sh -c wget http://d3kbcqa49mib13.cloudfront.net/spark-2.2.0.tgz && tar -xvf spark-2.2.0.tgz && cd spark-2.2.0 && ./dev/make-distribution.sh -Dscala-2.11 -Phadoop-2.7 -Phive && cd .. && mv spark-2.2.0/dist /spark && rm spark-2.2.0.tgz && rm -r spark-2.2.0' returned a non-zero code: 137
java.lang.RuntimeException: Nonzero exit code: 137
	at scala.sys.process.BasicIO$Streamed$.scala$sys$process$BasicIO$Streamed$$next$1(BasicIO.scala:48)
	at scala.sys.process.BasicIO$Streamed$$anonfun$scala$sys$process$BasicIO$Streamed$$next$1$1.apply(BasicIO.scala:49)
	at scala.sys.process.BasicIO$Streamed$$anonfun$scala$sys$process$BasicIO$Streamed$$next$1$1.apply(BasicIO.scala:49)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream.foreach(Stream.scala:548)
	at sbtdocker.DockerBuild$.build(DockerBuild.scala:87)
	at sbtdocker.DockerBuild$.buildAndTag(DockerBuild.scala:72)
	at sbtdocker.DockerBuild$.apply(DockerBuild.scala:45)
	at sbtdocker.DockerBuild$.apply(DockerBuild.scala:24)
	at sbtdocker.DockerSettings$$anonfun$baseDockerSettings$1.apply(DockerSettings.scala:17)
	at sbtdocker.DockerSettings$$anonfun$baseDockerSettings$1.apply(DockerSettings.scala:10)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

I'll give it a better look and post here again if I find out anything.

**Comment by austinnichols101** [comment]
@dwnichols - any idea how to generate the non-mesos version of the container via sbt?

**Comment by Sikwan** [comment]
@endriju did you manage to build it on mac OS?

I have a similar exception that seems to come from the maven build of spark. Doing the command manually works but it always crash within SBT (tried on two Macs, Sierra and High Sierra)

```
[info] The command '/bin/sh -c wget http://d3kbcqa49mib13.cloudfront.net/spark-2.2.0.tgz && tar -xvf spark-2.2.0.tgz && cd spark-2.2.0 && ./dev/make-distribution.sh -Dscala-2.11 -Phadoop-2.7 -Phive && cd .. && mv spark-2.2.0/dist /spark && rm spark-2.2.0.tgz && rm -r spark-2.2.0' returned a non-zero code: 1
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.process.BasicIO$Streamed$.scala$sys$process$BasicIO$Streamed$$next$1(BasicIO.scala:48)
	at scala.sys.process.BasicIO$Streamed$$anonfun$scala$sys$process$BasicIO$Streamed$$next$1$1.apply(BasicIO.scala:49)
	at scala.sys.process.BasicIO$Streamed$$anonfun$scala$sys$process$BasicIO$Streamed$$next$1$1.apply(BasicIO.scala:49)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream.foreach(Stream.scala:548)
	at sbtdocker.DockerBuild$.build(DockerBuild.scala:87)
	at sbtdocker.DockerBuild$.buildAndTag(DockerBuild.scala:72)
	at sbtdocker.DockerBuild$.apply(DockerBuild.scala:45)
	at sbtdocker.DockerBuild$.apply(DockerBuild.scala:24)
	at sbtdocker.DockerSettings$$anonfun$baseDockerSettings$1.apply(DockerSettings.scala:17)
	at sbtdocker.DockerSettings$$anonfun$baseDockerSettings$1.apply(DockerSettings.scala:10)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (root/*:docker) Nonzero exit code: 1
[error] Total time: 649 s, completed Feb 27, 2018 5:42:03 PM
```

**Comment by endriju** [comment]
@Sikwan I wasn't able to get past that exception, I reverted to using prebuilt image.

**Comment by dwnichols** [comment]
@austinnichols101 : looking at the [build.sbt](https://github.com/spark-jobserver/spark-jobserver/blob/e1a8b1711d209fafb6bb78b001064527c65ee890/build.sbt#L157) file, mesos is explicitly installed and there doesn't look to be an option to disable it. The [docs ](https://github.com/spark-jobserver/spark-jobserver#deployment)cover other methods of deployment, which require customization of the configuration. Hopefully you can find what you need there.

**Comment by karina-gitbub-id** [comment]
> The Dockerfile is dynamically created via sbt-docker. Here's how I build the image.
> 
> * Clone the repo with symlinks enabled: `$ git clone -c core.symlinks=true git@github.com:spark-jobserver/spark-jobserver.git`
> * Install sbt: http://www.scala-sbt.org/1.0/docs/Setup.html
> * Build your docker image: `$ sbt docker`
> 
> You will now be able to verify that the built docker image exists by running `docker images`:
> 
> ```
> $ docker images
> REPOSITORY                                      TAG                                                           IMAGE ID            CREATED             SIZE
> velvia/spark-jobserver                          0.8.1-SNAPSHOT.mesos-1.0.0.spark-2.2.0.scala-2.11.jdk-8-jdk   c506c682ef8b        19 seconds ago      1.37GB
> ```
> 
> And verify that that docker image is correctly built by running the image:
> 
> ```
> $ docker run -d -p 8090:8090 -p 32456-32472:32456-32472 <Docker Image>
> ```
> 
> If the docker image does not satisfy your requirements you may need to customize the configuration files (in `config/`) or Dockerfile (in `target/docker/`). The [docs](https://github.com/spark-jobserver/spark-jobserver#deployment) cover this in detail.

I got permission error when trying to clone git with symlink. Any one can help?
$ git clone -c core.symlinks=true git@github.com:spark-jobserver/spark-jobserver.git
Cloning into 'spark-jobserver'...
remote: Enumerating objects: 37, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 12172 (delta 5), reused 12 (delta 0), pack-reused 12135
Receiving objects: 100% (12172/12172), 3.11 MiB | 3.79 MiB/s, done.
Resolving deltas: 100% (6060/6060), done.
error: unable to create symlink config: Permission denied
error: unable to create symlink job-server-extras/config: Permission denied
error: unable to create symlink job-server/src/test/resources/db: Permission denied
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
