### ISSUE TITLE
Found non-empty schema `jobserver` without metadata table

### ISSUE THREAD

**Issue by YuanGunGun** [spark-jobserver/spark-jobserver#998]
**Used Spark version**
1.6.1
**Used Spark Job Server version**
(Released version, git branch or docker image version)
0.7.0
**Deployed mode**
yarn-client
**Actual (wrong) behavior**
first time deploy multiple jobserver in a new environment and use config flyway.locations = "db/mysql/migration"
**Steps to reproduce**
deploy jobserver in a new environment
**Logs**

```
[2018-01-04 15:03:32,960] ERROR spark.jobserver.JobServer$ [] [] - Unable to start Spark JobServer:
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at spark.jobserver.JobServer$.start(JobServer.scala:69)
        at spark.jobserver.JobServer$.main(JobServer.scala:156)
        at spark.jobserver.JobServer.main(JobServer.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.flywaydb.core.api.FlywayException: Found non-empty schema `jobserver` without metadata table! Use baseline() or set baselineOnMigrate to true to initialize the metadata table.
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1035)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
        at spark.jobserver.io.JobSqlDAO.init(JobSqlDAO.scala:117)
        at spark.jobserver.io.JobSqlDAO.<init>(JobSqlDAO.scala:105)
        ... 16 more
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by YuanGunGun** [comment]
This error message occur every time I deploy jobserver in a new enviroment.
Drop the database jobserver and recreate it can fix，but i need to auto deploy.
How can i fix it?

**Comment by YuanGunGun** [comment]
@noorul HELP

**Comment by YuanGunGun** [comment]
I try to add flyway.initOnMigrate = true , but not effect

**Comment by YuanGunGun** [comment]
cause by a Stored procedure. It make flywaydb whether the db is empty worong .  close it
